### ISSUE TITLE
Pull Requests - Attempt to build them

### ISSUE THREAD

**Issue by mindstorms6** [awslabs/aws-cdk#10]
The internet is a ✨magical✨ place.

It's even more magical when you submit pull requests and know if you broke the build _pre-merge_!

Since we're fans of the internet (and ✨magic✨) we should do some work to enable CodeBuild to validate pull requests!

https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-pull-request.html

If no one has any objections - I'm happy to wire this up.

**Comment by rix0rrr** [comment]
We have this now.
