### ISSUE TITLE
More guidance for unit testing construction code 

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#1008]
We have some guidance on testing construction code:
https://awslabs.github.io/aws-cdk/writing-constructs.html#testing

But users have asked for more guidance/detail/examples, including for other CDK languages.

**Comment by Doug-AWS** [comment]
Is this a duplicate of #1277 ?

**Comment by rix0rrr** [comment]
I think so, yes. Since the other one has more content, let's close this one.
