### ISSUE TITLE
java init template is broken

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1012]
java init template integration test failed. Seems like the application's test expected output needs to be updated for some reason

**Comment by rix0rrr** [comment]
Something about the new IAM policy normalization:

```
["",[{"Fn::GetAtt":["BucketsBucket04F23AD6D","Arn"]},"/","*"]]}],"Effect":"Allow"}
["",[{"Fn::GetAtt":["BucketsBucket04F23AD6D","Arn"]},"/*"]]}],"Effect":"Allow"},{"
```
