### ISSUE TITLE
codebuild: ProjectProps timeout does not resolve to TimeoutInMinutes

### ISSUE THREAD

**Issue by Stephen-Meyerhofer** [awslabs/aws-cdk#1028]
TimeoutInMinutes is not found in the synthesized CloudFormation template when using ProjectProps Timeout.

**Comment by skinny85** [comment]
Thanks for reporting this @Stephen-Meyerhofer! PR fixing this has been submitted [here](https://github.com/awslabs/aws-cdk/pull/1071).
