### ISSUE TITLE
codebuild: Artifact path is incorrect

### ISSUE THREAD

**Issue by Stephen-Meyerhofer** [awslabs/aws-cdk#1029]
S3BucketBuildArtifactsProps path value does not transfer to the CloudFormation template. It appears the path is {StackName}/{BucketName}.

**Comment by skinny85** [comment]
Thanks for reporting this @Stephen-Meyerhofer! PR fixing this has been submitted [here](https://github.com/awslabs/aws-cdk/pull/1072).
