### ISSUE TITLE
Project README doesn’t convey what CDK is

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/aws-cdk#103]
Currently the README in this project seems to be very geared towards how to build and contribute to the CDK. This feels like a mistake; the readme will probably be seen more by people unfamiliar with CDK, and those wishing to contribute will be a much smaller percentage. People shouldn’t have to download the project and run ‘cdk docs’ to find out what it does.

Split off details on how to build and develop CDK to a separate CONTRIBUTING.md file, and fill the main project README with much richer information on what CDK is, the problems it solves, and rich usage examples.

**Comment by rix0rrr** [comment]
No longer applies I think.
