### ISSUE TITLE
codepipeline: pollForSourceChanges defaults to true

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-cdk#1030]
All of the CodePipeline source actions currently default to enabling pollForSourceChanges, which is [no longer the recommended configuration](https://docs.aws.amazon.com/codepipeline/latest/userguide/run-automatically-polling.html).  These source actions should configure the [recommended change-detection methods](https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-about-starting.html#change-detection-methods) in the stack by default.

CodeCommit: 
https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codecommit/lib/pipeline-action.ts#L57

S3:
https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/pipeline-action.ts#L56

GitHub:
https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline/lib/github-source-action.ts#L69

**Comment by eladb** [comment]
I believe @skinny85 is working on this right now
https://github.com/awslabs/aws-cdk/pull/1026

**Comment by skinny85** [comment]
Thanks for reporting Claire. Yes, #1026 fixes it for CodeCommit, S3 and GitHub will soon follow suit.

**Comment by skinny85** [comment]
Thanks for reporting @jesterhazy. We're working on this right now in #1260.

**Comment by skinny85** [comment]
All of the CodePipeline Sources have been updated. Feel free to let us know if something doesn't work.

Thanks,
Adam
