### ISSUE TITLE
toolkit: can't have environmental context for multiple accounts in one app

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#1035]
From the Gitter channel:

```ts
new FooStack(app, 'foo-production', productionEnv)
new FooStack(app, 'foo-demo', stagingEnv)
```

Trying to synthesize this with credentials for one of the two environments in your shell will lead to:

```
Need to perform AWS calls for account 726415057446, but no credentials found. Tried: default credentials.
```

When trying to get context for the other. We're synthesizing both stacks at the same time.

This error should probably not be thrown by the toolkit, but the toolkit should report the failure to fetch the context into the app which should "this.addError()" to itself.

**Comment by eladb** [comment]
This should be resolved by #290. Closing as a dup.
