### ISSUE TITLE
cdk deploy for a stack with no changes shouldn't generate an error

### ISSUE THREAD

**Issue by ikluzak** [awslabs/aws-cdk#1048]
Doing a cdk deploy of a stack with no changes is generating an error:

 "Deployment of stack failed: Error: Failed to create ChangeSet <...> on <stack>: FAILED, No updates are to be performed."

This is also problematic when deploying an application spread across multiple stacks due to maximum number of resource limits eg: 200 ( or even just organizational preference I suppose )

"Rico Huijbers @rix0rrr 16:22
@ivankluzak_twitter you're supposed to pick the stack to deploy by specifying its name. But good point, this shouldn't be an error. Can you open an issue?"

**Comment by rix0rrr** [comment]
Okay this is interesting. I can't trivially reproduce this, and the code seems like it should be preventing this from happening. Are you still seeing this behavior on the latest version (0.14.1) and if so, could you share some more details on your setup?

**Comment by rix0rrr** [comment]
Closing because of no response.
