### ISSUE TITLE
PartitionKey as a property for aws-dynamodb.Table

### ISSUE THREAD

**Issue by BastLeblanc** [awslabs/aws-cdk#1051]
PartitionKey should be mandatory in TableProps of aws-dynamodb.Table as it is a mandatory parameter to create a DynamoDB Table.

Error if the table is missing partition key:
>   [xxx] a partition key must be specified

**Comment by eladb** [comment]
We could add it as an optional property. The reason we allow definition of a Table without a primary key is to allow use cases where the key is defined by some other part of the code (such as a third party library for example that accepts a table and defines the primary key for it). Not 100% sure that's the best reason, but that was the rational.
