### ISSUE TITLE
TS1039: Initializers are not allowed in ambient contexts

### ISSUE THREAD

**Issue by trondhindenes** [awslabs/aws-cdk#1075]
This code:
```
import cdk = require('@aws-cdk/cdk');

class MyStack extends cdk.Stack {
    constructor(parent: cdk.App, id: string, props?: cdk.StackProps) {
        super(parent, id, props);
    }
}

class MyApp extends cdk.App {
    constructor() {
        super();
        new MyStack(this, 'hello-cdk');
    }
}

new MyApp().run();
```
Fails to compile:

```
node_modules/@aws-cdk/cdk/lib/cloudformation/stack.d.ts:55:24 - error TS1039: Initializers are not allowed in ambient contexts.

55     readonly isStack = true;
                          ~~~~

```
This is straight from the documentation at https://awslabs.github.io so I'm not quite sure what to do

**Comment by eladb** [comment]
Looks like typescript compiler version. 

Please make sure you use version 3.x of typescript or above. Let us know if that helps. 

Reopen if there’s still an issue

**Comment by trondhindenes** [comment]
Thanks! Is the typescript compiler version requirement documented anywhere? I couldn't find it.

**Comment by eladb** [comment]
#1086

**Comment by trondhindenes** [comment]
btw, i was at 3.0.x, upgrading to 3.1.6 fixed it.
