### ISSUE TITLE
Large Files in Git

### ISSUE THREAD

**Issue by moofish32** [awslabs/aws-cdk#1084]
CDK Folks -- new repo pulls are taking longer. I did a quick git history search and it appears the docs are sort of bulky

```
af4a64787551  5.6MiB vendor/jsii-0.5.0-beta+b2fa7e5.zip
dc8fa9398242  5.6MiB versions/0.13.0/.doctrees/environment.pickle
262e882e0106  5.6MiB .doctrees/environment.pickle
d6985e8577e6  5.6MiB versions/0.14.0/.doctrees/environment.pickle
a48ff2e29d87  5.8MiB vendor/jsii-0.5.0-beta+cfa1246.zip
704ca6cac853  5.8MiB vendor/jsii-0.5.0-beta+08f4517.zip
442d379d7ef6  5.8MiB vendor/jsii-0.5.0-beta+286a400.zip
be0673635f76  6.1MiB vendor/jsii-0.5.0-beta+dcb3a12.zip
4cd398a31b54  6.1MiB vendor/jsii-0.5.0-beta+8cbf307.zip
3f9575f74303  6.1MiB vendor/jsii-0.5.0-beta+9be0071.zip
df641268afe9  8.5MiB versions/0.9.2/.doctrees/refs/_aws-cdk_aws-ec2.doctree
e54dbc1a5773  9.6MiB versions/0.10.0/.doctrees/refs/_aws-cdk_aws-ec2.doctree
2e17a8ad7881  9.7MiB versions/0.11.0/.doctrees/refs/_aws-cdk_aws-ec2.doctree
804cf3ac2eab  9.7MiB versions/0.13.0/.doctrees/refs/_aws-cdk_aws-ec2.doctree
e805d19759ad  9.7MiB versions/0.12.0/.doctrees/refs/_aws-cdk_aws-ec2.doctree
00b483454257  9.7MiB .doctrees/refs/_aws-cdk_aws-ec2.doctree
c6ed34f4e4be  9.7MiB versions/0.14.0/.doctrees/refs/_aws-cdk_aws-ec2.doctree
```
that's a commit sha on the left.

I prefer not to store those large files in the code repo.

**Comment by moofish32** [comment]
I used this script

```
 git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| gnumfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

Linux swap to `gnumfmt` to `numfmt` or just remove that line as it's only for pretty printing bytes.

**Comment by eladb** [comment]
* jsii is from the time before we published to npm, and we had to use a checked-in version of jsii
* everything that starts with `versions/` is from the docs website which is committed to the gh_pages branch

**Comment by rix0rrr** [comment]
It looks like every release is going to grow the repository by ~10MB.

That's not great...

**Comment by rix0rrr** [comment]
And we can't very well clear out the ZIPs from the history anymore... it's going to invalidate all of our release SHAs :/.

**Comment by rix0rrr** [comment]
At least we should be able to clear out the docs branch.

**Comment by eladb** [comment]
The old jsii archives are there to say I guess, but we really don't need the history in the `gh-pages` branch. @RomainMuller and @rix0rrr ran some tests and it appears we should be able to "force push" our updates to gh-pages when we release, which will effectively orphan these old big files and compact our repo.

**Comment by eladb** [comment]
I've tried to force-push an update to "gh-pages" that removes the history so we'll get into a more sane state, but it seems like this branch is "protected" by GitHub against force push. I am trying to push to a different branch and modify GitHub pages to use it as source, maybe that will unprotected "gh-pages" and we can update it. Stay tuned.

**Comment by eladb** [comment]
We need to move out gh-pages branch to a different repo nevertheless: 
1. We can't force push into the gh-pages branch, so it will have to grow (exponentially).
2. We still want the doc history there, so even if we always force pushed, cloning our source repo would be hell.

**Comment by eladb** [comment]
Okay, we have [aws-cdk-docs](https://github.com/awslabs/aws-cdk-docs) ready for this. Let's start planning for this change, probably in a month or so:

- [ ] Copy content from aws-cdk#gh-pages 
- [ ] Decide if we still want to maintain old versions. Seems like that's going to be an issue long term. Maybe we can just preserve X last versions
- [ ] Figure out what to do with redirects from the old site. We already have lots of links pointing to it. Maybe we should get a domain? Or expedite moving to the AWS docs site instead. At any rate, we are kind of screwed.

**Comment by moofish32** [comment]
The other option might be to write up how to drop the branch from the local Refs. I don't know what GitHub does with very large branches, but that would fix the issue for new devs. It's not a true fix, but would buy us some more time.

**Comment by markcuk** [comment]
Just started following this project but this sounds like the perfect use case for git-lfs

**Comment by eladb** [comment]
Welcome!

We actually just want to stop publishing our docs to the repo.

**Comment by eladb** [comment]
The new aws-delivlib library docs publisher will now force push to the GH Pages branch without history. This should effectively orphan all nodes and resolve this issue.

**Comment by RomainMuller** [comment]
Our next documentation release will be done using `aws-delivlib` and should address the issue. Resolving right away.
