### ISSUE TITLE
Document minimum toolchain versions for various languages (typescript, dotnet, java)

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1086]
- Java: Maven 3.5.4 and Java 8.

**Comment by debora-ito** [comment]
Related to #682.

**Comment by Doug-AWS** [comment]
I've added Java and TypeScript. Assigning to Matthew for C#/.NET. Please pass it on to the next language developer (Donald for Python?); when the last language dev is done, re-assign it back to me to resolve.

**Comment by Doug-AWS** [comment]
Closing. We'll track in #682
