### ISSUE TITLE
Create section on migrating from raw CFN to CDK

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1089]
We need to help customers move from raw CFN templates to CDK and work with a mixed system, where some stacks are synthesized from CDK and others are handwritten CFN templates.

We already have some information about using existing CFN templates in the CDK: https://awslabs.github.io/aws-cdk/passing-in-data.html#using-an-existing-cfn-template.

**Comment by eranation** [comment]
Hi Doug, it looks like this link is 404ing for me, did it move? thanks!

**Comment by Doug-AWS** [comment]
Duplicate of #2142
