### ISSUE TITLE
ecs: autoscaling for LoadBalanced[Fargate|EC2]Service

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-cdk#1112]
I added desiredCount as part of https://github.com/awslabs/aws-cdk/pull/1111, next step would be to enable configuring autoscaling on the load balanced service, like you can on the [Fargate|EC2]Service constructs.

Open to feedback on best approach, some ideas

1) Make the underlying [Fargate|EC2]Service visible, like the loadBalancer is:
https://github.com/awslabs/aws-cdk/blob/e4043163d0bbf974625575d7a8e9b96406d141a4/packages/%40aws-cdk/aws-ecs/lib/load-balanced-fargate-service.ts#L85
Then configuring autoscaling would be something like:
`myLoadBalancedService.service.autoScaleTaskCount(props).scaleOnSchedule('id', otherProps)`

2) Configure autoscaling in the constructor, and add autoscaling props to the constructor props.  This would be ideal for something like the applet case, but the methods don't seem set up well today for scaleOnSchedule or scaleOnMetric to pass in, as they rely on already having a ScalableTarget and ScalableAttribute
```
new ecs.LoadBalancedFargateService(stack, 'Service', {
      cluster,
      image: ecs.DockerHub.image('test'),
      desiredCount: 2,
      autoscaling: {min: 2, max: 4},
      // how to configure the scaling on schedule or on metric tracking???
    });
```

@SoManyHs @rix0rrr

**Comment by rix0rrr** [comment]
Exposing `service` will by far be the easiest.

Another potential solution is copying the scaling methods onto the `LoadBalancedXxxService` class.

Apart from schedule, which is tricky to take as constructor parameters, we could think about taking a `defaultSaneScalingPlease: true` parameter in the constructor, where we set rules that we think are the best. Obviously they won't cover all cases users might care about, but users with specialized needs can always drop down to calling the methods if they care.

**Comment by SoManyHs** [comment]
Addressed in https://github.com/awslabs/aws-cdk/pull/2395
