### ISSUE TITLE
cdk init: rename "dotnet" to "csharp"

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1123]
Because it's a C# project

**Comment by Niladri24dutta** [comment]
@eladb Can I work on this ? it seems only this below directory needs to be changed for this `https://github.com/awslabs/aws-cdk/tree/master/packages/aws-cdk/lib/init-templates/app/dotnet` to `https://github.com/awslabs/aws-cdk/tree/master/packages/aws-cdk/lib/init-templates/app/csharp` and the corresponding change should be updated in the documentation for `language` argument of command line params . Let me know I my understanding is correct . 
I think below below line looks for the existing template languages based on the directory name 
https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/bin/cdk.ts#L38

**Comment by eladb** [comment]
Thanks so much for proposing. And you are correct in your approach. Technically this is all that needs to be changed in the CDK repo, but we have a bunch of integration tests for "cdk init" in another repo that also must be updated.

Perhaps what we can do is copy & paste the "dotnet" directory into "csharp" so the change will be backwards compatible and then we can update our integration tests and deprecate "dotnet".

**Comment by Niladri24dutta** [comment]
@eladb that would be a good idea. I Can start making the changes in my branch if it's fine with you.

**Comment by eladb** [comment]
Go ahead, much appreciated

**Comment by eladb** [comment]
Our integration tests are mastered in a private repo. Let's just start with duplicating "dotnet" to "csharp" and we'll take it from there.

**Comment by Niladri24dutta** [comment]
@eladb  got it ... I will create the PR for this
