### ISSUE TITLE
NLB: NetworkTargetGroup does not depend on NetworkListener

### ISSUE THREAD

**Issue by inoutch** [awslabs/aws-cdk#1139]
I tried to deploy NLB with ECS Fargate, but I couldn't deploy Service of ECS because the following reason.

```
The target group with targetGroupArn arn:aws:elasticloadbalancing:ap-northeast-1:*****:targetgroup/*****/***** does not have an associated load balancer. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: *****)
```

I found that NetworkTargetGroup does not to depend on NetworkListener.
In addition, I found not to call `targetGroup.registerListener(this)` in only NLB.

https://github.com/awslabs/aws-cdk/blob/6f2569fd51e7b6152830d40b146ff5f2d607e4c2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts#L69
https://github.com/awslabs/aws-cdk/blob/6f2569fd51e7b6152830d40b146ff5f2d607e4c2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/nlb/network-listener.ts#L60
https://github.com/awslabs/aws-cdk/blob/6f2569fd51e7b6152830d40b146ff5f2d607e4c2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-listener.ts#L38-L43

I think it should call this `registerListener` function as the same way as ALB.

https://github.com/awslabs/aws-cdk/blob/6f2569fd51e7b6152830d40b146ff5f2d607e4c2/packages/%40aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts#L252-L255

Is this bug?, or is there any reasons in only NLB?

**Comment by rix0rrr** [comment]
That's a bug. Thanks

**Comment by rix0rrr** [comment]
Ooh, I totally misunderstood what the error report was about.

Could you show some of your code please?

**Comment by rix0rrr** [comment]
Here's what the load balancer part should look like:

https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/test/ec2/integ.lb-awsvpc-nw.ts#L36

**Comment by inoutch** [comment]
My source code where the error occurred is general constitution using NetworkLoadBalancer. I think the same error occurs replacing ALB with NLB in the test(integ.lb-awsvpc-nw) you pasted.

I think there is a cause in `addTargetGroups`(called by `addTargets`) method of NetworkListener class. In the `addTargetGroups`, `_addDefaultTargetGroup` is called, but I think that `targetGroup.registerListener` method should also be called together. By calling the `registerListener` method, NetworkTargetGroup depends on NetworkListener. This implementation is only in ALB, not in NLB. Therefore ALB succeed.

It is another small problem, but also I report that `unhealthyThresholdCount` of  TargetGroup properties is not reflected.

Sorry for my bad english.
