### ISSUE TITLE
Support for lambda Kinesis event source

### ISSUE THREAD

**Issue by sam-goodwin** [awslabs/aws-cdk#114]
Add support for Lambda event source mappings: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html

See #86 for conversation.

**Comment by sam-goodwin** [comment]
Separated out Dynamo requirement to #1562 so seprate PRs can be made.

**Comment by johnagan** [comment]
This looks like it was added to master, but it doesn't appear to be included in the npm package of the same version `0.22`

**Comment by johnagan** [comment]
@sam-goodwin gentle bump. not sure if you get alerted on this closed issue 🌥
