### ISSUE TITLE
Documentation: Construct Library API Reference – Intro text

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#1148]
The main/landing page for the AWS Construct Library API Reference could use a little intro text to set context.  It would be good to explain these are the construct libraries that compose the core AWS CDK framework, plus the AWS Construct Library.  Could be interesting to consider grouping them by AWS Construct Library versus CDK Core Framework, too. 
https://awslabs.github.io/aws-cdk/reference.html

**Comment by Doug-AWS** [comment]
The current TOC has ~90 entries, non of which have any description in reference.html. Does anyone have an idea how we could programmatically add descriptions? Determine which have L2s? If so, we should build a table listing the L2s (and L1s?) using a script, and incorporate that table in the reference landing page.

**Comment by eladb** [comment]
I think what @fulghum asked is to just add a preface before the TOC itself (i.e. [line 16](https://github.com/awslabs/aws-cdk/blob/9a7709e5fa97c4c5aa0484fbbd041291efaa3bcf/docs/src/reference.rst.template#L16))

**Comment by Doug-AWS** [comment]
See PR #1470

**Comment by Doug-AWS** [comment]
Feel free to re-open this if you can point me to the file where I can add content.
