### ISSUE TITLE
AWS::ECS::Service needs DependsOn AWS::ElasticLoadBalancingV2::ListenerRule

### ISSUE THREAD

**Issue by nathanpeck** [awslabs/aws-cdk#1160]
```
22/26 | 10:15:33 | CREATE_FAILED        | AWS::ECS::Service                         | greeting-service/Service (greetingserviceService8DA58640) The target group with targetGroupArn arn:aws:elasticloadbalancing:us-east-1:209640446841:targetgroup/greet-inter-7A1DWCFAH8FU/c4bab708f6cad935 does not have an associated load balancer. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: f6e72ff4-e756-11e8-afbf-dd214588018c)
```

When creating a service and adding it to a load balancer the CloudFormation template fails to deploy with the above error. Example code:

```js
const greeterService = new ecs.Ec2Service(this, 'greeter-service', {
      cluster: cluster,
      desiredCount: 2,
      taskDefinition: greeterTaskDefinition
    });

     // Internet facing load balancer for the frontend services
    const externalLB = new elbv2.ApplicationLoadBalancer(this, 'external', {
      vpc: vpc,
      internetFacing: true
    });

    const externalListener = externalLB.addListener('PublicListener', { port: 80, open: true });

    externalListener.addTargets('greeter', {
      port: 80,
      targets: [greeterService]
    });
```

This is probably happening because the `AWS::ECS::Service` resource needs a `DependsOn` to the `AWS::ElasticLoadBalancingV2::ListenerRule` resource. Otherwise it is a race condition that causes a failure if the service resource creation starts before the listener rule is ready.

**Comment by rix0rrr** [comment]
I think the missing `DependsOn` actually needs to go to `Listener`, not `ListenerRule`:

```
┌───────────────┐         ┌───────────────┐               
│ LoadBalancer  │         │ ListenerRule  │──────┐        
└───────────────┘         └───────────────┘      │        
        ▲                         ▲              │        
        │                         │              │        
        │                         │              │        
        │    ┌───────────────┐    │              │        
        └────│   Listener    │────┘              │        
             └───────────────┘                   │        
                     ▲                           ▼        
                     │                   ┌───────────────┐
                      ─ ─ ─ ─ ─ ─ ─ ─ ─ ─│  TargetGroup  │
                    missing dependency   └───────────────┘
                                                 ▲        
                                                 │        
             ┌───────────────┐                   │        
             │    Service    │───────────────────┘        
             └───────────────┘                            
```

**Comment by RafeArnold** [comment]
Not sure if it will be seen here, but I don't understand why the service would have to depend on any the other declared resources (load balancer, listener, target group). Surely the service can exist independently of any of these other resources, and rather should be a dependency of the other resources?

I'm bringing this up because I want to conditionally create a load balancer and target group containing a service that will always exist, but the CloudFormation cannot construct the service when the load balancer isn't created because the service depends on the load balancer listener.

**Comment by dcaruso-pathpoint** [comment]
I am not sure why this is needed either.

The NLB or ALB and ECS Service should be allowed to create in parallel. 

The target group evaluates LB health checks correct?

Only the Target group should be waiting on creation of the ECS Service and LB?

**Comment by nathanpeck** [comment]
At the time I opened this issue the Amazon ECS service attempted to
communicate with the load balancer and target group as part of the service
setup process therefore the load balancer and target group must already
exist prior to the service being created.

Years later we added the ability for an ECS service to start out with no LB
or target group and add one later. However, in terms of CloudFormation it
would still be better to just procreate the dependency resources and create
the ECS service once rather than creating the service and then updating it
to use the LB and target group
