### ISSUE TITLE
Model Lambda's Alias.updatePolicy in our AWS::Lambda::Alias L1

### ISSUE THREAD

**Issue by skinny85** [awslabs/aws-cdk#1177]
Some CloudFormation resources (the example I know is [AWS::Lambda::Alias with its UpdatePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html#aws-resource-lambda-alias-example2)) have attributes that are not listed under the `Properties` key in a template. These are currently not available in our L1s.

They need to be added if we want to model these in the CDK.

**Comment by eladb** [comment]
Technically you should be able to use `updatePolicy` but the Alias update policy schema is not available there at the moment:

```ts
myResource.options.updatePolicy = {
  autoScalingReplacingUpdate: {
    willReplace: true
  }
}
```

Maybe we should convert this issue? And also add L2 support?

**Comment by skinny85** [comment]
Fair enough - I changed the title of the issue.

L2 support is exactly why I'm opening this issue - because I want to add it :).

**Comment by rix0rrr** [comment]
L1 creation/update policies are not generated but hand-written, so it should be easy enough to add the appropriate policies for Alias:

https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/cdk/lib/cloudformation/resource-policy.ts

**Comment by skinny85** [comment]
@rix0rrr but how to change the type of the `UpdatePolicy` in the Lambda alias L1? Right now, it's the same `UpdatePolicy` [that's used in auto-scaling groups](https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/cdk/lib/cloudformation/resource-policy.ts#L104), and it's set [in the Resource class itself](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/cloudformation/resource.ts#L271).

How to go about changing the type of `updatePolicy` for `AliasResource`?

**Comment by rix0rrr** [comment]
You don't, but you can just make the one `UpdatePolicy` type the union of all possible updatepolicy configurations. That is, you would add a `CodeDeployLambdaAliasUpdate` field to the current `UpdatePolicy` type.

That is how CloudFormation "thinks" about it as well. They don't have an `UpdatePolicy` per resource type page. Instead, they have a single `UpdatePolicy` page with all possible configurations under it:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html
