### ISSUE TITLE
Allow fixed string input to CW Event

### ISSUE THREAD

**Issue by mattmcclean** [awslabs/aws-cdk#1198]
I would like to use CDK to trigger the execution of a Step Function state machine on a periodic basis. Step functions can take input provided by the CloudWatch event however it seems that the Event resource only modifies the event object via a template rather than provide a static JSON text as the input field. 

Today I have had to use the underlying cloudformation resources to do this with the "input" field. Would be nice to be able to do this with the L2 construct for Event.

```
      /** Create the CW Event */
      new events.cloudformation.RuleResource(this, 'EveryEveningEvent', {
        roleArn: ruleRole.roleArn,
        scheduleExpression: props.scheduleExpression,
        targets: [
            {
                arn: statemachine.stateMachineArn,
                roleArn: ruleRole.roleArn,
                id: 'StepMachineTarget',
                input: "{ \"NotebookName\": \"" + props.notebookName + "\", \"EmailAddress\": \"" + props.emailAddress + "\" }"
            }
        ]
      });
```

**Comment by rix0rrr** [comment]
I'm not 100% up to date on this API, but looking at it, wouldn't the following work?

```ts
const rule = new Rule(this, 'Rule', { ... });
const stateMachine = new StateMachine(this, 'SM', { ... });

rule.addTargeT(stateMachine, {
  jsonTemplate: {
    NotebookName: props.notebookName,
    EmailAddress: props.emailAddress,
  },
});
```

If not, why not?

**Comment by mattmcclean** [comment]
I tried this but it gave me the following error:
```
While synthesizing CdkSagemakerNotebookWorkflowStack/MySageMakerStopNotebookWorkflow/ScheduledRule/Resource: Supplied properties not correct for "RuleResourceProps"
  targets: element 0: supplied properties not correct for "TargetProperty"
    inputTransformer: supplied properties not correct for "InputTransformerProperty"
      inputTemplate: {} should be a string
```

I think it is because it is trying to fill in the `InputTemplate` field of the `EventRuleResource` rather than the `Input` field which accepts static text.

**Comment by eladb** [comment]
`jsonTemplate` expects a JSON string, not a JSON object (probably something we can automatically determine and avoid the grief). Can you try this?

```ts
const rule = new Rule(this, 'Rule', { ... });
const stateMachine = new StateMachine(this, 'SM', { ... });

rule.addTarget(stateMachine, {
  jsonTemplate: JSON.stringify({
    NotebookName: props.notebookName,
    EmailAddress: props.emailAddress,
  }),
});
```

**Comment by mattmcclean** [comment]
I have tried this out and it works fine. Thanks!

**Comment by eladb** [comment]
Reopening, we should change the type of `jsonTemplate` from `any` to `string`.
