### ISSUE TITLE
aws-ecs: downscope permissions required by instance draining hook

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#1204]

**Comment by rix0rrr** [comment]
Reference to source where downscoping should happen:

https://github.com/awslabs/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/drain-hook/instance-drain-hook.ts#L76

**Comment by SoManyHs** [comment]
In all of the [managed ECS policies](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_managed_policies.html#AmazonEC2ContainerServiceTaskRole), the resource field for the actions specified in the above link are all `"Resource": [*]`.

For the autoscaling permissions in particular, the required resource for CompleteLifecycleAction (according in the [IAM docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonec2autoscaling.html) ) is an autoscaling group, and if I'm understanding it, the policy won't work if the resource is not compatible with the required ones. All this to say, I think that the way the policy is defined in the Lambda should be fine, but feel free to clarify if I'm missing something.

**Comment by rix0rrr** [comment]
Probably: asg:CompleteLifeCycleAction will need ASG ARN? And the ecs calls need the ClusterArn?

Describe calls can stay at resource-* for all I care.

**Comment by pkandasamy91** [comment]
This can be resolved.
