### ISSUE TITLE
Adding versioning to the staging bucket created by cdk bootstrap

### ISSUE THREAD

**Issue by lboucher** [awslabs/aws-cdk#1215]
Hello,

I have a use case where I would like to use the staging bucket created by cdk bootstrap in the source stage of my CodePipeline that is created as part of my CDK application. While my synthesized CloudFormation stack will create successfully and my asset code will be successfully uploaded to the staging bucket, my CodePipeline will fail to execute because the staging bucket does not support versioning. 

I see that the CFN template that creates the staging bucket is hardcoded in bootstrap-environment.ts. Would it be possible to add the VersioningConfiguration property to the S3 bucket resource or is there a particular reason why versioning is disabled? 

Thanks!

**Comment by rix0rrr** [comment]
Hi @lboucher, thanks for the question. I'll forward this to the people working on CodePipeline support.

**Comment by RomainMuller** [comment]
Hey @lboucher, would you be able to provide a little extra context on what you are trying to do, from a broader perspective?

I always thought of the CDK bootstrap stack's content as an implementation detail of the CDK toolkit, so I'm super interested to know more about your use-case so we can make sure we determine the best way forward here.

**Comment by lboucher** [comment]
Hi @RomainMuller ,

Thank you for the quick response.

Currently, I am just experimenting with the CDK in order to get more familiar with it. As part of my learning I thought I would try to make an app that makes a simple CodePipeline. The CodePipeline would consist of a source stage (which would be a S3 bucket) and a deployment stage that uses CodeDeploy to deploy to an autoscaling group of EC2 instances. 

During my experimentation I read about the assets feature that allows one to package local files and directories which are needed by the CDK app to function. 

https://awslabs.github.io/aws-cdk/refs/_aws-cdk_assets.html

The example provided talks about packaging handler code for a Lambda function, but I started wondering if I could use the assets feature to package and upload the web application I was planning on deploying using CodeDeploy. I saw that the assets feature uploads the files to a staging S3 bucket that is created as part of the cdk bootstrap command. This functionality got me wondering if I could use that same staging bucket as a source for my CodePipeline. If the code is in place in S3 once the CodePipeline resource finishes creation then a deployment of my application can start immediately.

To test, I ended up modifying my local version of the "bootstrap-environment" file so that it creates a S3 bucket that supports versioning. Once this change was in place I decided to try to following in my CDK application:

First I place the code I want to deploy using CodeDeploy in a directory called "sample-asset-directory". I then tell my cdk application to zip that directory and upload it to the staging bucket:

const asset = new assets.ZipDirectoryAsset(this, 'SampleAsset', {
path: './sample-asset-directory',
versioned: true,
});

I then add the bucket to my CodePipeline as the source stage and point CodePipeline to the s3 object key of my assets zip file:

const sourceAction = asset.bucket.addToPipeline(sourceStage, 'S3Source', {
bucketKey: asset.s3ObjectKey,
});

Since the asset zip file is uploaded before the CodePipeline is created then a deployment is automatically triggered to my EC2 instances once the CopePipeline finishes creation.


From my observations the synthesized CloudFormation stack and all of the resources it manages create successfully. By adding the versioning configuration to the staging S3 bucket my CodePipeline is able to grab my code from the bucket and deploy it to my CodeDeploy deployment group successfully. Without versioning on the bucket the execution of the pipeline won't work as CodePipeline requires S3 buckets that are used in a source stage to have versioning enabled.

The other cool thing I can do is I can update the code in the "sample-asset-directory" and then run cdk deploy. When cdk deploy is executed the CDK will upload a new version of the assets zip file to the staging S3 bucket. This in turn will trigger the CodePipeline to deploy the newest iteration of code to my EC2 instances with CodeDeploy. This makes it easy to deploy new iterations of my CodeDeploy application to my deployment group by using the cdk deploy command. 

I imagine this work flow could maybe be used to package and deploy applications to Elastic Beanstalk as well. The deploy stage of the CodePipeline would just have to point to an Elastic Beanstalk environment. I haven't tested this functionality yet though.

I hope this is sufficient information about my use case. I am new to the CDK and am still learning so I am open to feedback. Feel free to let me know if there is a more preferred method of accomplishing my use case or if anymore information is needed. 

Thanks!

**Comment by eladb** [comment]
I am wondering if a better approach would have been to use [bucket deployments](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-s3-deployment.html). This approach would give you full control over the bucket (since you will be defining it in your stack).

What do you think?

**Comment by eladb** [comment]
@lboucher Please re-open if bucket deployments won't work for your use case and we'll continue the conversation.
