### ISSUE TITLE
CodePipeline Manual Approval Notifications 

### ISSUE THREAD

**Issue by moofish32** [awslabs/aws-cdk#1222]
Right now we can't fully configure notifications for Manual approvals because we are missing the properties in:

```
export interface ManualApprovalActionProps extends actions.CommonActionProps,
    actions.CommonActionConstructProps {
}
```

The two extended Props objects do not enable us to use the `configuration` property of CodePipeline Actions. 

The first recommendation via @skinny85 in gitter is that we should add a property to pass in `TopicRef` to `ManualApprovalActionProps`. During the discussion we agreed that it might also make sense for us to create a `ManualApprovalWithEmailNotifcationAction` (naming open for discussion). This action would instead take a list of emails and add subscriptions for each to an SNS topic that was created for the user. This seems to be a very common use case.

I'm not sure how we want to view support for a generic ARN vs LambdaRef etc at this point. For now the SNS Topic seems the most logical. Of course leaving the Slack discussion off the table for the moment, but we are all aware of its popularity.

**Comment by skinny85** [comment]
How about this API @moofish32 ?

```ts
export interface ManualApprovalActionProps extends actions.CommonActionProps,
    actions.CommonActionConstructProps {
  /**
   * Optional SNS topic to send notifications to when an approval is pending.
   */
  notificationTopic?: sns.TopicRef;

  /**
   * A list of email addresses to subscribe to notifications when this Action is pending approval.
   * If this has been provided, then you must also provide the `notificationTopic` property.
   */
  notifyAddresses?: string[];
}
```

Thoughts?

**Comment by eladb** [comment]
> If this has been provided, then you must also provide the `notificationTopic` property.

Why not just create a topic if one is not provided?

**Comment by moofish32** [comment]
I'm 50/50 on `notifyAddresses` vs `notifyEmails`. I agree with @eladb just make them both optional and create a topic if it's missing, but I think I want the topic available as a `public readonly` so that we can use this later in a resource policy, etc.

**Comment by skinny85** [comment]
> Why not just create a topic if one is not provided?

Slick. Haven't thought about this possibility, but I like it.

@moofish32 sure, `notifyEmails` and having the topic as a `public readonly topic?: Topic` on the Action both sound good to me.
