### ISSUE TITLE
Simplify dependency management for applets

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1245]
When trying to use applets in 0.18.1 via a globally installed toolkit, you will get the following error:

```
Error: The child XXX of Program must be a Stack
```

This is because when the toolkit is globally installed, the copy of @aws-cdk/cdk (which defines `Stack`) is different than the one installed in the local node_modules. In JavaScript, instanceof is based on constructor object equality and they have to be the exact same copy in order to align.

Reported by @clareliguori

**Comment by rix0rrr** [comment]
> The fact that the toolkit takes a dependency on the CDK framework is not a good idea in general.

True.

But the alternative is having to make a `package.json` and `npm install`ing in a directory which is supposed to only contain a YAML file, which seems suboptimal as well. I was talking @SoManyHs through how to set up an applet and I couldn't in good conscience justify all the steps.

* Write your YAML (should be the one and only step)
* Write a `package.json`
* Install `@aws-cdk/applets-js` and `@aws-cdk/aws-ecs`.
* Create a `cdk.json` with the following in it:

```
{
  "app": "node_modules/.bin/cdk-applet-js template.yml"
}
```

* Finally you get to run `cdk deploy`

The single `cdk.json` makes it impossible to have multiple applet files in the same directory and access them easily (Yes, we can have multiple stacks in one file, but I think there's value in organizing into files).

We need to simplify this process.

**Comment by eladb** [comment]
I agree that we need to simplify but I think we should think of the end-to-end experience. If we really want only a .yaml file to be needed, then all dependencies should be implicitly managed somehow, which also means we need to be able to define version requirements in the applet, and we need to figure out how to cache those dependencies so that subsequent invocations won't need to install everything every time.
