### ISSUE TITLE
CLI commands with -h flag still run

### ISSUE THREAD

**Issue by awood45** [awslabs/aws-cdk#1259]
Generally, CLI commands run with a `-h ` flag have a behavior expectation that the action will not take place, and that a help message will be displayed instead.

Currently, a command like `cdk deploy -h` will run the deployment command.

While it's very reasonable for a flag to throw an error if desired (such as "use a different command structure to see a help message"), this definitely led to customer surprise for me.

**Comment by rix0rrr** [comment]
Agreed, sounds like a bug.
