### ISSUE TITLE
aws-ecs: doesn't apply healthCheckGracePeriodSeconds

### ISSUE THREAD

**Issue by inoutch** [awslabs/aws-cdk#1265]
The BaseServiceProps interface has **healthCheckGracePeriodSeconds**, but it isn't applied to cloudformation.ServiceResource properties on BaseService constructor.

BaseServiceProps:
https://github.com/awslabs/aws-cdk/blob/72413c12ef5fde720b9d87b844fe70721b8166f4/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L47-L52
In BaseService constructor:
https://github.com/awslabs/aws-cdk/blob/72413c12ef5fde720b9d87b844fe70721b8166f4/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L106-L117

**Comment by rix0rrr** [comment]
Thanks for the report!
