### ISSUE TITLE
Unable to deploy after manually deleted all s3 buckets

### ISSUE THREAD

**Issue by mouyigang** [awslabs/aws-cdk#1270]
manually destroyed all s3 buckets and this happened:

```bash
cdk deploy
CdkWorkshopStack: deploying...

 ❌  CdkWorkshopStack failed: NoSuchBucket: The specified bucket does not exist
The specified bucket does not exist
```

Tried:
Created a new project with cdk init
then cdk bootstrap(doesn't do anything),
still can't deploy

Expect: Provide a way to fix this situation rather than re-create aws account would be nice

**Comment by rix0rrr** [comment]
You probably deleted the toolkit bucket as well. No need to create a new account, this is fixable.

Delete the toolkit stack using CloudFormation. It will complain that it cannot delete the S3 bucket. Give the delete stack command again and acknowledge that it can't delete the bucket. Then bootstrap again and redeploy.

Let me know if that fixes it for you.

**Comment by mouyigang** [comment]
Yeh, that fixed it. Thanks!
