### ISSUE TITLE
Handle Build Args in ContainerImage.fromAsset()

### ISSUE THREAD

**Issue by MrArnoldPalmer** [awslabs/aws-cdk#1271]
When building a docker container locally and deploying that image, it would be useful to be able to pass build args to the `ecs.ContainerImage.fromAsset()` constructor.

As far as I can tell this could go something like adding a "buildArgs" property to the `DockerImageAssetProps` interface which would be an object (key/val pairs). These would flow through to `DockerImageAsset` in @aws-cdk/assets-docker and be added to the asset metadata.

Then, when building containers during deployment in aws-cdk/lib/docker.js
```
    const commandArgs = Object.entries(asset.buildArgs) // Where buildArgs defaults to {}
      .map(([buildArgKey, buildArgVal]) => `--build-arg ${buildArgKey}=${buildArgVal}`);

    const command = ['docker',
      'build',
      ...commandArgs,
      '--quiet',
      asset.path];
```

There are other docker build CLI options that may be useful to handle similarly, looking through the list, maybe "target" to allow users to specify a specific stage to be built in a multi stage build.

Does this seem like something cdk should allow?

**Comment by rix0rrr** [comment]
It could be, but I'm curious as to what the types of arguments are you would be wanting to pass. Could you tell us a little about your use case?

**Comment by MrArnoldPalmer** [comment]
Generally any build time configuration values. For me these are values that we need present during build steps. Stuff like the NODE_ENV environment variable for when we precompile static assets in the container.

Ours is a rails app, and unfortunately when running build steps in rails it expects all environment variables to be set. So we have a set of "build" environment variables that we need to pass in.

**Comment by jewelsjacobs** [comment]
I'm in the same boat. Needing to pass an NPM_TOKEN variable as an ARG to install node modules from a private repo.

**Comment by jogold** [comment]
Another use case is the pass a port to EXPOSE via build args so that we can have the port defined only once  somewhere in the stack/construct code.

**Comment by jogold** [comment]
@rix0rrr would you accept a PR for this?
