### ISSUE TITLE
Please add name for codebuild ProjectProps

### ISSUE THREAD

**Issue by mouyigang** [awslabs/aws-cdk#1285]
This will endup creating a codebuild project called: ChromeBuildProjectCF1ECDFF-pzCWvLzMTWlA
However both pipeline and codecommit allow specify name.

```
//codebuild
    const codebuildproject = new codebuild.Project(this, 'ChromeBuildProject', {
      source: new codebuild.CodeCommitSource({
          repository: sourcerepo
      }),
      environment: {
        buildImage: LinuxBuildImage.UBUNTU_14_04_DOCKER_17_09_0,
        privileged: true
      }
    });
```

**Comment by skinny85** [comment]
Is the [projectName property](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-codebuild.html#@aws-cdk/aws-codebuild.ProjectProps.projectName) what you're looking for?

Thanks,
Adam

**Comment by skinny85** [comment]
@mouyigang ping :)

**Comment by mouyigang** [comment]
Yes that's the thing I was looking for, close.
Thanks,
Andy
