### ISSUE TITLE
java: Lambda Code.asset does not recognize jar as a zip file

### ISSUE THREAD

**Issue by digitalsanctum** [awslabs/aws-cdk#1294]
I attempted to create a Lambda function and passing a path to a jar file to the `withCode` and got an exception: `Asset must be a .zip file or a directory`.

The asset validation should pass if the path points to a valid jar file (which is essentially a zip file).

As a workaround I found that by simply renaming the file from app.jar to app.zip gets past the validation.

**Comment by eladb** [comment]
Are you using `lambda.Code.asset(file)`? 
Can you paste a code snippet?

**Comment by digitalsanctum** [comment]
Sure, here's the snippet:
```
        Code codeFromLocalPath = Code.asset("/Users/switbe/projects/app/app-0.1.jar");

        Function func = new Function(this, "test-func-cdk", FunctionProps.builder()
            .withCode(codeFromLocalPath)
            .withHandler("com.myorg.MyFunction::handle")
            .withMemorySize(512)
            .withTimeout(60)
            .withRole(role)
            .withRuntime(Runtime.JAVA8)
            .build());
```

If I rename the jar file to `app-0.1.zip`, change the asset path above to match and rerun `synthesize` the validation passes.

**Comment by digitalsanctum** [comment]
Looking at CDK code, a quick fix would be to update the following to also accept jar extension: https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/assets/lib/asset.ts#L93

**Comment by eladb** [comment]
Yes, makes sense. Thanks for reporting, I misread the original description that the problem is that JARs are not supported.

**Comment by digitalsanctum** [comment]
I'll be glad to contribute the fix for this. I'll have a PR in the next couple of days.
