### ISSUE TITLE
LoadBalancedFargateService does not expose environment variables

### ISSUE THREAD

**Issue by PaulMaddox** [awslabs/aws-cdk#1296]
When using the higher level `LoadBalancedFargateService` construct to create a load balanced Fargate service, it's not possible to configure the container at runtime with environment variables.

**Comment by rix0rrr** [comment]
cc @SoManyHs

**Comment by SoManyHs** [comment]
@PaulMaddox Are you looking to use [ECS Secrets](https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/) or simply pass in custom User Data?

**Comment by SoManyHs** [comment]
@PaulMaddox There is also [Private Registry Auth](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html),  which is used specifically for creds to pull/push images. Let me know what your use case is!

**Comment by PaulMaddox** [comment]
Hi @SoManyHs - to start with, i was starting with just trying to set basic environment variables, but suspect customers would also want to use ECS Secrets longer term.

I would expect the API to mirror the way environment variables and secrets are provided in task definitions. For example:

```typescript
// Create a nginx service
const nginxService = new ecs.LoadBalancedFargateService(this, 'NginxService', {
  cluster: cluster,
  image: ecs.ContainerImage.fromDockerHub('nginx:latest'),
  environment: [ { name: "TEST_ENV", value: "test value" } ],
  secrets: [ { name: "TEST_SECRET",  valueFrom: "arn:aws:ssm:region:aws_account_id:parameter/parameter_name" } ],
})
```

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

**Comment by PaulMaddox** [comment]
As a side note @rix0rrr / @eladb, i'm struggling to overcome this with parameter overrides in the meantime. It would be great to have a workaround in this issue as a couple of people have reached out to me asking for one (inc. @mikeapted). 

Things i've tried and their result (but have failed due to my lack of understanding of property overrides probably...):

```
   // Create a nginx service
    const nginxService = new ecs.LoadBalancedFargateService(this, 'NginxService', {
      cluster: cluster,
      image: ecs.ContainerImage.fromDockerHub('nginx:latest'),
    })

    const task = nginxService.node.findChild('TaskDef') as ecs.CfnTaskDefinition
    const container = task.node.findChild('web') as ecs.CfnTaskDefinition.ContainerDefinitionProperty;
    container.environment = [{ name: 'TEST_ENV', value: 'TEST_VALUE' }]
    task.propertyOverrides.containerDefinitions = [container]
```
Results in `TypeError: Cannot set property 'containerDefinitions' of undefined`

```
const task = nginxService.node.findChild('TaskDef') as ecs.CfnTaskDefinition
    const containers = task.propertyOverrides.containerDefinitions as Array<ecs.CfnTaskDefinition.ContainerDefinitionProperty>
    for (let container of containers) {
      container.environment = [{
        name: "TEST_ENV",
        value: "test value"
      }]
    }
```

Also results in `TypeError: Cannot read property 'containerDefinitions' of undefined`

I feel i'm missing something obvious, but not sure what.

**Comment by aidanjryan** [comment]
@eladb thanks for the suggested workaround. Unfortnately when I try this I'm getting `Encountered unsupported property name` (it doesn't name any property). Any ideas?

**Comment by biffgaut** [comment]
@eladb - The downside with addPropertyOverride is that it overwrites the environment - any suggestions on how to obtain the environment and add a variable to the list that already exists?

**Comment by cyommer** [comment]
@eladb #1537 supports individual variables, but I can't see a way to use environmentFiles in order to pull them in via a file from s3.   Is that possible?
