### ISSUE TITLE
codecommit.Repository.import doesn't fail on importing non-existing repo

### ISSUE THREAD

**Issue by mouyigang** [awslabs/aws-cdk#1297]
```
    //codecommit
    const sourcerepo = codecommit.Repository.import(this, 'CDKRepoxxxx' ,{
      repositoryName: 'CDKRepoxxxx'
    });
```

cdk deploy succeed, cloudformation succeed, even though the repo doesn't exist, and was not created(should not).

Should I expecting a failure?

**Comment by skinny85** [comment]
Hey @mouyigang,

you are correct - the CDK does no validation whether something you're importing actually exists. Whether things fail or not basically depend on how much validations do the various service APIs that you are providing non-existing things to do - in this case, it seems like you haven't referenced `sourceRepo` anywhere that checks if it actually exists, so everything passed. That might not be always true.

Does this make sense?

Thanks,
Adam

**Comment by mouyigang** [comment]
I see, thanks for the detailed explanation.
