### ISSUE TITLE
RFC: missing security-impacting changes from cdk diff "scrutiny report"

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#1299]
![How's our driving?](https://upload.wikimedia.org/wikipedia/commons/3/37/Feedbackbumpersticker.jpg)

## Summary

CDK libraries you depend on may affect your security posture. In order to increase confidence in stacks generated the CDK, we will attempt to identify when you're making changes that are potentially security-sensitive. You will see a prompt that looks like this:

```
This deployment will make potentially sensitive changes.
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬─────────────────────────┬────────┬───────────────────────┬──────────────────────────────┬─────────────────────────────────┐
│   │ Resource                │ Effect │ Action                │ Principal                    │ Condition                       │
├───┼─────────────────────────┼────────┼───────────────────────┼──────────────────────────────┼─────────────────────────────────┤
│ + │ ${Echo}                 │ Allow  │ lambda:InvokeFunction │ Service:sns.amazonaws.com    │ "ArnLike": {                    │
│   │                         │        │                       │                              │   "AWS:SourceArn": "${MyTopic}" │
│   │                         │        │                       │                              │ }                               │
├───┼─────────────────────────┼────────┼───────────────────────┼──────────────────────────────┼─────────────────────────────────┤
│ + │ ${Echo/ServiceRole.Arn} │ Allow  │ sts:AssumeRole        │ Service:lambda.amazonaws.com │                                 │
└───┴─────────────────────────┴────────┴───────────────────────┴──────────────────────────────┴─────────────────────────────────┘
IAM Policy Changes
┌───┬─────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                │ Managed Policy ARN                                                             │
├───┼─────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
│ + │ ${Echo/ServiceRole.Arn} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole │
└───┴─────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘

Do you wish to deploy these changes (y/n)? 
```

## Request for comments

Please use this GitHub issue to let us know how this feature is working out for you. Is the diff correct? Is CDK identifying the right changes? Anything else you'd like to tell us?

**Comment by rix0rrr** [comment]
Here's a known list of resources that are not currently included in the diff:

- [ ] AWS::IAM::User
- [ ] Network ACLs

**Comment by insanitybit** [comment]
I like this in principal, but is there a way to opt out? Sometimes I'm working on a dev setup, and it takes ~15-20 minutes to run all of my cdk deployments. Having to sit there and hit 'y' is actually quite a pain, and really slows me down. If I could run the deployment script I have and walk away from the computer, it would be great.

A flag like --accept-scrutiny-report would be really helpful for me.

**Comment by davidbarsky** [comment]
@insanitybit `cdk deploy --require-approval=never` might resolve your issue.

**Comment by insanitybit** [comment]
That looks like it'd be exactly what I want, thanks.

**Comment by skinny85** [comment]
Resolving, as I think @insanitybit got the info they needed, feel free to re-open if not.

**Comment by emanserav** [comment]
"CDK libraries you depend on may affect your security posture. In order to increase confidence in stacks generated the CDK, we will attempt to identify when you're making changes that are potentially security-sensitive. You will see a prompt that looks like this:"

My concern is more general than security related ( I am thinking to ask here 1st maybe I am missing something ):
I've just noticed that `cdk diff` **is not displaying the ChangeSet in the AWS CF Console**.
Why  ? Any reason for that ? 
( seeing the ChangeSet in AWS CF Console history is too late )

I like seeing the changes in console using `cdk diff` but they should be identical to what I should be visualising in AWS CF ChangeSet before applying them. Are they ?

**Comment by shivlaks** [comment]
Still relevant.

Please use this GitHub issue to let us know how this feature is working out for you. Is the diff correct? Is CDK identifying the right changes? Anything else you'd like to tell us?

Although the issue is closed, the conversation is not locked.

**Comment by gmiretti** [comment]
Using CfnInclude with template
https://s3.amazonaws.com/aws-transfer-resources/custom-idp-templates/aws-transfer-custom-idp-secrets-manager-apig.template.yml
`cdk diff` doesn't report any policy created with a role, is that expected?

**Comment by skinny85** [comment]
It is not @gmiretti .... would you mind opening us a separate issue about this?

**Comment by gmiretti** [comment]
Bug reported as https://github.com/aws/aws-cdk/issues/8683

**Comment by skinny85** [comment]
> Bug reported as #8683

Thanks!

**Comment by muhammadhassaan2022skipq** [comment]
facing the warning and errors


current credentials could not be used to assume 'arn:aws:iam::id:role/cdk-hnb659fds-deploy-role-id-eu-west-3', but are for the right account. Proceeding anyway.
[0%] start: Publishing 2c53ef6888e9dfdbd68f018e34cf72270027b07ea80bfe"id"f0:current_account-current_region
current credentials could not be used to assume 'arn:aws:iam::id:role/cdk-hnb659fds-file-publishing-role-id-eu-west-3', but are for the right account. Proceeding anyway.
[50%] fail: No bucket named 'cdk-hnb659fds-assets-id-eu-west-3'. Is account id bootstrapped?
[50%] start: Publishing 4302a673e3a738e01f47c6818002ac04465f36d6e8f8201247e22ab358b5b409:current_account-current_region
[100%] fail: No bucket named 'cdk-hnb659fds-assets-id-eu-west-3'. Is account id bootstrapped?

 ❌  MHassaanStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/home/ubuntu/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/util/asset-publishing.ts:25:11)
    at CloudFormationDeployments.publishStackAssets (/home/ubuntu/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:424:7)
    at CloudFormationDeployments.deployStack (/home/ubuntu/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:317:5)
    at CdkToolkit.deploy (/home/ubuntu/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/home/ubuntu/.nvm/versions/node/v16.3.0/lib/node_modules/aws-cdk/bin/cdk.ts:281:9)
Failed to publish one or more assets. See the error messages above for more information.

**Comment by byteshiva** [comment]
Errors when deploying via cdrlocal

```
bash-5.0# cdklocal deploy 

✨  Synthesis time: 1.67s

Could not assume arn:aws:iam::000000000000:role/cdk-hnb659fds-lookup-role-000000000000-us-east-1, proceeding anyway.
(To get rid of this warning, please upgrade to bootstrap version >= 8)
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬──────────────────┬────────┬─────────────────┬─────────────────────────────────────┬─────────────────────────────────────┐
│   │ Resource         │ Effect │ Action          │ Principal                           │ Condition                           │
├───┼──────────────────┼────────┼─────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│ + │ ${TestQueue.Arn} │ Allow  │ sqs:SendMessage │ Service:sns.amazonaws.com           │ "ArnEquals": {                      │
│   │                  │        │                 │                                     │   "aws:SourceArn": "${TestTopic}"   │
│   │                  │        │                 │                                     │ }                                   │
└───┴──────────────────┴────────┴─────────────────┴─────────────────────────────────────┴─────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
TestStack: deploying...

 ❌  TestStack failed: Error: TestStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
    at CloudFormationDeployments.validateBootstrapStackVersion (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:448:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CloudFormationDeployments.publishStackAssets (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:423:7)
    at CloudFormationDeployments.deployStack (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:323:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:281:9)
TestStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
bash-5.0# 



```

**Comment by TrentonAdams** [comment]
I receive this message...
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

I'm unsure why the message is showing up.  The diff shows me IAM changes and security group changes.  Is that the reason it's showing up?  It claims that there may be security related changes not in the list, but I don't know what that means.   Could the message just tell me what other security related changes there are?

**Comment by eb-jorgemaroto** [comment]
Is this still an issue? I'm always seeing the warning, but not sure if it's kept updated.
I'm using:
├── aws-cdk-lib@2.64.0
├── aws-cdk@2.64.0

**Comment by selsAT** [comment]
yeah please remove the warning if its not relevant, PLEASE

**Comment by nerdile** [comment]
CDK Deploy gives a warning that implies there are known issues preventing IAM policy diffs from showing up in the confirmation prompt, and directs users to read this issue for more information.

However, this issue reads like you know there is an issue, but you don't know what it is.  There is no information on this page.

Why is it necessary for developers to consult this page on every deployment?  It seems unnecessary.  Should I assume that all similar warnings from the CDK are equally irrelevant?  Please consider what action you are requesting from developers when they deploy, and then reword the known issue warning to make it clear, or remove it if there is no action required from developers.

**Comment by nilroy** [comment]
Is this still relevant? I am seeing this issue linked in `cdk deploy` prompt and I am using 2.129.0. Could you please remove this warning message if its not relevant anymore. It creating confusion

**Comment by jonasfschuh** [comment]
I'm using CDK version 2.158.0 and for me this message still appears.

**Comment by nilroy** [comment]
Guys I am now at `2.170.0` and the message still appear. Could you please remove the message? Is there some reason why its still there?  Also if there is some other way we can disable the message from our end that should also serve the purpose
