### ISSUE TITLE
Toolkit: bail out early if credentials are not defined

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#130]
Seems like currently even if there are no credentials defined in the default chain, the toolkit will still execute `Looking up default account ID from STS` which will time out and only then a message is displayed that credentials are not found.

We should be able to bail out early if there are no credentials defined in the chain (we should make sure that plugins can still do their job)

**Comment by rix0rrr** [comment]
This might be useful for an optimization:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/identify_ec2_instances.html

On Lambda we get environment variables prepopulated.

Don't know about ECS.

**Comment by 0xdevalias** [comment]
I've just run into this issue myself (from #702), I tend not to have default creds set, but use a profile (which I hadn't specified), takes forever to eventually get the timeout from `169.254.169.254` being unreachable.

A couple of questions:
* As mentioned above, could we detect in a better way when in a 'cloud like' environment, and only then attempt to use the 'magic IP'
* Could we turn down the timeout on the connect request to something smaller (eg. 5sec), which would presumably be more than enough to hit an 'internal address' when running on a cloud-like environment
* How does a command such as `aws sts get-caller-identity` handle this sort of situation? As for me, it figures out instantly that I don't have creds defined:

```
⇒  aws sts get-caller-identity
Unable to locate credentials. You can configure credentials by running "aws configure".
```
