### ISSUE TITLE
Add bucket name check

### ISSUE THREAD

**Issue by mouyigang** [awslabs/aws-cdk#1308]
Wonder if can do this at cdk diff stage

`
1/5 | 11:43:29 | UPDATE_FAILED | AWS::S3::Bucket | seleniumbase_bucket (seleniumbasebucket4FC88E60) Bucket name should not contain '_'
`

**Comment by eladb** [comment]
Absolutely. Should be easy to add this validation.

**Comment by rix0rrr** [comment]
We had some at some point but removed it because of stringified tokens. But that's just an `if` away
