### ISSUE TITLE
Long strings/refs incorrectly split over newlines causing broken user-data/etc

### ISSUE THREAD

**Issue by 0xdevalias** [awslabs/aws-cdk#1309]
When I am building strings to use in my user-data/etc, CDK seems to incorrectly insert newlines (at long lines?), causing scripts to break.

**Relevant Snippets from code:**

```
const cfnInitCmd = `/opt/aws/bin/cfn-init -v --stack=${new cdk.AwsStackName} --region=${new cdk.AwsRegion} --resource=${asgLaunchConfig.logicalId}`;

appAsg.addUserData(
            "yum install -y aws-cfn-bootstrap;",
            `${cfnInitCmd} --configsets install;`,
            `/opt/aws/bin/cfn-signal --stack=${new cdk.AwsStackName} --region=${new cdk.AwsRegion} --resource=${asgLaunchConfig.logicalId} --exit-code \$?;`,
        );
```

When synthesized, this ends up like:

```
AppAutoScalingGroupLaunchConfig48178128:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
..snip..
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - |-
                #!/bin/bash
                yum install -y aws-cfn-bootstrap;
                /opt/aws/bin/cfn-init -v --stack=
              - Ref: AWS::StackName
              - " --region="
              - Ref: AWS::Region
              - >-2
                 --resource=AppAutoScalingGroupLaunchConfig48178128 --configsets
                install;
                /opt/aws/bin/cfn-signal --stack=
              - Ref: AWS::StackName
              - " --region="
              - Ref: AWS::Region
              - " --resource=AppAutoScalingGroupLaunchConfig48178128 --exit-code
                $?;"
```

Which ends up in the end user-data as:

```
#!/bin/bash
yum install -y aws-cfn-bootstrap;
/opt/aws/bin/cfn-init -v --stack=TokenizedEC2 --region=ap-southeast-2 --resource=AppAutoScalingGroupLaunchConfig48178128 --configsets
install; /opt/aws/bin/cfn-signal --stack=TokenizedEC2 --region=ap-southeast-2 --resource=AppAutoScalingGroupLaunchConfig48178128 --exit-code $?;
```

Note how the `install` parameter ends up on a new line, when it shouldn't, which then breaks things.

This is also happening in my `AWS::CloudFormation::Init` `Metadata` override, breaking my `/etc/cfn/cfn-hup.conf` config.

**Comment by eladb** [comment]
How are you deploying this? Through the toolkit or by synthesizing a YAML output and then deploying via some other tool? I am wondering if the issue is our YAML formatter?

**Comment by rix0rrr** [comment]
The maintainer of this YAML was very responsive last time around and had a patch out the next day. We can also take this to them.

**Comment by rix0rrr** [comment]
But in the mean time, yeah, no reason not to use JSON internally I suppose. It's not for human consumption anyway.

**Comment by eladb** [comment]
If we allow users to synthesize YAML, then it should work. It would be an awful experience if “cdk deploy” worked and “cdk synth” didn’t. Happy to continue to try make YAML work, but I am concerned...

**Comment by rix0rrr** [comment]
As far as I can tell the issue is because of the 

```
              - >-2
                 --resource=AppAutoScalingGroupLaunchConfig48178128 --configsets
                install;
                /opt/aws/bin/cfn-signal --stack=
```

quoting, as opposed to

```
              - " --resource=AppAutoScalingGroupLaunchConfig48178128 --exit-code
                $?;"
```

**Comment by rix0rrr** [comment]
Reported here: https://github.com/eemeli/yaml/issues/55

**Comment by eladb** [comment]
@eemeli thanks for the amazingly quick turnaround!
