### ISSUE TITLE
Should grant ecr:GetAuthorizationToken on resource: * for build stage which required docker runtime

### ISSUE THREAD

**Issue by mouyigang** [awslabs/aws-cdk#1319]
Without this permission, every time I created a build project I have to do something like:
```js
if (codebuildproject.role) {
            codebuildproject.role.addToPolicy(new PolicyStatement()
            .addAllResources()
            .addAction('ecr:GetAuthorizationToken'));
}
```
Which you may argue it's not always the case.
That's also true.

Or is there an easy way to tackle this problem?

Related error stack:
```
[Container] 2018/12/10 19:42:06 Running command echo Logging in to Amazon ECR...
Logging in to Amazon ECR...
 [Container] 2018/12/10 19:42:06 Running command $(aws ecr get-login --no-include-email --region us-east-1)
 An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: 
User: arn:aws:sts::xxx is not authorized to perform: ecr:GetAuthorizationToken on resource: *
```

**Comment by skinny85** [comment]
@mouyigang , can you specify what you mean by "build stage which requires Docker runtime"? Can you show the code of creating the CodeBuild Project?

Thanks,
Adam

**Comment by skinny85** [comment]
Right. So these permissions are very specific to your `buildspec`, so it makes sense that you need to provide them separately. We have no idea of knowing what AWS APIs you're calling during your build, and so we can't add permissions for them.

In other words, if my `buildspec` was:

```yml
phases:
  pre_build:
    commands:
      - aws s3 get my-bucket/my-file.zip
```

There's no way the CodeBuild Construct can figure out it needs to give the Project Role read permissions to `my-bucket`.

Does this make sense?

**Comment by mouyigang** [comment]
I guess it does. 
Adding docker as build environment doesn't always mean that it will access ECR.

**Comment by skinny85** [comment]
> Adding docker as build environment doesn't always mean that it will access ECR.

Yep.
