### ISSUE TITLE
Exporting DynamoDB Tables Across Stacks?

### ISSUE THREAD

**Issue by mikecann** [awslabs/aws-cdk#1321]
[The docs](https://awslabs.github.io/aws-cdk/passing-in-data.html#passing-in-a-value-from-another-stack) talk about how to share an S3 bucket across stacks but I cant seem to get it to work for DynamoDB Tables? There [doesnt seem to be](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-dynamodb.html?highlight=aws%20cdk%20aws%20dynamodb#module-@aws-cdk/aws-dynamodb) any "export" method. 

Does this not work Universally? Is there a work-around (maybe `cdk.Output`)?

**Comment by mikecann** [comment]
@eladb okay cool, thanks thats what I suspected. No worries ill work around it as you mention above.

**Comment by eladb** [comment]
Let’s keep this open until we implement this feature

**Comment by mikecann** [comment]
Oh apologies 👍 BTW im sure you are aware but UserPoolResource, UserPoolClientResource and IdentityPoolResource are all missing export too 😄

**Comment by eladb** [comment]
Yes, we are planning a more rigorous process to align our APIs :-)

**Comment by mikecann** [comment]
@eladb suppose im trying to export a table's Arn from one stack eg:

```
this.myTableArnOutput = new cdk.Output(this, "EventStoreTableArn", {
      value: eventStoreTable.tableArn
    });
```

I then want to use that Arn in a Role Policy:

```
myFunction.addToRolePolicy(
      new PolicyStatement()
        .addAction("dynamodb:Scan")
        .addResource(props.myTableArnOutput.makeImportValue())
    );
```

But I cant because `makeImportValue()` doesnt return the actual Arn only an import statement.

Do you have any suggestions here?

**Comment by eladb** [comment]
`makeImportValue` returns an token that resolves only at deploy-time, but since the value you are importing will eventually be a string (ARN), you can use `makeImportValue().toString()` to "stringify" the token so it can be "plugged in" anywhere strings go (in your case `addResource(s)`).

**Comment by mikecann** [comment]
@eladb oh cool, neat trick thanks, ill give that a shot tomorrow 😄

**Comment by rix0rrr** [comment]
Exports are actually transparent now, as long as your stacks are in the same app.

Closing.

**Comment by eladb** [comment]
@ranguard sorry for the delay. We will be able to publish a release next week.

**Comment by ranguard** [comment]
@eladb wonderful - thank you - I am looking forward to it :)

**Comment by kennu** [comment]
The new DynamoEventSource for Lambda expects a dynamodb.Table parameter. Is there some way to construct it from a table that is outside of the current stack? Or is there some alternative way to setup a DynamoEventSource?

**Comment by kennu** [comment]
Looking at the source code here, maybe DynamoEventSource could just allow configuring the `tableStreamArn` manually (instead of specifying a Table) in cases like this? https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-event-sources/lib/dynamodb.ts#L36

**Comment by kennu** [comment]
Meanwhile I used this as a workaround to do the same thing as DynamoEventSource:

      new lambda.EventSourceMapping(this, 'DynamoDBEvent', {
        target: lambdaFunction,
        batchSize: 100,
        eventSourceArn: props.tableStreamArn,
        startingPosition: lambda.StartingPosition.Latest,
      })
      lambdaFunction.addToRolePolicy(new iam.PolicyStatement()
        .addAction('dynamodb:ListStreams')
        .addResource('*')
      )
      lambdaFunction.addToRolePolicy(new iam.PolicyStatement()
        .addActions('dynamodb:DescribeStream', 'dynamodb:GetRecords', 'dynamodb:GetShardIterator')
        .addResource(props.tableStreamArn)
      )
