### ISSUE TITLE
Tools assume `lerna` is installed globally

### ISSUE THREAD

**Issue by otterley** [awslabs/aws-cdk#1338]
Developers who don't have `lerna` installed globally (i.e., via `npm install --global lerna`) are going to encounter errors with the build scripts:

```
exec: lerna: not found
```

One should be able to wrap most `lerna` invocations in scripts such as `buildup` and `builddown` with `npx` in order to resolve at least that issue, but overall, the directions in CONTRIBUTING should be reviewed to ensure the steps all work without any globally-installed npm packages.

**Comment by rix0rrr** [comment]
Can yoi give examples of locations where lerna is invoked globally?

**Comment by otterley** [comment]
Here are a few:

* https://github.com/awslabs/aws-cdk/blob/master/scripts/builddown#L5
* https://github.com/awslabs/aws-cdk/blob/master/scripts/buildup#L5

**Comment by akkaash** [comment]
I guess the larger issue is around being able to use the versions of `lerna` and other tools from the the npm dependencies as specified in the project `package.json`. It would be safe to use `npx lerna` and safer to replace occurrences of `export PATH=node_modules/.bin:$PATH` with ` export PATH=$(npm bin):$PATH` and then use the `lerna` (and others) as is since these binaries would be available in the path.

**Comment by mattmcclean** [comment]
Am not sure this fixes the problem. Running the `./install.sh` script no longer depends on having `lerna` installed globally but when running `../../../scripts/buildup` in the package dir it complains that `lerna: not found`. 

Taking a look at the `node_modules/.bin` dir at the project root level I see the `lerna` symlink exists whereas in the package dir the subfolder `node_modules/.bin` does not contain the `lerna` symlink. 

[Fix 1338](https://github.com/awslabs/aws-cdk/pull/2667) only adds the `node_modules/.bin` to **PATH** but if `lerna` is not installed then it will still not work. Perhaps the buildup script needs to also add `../../../node_modules/.bin` to the **PATH** as it is the only place where `lerna` is installed

**Comment by hencrice** [comment]
I ran into the same issue that @mattmcclean mentioned. For now I had to run the following before invoking `buildup`:

```
$ ./install.sh
$ export PATH=$(npm bin):$PATH # put project-global lerna on the PATH
$ cd packages/@aws-cdk/aws-ecs
$ ../../../scripts/buildup
```
