### ISSUE TITLE
S3BucketBuildArtifacts ignoring "withIncludeBuildId" value

### ISSUE THREAD

**Issue by wmunyan** [awslabs/aws-cdk#1347]
When creating an S3BucketBuildArtifacts instance, using the S3BucketBuildArtifactsProps.builder() methods, specifically the `withIncludeBuildId`, it doesn't matter if I set the property to `true` or `false`.  When I execute `cdk synth` on my Stack, the Artifact always indicates a `NamespaceType: BUILD_ID`.  I'd like that to be "None".

Code snippet:
```
S3BucketBuildArtifacts codebuildS3BucketBuildArtifacts = new S3BucketBuildArtifacts(
	S3BucketBuildArtifactsProps.builder()
		.withBucket(deploymentBucket)
		.withPath("Workflow-Path")
		.withName("Workflow-Name")
		.withPackageZip(Boolean.FALSE)
		.withIncludeBuildId(Boolean.FALSE)  // doesn't matter what I put here...
		.build())
```
Thanks for any help/advice.

**Comment by RomainMuller** [comment]
I made a minimal reproduction using the sample you provided (thanks for that!) and it looks like there is a bug. Running `cdk synth` with `JSII_DEBUG=1` seems to indicate the `includeBuildId` property is never queried from the userland, which is unexpected.

**Comment by RomainMuller** [comment]
Found the issue to stem from how the property is named in TypeScript, which causes the dynamic override to be on an other name.

**Comment by RomainMuller** [comment]
Created an issue on JSII side to address the suboptimal behavior of the Java code generation that, if fixed, would have made this issue *much faster* to identify and fix.

**Comment by wmunyan** [comment]
Hello, 
I see that the fix for this has been included in release 0.21.0.  I have referenced the new version in my gradle project, but the issue persists.  Should the function name have changed to `withIncludeBuildID` (in the Builder for `S3BucketBuildArtifactsProps`)?

Thanks for any help!
Cheers, 
-Bill M.

**Comment by rix0rrr** [comment]
No, the correct name is still `withIncludeBuildId`.

**Comment by rix0rrr** [comment]
This is odd.

**Comment by rix0rrr** [comment]
I would prefer to wait for @RomainMuller to get back from holidays as he has more state on this issue and will be able to diagnose/validate the situation quicker.

**Comment by rix0rrr** [comment]
No problem, glad to hear it got solved!
