### ISSUE TITLE
cdk: cannot use intrinstic function as Tag value

### ISSUE THREAD

**Issue by tokkiyaa** [awslabs/aws-cdk#1369]
This Tag Definition can be applied in CloudFormation

```json
{
  "Key": "SampleKey",
  "Value": {
    "Fn::Join": ["-",[{"Ref": "SampleService"},"sample"]]
  }
}
```

But This Code causes compile Error.

```typescript
new s3.cloudformation.BucketResource(this, 'SampleBucket',
      {
        "accessControl": "Private",
        "bucketName": new cdk.FnJoin('-', [sampleService.ref,'sample']),
        "tags": [
          { "key": "Name", "value": new cdk.FnJoin('-', [sampleService.ref, 'sample']) },
        ]
      });
```

According to [intrinsic-function-reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) intrinsic-function can be used as Resource Tag Value.

So I guess `value` in [Tag's type definition](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/cloudformation/tag.ts) should accept Token other than string.

**Comment by eladb** [comment]
@tokkiyaa tokens that represent string values can be "stringified" via `.toString` so they can be assigned to string values.

In your case:



```ts
new s3.cloudformation.BucketResource(this, 'SampleBucket',
      {
        "accessControl": "Private",
        "bucketName": new cdk.FnJoin('-', [sampleService.ref,'sample']),
        "tags": [
          { "key": "Name", "value": new cdk.FnJoin('-', [sampleService.ref, 'sample']).toString() },
        ]
      });
```

You could even just use JavaScript back-quotes because `ref.toString()` will "Just Work":

```ts
value: `${sampleService.ref}-sample`
```

Closing for now. Let us know if this is still an issue.
