### ISSUE TITLE
Dev Guide should link to other good CDK educational resources

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#1383]
We should link to the CDK Workshop website in our Dev Guide.  Might even make sense to simplify our walkthroughs in the CDK Dev Guide and focus on sending developers to the workshop site: 
https://cdkworkshop.com/

The CDK re:Invent session also has a nice overview of the CDK and would be good to link from the Dev Guide:
https://www.youtube.com/watch?v=Lh-kVC2r2AU

**Comment by Doug-AWS** [comment]
I've already added a link to the workshop; I'll add a link to the re:Invent session soon.

**Comment by Doug-AWS** [comment]
I just added the link to the re:Invent 2018 demo to the guide. I'll publish it as soon as I can and close this once it's on the AWS docs site.

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/what-is.html#additional_docs
