### ISSUE TITLE
Add ECS Deploy Action for Codepipeline

### ISSUE THREAD

**Issue by aweiher** [awslabs/aws-cdk#1386]
Codepipeline can deploy to ESC-Cluster. Package `aws-ecs` need connectors for codepipeline, like `pipeline-actions.ts` in `aws-ecr`, but extends from `codepipeline-api.DeployAction`.

Allowed Input Artifacts: 1 [(image definition file)](https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-create.html#pipelines-create-image-definitions)
Allowed Output Artifacts: 0

See [(Action Type Constraints for Artifacts)](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements)  for all codepipeline actions

**Comment by madshargreave** [comment]
This would be awesome

**Comment by defel** [comment]
Hi, 

I would like to start working on this one :v:

**Comment by skinny85** [comment]
@defel go right ahead :) And thanks!

**Comment by skinny85** [comment]
Hey @defel ,

any progress working on this?

Thanks,
Adam

**Comment by defel** [comment]
Hej, sorry for the delay. Yes, still working on this. 

Had a blocker with extending ecs-cluster (`addToPipeline`). But just saw, that you have added new `codepipeline.DeployAction` helpers since january, which will help me.

Please give me a week more, will try to create a pull-request, thanks :)

**Comment by skinny85** [comment]
No worries, I was just checking in :). Thanks!
