### ISSUE TITLE
Add support for Lambda Layers in lambda.Function construct 

### ISSUE THREAD

**Issue by spg** [awslabs/aws-cdk#1399]
As of now, adding layers to a lambda function requires jumping through a few hoops:
```typescript
const entrypoint = new lambda.Function(this, 'MyFunc', {
    runtime: new Runtime("python3.7"),
    code: lambda.Code.asset("my_custom_python_func"),
    handler: "hello.my_handler"
});

const asset = new assets.ZipDirectoryAsset(this, 'SampleAsset', {
    path: path.join(__dirname, '../layers/my-layer')
});

const layer = new cdk.Resource(this, 'MyLayer', {
    type: 'AWS::Lambda::LayerVersion',
    properties: {
        Content: {
            S3Bucket: asset.s3BucketName,
            S3Key: asset.s3ObjectKey,
        }
    }
});

const functionResource = entrypoint.findChild('Resource') as lambda.cloudformation.FunctionResource;
functionResource.propertyOverrides.layers = [layer.ref];
```
Adding layers support to `lambda.FunctionProps` would simplify this process.

**Comment by eladb** [comment]
👍

**Comment by madshargreave** [comment]
👍

**Comment by spg** [comment]
Done in https://github.com/awslabs/aws-cdk/pull/1411

**Comment by yoslev** [comment]
The python version of cdk layer deployment for those who need:
import typing

from aws_cdk import (
    aws_lambda as _lambda,
    core,
    aws_iam)
from aws_cdk.aws_iam import PolicyStatement
from aws_cdk.aws_lambda import LayerVersion, AssetCode
from aws_cdk.core import Stack

class CdkLayersStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # 1) deploy lambda functions
        testLambda : _lambda.Function = CdkLayersStack.cdkResourcesCreate(self)

        # 2) attach policy to function
        projectPolicy = CdkLayersStack.createPolicy(self, testLambda)

    # -----------------------------------------------------------------------------------
    @staticmethod
    def createPolicy(this, testLambda:_lambda.Function) -> None:
        projectPolicy:PolicyStatement = PolicyStatement(
            effect=aws_iam.Effect.ALLOW,
            # resources=["*"],
            resources=[testLambda.function_arn],
            actions=[ "dynamodb:Query",
                      "dynamodb:Scan",
                      "dynamodb:GetItem",
                      "dynamodb:PutItem",
                      "dynamodb:UpdateItem",
                      "states:StartExecution",
                      "states:SendTaskSuccess",
                      "states:SendTaskFailure",
                      "cognito-idp:ListUsers",
                      "ses:SendEmail"
                    ]
        )
        return projectPolicy;
    # -----------------------------------------------------------------------------------
    @staticmethod
    def cdkResourcesCreate(self) -> None:
        lambdaFunction:_lambda.Function = _lambda.Function(self, 'testLambda',
                                                           function_name='testLambda',
                                                           handler='testLambda.lambda_handler',
                                                           runtime=_lambda.Runtime.PYTHON_3_7,
                                                           code=_lambda.Code.asset('functions'),
                                                           )
        ac = AssetCode("layers")
        layer  = LayerVersion(self, "l1", code=ac, description="test-layer", layer_version_name='Test-layer-version-name')
        lambdaFunction.add_layers(layer)

        return lambdaFunction
    # -----------------------------------------------------------------------------------
