### ISSUE TITLE
Figure out how package lock works and see if we need to use "npm ci" on our build servers

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1405]
I think npm is not using package-lock.json in our CI/CD, which can cause sneak up of breaking changes (such as additional tslint rules). This is also important for software assurance and build reproducibility.

**Comment by sam-goodwin** [comment]
Why do you think this?

**Comment by eladb** [comment]
https://docs.npmjs.com/cli/ci.html
