### ISSUE TITLE
AwsLogDriverProps interface property streamPrefix should be required

### ISSUE THREAD

**Issue by nathanpeck** [awslabs/aws-cdk#1422]
The `AwsLogDriverProps` interface has a property `streamPrefix`. This is currently not required by CDK, so you can `cdk synth` and attempt to `cdk deploy` the stack without specifying this property. However CloudFormation deployment will then fail with an error:

```
Fargate requires log configuration options to include awslogs-stream-prefix
to support log driver awslogs. (Service: AmazonECS; Status Code: 400;
Error Code: ClientException
```

Example code that reproduces the issue:

```js
    const definition = new ecs.FargateTaskDefinition(this, 'definition', {});
    definition.addContainer('my-app', {
      image: ecs.ContainerImage.fromAsset(this, 'my-app-image', { directory: './app' }),
      logging: new ecs.AwsLogDriver(this, 'my-app', {})
    });

    // Launch the image as a service in Fargate
    new ecs.FargateService(this, 'app', {
      cluster: cluster, 
      cpu: '256',
      memoryMiB: '512',
      desiredCount: 1,
      taskDefinition: definition
    });
```

Ideally this `streamPrefix` property should be marked as required by CDK for Fargate task definitions such that `cdk synth` and `cdk deploy` fail locally with an error message prior to sending the synthesized CF template off to CloudFormation

Alternatively perhaps CDK could choose to automatically fill the `streamPrefix` with the container name, as this is a fairly logical default.

**Comment by eladb** [comment]
If we have a good smart default, that's always the preferred option in the CDK.

**Comment by pkandasamy91** [comment]
The streamPrefix is already a required property.

**Comment by SoManyHs** [comment]
Can confirm: see https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/log-drivers/aws-log-driver.ts#L21
