### ISSUE TITLE
Unable to create a cognito user pool client

### ISSUE THREAD

**Issue by lestephane** [awslabs/aws-cdk#1426]
I don't know how to create a user pool's associated user pool client, as there does not seem to be a way to get the user pool `!Ref` when using the cloudformation resources, which I'm forced to use since there is no first class support for cognito user pools (and clients) in cdk just yet.

This is what i do without CloudFormation resources
(the "??????" marker shows where i don't know what to do)

```java
UserPoolResource userPool = new UserPoolResource(this,
                userPool().poolLogicalId(),
                UserPoolResourceProps.builder()
                        .withUserPoolName(userPool().poolName())
                        .withPolicies(
                                PoliciesProperty.builder()
                                        .withPasswordPolicy(
                                                PasswordPolicyProperty.builder()
                                                        .withMinimumLength(8)
                                                        .build())
                                        .build())
                        .build());


new UserPoolClientResource(this,
        userPool().clientLogicalId(),
        UserPoolClientResourceProps.builder()
                .withClientName(userPool().clientName())
                .withGenerateSecret(false)
                .withRefreshTokenValidity(30)
                .withUserPoolId(??????)
                .build());
```

**Comment by eladb** [comment]
You should be able to use either `userPool.getUserPoolId()` or `userPool.getRef()` to get a stringified token that represents the `!Ref`

**Comment by eladb** [comment]
Reopen if this doesn't resolve your issue

**Comment by eladb** [comment]
Hopefully this will be less confusing starting 0.22.0 as we have moved all of construct’s api under construct.node so hopefully the construct’s “id” property won’t be in the way.
