### ISSUE TITLE
Align docs to changes after AWS construct library renames

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1442]
See #1434

**Comment by Doug-AWS** [comment]
I've grepped all the user guide files and it looks like I have to update:

- XxxRefProps are now XxxImportProps
- XxxRef.import(...) are now Xxx.import(...) accept XxxImportProps and return IXxx
- Route53 record classes now require a zone when created (not assuming zone is the parent construct).

**Comment by Doug-AWS** [comment]
Done. The docs should be live by EOD tomorrow.

**Comment by Doug-AWS** [comment]
The updated docs are now live: https://docs.aws.amazon.com/CDK/latest/userguide
