### ISSUE TITLE
CDK Tutorial Steps Don't Work with cdk-init

### ISSUE THREAD

**Issue by rzigweid** [awslabs/aws-cdk#1452]
I am new to CDK, so I've been trying to follow the tutorial steps found at https://awslabs.github.io/aws-cdk/tutorial.html.  The sequence of commands that is stated amounts to:
```
mkdir hello-cdk
cd hello-cdk
git init
cdk init --language typescript
```

When this sequence of commands is run, an error is issued. 

```
`cdk init` cannot be run in a non-empty directory!
```

Removing the `.git` directory created from git init allows the `cdk init` command to run.   This appears to be because cdk init takes the step of creating `git init` for the user.  Documentation appears out of date. 

Version details: 
```
cdk --version
0.21.0 (build 9badc1c)
```
Running on MacOs Mojave

**Comment by eladb** [comment]
@rzigweid you are correct. Thanks for reporting. There is no need to manually `git init` before calling `cdk init`. @Doug-AWS assigning to you.

**Comment by Doug-AWS** [comment]
The user guide repo has moved. I've updated the doc source there and will update the README to reflect the change.
