### ISSUE TITLE
Cannot use `Condition` (or `condition.ref`) in `FnOr`

### ISSUE THREAD

**Issue by mipearson** [awslabs/aws-cdk#1457]
eg:

```yaml
    HasManagedPolicies:
      !Or [ { Condition: UseManagedPolicyARN }, { Condition: UseECR } ]
```

or even:

```yaml
    CreateMetricsStack:
      Condition: UseAutoscaling
```

It *feels* like I should be able to do this:

```typescript

    const useManagedPolicyARN = new cdk.Condition(...);
    const useEcr = new cdk.Condition(...);
    const hasManagedPolicies = new cdk.Condition(this, "HasManagedPolicies", {
      expression: new cdk.FnOr(
        useManagedPolicyARN,
        useEcr
      )
    });
```

But the `cdk.Condition` class does not match the type definition of the predicate functions (which require `FnCondition`.

After some mucking around, I found the following workaround, but it relies on `Fn` simply re-emitting exactly what it's passed:

```typescript
    const hasManagedPolicies = new cdk.Condition(this, "HasManagedPolicies", {
      expression: new cdk.FnOr(
        new cdk.Fn("Condition", "UseManagedPolicyARN"),
        new cdk.Fn("Condition", "UseECR")
      )
    });
```

This applies to referring to Conditions within `FnOr` and so forth within resources as well.

What is the correct way to express this in CDK?

**Comment by rix0rrr** [comment]
We've generally avoided Conditions so far, since we prefer expressing conditions in the CDK app.

I'm assuming you're using CDK to generate reusable templates that will be deployed by someone else?

**Comment by mipearson** [comment]
Yep, this is me evaluating CDK as "a tool to synthesize templates" rather than "a tool to manage AWS".

We're not big users of conditions anyway, but nice to have coverage.

That example unfortunately doesn't work - `ref` is a string, and `FnOr` expects an `FnCondition`.
