### ISSUE TITLE
Support for multiple instances of a cdk.App

### ISSUE THREAD

**Issue by BDQ** [awslabs/aws-cdk#1479]
The current definition of an environment for CDK seems to be an Account Id + Region pair, but what about a use case where we might want multiple instances of a single App in the same account / region?

In our use case, we want to have many separate staging/qa instances of a (multi-stack) cdk.App - and in some cases each App instance may include slight tweaks to the underlying CDK code.

As a workaround for now, I'm injecting the local branch name into the stack names for each app instance, as follows:

```typescript
  const app = new cdk.App();

  const registryStack = new RegistryStack(app, `mp-${branchSafe}-ecr`);
  new BuildStack(app, `mp-${branchSafe}-bld` });

  app.run();
```

It'd be great to have official support for environment / instance labels to allow multiple copies of the same app in the same account/region. Bonus points if it could leverage tags.

**Comment by rix0rrr** [comment]
As a design note, I think a higher-level `Construct` that:

* Can contain `Stack`s.
* Can set an `account/region` that applies to all stacks in it.
* Participates in the generation of the stack names

Should be sufficient to achieve this. Then that containing construct can be instantiated multiple times.

**Comment by BDQ** [comment]
@rix0rrr - #1940 looks great! Thanks for this, it'll really help clean up my code!
