### ISSUE TITLE
Support the new "Parameters" option of AWS Step Functions

### ISSUE THREAD

**Issue by guisrx** [awslabs/aws-cdk#1480]
AWS Step Functions released support for [Parameters](https://docs.aws.amazon.com/step-functions/latest/dg/input-output-inputpath-params.html) option in the input definition.

CDK should be able to define this attribute:

```typescript
    const initalTask = new stepfunctions.Task(this, "InitialTask", {
      resource: asyncLambda,
      parameters: {
        "task.$": "$.task"
      }
      inputPath: "$",
      outputPath: "$.state"
    }).next(nextTask);
```

**Comment by rix0rrr** [comment]
In the mean time, I hope you are aware you can use [CloudFormation overrides](https://awslabs.github.io/aws-cdk/aws-construct-lib.html#access-the-aws-cloudformation-layer) to work around the lack of support for now.

**Comment by guisrx** [comment]
I could not use the CloudFormation overrides because what I need is a property (on TaskProps) that will end up as a JSON object. I got it to work for now with this:

```typescript
    interface ParameterizedTaskProps extends sf.TaskProps {
      parameters: any;
    }

    class ParameterizedTask extends sf.Task {
      private parameterizedProps: ParameterizedTaskProps;

      constructor(parentConstruct: cdk.Construct, id: string, parameterizedProps: ParameterizedTaskProps) {
        super(parentConstruct, id, parameterizedProps);
        this.parameterizedProps = parameterizedProps;
      }

      public toStateJson(): object {
        const stateJson = {
          ...super.toStateJson(),
          Parameters: this.parameterizedProps.parameters
        };
        return stateJson;
      }
    }
```

**Comment by rix0rrr** [comment]
You are right, of course. Sorry!

**Comment by fabio-vitali** [comment]
commit d0c52832ec4df8e49f9ddef4bc8b8032019b54df has removed this... can this issue be reopened?

**Comment by davidleeshanok** [comment]
I'm unable to set Parameters on Step Functions tasks in CDK v1.3.

Can this issue be reopened?

**Comment by chechedotmx** [comment]
This is still missing in CDK v1.100.0

Again, can this issue be reopened?

**Comment by eiva** [comment]
I see this StepFunctionsInvokeActivity still have no parameters path.
I think this need to be reopened.
