### ISSUE TITLE
s3 notifications: be able to tag custom resource

### ISSUE THREAD

**Issue by ManRueda** [awslabs/aws-cdk#1497]
When S3 notifications is used, a custom Resource is created to allow this with a Lambda Function backing this custom resource ([fixed logicalId: BucketNotificationsHandler050a0587b7544547bf325f094a3db834](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts#L32)).

In our AWS structure we have to tag all resource with some values to be compliant with our internal rules. This internal Lambda resource is not expose in any way now (the only way is to copy the fixed logicalId and get it from the root with tryFindChild).

I was thinking in exposing this fixed id or the resource instance itself can be a good idea so tags can be added to the resource.

I am open to create a PR with the proposed changed.

Thanks!

**Comment by eladb** [comment]
@moofish32's PR #1451 should address this concern without needing to expose the underlying resource. @ManRueda you'll be able to simply apply a tag at any level and it will automatically propagate to all underlying resources. Would that address your use case?

**Comment by ManRueda** [comment]
It should cover my case but it's not happening. I am updating all my stack to use the tag propagation, the tags are correctly propagated to all resources but this Lambda created by BucketNotifications.

Here is a chunk of my `cdk diff` after my code update where i remove all the manual tagging.

```
[~] AWS::Lambda::Function BucketNotificationsHandler050a0587b7544547bf325f094a3db834 BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691
 └─ [-] Tags
     └─ [{"Key":"XXXX","Value":"XXXX"}...]
[~] AWS::Lambda::Function XXXXXX XXXXXAF403C3B
```

**Comment by moofish32** [comment]
@ManRueda let me verify a reproduction and add a test case here.

**Comment by moofish32** [comment]
@eladb -- we need to reopen this it's a bug. I didn't see this line: 

https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/notifications-resource/notifications-resource-handler.ts#L18

Since this is not actually a Lambda resource it doesn't get the `tags` attribute. I'll put in a quick fix, but not sure if we want to take a hard look at this cycle issue?
