### ISSUE TITLE
Support for VPC link between APIGW and Fargate Service

### ISSUE THREAD

**Issue by dotxlem** [awslabs/aws-cdk#1500]
I've implemented some changes in a fork to allow using API Gateway as a proxy to a Fargate service. I wanted to check here first if this is something that could be pushed back upstream, and if so how to go about it properly. 

There are changes to both aws-apigateway and aws-ecs, and I wasn't sure whether it was fine to make changes to both in the same PR if they're related.

**API Gateway Changes**
Added `connectionType` to the `IntegrationOptions`, to allow specifying VPC_LINK.
Added `requestParameters` to the `MethodOptions` to allow setting proxy path variable.

**ECS Changes**
For `LoadBalancedFargateService`:
 * Added `loadBalancerType` prop to allow specifying a Network Load Balancer.
* Added `containerEnvironment` prop to allow passing environment variables to the container.

I'm not using it personally, but for completeness it wouldn't be much effort to do the same for the `LoadBalancedEcsService`.

**Comment by rix0rrr** [comment]
I would love to pull those changes upstream!

I would insist that you make the same changes to `LoadBalancedEcsService` though, and also please don't forget to include tests!

**Comment by rix0rrr** [comment]
cc @SoManyHs

**Comment by dotxlem** [comment]
Great! I'll aim to get a PR up sometime later this week, assuming it doesn't take me too long to write tests and update `LoadBalancedEcsService`.
