### ISSUE TITLE
IRole vs Role types

### ISSUE THREAD

**Issue by cybergoof** [awslabs/aws-cdk#1506]
I'm having trouble understanding how I would import a role that has already been created, and use that role when creating a lambda function.   The ```Role.import``` returns a type IRole, which is not assignable to the props when creating a Lambda function.

**Comment by eladb** [comment]
This is a bug in our Lambda resource. It should accept an `IRole` and not a role. We are working on cleaning up those APIs.

If you are using typescript, as a temporary workaround, you might be able to add `as any` when you assign the role and hope for the test

Thanks for reporting!

**Comment by rix0rrr** [comment]
If so, that's a mistake in the Lambda construct, because you're doing it right.

Use a CloudFormation override to work around that for the time being.

**Comment by cybergoof** [comment]
holy smokes, I was going nuts trying to figure this out.  I'm new to Typescript so I couldn't figure out where I was going wrong.

Can you point me to what a CloudFormation override looks like?

**Comment by cybergoof** [comment]
```as any``` seems to be working.  Thanks for guidance.

**Comment by eladb** [comment]
Fixed by #1509

**Comment by badfun** [comment]
Looks like this problem has returned. I had the exact same issue, and the "as any" fix seems to work. My error is:
`Type 'Role' is not assignable to type 'IRole'.`
 
using cdk 1.89.0 (build df7253c)
