### ISSUE TITLE
CloudWatch events: multi-line target input template is broken

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/aws-cdk#1514]
When using `textTemplate`, the `TargetInputTemplate` tries to quote and escape the template, however when the template is multi-line, the quoting has to be different. This makes the multiline template invalid & unusable.

A (dirty) workaround is to use `jsonTemplate` instead, which will not incur any quoting and escaping action.

**Comment by coolprasanth** [comment]
> When using `textTemplate`, the `TargetInputTemplate` tries to quote and escape the template, however when the template is multi-line, the quoting has to be different. This makes the multiline template invalid & unusable.
> 
> A (dirty) workaround is to use `jsonTemplate` instead, which will not incur any quoting and escaping action.

Just the thing I was looking for. But I'm not sure what you mean by jsonTemplate. Can you please give some details/reference for it.

Regards
Prasanth
