### ISSUE TITLE
Missing topic about cross stack references

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1525]
Maybe we should wait until we finish with refactoring imports/exports but we definitely should add some documentation on automatic cross stack references and manual imports/exports between apps

**Comment by Doug-AWS** [comment]
FYI, we currently document the xrefs in "Passing in External Values to Your AWS CDK App", https://docs.aws.amazon.com/CDK/latest/userguide/passing_in_data.html

**Comment by Doug-AWS** [comment]
I'm moved the guts of "Passing in External Values to Your AWS CDK App" to the how-tos: https://alpha-docs-aws.amazon.com/CDK/latest/userguide/how_tos.html.

I'll likely bust each how-to out into a separate leaf soon.

**Comment by eladb** [comment]
@Doug-AWS is this on your plate? needs to be under "concepts"

**Comment by Doug-AWS** [comment]
Yes, I'm tracking this.

**Comment by Doug-AWS** [comment]
https://docs.aws.amazon.com/CDK/latest/userguide/passing_stack_value.html covers export/import. Am I correct in waiting on #1546 for the rest?

**Comment by Doug-AWS** [comment]
Done: https://docs.aws.amazon.com/cdk/latest/guide/use_cfn_template.html
