### ISSUE TITLE
lambda.PipelineInvokeAction.addInputArtifact missing from .NET

### ISSUE THREAD

**Issue by bfeinb** [awslabs/aws-cdk#1527]
The goal is to try and add a lambda.PipelineInvokeAction with an input artifact to a CodePipeline pipeline in CDK v0.22.  PipelineInvokeActionProps nicely now has an InputArtifacts property, but I can't construct an Artifact without specifying the action as the scope of the artifact.  The obvious way to accomplish this would be to use the addInputArtifact method on lambda.PipelineInvokeAction but this is missing in .NET.

**Comment by skinny85** [comment]
Hey @bfeinb ,

the way you get input artifacts is not by instantiating them directly, but from the outputs of previous Actions. Example:

```ts
const pipeline = new codepipeline.Pipeline(this, 'Pipeline');

const sourceStage = pipeline.addStage('Source');
const sourceAction = new codepipeline.GitHubSourceAction(this, 'GitHub', {
  // ...
}); // any other source would also work, of course

const fn = new lambda.Function(this, 'Lambda', {
  // ...
});
const lambdaStage = pipeline.addStage('Lambda');
fn.addToPipeline(lambdaStage, 'LambdaInvoke', {
  inputArtifacts: [
    sourceAction.outputArtifact,
  ],
});
```

You can also check out [the unit test for this functionality](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline/test/test.pipeline.ts#L269).

Hope this helps,
Adam

**Comment by bfeinb** [comment]
Yes, that is what I needed to do.  Thanks!
