### ISSUE TITLE
Can't specify kms.EncryptionKey for s3.BucketProps and codebuild.ProjectProps EncryptionKey property for .NET

### ISSUE THREAD

**Issue by bfeinb** [awslabs/aws-cdk#1530]
In the .NET v0.22 version of the CDK, Amazon.CDK.AWS.KMS.EncryptionKey doesn't implement the Amazon.CDK.AWS.KMS.IIEncryptionKey interface, therefore instances of EncryptionKey can't be stored in the EncryptionKey properties of s3.BucketProps and codebuild.ProjectProps which are of type IIEncryptionKey.  While I could import the key this prevents the automatic addition of the necessary permissions so that CodePipeline/CodeCommit/CodeBuild roles can access the encryption key.

**Comment by eladb** [comment]
when we rename EncryptionKey to Key, awslint would have caught this
