### ISSUE TITLE
Feature Request: Use `ts-node` rather than `npm watch` for boilerplate

### ISSUE THREAD

**Issue by mipearson** [awslabs/aws-cdk#1532]
This is a suggestion rather than a bug - something to consider for your boilerplate generated by `cdk init`:

In my CDK projects I've been doing the following:

```
cdk init sample-app
npm i ts-node
```

And then modifying the `cdk.json`:
```
{
  "app": "./node_modules/.bin/ts-node -T bin/cdk.ts"
}
```

The `-T` flag skips typechecking, speeding up runtime, as I generally have a test suite / editor that will get cross if there's a typing issue.

I've done this as the workflow is a bit easier day to day, and avoids a potential problem when sharing this code with others less familiar with TypeScript where they may not know that they need to compile it & keep that compilation up to date. I also anticipate that people will be directly resistant to this if they're used to Ruby/Python/etc.

**Comment by kennu** [comment]
Thanks @eladb for pointing to this suggestion in #539. I converted a monorepo project to use this approach (although without the -T option) and it seems to work quite well when sharing the package.json and tsconfig.json for the Stack and its Constructs. Maybe it also works when the Constructs are separate repos/packages but didn't really try it yet.

**Comment by mitchlloyd** [comment]
@rix0rrr Does the CDK team agree with this change? Happy to submit a PR if that is the case. For people getting introduced to TypeScript through CDK, the boostrapped experience is a little rough.

**Comment by eladb** [comment]
Sounds good to me. It will definitely reduce some friction. @Doug-AWS this will require some updates to sample code and workshop once it lands.
