### ISSUE TITLE
topic.subscribeQueue across stacks creates a cyclic dependency

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1534]
Repro:

```ts
import cdk = require('@aws-cdk/cdk');
import sns = require('@aws-cdk/aws-sns');
import sqs = require('@aws-cdk/aws-sqs');

const app = new cdk.App();

const stackWithTopic = new cdk.Stack(app, 'stack-with-topic');
const stackWithQueue = new cdk.Stack(app, 'stack-with-queue');

const queue = new sqs.Queue(stackWithQueue, 'MyQueue');
const topic = new sns.Topic(stackWithTopic, 'MyTopic');

topic.subscribeQueue(queue);

app.run();
```

Error:

```
Stack 'stack-with-topic' already depends on stack 'stack-with-queue'. Adding this dependency would create a cyclic reference.
```

This is because `sns.Subscription` references the queue and `sqs.QueuePolicy` references the topic. I wonder if the right solution to this is to create the subscription in the scope of the queue and not in the scope of the topic.

**Comment by eladb** [comment]
@rix0rrr what do you think?

**Comment by rix0rrr** [comment]
For this particular case, I think that's a pragmatic solution.

The generically correct way of dealing with these is to put the `QueuePolicy` into a 3rd stack (automatically), but we don't have support for that yet.
