### ISSUE TITLE
`grant`-ing dynamodb table constructs does not allow access to indices

### ISSUE THREAD

**Issue by mipearson** [awslabs/aws-cdk#1540]
Saw in my lambda output:
```
User: arn:aws:sts::REDACTED:assumed-role/REDACTED is not authorized to perform: dynamodb:Query on resource: arn:aws:dynamodb:us-east-1:REDACTED:table/REDACTED/index/uuid
```

cdk was set up as so:

```typescript
    const table = new dynamodb.Table(this, "Alerts", {...});
    table.addLocalSecondaryIndex({indexName: "uuid", ...});
    
    const fn = new lambda.Function(...);
    table.grantReadWriteData(fn.role);
```

Googling found me https://stackoverflow.com/questions/51537795/accessdenied-on-dynamodb-gsi-index

Applied a kind of hacky workaround to replace the `.grantReadWrite`:

```typescript
   fn.addToRolePolicy(
      new PolicyStatement()
        .addAction("dynamodb:*")
        .addResources(
          `${table.tableArn}/index/*`,
          table.tableArn,
        )
    );
```

This resolved the error.

Looking at the source, it looks like the dynamodb construct needs to call `addResource` once again for the index if one is defined.

**Comment by aveeday** [comment]
When I use `Table.fromTableArn` then there are no access to table indices with `grantReadData`

**Comment by skinny85** [comment]
@aveeday see #1445
