### ISSUE TITLE
RFC: Unique name generator

### ISSUE THREAD

**Issue by rsmogura** [awslabs/aws-cdk#1545]
# Overview

I would like to have unique name generator, so I can generate unique name during execution of CDK program and pass it to my construct (eg.: role name)

When name is uniquely generated it will be associated with parent construct and additional id (if for one construct I would like to have few names) and stored in `cdk.json`.

Subsequent calls for generate for same construct, Id, and options will return same name.

This way I would be able to commit `cdk.json` to repository and generate same stack in other environments.

In addition I would like to specify generation options, like characters used, upper lower case, max length (eventually it can be postfix or prefix, however simple random set of characters will solve my issue)

# Motivation

When generating cross-stack constructs some of those can be passed only with physical ARN. Knowing it’s name I would be able to synthesise it using resource ARN patterns.

Having such generator I would be able to transparently create roles for cross-account deployments in cross-account scaffold stacks (other pull request)

**Comment by eladb** [comment]
@rsmogura thanks for this. I am wondering: can you use `construct.node.uniqueId` for this purpose? It's an app-global unique ID that's available for all constructs.

**Comment by rsmogura** [comment]
> @rsmogura thanks for this. I am wondering: can you use `construct.node.uniqueId` for this purpose? It's an app-global unique ID that's available for all constructs.

Actually I thought about something similar, there's method `pathHash` it can be exported and I can pass to it `this.rootPath().map(c => c.node.id).push('MyId')`. I will close this issue
