### ISSUE TITLE
Support Service discovery in ECS

### ISSUE THREAD

**Issue by kraigor** [awslabs/aws-cdk#1554]
Hi,
it seems like there's no way to relate Discovery Service to Ec2Service.  Are there any plans on implementing this?
Thanks

**Comment by kraigor** [comment]
I found a workaround, here's an example (I hope it may be useful to somebody):
`var ns = new dis.CfnPrivateDnsNamespace(...
var discovery = new dis.CfnService(...
var service = new ecs.Ec2Service(...

var hook = ((<any>kt.service).resource as ecs.CfnService);
hook.propertyOverrides.serviceRegistries = [{
    registryArn: discovery.serviceArn
}];`

**Comment by nacitar** [comment]
An example workaround with the cfn escape hatch in c#:

```c#
// Assumes service and discoveryService are both defined.

// ABRITRARY BLOCK; ServiceRegistries isn't exposed in the cdk constructs
// https://github.com/aws/aws-cdk/issues/1554
{
    ECS.CfnService cfnService = service.Node.DefaultChild as ECS.CfnService
        ?? throw new Exception("If you see this, ECS.Ec2Service no longer wraps ECS.CfnService.");
    cfnService.ServiceRegistries = new[] {
        new ECS.CfnService.ServiceRegistryProperty {
            Port = 12345,
            RegistryArn = discoveryService.ServiceArn
        }
    };
}
```

The arbitrary block keeps the workaround from polluting the enclosing namespace.
