### ISSUE TITLE
Unresolved resource dependencies when using an exported VPC in another stack

### ISSUE THREAD

**Issue by BDQ** [awslabs/aws-cdk#1568]
I'm experiencing issues using the new 0.22.0 export mechanisms, in this case I'm trying to pass a VPC created in one stack into a ALB created in another - when running `deploy` it results in:

> test-app failed: ValidationError: Template format error: Unresolved resource dependencies [vpcIGWE57CBDCA] in the Resources block of the template

*app.ts*
```typescript
import cdk = require("@aws-cdk/cdk");
import { VpcStack } from "../lib/stacks/vpc-stack";
import { AppStack } from "../lib/stacks/app-stack";

const app = new cdk.App();

const vpcStack = new VpcStack(app, "test-vpc");
 
new AppStack(app, "test-app", {
  vpc: vpcStack.vpc
});

app.run();
```

*lib/stacks/vpc-stack.ts*
```typescript
import cdk = require("@aws-cdk/cdk");
import ec2 = require("@aws-cdk/aws-ec2");

export class VpcStack extends cdk.Stack {
  public readonly vpc: ec2.IVpcNetwork;

  constructor(parent: cdk.App, name: string) {
    super(parent, name);

    const vpc = new ec2.VpcNetwork(this, "vpc", {
      cidr: "10.0.0.0/24",
      maxAZs: 2
    });

    this.vpc = vpc;
  }
}
```

*lib/stacks/app-stacks.ts*
```typescript
import cdk = require("@aws-cdk/cdk");
import ec2 = require("@aws-cdk/aws-ec2");
import elbv2 = require("@aws-cdk/aws-elasticloadbalancingv2");

interface AppStackProps {
  vpc: ec2.IVpcNetwork;
}

export class AppStack extends cdk.Stack {
  constructor(parent: cdk.App, name: string, props: AppStackProps) {
    super(parent, name);

    new elbv2.ApplicationLoadBalancer(this, "lb", {
      vpc: props.vpc,
      internetFacing: true
    });
  }
}
```

I've created a [small repo](https://github.com/BDQ/cdk-alb-ref-issue) with a full app using this code, if it helps.

This issue only appears when `internetFacing: true` - if `false` the error doesn't occur.

**Comment by rix0rrr** [comment]
You are completely correct. We shouldn't be emitting those dependencies anymore.

**Comment by rix0rrr** [comment]
@eladb whaddaya reckon? Time for an overhaul of the dependency mechanism, or local fix at the template level? (Strip all dependencies that aren't in the same template)?

First one is better obviously, but I'm on the fence for releasing the fix quickly as well.

**Comment by BDQ** [comment]
Just a quick FYI for anyone else stuck on this in the short term, using the CFN override solves the problem. Thanks @rix0rrr for the pointer.

Added two lines after my ALB definition to manually drop the dependency.

```typescript
    const lb = new elbv2.ApplicationLoadBalancer(this, "lb", {
      vpc: props.vpc,
      internetFacing: true
    });

    const lbResource = lb.node.findChild("Resource") as elbv2.CfnLoadBalancer;
    lbResource.addOverride("DependsOn", []);
```

**Comment by eladb** [comment]
@rix0rrr How do you envision the overhaul of the dependency system (#95), which we should definitely do, solve this issue?

**Comment by rix0rrr** [comment]
If we take dependencies on constructs directly as you suggested, during `toCloudFormation` rendering we can determine if they are in the same stack or not (and replace the resource dependency with a stack dependency if we want to be very correct).
