### ISSUE TITLE
Getting latest version of the SSM parameter 

### ISSUE THREAD

**Issue by farminf** [awslabs/aws-cdk#1587]
Version for ParameterStoreStringProps is mandatory and number. 
https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-ssm.html#parameterstorestringprops-interface
I want to get the latest version of the parameter value.

**Comment by rix0rrr** [comment]
This is unfortunately not supported by CloudFormation using that construct for it. If you use a Secrets Manager value, you can retrieve the latest version.

However, you may be able to use a [`Parameter` configured for reading values from SSMPS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types).

**Comment by farminf** [comment]
Thanks,
Anyway, I got it without specifying version, like this:

```js
const { SSMParameterProvider } = require("@aws-cdk/cdk");

    value = new SSMParameterProvider(this, {
      parameterName: "/xxx/xxx",
    }).parameterValue();
```

**Comment by bskarda** [comment]
Here's an example of how to use a parameter to read the latest version from the SSMPS.
```js
const amiId = new cdk.Parameter(this,
  'AmiId',
  {
    type: 'AWS::SSM::Parameter::Value<String>',
    default: '/ami/sandbox/spark-standalone'
  }).ref;
```
