### ISSUE TITLE
Make it easier to explicitly control logical IDs

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1594]
When users migrate over from an existing CloudFormation deployment, they need control over logical IDs of resources. Our current approach based on renames is convoluted and we should improve the ergonomics.

**Comment by eladb** [comment]
We can make `resource.logicalId` return a lazy string (token) and then add something like `resource.overrideLogicalId('xxx')`.

When #1595 is implemented, the experience will be:

```ts
bucket.cfnresource.overrideLogicalId('MyAwesomeBucket');
```

**Comment by peterb154** [comment]
Thank you SOO Much for doing this.. just saved our bacon!
