### ISSUE TITLE
ux: IAM Statement Changes table is too big and unreadable sometimes

### ISSUE THREAD

**Issue by piotrkubisa** [awslabs/aws-cdk#1600]
Sometimes the summary table which starts with caption `IAM Statement Changes` during the `cdk deploy` is very big and does not fit the terminal with 200 characters width. It starts becoming unreadable if the arns and arns with paths are very specific like dynamodb index, or an Arn for a codebuild/lambda log groups. I think it would be nice to list in the tree rather than a table, so it will fit on smaller displays than 4K.

![screenshot from 2019-01-23 15-55-32](https://user-images.githubusercontent.com/3073499/51615112-59a9da00-1f27-11e9-89ae-346c081f5045.png)

**Comment by rix0rrr** [comment]
Was fixed in https://github.com/awslabs/aws-cdk/pull/1542, but hasn't been released yet.

**Comment by piotrkubisa** [comment]
Thanks, It looks way better in the new version :)
