### ISSUE TITLE
Update user guide with additional samples

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1601]
Here's a brain dump I've been gathering (there's no importance to the numbers, it'll just help us refer to the individual sample):

1. with account credentials (?),
2. professional CI/CD examples (not deployment from a dev desktop)
3. Multiple stacks in a single CDK app
4. Multiple stacks in multiple accounts
    e.g., want other developers to use the SNS topic in the master account.
6. Pass the ARNs in CDK apps around
7. Give SQS subscriptions permissions to the central topic
    Use SSM parameter store? Or ???
9. Deploy 3rd party services with CDK
10. Use custom resources, like Terraform
11. Deploy multiple stacks to multiple environments
12. CloudFormation stack sets support
13. Auditing, traceability, governance
14. Convert existing resource to CDK
15. Migration path
16. Pass a region to *AWS CDK* CLI

**Comment by Doug-AWS** [comment]
See also #1277 about testing.

**Comment by rix0rrr** [comment]
I don't think these are all created equal. Some of them are about the toolkit, some about writing the CDK app. We should split those out.

**Comment by rix0rrr** [comment]
"Samples" is also a little vague. Where were you seeing these subjects in the TOC?

**Comment by Doug-AWS** [comment]
I agree that "Samples" is vague. Most of these entries are what I've been calling a how-to, such as "How to Deploy a Stack to Multiple Environments". The entries should contain code that implements the task. 

The editor just finished looking at the guide. She pointed out that the AWS docs style is not to have a how-to section, but a "Using the CDK" section, so I'm going to make that change. The information won't change, just the heading.

For example, I will soon add a section on setting CloudWatch alarms. Originally I had the heading as "How-To: Set a CloudWatch Alarm", but once I rename the parent topic to "Using the CDK", the heading will be "Setting a CloudWatch Alarm", or something close to that.

**Comment by rix0rrr** [comment]
Can we make an argument against the AWS style headings or is that a losing battle?

**Comment by Doug-AWS** [comment]
The editor says we can keep the top-level heading, "How Tos", but shouldn't have each sub-section title starting with "How-To:", just the rest of the heading, like "Set a CloudWatch Alarm". Sound good?

**Comment by rix0rrr** [comment]
That sounds fine

**Comment by Doug-AWS** [comment]
I've split this up into separate issues.
