### ISSUE TITLE
Support AWS::Serverless::Application as a CDK Construct

### ISSUE THREAD

**Issue by jlhood** [awslabs/aws-cdk#1602]
allow CDK users to leverage the AWS::Serverless::Application SAM resource type in CDK apps.

https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapplication

**Comment by sam-goodwin** [comment]
So we currently have a package [@aws-cdk/aws-serverless](https://github.com/awslabs/aws-cdk/tree/master/packages/@aws-cdk/aws-serverless) generated from the follow specification files:
* Spec: https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/spec-source/000_sam.spec.json
* Patch File: https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/spec-source/100_sam.spec_DeploymentPreference_patch.json

The following PR attempts to translate the github description into a CFN spec: https://github.com/awslabs/aws-cdk/pull/1634

Do we have an official CFN spec for `Application`?
