### ISSUE TITLE
Reorganize and expand the user guide

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1607]
The current TOC for the guide (those with a + have sub-section):

What is the AWS Cloud Development Kit?
Install and Configure
Tutorial
+Concepts
+AWS Construct Library
+Examples
AWS CDK CLI
Writing Constructs
Document History

New Sections: **Tutorials** and **How-Tos**

- I'm are going to add another tutorial based on the CDK Workshop,
   so I'll create a top-level topic, Tutorials, and move the existing tutorial under it as "Hello World"
- The CDK Workshop tutorial will be called "Advanced Tutorial"
- I'll also include a brief synopsis at the beginning of both tutorials,
   explaining what it does and what you'll end up with when you're done.
- The top-level Tutorials topic will include a briefer version of the two synopsis.

I'm also going to add a **How-To** section, after **Tutorials** and before **Examples**.
Haven't decide where yet, but leaning toward right after **Tutorials**.
I liken a how-to to a cooking recipe.
Step 1, ...
Step 2, ...
...
Step N, 

We have a number of doc issues proposing specific how-to entries,
we just need to prioritize them, as that determines their order in the section.

So the guide TOC will soon be:

What is the AWS Cloud Development Kit?
Install and Configure
+Tutorials
+Core Concepts
+AWS Construct Library
+Examples
AWS CDK CLI
Writing Constructs
Document History

**Core Concepts** contains:

Constructs
Stacks
Logical IDs
Env and Auth
Apps
Passing in Data
Context
Assets
Applets

This will change to:

Apps and Stacks, which will also incorporate Env and Auth
Constructs
Logical IDs
Context
Assets

**Passing in Data** will be deleted and the content added as How-To sub-sections:

- How-To Get a Value from a Context Variable
- ...

- **Applets** will go away
- **Assets** will get some more love

I'll also add some blurbs to **Core Concepts** about the sub-sections.

**Comment by rix0rrr** [comment]
I would like to propose the following ToC: 

* What is the AWS Cloud Development Kit?
  * So you are coming from CloudFormation...
* Setup
* Tutorial (new)
  * Hello world tutorial
  * Serverless website tutorial
  * ECS tutorial
* Concepts
  * Core Concepts
    * Constructs
    * Apps and Stacks
    * Environments and Context
    * Assets
  * AWS Construct Library Concepts
    * IDs vs names
    * Grants
    * Security Groups
    * Metrics
    * Exports and imports
    * Event-driven APIs
* How To (in no particular order)
  * How to use secrets
  * How to create a Custom Resource
  * How to grant permissions
  * How to create multi-stacks apps
  * How to start EC2 instances in an AutoScaling Group
  * How to set up AutoScaling
  * How to deploy my application using a Pipeline
  * How to work around missing CDK features
  * How to set up monitoring
  * How to do complicated auth using the CLI
  * How to respond to CloudWatch events
  * How to control generated CloudFormation template
* Examples
* AWS CDK CLI
  * Auth using the CLI
* Writing Constructs
* Reference

> Haven't decide where yet, but leaning toward right after Tutorials.
> I liken a how-to to a cooking recipe. Step 1, Step 2, ... Step N

I think a different style of content is warranted for an Infrastructure-as-Code product, vs our usual products, and therefore docs. Previously, clicking in the console or running CLI commands had to be done in a particular order, so the "Step 1", "Step 2" paradigm made sense, but I don't think this is true for code. I think it's fine to give it all at once, and it will aid comprehension as well.

So what I'd prefer for the CDK is a short summary of the solution, then complete example code (with irrelevant parts omitted).

After the example code come *reasons why* or *things to keep in mind*, but the example code should come up front and center, all at once.

**Comment by Doug-AWS** [comment]
Okay, the How-Tos will have the format:

This section demonstrates how to _do something_.

// code

See Also
- link to ref
