### ISSUE TITLE
"Tutorial: Creating an AWS CDK Application" does not explain how to destroy the application

### ISSUE THREAD

**Issue by toolness** [awslabs/aws-cdk#1614]
Hi! Thanks for making this tool, it is making me much less afraid of AWS.

However, something I was confused by when running the [Creating an AWS CDK Application](https://awslabs.github.io/aws-cdk/tutorial.html) tutorial is that it doesn't explain how to _destroy_ the stack you created.  I ran `cdk --help` and it pointed me to a `cdk destroy` command, which sounded like the opposite of `cdk deploy`, so I tried it:

```
Are you sure you want to delete: HelloCdkStack (y/n)? y
HelloCdkStack: destroying...

 ✅  HelloCdkStack: destroyed
```

No errors were reported, so I thought everything created by `cdk deploy` would be undone.

However, when I looked at my AWS S3 console, it appeared that the S3 bucket that was part of my stack wasn't deleted.  Perhaps deleting S3 buckets isn't something the CDK explicitly does because it might result in data loss?  If this is the case, it'd be great if it told me that I had to manually delete it... Otherwise I feel unsettled because I'm not sure if there's other detritus laying about my AWS account as a result of tinkering with the CDK.

To inspire full confidence in the CDK, I think it'd be great to have a section at the very end of the tutorial that explains how to "uninstall" the application, so that users feel comfortable experimenting without accidentally polluting their AWS account.

**Comment by Doug-AWS** [comment]
I've added the following blurb at the end of the tutorial:

In some cases this command fails, such as when a resource isn't empty and must be empty before it can be deleted. See Delete Stack Fails in the AWS CloudFormation documentation for details.

Note that we are moving the guide to the official AWS Docs site. I'll post a link to the tutorial when I get the docs up.

**Comment by toolness** [comment]
Awesome, thanks @eladb and @Doug-AWS!

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/hello_world_tutorial.html#hello_world_tutorial_delete_stack
