### ISSUE TITLE
Implement KinesisEventSource in @aws-cdk/aws-lambda-event-sources

### ISSUE THREAD

**Issue by zmgehlke** [awslabs/aws-cdk#1650]
The CDK documentation suggests a roadmap of implementing all the event sources from here:
https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html

In particular, implementing Kinesis stream support for triggering Lambda handlers enables many IoT and data analysis workloads:
https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html#supported-event-source-kinesis-streams

Implementing this as a construct would be a large improvement to the CDK capabilities.

**Comment by eladb** [comment]
[coming up](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-event-sources/lib/kinesis.ts) in the next release (probably next week).
