### ISSUE TITLE
codepipeline: GitHubSourceAction should allow setup without polling or webhook

### ISSUE THREAD

**Issue by jesterhazy** [awslabs/aws-cdk#1652]
codepipeline.GitHubSourceAction takes a 'pollForSourceChanges' setting. If it is true, codepipeline will poll github for changes. If it is false, then cdk will automatically create a webhook and configure the pipeline use it as a trigger.

This is almost always the right thing to do.

But if you want to trigger a pipeline on a schedule, it would be great to be able to create a pipeline with both of these triggers disable.

There is a workaround to achieve this:

```
new codepipeline.GitHubSourceAction(this, construct_base_name + 'GitHubSource', {
    ... other settings ...
    // this is needed to prevent webhook creation, but we'll disable it later
    pollForSourceChanges: true
})

const cfnPipeline = pipeline.node.findChild('Resource') as codepipeline.CfnPipeline  		      cfnPipeline.addPropertyOverride('Stages.0.Actions.0.Configuration.PollForSourceChanges', false)
```

**Comment by jesterhazy** [comment]
Yes this is possible to set up in CP. It works. I have a setup where Cloudwatch scheduled events parameterized by pipeline name trigger a Lambda that triggers the pipeline.

**Comment by eladb** [comment]
@jesterhazy that's cool. good to know

**Comment by skinny85** [comment]
@eladb we can easily add another optional parameter to `GitHubActionProps` like `createWebhook?: boolean` that's `true` by default. If `pollForSourceChanges` is `false` (the default) and `createWebhook` is also `false`, it will result in a Pipeline that can only be triggered explicitly (it will not trigger simply from pushing to the GitHub repo).

My only worry is that it's such an edge case, I'm almost not sure if it's worth to have a separate property for it, and perhaps @jesterhazy's workaround is 'good enough' in those rare situations when you do need it...

Thoughts?

**Comment by eladb** [comment]
Sounds like this should be an enum

**Comment by skinny85** [comment]
What should be an `enum`?

**Comment by eladb** [comment]
Instead of `pollForSourceChanges` we could use an enum that allows users to pick one of the three options:

```ts
enum Trigger {
  None,
  Poll,
  WebHook,
}
```

**Comment by skinny85** [comment]
That's giving even more visibility to that edge case, which is the exact opposite of my intention here...

**Comment by eladb** [comment]
What's wrong with making this option visible? I think it's a perfectly viable option for people. We should obvsiouly default to the preferred option, but I don't see any reason to be opinionated about which options are more "visible" as long as the API is clear

**Comment by abrooksv** [comment]
What is the status of this?

**Comment by jesterhazy** [comment]
no idea. we are still using the workaround I mentioned in the issue description above.

**Comment by SanderKnape** [comment]
I'm also interested in this. We have some pipelines that only trigger on a schedule.
