### ISSUE TITLE
No VPCEndpointService construct

### ISSUE THREAD

**Issue by mattias-fjellstrom** [awslabs/aws-cdk#1659]
It appears that there is no construct for a VPCEndpointService (i.e [AWS::EC2::VPCEndpointService](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html))

Is there a plan to add a construct for this?

**Comment by eladb** [comment]
No short term plan. Happy to accept a PR

**Comment by ccurrie-amzn** [comment]
At this point there isn't even an L1 resource, as the resource type appears to be missing from the CloudFormation Resource spec.

**Comment by PatMyron** [comment]
[`AWS::EC2::VPCEndpointService`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html) is now in the [`us-east-1` resource specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)
