### ISSUE TITLE
CloudWatch Events: new classes for Targets

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#1663]
It probably makes more sense for CloudWatch Events to introduce special "integration classes" that allow typesafe specification of the `inputTemplate` blob that goes to the target. See for example this PR:

https://github.com/awslabs/aws-cdk/pull/1571

The following is pretty awkward and could be typesafe:

```ts
    rule.addTarget(target, {
      jsonTemplate: JSON.stringify({
        containerOverrides: [{
          name: 'TheContainer',
          environment: [{ name: 'I_WAS_TRIGGERED', value: 'From CloudWatch Events' }]
        }]
      })
    });
```

**Comment by rix0rrr** [comment]
Could be a non-breaking change if simply model it as an `IEventTarget` that has a template built-in, and we disallow combination of target-provided `inputTemplate` and user-provided `inputTemplate`.

**Comment by eladb** [comment]
Superseded by #2403 #2404 #2405
