### ISSUE TITLE
Doc Update: Passing external values

### ISSUE THREAD

**Issue by costleya** [awslabs/aws-cdk#1671]
https://awslabs.github.io/aws-cdk/passing-in-data.html

The sample code:
```ts
const bucket_name string = this.getContext("bucket_name");
```

Needs to be revised to:
```ts
const bucket_name: string = this.node.getContext("bucket_name");
```

1. You now have to retrieve context through a ConstructGraph node
2. Syntax error in the typescript

**Comment by Doug-AWS** [comment]
Thanks for the info. I'll update the docs. Note that the user guide is moving to the official AWS Docs site. I'll post the URL here when I get the docs up.

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/get_context_var.html
