### ISSUE TITLE
Unable to set instance parameter group on instances in rds.DatabaseCluster

### ISSUE THREAD

**Issue by aaronbrashears** [awslabs/aws-cdk#1693]
When building an rds.DatabaseCluster, there is no obvious way to associate an instance parameter group to instances in the cluster. Without this, there's no way to set common configuration like `log_min_duration_statement` or `shared_preload_libraries`.

**Comment by eladb** [comment]
As a workaround, can you use [escape hatches](https://docs.aws.amazon.com/CDK/latest/userguide/cfn_layer.html)?

**Comment by aaronbrashears** [comment]
I believe instantiating a `rds.CfnDBParameterGroup` and then set the `dbParameterGroupName` for every `﻿AWS::RDS::DBInstance` in the construct's children would work.

**Comment by aereal** [comment]
I also want this improvement.
There is any blocker on this issue?

If there is no problem, I'll send a pull request.

How about this? @eladb

**Comment by eladb** [comment]
@aereal +1

**Comment by aereal** [comment]
sent #2075
