### ISSUE TITLE
Running local CDK with NPX

### ISSUE THREAD

**Issue by spg** [awslabs/aws-cdk#1694]
Hey! I'm trying to run a locally installed version of the CDK, on a per-git-project basis. In other words, for each git project I work on, I want to use different CDK versions. 

For example, project A can require CDK v0.23.0 and project B can require CDK v0.22.0.
For this reason, I don't want to use a globally-installed CDK binary (i.e. `npm install -g aws-cdk`).
What I want to do is install the CDK locally (i.e. `npm install aws-cdk`) in each separate project and leverage `npx` to interact with the CDK. 

This should work fine in theory. However, the CDK complains if I try to `init` in a non-empty directory:
```
 npx cdk init app --language=typescript
`cdk init` cannot be run in a non-empty directory!
```
I guess this is expected, since my current directory contains `node_modules` and `package-lock.json` (both resulting from the local installation of the CDK).

Is there a workaround for that?

**Comment by skinny85** [comment]
Hey @spg ,

the way you can work around that, is to do `npx cdk init app --language=typescript` in a sub-directory of the directory you have the `package.json` and `node_modules` with the specific version of `aws-cdk`. NPX will traverse up the file hierarchy looking for the command.

Let me know if this works!

Adam

**Comment by spg** [comment]
Yes that worked, thanks!
