### ISSUE TITLE
apigateway: missing support for models

### ISSUE THREAD

**Issue by john-shaskin** [awslabs/aws-cdk#1695]
When defining a REST API with API gateway, we can't currently define a collection of models that can be used to map response payloads from an integration to what is returned to a client.

https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html

https://github.com/awslabs/aws-cdk/pull/1572 introduces the base support for MethodResponses, but only gives the functionality to use the default provided `Empty` and `Error` models that are generated, when you create a REST API. This work should be continued to provide full support for defining models.

**Comment by john-shaskin** [comment]
Starting to look into this one.

**Comment by eladb** [comment]
👍

**Comment by john-shaskin** [comment]
I've been slow at working on this. Think I've got most of the changes sorted out. Just trying to wrap enough testing around creating and consuming models. Will try to get a PR open soon, to get some discussion going.

**Comment by eladb** [comment]
Thanks for the update! Looking forward

**Comment by john-shaskin** [comment]
PR https://github.com/awslabs/aws-cdk/pull/2102 has been opened to address this issue.
