### ISSUE TITLE
Partitions

### ISSUE THREAD

**Issue by mindstorms6** [awslabs/aws-cdk#17]
If there's one thing I love about AWS - it's how everywhere we are 🌐 🌏 🌍 🌎!

Downside, there's a lot of fun that goes into making templates not tied to a region/partition.

I don't think it's in many places, but I happened to find one spot (addressed in #16 ) where we had hardcoded partition in a string arn construction.

We should avoid those types of bugs :)

This just serves as a high level tracking item to remove any references to partitions/regions.

Some places to check: 
* ARN construction with region or partition info (of resources or policies)
* Service Principals (they can, though, should not often) vary per partition
* S3 "domain endpoints" ( `mybucket.s3.amazonaws.com`, `mybucket.s3.amazonaws.com.cn`)

**Comment by rix0rrr** [comment]
This issue is not really actionable (anymore?) so in the interest of clearing up our backlog I'm going to close it. If we detect places where we're doing it wrong, we can create new issues.
