### ISSUE TITLE
Documentation Broken

### ISSUE THREAD

**Issue by CLowenthal-zmi** [awslabs/aws-cdk#1710]
https://awslabs.github.io/aws-cdk/getting-started.html is returning a 404.

All that is visible on the welcome page is the Reference sections, and none of the previously available documentation.

**Comment by rix0rrr** [comment]
The user guide has moved: https://docs.aws.amazon.com/CDK/latest/userguide/what-is.html

There is a PR out to update the links: https://github.com/awslabs/aws-cdk/pull/1712

**Comment by debora-ito** [comment]
Hi @CLowenthal-zmi, apologies for the inconvenience. The links in README were updated, so please check the new docs.

Closing this, feel free to reopen if you have further questions.
