### ISSUE TITLE
Bug: PipelineProject badge error

### ISSUE THREAD

**Issue by seawatts** [awslabs/aws-cdk#1749]
When creating a new PipelineProject I get an error when trying to enable badge

```ts
 const project = new codebuild.PipelineProject(this, 'TestProject', {
      environment: {
        buildImage: codebuild.LinuxBuildImage.UBUNTU_14_04_NODEJS_8_11_0
      },
      badge: true
    });
```

```
UPDATE_FAILED  | AWS::CodeBuild::Project  | TestProject (TestProjectF1529E8A) Failed to call UpdateProject, reason: Build badges are not supported for CodePipeline source (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; 
```

**Comment by eladb** [comment]
As the error says, I don't believe badges are supported for a PipelineProject, you should use a regular `codebuild.Project` construct instead.

We should add a validation in `PipelineProject` (or even better, remove this property from `PipelineProject`).

**Comment by seawatts** [comment]
Ah ha, yeah I just noticed that. Yeah probably should take it out then.

**Comment by jamiepmullan** [comment]
Hey @eladb & @skinny85 - are there any plans to fix this? i.e. so you can use `PipelineProject` and badges?

**Comment by skinny85** [comment]
Hi @jamiepmullan ,

like the error says:

```
UPDATE_FAILED  | AWS::CodeBuild::Project  | TestProject (TestProjectF1529E8A) Failed to call UpdateProject, reason: Build badges are not supported for CodePipeline source (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; 
```

this is actually a CodeBuild limitation - there's nothing we can do in the CDK to ad support for these, since the service itself doesn't support this usecase.

Sorry!

**Comment by mmuller88** [comment]
With today I released an AWS CDK custom construct for creating badges with using a lambda https://github.com/mmuller88/aws-cdk-build-badge
