### ISSUE TITLE
allow `cdk init` in non-empty directory

### ISSUE THREAD

**Issue by Vandivier** [awslabs/aws-cdk#1758]
step 1 - create empty repo
step 2 - cd in and `cdk init app --langugage=...`

receive `cdk init` cannot be run in a non-empty directory!

This is probably because of the hidden .git folder no? Why should that be problematic for the cdk? I think we should allow this. It can be worked around by making an arbitrary dir, but why should we do that? On second thought, I think we should allow `cdk init` if no conflicting folders/files exist. On third thought, we might just notify the user and allow them to y/n eg "You ran cdk init but README.md already exists which conflicts with aws-cdk. If you proceed the prior file will be overwritten."

Thoughts?

**Comment by Lilja** [comment]
It would be amazing if this also could be supported for when you create an subdirectory in your app like this:
```
$ mkdir infra && cd infra
$ yarn add -D aws-cdk
$ yarn cdk init --language=python
error: cannot be run in a non-empty directory
```
