### ISSUE TITLE
VpcNetworkProvider documentation results in an error

### ISSUE THREAD

**Issue by cynicaljoy** [awslabs/aws-cdk#1770]
The [provided example](https://docs.aws.amazon.com/CDK/latest/userguide/context.html) for using the VpcNetworkProvider doesn't work.

```
const provider = new VpcNetworkProvider(this, {
  tags: {
    Purpose: 'WebServices'
  }
});
```

`cdk synth` **Result:** The filter 'Purpose' is invalid

In order to get it to work I had to change the key to:

```
const provider = new VpcNetworkProvider(this, {
  tags: {
    "tag:Purpose": 'WebServices'
  }
});
```

`cdk synth` **Result:** \<CloudFormation YAML\> as expected

The ideal solution would be for the VpcNetworkProvider to automatically prepend "tag:" to any keys in the `tags` map.

**Comment by Doug-AWS** [comment]
I've updated the doc source. I should have the fix live by EOD tomorrow.

**Comment by Doug-AWS** [comment]
See VpcNetworkProvider under https://docs.aws.amazon.com/CDK/latest/userguide/environments_and_context.html
