### ISSUE TITLE
@aws-cdk/aws-codebuild :: Project missing vpcConfig property.

### ISSUE THREAD

**Issue by DavidChristiansen** [awslabs/aws-cdk#1775]
### Issue 

`codebuild.Project` does not allow a codeBuild project to have VPC configuration defined as per [CloudFormation definition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-vpcconfig.html).

### Expectation

A codebuild project should have a VPC Config property akin to :

```typescript
        this.CodeBuildProject = new codebuild.Project(stack, 'BuildProject', {
                ...
                vpcConfig = {
                        vpcId: myVPC.vpcId,
                        securityGroupIds: [myCodeBuildSecurityGroup.securityGroupId],
                        subnets: myVPC.privateSubnets
                }
                ...
        }
```

### Workaround

1. Define a service role to be used by the CodeBuild Project
```typescript
        const buildRole = new iam.Role(this, 'CodeBuildRole', {
            assumedBy: new iam.ServicePrincipal('codebuild.amazonaws.com'),
            path: '/'
        });
```
2. Define a policy statement that provides the service role with permissions to perform the required ec2 actions.  Add statement to service role.

```typescript
        const ec2PolicyStatement = new iam.PolicyStatement(iam.PolicyStatementEffect.Allow);
        ec2PolicyStatement.addAllResources();
        ec2PolicyStatement.addActions('ec2:DescribeSubnets', 'ec2:DescribeSecurityGroups', 'ec2:DescribeDhcpOptions', 'ec2:DescribeVpcs');
        buildRole.addToPolicy(ec2PolicyStatement);
```
3. Assign service role to code build project
```typescript
        this.CodeBuildProject = new codebuild.Project(stack, 'BuildProject', {
            ...
            role: buildRole,
            ...
        });
```
4. Perform [escape hatch method ](https://docs.aws.amazon.com/CDK/latest/userguide/cfn_layer.html)to define vpcConfig properties.

```typescript
        const project = this.CodeBuildProject.node.findChild('Resource') as codebuild.CfnProject
        project.propertyOverrides.vpcConfig = {
            vpcId: myVPC.vpcId,
            securityGroupIds: [myCodeBuildSecurityGroup.securityGroupId],
            subnets: myVPC.privateSubnets
        }
```

### Actions

- [ ] @DavidChristiansen to implement and produce PullRequest

**Comment by skinny85** [comment]
Thanks for opening the issue @DavidChristiansen !

Just one note on the implementation front: most likely, the Project should take a new, optional property when being constructed, `vpc` of type `ec2.VpcNetwork`, from the `aws-ec2` Construct Library.

**Comment by DavidChristiansen** [comment]
The way it's going vpcConfig will be an optional property and it will look like this: 

```typescript
const stack = new cdk.Stack(app, 'aws-cdk-codebuild-project-vpc');
const vpc = new ec2.VpcNetwork(stack, 'MyVPC');
const securityGroup = new ec2.SecurityGroup(stack, 'SecurityGroup1', {
    groupName: 'Bob',
    vpc: vpc,
    allowAllOutbound: true,
    description: 'Example',
});
new Project(stack, 'MyProject', {
    vpcConfig: {
        vpc: vpc,
        vpc_securityGroupIDs: [securityGroup.securityGroupId],
        vpc_subnets: [vpc.privateSubnets[0].subnetId]
    }
});
```

**Comment by cjyclaire** [comment]
+1 for adding this support
