### ISSUE TITLE
add hook for deployment-time validation

### ISSUE THREAD

**Issue by jesterhazy** [awslabs/aws-cdk#1784]
cdk should provide a hook for deployment-time validation checks.

for example, consider an app that includes two stacks... a Dev stack with implicit environment, and a Prod stack with explicit prod account/region set.

When I run my stack with prod credentials, there is nothing to prevent me from deploying my Dev stack into my prod account (and probably causing many problems that way).

I'd like to add a check somewhere in the Dev stack code to say `if (currentAccount === prodAccount) throw Error(...)`, but this means I the app doesn't work at all when run with Prod credentials (even cdk list throws the account check error).

Ideally, if I added this check in this new hook, I'd only get the error if i try diff/deploy/destroy the Dev stack.

**Comment by rix0rrr** [comment]
I think your solution would be to not throw an Error but instead use 

```
this.node.addError()
```

to attach an error to the current construct node. This  will not abort your program but WILL prevent the  stack from deploying.

**Comment by jesterhazy** [comment]
@rix0rrr I tried the solution you suggested... every op, even `cdk list` throws the dev-related error if I run under prod credentials, so this won't work.
