### ISSUE TITLE
CDKWorkshop: documentation links on Congrats! page broken

### ISSUE THREAD

**Issue by ccfife** [awslabs/aws-cdk#1787]
The broken doc links are on this page:
https://cdkworkshop.com/70-conclusion.html

The examples link too.

**Comment by debora-ito** [comment]
The `Version Reporting` link on the bottom of the `New Project > cdk synth` page is also broken.

**Comment by Doug-AWS** [comment]
- "Get started" -> https://docs.aws.amazon.com/CDK/latest/userguide/install_config.html
- "CDK Concepts" -> https://docs.aws.amazon.com/CDK/latest/userguide/concepts.html
- "Constructs" -> https://docs.aws.amazon.com/CDK/latest/userguide/constructs.html
- "Stacks" -> https://docs.aws.amazon.com/CDK/latest/userguide/apps_and_stacks.html#stacks (or replaced with [Apps and Stacks](https://docs.aws.amazon.com/CDK/latest/userguide/apps_and_stacks.html)
- "Logical IDs" -> https://docs.aws.amazon.com/CDK/latest/userguide/logical_ids.html
- "Environments" -> [Environments and Context[(https://docs.aws.amazon.com/CDK/latest/userguide/environments_and_context.html)
- "Apps" should go away
- "Passing in Values" -> [How-To Get External Values[(https://docs.aws.amazon.com/CDK/latest/userguide/how_to_get_ext_values.html)
- "Environmental Context" should go away
- "Asssets" -> https://docs.aws.amazon.com/CDK/latest/userguide/assets.html
- "Applets" should go away
- "AWS Construct Library" -> https://docs.aws.amazon.com/CDK/latest/userguide/aws_construct_lib.html
- "write your own constructs" -> https://docs.aws.amazon.com/CDK/latest/userguide/writing_constructs.html
- "examples" -> https://github.com/aws-samples/aws-cdk-examples

**Comment by Doug-AWS** [comment]
Source is in https://github.com/aws-samples/aws-cdk-intro-workshop

**Comment by Doug-AWS** [comment]
I've fixed the links here: https://github.com/aws-samples/aws-cdk-intro-workshop/pull/27
