### ISSUE TITLE
Cannot use cdk.Token in the codepipeline.Pipeline

### ISSUE THREAD

**Issue by piotrkubisa** [awslabs/aws-cdk#1788]
During creation of the CodePipeline CI/CD pipeline I noticed it is not possible to use `cdk.Token` values in the `pipelineName`, because following property is always validated against string.

Having following configuration (`this` = `cdk.Stack`)...:

```ts
    const pipeline = new codepipeline.Pipeline(this, 'Pipeline', {
      pipelineName: this.stackName,
      artifactBucket,
    })
```

... I will encounter following command when trying to synthesize template:

```console
/some_project/_cdk/node_modules/@aws-cdk/aws-codepipeline-api/lib/validation.ts:48
    throw new Error(`${thing} name must match regular expression: ${VALID_IDENTIFIER_REGEX.toString()}, got '${name}'`);
          ^
Error: Pipeline name must match regular expression: /^[a-zA-Z0-9.@_-]{1,100}$/, got '${Token[my-stack.AWS::StackName.79]}'
    at Object.validateName (/some_project/_cdk/node_modules/@aws-cdk/aws-codepipeline-api/lib/validation.ts:48:11)
```

May `cdk.Token` be whitelisted as a value for `pipelineName` property?

**Comment by eladb** [comment]
Yes, we should not validate the name if it's a token (`cdk.unresolved` would return `true` in that case and we should forgo validation).
