### ISSUE TITLE
Allow to specify GitCloneDepth in codebuild.Project

### ISSUE THREAD

**Issue by piotrkubisa** [awslabs/aws-cdk#1789]
While defining the source in `codebuild.Project` resource I noticed [GitCloneDepth](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-gitclonedepth) property is missing. Hopefully, it is available in the `codebuild.CfnProject`.

**Comment by skinny85** [comment]
Yep, this is a gap. Thanks for reporting @piotrkubisa .
