### ISSUE TITLE
pull request template: require docs website to be uploaded when making changes in this area

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1793]
COE action: to reduce the chance of corrupted documentation website, require that docs website will be uploaded to e.g. s3 static web site and shared as part of any PR in that area

**Comment by rix0rrr** [comment]
I think the ops pipeline should be able to do this automatically in a dev version of the pipeline.

**Comment by eladb** [comment]
> I think the ops pipeline should be able to do this automatically in a dev version of the pipeline.

Interesting idea, but people usually just push to a branch for PR. How do you envision the set up that allows people to review the documentation website output as part of a PR?

**Comment by rix0rrr** [comment]
The code to build the docs website lives in the cdk-ops  repository, so gets updated as part of PR to the ops repo. A dev pipeline could be built from the PR code, which could publish to a temporary bucket.

**Comment by eladb** [comment]
What happens if there are multiple PRs against the docs generation code? Which one is picked up by the dev pipeline and deployed?

**Comment by rix0rrr** [comment]
I would say everyone has their own copy (like the `cdk-dev-benisrae` pipelines we use to have, but shorter lived.

**Comment by fulghum** [comment]
@RomainMuller – do you have time to add this to the PR template as part of on-call tasks?
