### ISSUE TITLE
Cross Account Cloudformation ChangeSet

### ISSUE THREAD

**Issue by bensechrist** [awslabs/aws-cdk#1794]
I am in the process of writing a CDK app that creates a CodePipeline that deploys to a stage in another account. In CloudFormation I can change the RoleArn for the CodePipeline Action and for the configuration of the CloudFormation ChangeSet but when I try doing this in CDK I get the following error:

> Error: Can only reference cross stacks in the same region and account.

Is there a way to do this currently?

**Comment by rix0rrr** [comment]
You have to build the ARN manually from well-defined parts (not resource attributes) using `stack.formatArn()`.

**Comment by bensechrist** [comment]
There doesn't appear to be anyway to include an ARN manually in either [PipelineCreateReplaceChangeSetAction](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-cloudformation.html#pipelinecreatereplacechangesetaction) or [PipelineExecuteChangeSetAction](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-cloudformation.html#pipelineexecutechangesetaction)

**Comment by skinny85** [comment]
Hey @bensechrist ,

I'm actually working on this functionality as we speak :). It involves some framework changes, so I can't promise when it'll be released, but rest assured we're aware of this use-case, and working hard on making it awesome :).

In the mean time, like Rico said, you need to import and `IRole` using `Role.import(this, 'Role', {
  roleArn: yourArnHere,
})`, and then pass this `role` as a property when creating either a `PipelineCreateReplaceChangeSetAction` or a `PipelineExecuteChangeSetAction`.

Thanks,
Adam

**Comment by bensechrist** [comment]
Thanks! That fixed the issue around the role but now I get the same error when I try to set the region to anything.

**Comment by rix0rrr** [comment]
Could you give an example? I don't understand what "set the region to anything" means.

**Comment by bensechrist** [comment]
When setting the [region param](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-cloudformation.html#@aws-cdk/aws-cloudformation.PipelineCreateReplaceChangeSetActionProps.region) to 'us-east-1' with the pipeline in 'us-west-2' and passing in an imported role for the `role` and `deploymentRole` properties it gives me that error.

**Comment by rix0rrr** [comment]
Could you reduce to a minimal reproducing example? Unfortunately, our error reporting here is a little lacking and it's hard for me to judge from the error message alone.

**Comment by bensechrist** [comment]
```javascript
const region = 'us-east-1'; // Current stack and Pipeline are in us-west-2
const crossAccountRoleArn = `arn:aws:iam::${crossAccountId}:role/CrossAccountRole`;
const cloudformationRoleArn = `arn:aws:iam::${crossAccountId}:role/CloudformationRole`;
const crossAccountRole: iam.IRole = iam.Role.import(this, 'CrossAccountRole', {
  roleArn: crossAccountRoleArn
});
const cloudformationRole: iam.IRole = iam.Role.import(this, 'CloudformationRole', {
  roleArn: cloudformationRoleArn
});
new PipelineCreateReplaceChangeSetAction(this, `MakeChangeSet${stage}-${region}`, {
  region,
  stackName,
  changeSetName,
  stage: stageSpecificStage,
  runOrder: 1,
  adminPermissions: false,
  role: crossAccountRole,
  deploymentRole: cloudformationRole,
  capabilities: CloudFormationCapabilities.AnonymousIAM,
});
```

Removing the region parameter gets rid of the error.

**Comment by rix0rrr** [comment]
Unfortunately that example was not complete. I tried the following and did not reproduce the error.

Can you try this code, or paste your full reproducing example?

```ts
import { CloudFormationCapabilities, PipelineCreateReplaceChangeSetAction } from '@aws-cdk/aws-cloudformation';
import codepipeline = require('@aws-cdk/aws-codepipeline');
import { Artifact, ArtifactPath } from '@aws-cdk/aws-codepipeline-api';
import iam = require('@aws-cdk/aws-iam');
import cdk = require('@aws-cdk/cdk');
import { Secret } from '@aws-cdk/cdk';

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, { env: { account: '13255', region: 'eu-west-1' }, ...props});

    const crossAccountId = 'ap-southeast-1';
    const stage = 'prod';
    const stackName = 'Henk';
    const changeSetName = 'Biertje';

    const pipeline = new codepipeline.Pipeline(this, 'Pipeline', {
    });

    const sourceStage = new codepipeline.Stage(this, 'SourceStage', {
      pipeline
    });
    const action = new codepipeline.GitHubSourceAction(this, 'Action', {
      owner: 'bier',
      repo: 'lekker',
      stage: sourceStage,
      oauthToken: new Secret()
    });

    const region = 'us-east-1'; // Current stack and Pipeline are in us-west-2
    const crossAccountRoleArn = `arn:aws:iam::${crossAccountId}:role/CrossAccountRole`;
    const cloudformationRoleArn = `arn:aws:iam::${crossAccountId}:role/CloudformationRole`;
    const crossAccountRole: iam.IRole = iam.Role.import(this, 'CrossAccountRole', {
      roleArn: crossAccountRoleArn
    });
    const cloudformationRole: iam.IRole = iam.Role.import(this, 'CloudformationRole', {
    roleArn: cloudformationRoleArn
    });

    const stageSpecificStage = new codepipeline.Stage(this, 'Stage', {
      pipeline
    });
    new PipelineCreateReplaceChangeSetAction(this, `MakeChangeSet${stage}-${region}`, {
      region,
      stackName,
      changeSetName,
      stage: stageSpecificStage,
      runOrder: 1,
      adminPermissions: false,
      role: crossAccountRole,
      deploymentRole: cloudformationRole,
      templatePath: new ArtifactPath(new Artifact(action, 'henk'), 'asdf'),
      capabilities: CloudFormationCapabilities.AnonymousIAM,
    });
  }
}

```

**Comment by bensechrist** [comment]
I discovered the problem was I was creating my own `crossRegionReplicationBuckets` and was using the `bucketName` reference. When I changed that to the static bucket name, I don't get the error any more.
