### ISSUE TITLE
context.default-region is no longer supported. But docs still states it is a possible option.

### ISSUE THREAD

**Issue by seanyu4296** [awslabs/aws-cdk#1803]
I'm getting this error 
```
The 'context.default-region' key was found in /Users/seanyu/Zap/test-cdk-static/cdk.json, but it is no longer supported. Please remove it.
```
when i  run ``cdk deploy`` when my cdk.json have default-region
```json
{
  "app": "node dist/cdk/index",
  "context": {
    "default-region": "ap-southeast-1",
  }
}
```
but it states in the docs https://docs.aws.amazon.com/CDK/latest/userguide/awscdk.pdf Environment and Aunthentication section that it still supports it.

**Comment by rix0rrr** [comment]
cc @Doug-AWS

**Comment by seanyu4296** [comment]
is there an alternative to having a "default" region aside from writing it directly in code?

**Comment by rix0rrr** [comment]
No. We recommend you specify your region directly in the code. If you want to deploy the same stack to multiple regions, instantiate all of them and give each of them a different region.

**Comment by seanyu4296** [comment]
Got it! @rix0rrr

**Comment by Doug-AWS** [comment]
What about default-account? Does that go away also?

**Comment by Doug-AWS** [comment]
Should I just delete:

Otherwise, read default-account and default-region from the application's context. These can be set in the AWS CDK Toolkit in either the local cdk.json file or the global version in $HOME/.cdk on Linux or MacOS or %USERPROFILE%\\.cdk on Windows.

**Comment by rix0rrr** [comment]
Yes, please.

**Comment by Doug-AWS** [comment]
Done. The change will be visible when I rebuild the docs. I'll post a link to the new docs when I'm done.

**Comment by seanyu4296** [comment]
Thanks @Doug-AWS !

**Comment by Doug-AWS** [comment]
Both the online and PDF versions no longer include that passage.
