### ISSUE TITLE
Add install instructions for Cloud9

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/aws-cdk#1809]
Apparently, Cloud9 instances come with `node@6` preinstalled, however we require `node@8`. Since Cloud9 is a controlled environment that we (I mean AWS) also own, we should provide specific instructions to run `nvm install 8` so that `node@8` is available in the instance.

**Comment by Doug-AWS** [comment]
Cloud9 has a sample on using the CDK. I link to it in the "Additional Resources and Documentation" section of the docs: https://docs.aws.amazon.com/CDK/latest/userguide/what-is.html#additional_docs. The sample has the user install the latest version of node. I'll give Paul the prerequisites for the CDK and he can add that info to the Cloud9 doc sample.
