### ISSUE TITLE
Doc: Need use case and example for adding metadata to a contruct

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1814]
In the constructs () section we state:

You can attach metadata to a construct using the aws-cdk.Construct.node.addMetadata operation. Metadata entries automatically include the stack trace from which the metadata entry was added to allow tracing back to your code, even if the entry was defined by a lower-level library that you don't own.

Why would you attach metadata to a construct? What's the advantage of adding a stack trace? Do we have an example (in a README)? How does it differ from tags?

**Comment by rix0rrr** [comment]
Unlike Tags, metadata is a CDK-level annotation. It does not reflect into the deployed resources.

It's an extension mechanism, in the future you'll be able store and load arbitrary things from there.

At the moment though, most useful ones are `this.node.addWarning()` and `this.node.addError()`, which show up when you do synthesis (and `addError()` even prevents deployment of stacks that have errors in them).

**Comment by Doug-AWS** [comment]
Thanks. I'll try to create a draft soon.

**Comment by Doug-AWS** [comment]
Here's what I have so far:

Construct Metadata

Attach metadata to a construct using the **addMetadata** method. Metadata is an AWS CDK-level annotation, and as such, does not appear in the deployed resources. Metadata entries automatically include the stack trace from which the metadata entry was added to allow tracing back to your code, even if the entry was defined by a lower-level library that you don't own.

Use the **addWarning** method to emit a message when you you synthesis a stack; use the **addError** method to not only emit a message when you you synthesis a stack, but to also block the deployment of a stack.

The following example blocks the deployment of *myStack* if it is not in us-west-2:

```typescript
if (myStack.region != 'us-west-2') {
    myStack.node.addError('myStack is not in us-west-2');
}
```

**Comment by rix0rrr** [comment]
That sounds fine. Be sure to always use `===` and `!==` when comparing things for equality in JavaScript/TypeScript.

**Comment by Doug-AWS** [comment]
Ah yes, I'm still a TypeScript newbie. I guess I was hoping the linter would remind me.

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/constructs.html#constructs_metadata
