### ISSUE TITLE
Physical resource names

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#1829]
This topic discusses support for physical resource names in the AWS Construct Library

**Comment by eladb** [comment]
@skinny85 Our little pet project made me realize we need rich support for physical names in L2s. For example, I would have expected that if I supply a physical name to a quque for example upon construction, then both `queueName` and `queueArn` and `queueUrl` will resolve during synthesis and not during deployment. 

@rix0rrr  this makes me realize your intuition was correct, we need to "wrap" all the L2 attributes with magical tokens that can resolve to physical names (and move the cross stuff references from L1 to L2). The heuristics of producing a queueURL and queueARN from a queueName is something that each L2 will need to supply, and that is also the same heuristics we can apply when we import a resource and only support one of these attributes.

**Comment by RomainMuller** [comment]
We need to make sure to continue using the `Ref`/`Fn::GetAtt` output when rendering references in-stack, and probably also in-region in-account cross-stack, so we get the *CloudFormation*-provided dependency orchestration at no additional cost.

**Comment by eladb** [comment]
Superseded by #2283
