### ISSUE TITLE
Codebuild does not connect to github with oauth token

### ISSUE THREAD

**Issue by yangaws** [awslabs/aws-cdk#1844]
Hi there,

My codes looked like:
```
const oauthToken = new cdk.Secret('my-github-personal-access-token-value')

const myGithubSource = new codebuild.GitHubSource({
            identifier: 'some-name',
            owner: 'some-owner',
            repo: 'some-repo',
            oauthToken: oauthToken,
            webhook: false
        })

const cb = new codebuild.Project(this, 'myProject', {
            source: myGithubSource,
            // enviornment, build_spect should not be related to this issue
        })
```
Basically I created the source myself with my github personal access token and pass it to codebuild. When I try deployment, I got error message:

`No Access token found, please visit AWS CodeBuild console to connect to GitHub (Service: AWSCodeBuild; Status Code: 400; Error Code: InvalidInputException; Request ID: 8f331e4a-36f5-11e9-a1b1-c9b2eb640025)`

I tried to connect to my github in CodeBuild console and then deployment can succeed. But I was wondering why I needed this manual console step? Should the codes just work if I provide my github access token?

Also my colleague @jesterhazy confirmed to have same error and discovered more weird things. After he got same error when doing `cdk deploy`. He went into the console, started to create a codebuild job, clicked the buttons for github source and personal access token, entered a completely bogus token and clicked save, and got an error message. (So this codebuild job was not created) Then he went back to terminal and `cdk deploy` succeeded to deploy the stack into that region.

**Comment by yangaws** [comment]
I also forwarded this issue to codebuild people. Seems it's not related to cdk. It's just codebuild's design that the github auth part can only work in console. 

See:
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ImportSourceCredentials.html

Not sure if cdk wants to update documentation to include this part?

**Comment by RomainMuller** [comment]
Hey @yangaws - we do in fact mention that you need to go through the console in order to complete the OAUTH set-up in the documentation [here](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-codebuild.html?highlight=githubsource#@aws-cdk/aws-codebuild.GitHubSourceProps.oauthToken).

I'm wondering where you'd have expected that information to be made visible, so we propagate on there, too.

**Comment by yangaws** [comment]
Hi @RomainMuller ,

Thanks for you explanation. Sorry that I missed that explanation in the the cdk docs you linked. I feel good for the current doc on CDK. I am involved in discussion with CodeBuild now and hope they can improve this. But anyway that's not CDK's issue.

Will close this. Thanks for your help!
