### ISSUE TITLE
Route53 ZoneDelegationRecord doesn't accept PublicHostedZone hostedZoneNameServers

### ISSUE THREAD

**Issue by skorfmann** [awslabs/aws-cdk#1847]
Given I have two zones, where I want to delegate from one zone to the other, I can't use the L2 Route53 ZoneDelegationRecord. 

![screenshot 2019-02-24 at 12 51 37](https://user-images.githubusercontent.com/136789/53298814-59a53e80-3833-11e9-9a32-96edd22297ea.png)
![screenshot 2019-02-24 at 12 51 50](https://user-images.githubusercontent.com/136789/53298813-59a53e80-3833-11e9-818e-e41f88d9d042.png)

So, this issue appears to be, that `hostedZoneNameServers` returns `null | string[]` rather than just `string[]`. I tried this:

```typescript
{
  zone: mainZone,
  delegatedZoneName: previewZone.zoneName,
  nameServers: <string[]>mainZone.hostedZoneNameServers
}
```

While this satisfies the type, it fails when actually running it via the CDK. 

What I ended up doing for now:

```typescript
const zoneDelegationResource = zoneDelegation.node.findChild(
  "Resource"
) as route53.CfnRecordSet;

zoneDelegationResource.addPropertyOverride(
  "ResourceRecords",
  mainZone.hostedZoneNameServers
);
```

**Comment by rix0rrr** [comment]
> While this satisfies the type, it fails when actually running it via the CDK.

Could you give more details on this? Because it sure seems like that should work.

**Comment by RomainMuller** [comment]
@skorfmann as mentioned in [the documentation](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-route53.html?highlight=ihostedzone#@aws-cdk/aws-route53.IHostedZone.hostedZoneNameServers) the `nameServers` attribute is not available for private hosted zones and hosted zones that are `import`ed from another stack.

In your particular case, you can assert the name servers are present by simply adding an exclamation mark:

```ts
const zoneDelegation = new route53.ZoneDelegationRecord(this, 'PreviewZoneDelegation', {
  zone: mainZone,
  delegatedZoneName: previewZone.zoneName,
  nameServers: mainZone.hostedZoneNameServers! // <-- the "!" means "I know this won't be undefined"
});
```

**Comment by RomainMuller** [comment]
I've tested this and it appears there is a bug related to how the tokens are handled here, which causes the code to crash with an obscure error. I am preparing a fix for this.

**Comment by RomainMuller** [comment]
#1853 includes a fix for the bug in question, and also introduces an API such that you could:

```ts
mainZone.delegateTo(previewZone);
```

**Comment by skorfmann** [comment]
> In your particular case, you can assert the name servers are present by simply adding an exclamation mark:

Sweet, didn't know that.

> #1853 includes a fix for the bug in question, and also introduces an API such that you could:

Awesome, thank you!
