### ISSUE TITLE
Create how-to on using secrets

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1857]

**Comment by rix0rrr** [comment]
## Using Secrets with the AWS CDK

The best way of using secrets in CDK programs is by using AWS SecretsManager. To
use a secret value in your CDK application, first provision the secret by hand,
then import the secret into your CDK application and use either
`secret.stringValue` or `secret.jsonFieldValue(field)`:


```ts
const secretsmanager = require('@aws-cdk/aws-secretsmanager');

// ...

const secret = Secret.import(this, 'ImportedSecret', {
  secretArn: 'arn:aws:secretsmanager:<region>:<account-id-number>:secret:<secret-name>-<random-6-characters>',
});

// If the whole value of the Secret contains the secret value
// you want to use.
new iam.User(this, 'User', {
    password: secret.stringValue,
});

// If the Secret contains a JSON object that you only need
// a single field of, do this:
new iam.User(this, 'User', {
    password: secret.jsonFieldValue('password'),
});
```

For more information, see the documentation of the `@aws-cdk/aws-secretsmanager`
library.

### AWS SSM Parameter Store SecureStrings

In limited cases, it is also possible to use SSM Parameter Store SecureStrings to store secrets. You must know the
version of the Parameter you want to use, and the use of SecureStrings is only supported in a limited set of resource
properties. See the [CloudFormation Dynamic References
documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) for the supported
list of properties.

```ts
import ssm = require('@aws-cdk/aws-ssm');

// ...

const secureString = new ssm.ParameterStoreSecureString(this, 'SecretValue', {
    parameterName: '/My/Secret/Parameter',
    version: 5
});

new iam.User(this, 'User', {
    password: secureString.stringValue
});
```

**Comment by Doug-AWS** [comment]
Thanks Rico. I'll add this to the guide and publish a review soon.

**Comment by Doug-AWS** [comment]
Changed in 0.28.0. I'm working on this now and hope to get the info reviewed and live by EOW.

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/passing_secrets_manager.html. I have an update that shows how to use the CLI to create a new secret. I've confirmed the code works on 0.28.0.
