### ISSUE TITLE
Adding an `Output` to a stack does not count as a change so the stack is not deployed

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#186]
## Reproduction

Have a stack, deploy it. Add an `Output` object to it. Deploy it again.

## Expectation

Stack is deployed and the `Output` is added.

## Reality

```
 ⏳  Starting deployment of stack XXXX...
 ✅  Stack was already up-to-date, it has ARN XXXXXX
```

**Comment by ijcd** [comment]
I'm hitting this as well. Is there a workaround?

**Comment by eladb** [comment]
@ijcd make some other change to the template such as adding metadata.

**Comment by eladb** [comment]
@rix0rrr this is resolved, correct?

**Comment by rix0rrr** [comment]
Yes, was fixed in https://github.com/awslabs/aws-cdk/pull/2029
