### ISSUE TITLE
Create how-to on working around missing CDK features

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1864]
Do we want to just add to the existing Accessing the AWS CloudFormation Layer topic, https://docs.aws.amazon.com/CDK/latest/userguide/cfn_layer.html?

**Comment by Doug-AWS** [comment]
See also: https://github.com/aws-samples/aws-cdk-examples/issues/11

**Comment by rix0rrr** [comment]
I think this is covered with the "Accessing the AWS CloudFormation layer" topic, modulo examples in other languages.

**Comment by Doug-AWS** [comment]
Okay, I'm closing then.
