### ISSUE TITLE
Create example of multiple stacks in a single app

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#1870]

**Comment by Doug-AWS** [comment]
From 355:

To create a stack in **us-west-2** in your app,
and set the **region** property of the **env**
member of the **StackProps** argument to your stack when creating it,
as shown in the following example.

.. code-block:: js

new HelloStack(this, 'hello-cdk-us-west-2', {
env: {
region: 'us-west-2'
}});

**Comment by rix0rrr** [comment]
## How to deploy a stack to multiple regions

In CDK, we encourage you to define a complete model of your application. That is, you don't just define an abstract skeleton of your application, you also define exactly where you want to deploy which part of your application. This gives the CDK (and future other tools) a holistic view of your application which they can use to make things like deployments easier for you.

The following example shows a hypothetical `MyStack`, which gets deployed to a set of account/region pairs. `MyStack` is parameterized by a parameter `dev` to show how to switch out expensive compute instances for cheap ones in non-production regions.

```ts
// lib/mystack.ts
// Defines my parameterized application which can be deployed anywhere
interface MyStackProps extends cdk.StackProps {
    dev: boolean;
}

class MyStack extends cdk.Stack {
    constructor(scope: cdk.App, id: string, props: MyStackProps) {
        super(scope, id, props);

        const instanceType = props.dev
            ? new ec.InstanceType('t2.micro')
            : new ec.InstanceType('c5.2xlarge');

        const fleet new MyComputeFleet(this, 'Fleet', {
            instanceType,
        });

        const queue = new sqs.Queue(this, 'Queue');
        queue.grantConsumeMessages(fleet.role);
    }
}

// bin/myapp.ts
// Controls where MyStack is ACTUALLY going to be deployed
const app = new cdk.App();

const environments = [
    { account: '12345678', region: 'us-east-1' },
    { account: '87654321', region: 'eu-west-1' },
    { account: '12344321', region: 'ap-southeast-1' },
];

// Beta instance in the first environment
new MyStack(app, 'BetaStack', { dev: true, env: environments[0] });

// Production instance in every other environment
for (const env of environments) {
    new MyStack(app, `ProdStack-${env.region}`, { dev: false, env });
}
```

**Comment by Doug-AWS** [comment]
Thanks Rico. I'll add this to the guide and have it ready for review by EOD.

**Comment by Doug-AWS** [comment]
Done: https://docs.aws.amazon.com/cdk/latest/guide/stack_how_to_create_multiple_stacks.html

**Comment by therealwolf42** [comment]
@Doug-AWS The text in your linked documentation doesn't seem to fit with the code.

> .. It creates one stack with a t2.micro AMI for development, and three stacks with the more expensive c5.2xlarge AMI ...

**Comment by Doug-AWS** [comment]
Dang, the text was from a previous example. I'll fix it now.

**Comment by Doug-AWS** [comment]
Fixed.
