### ISSUE TITLE
what is the DeploymentPipeline class mentionned in the doc ?

### ISSUE THREAD

**Issue by barroij** [awslabs/aws-cdk#1915]
More a question a bout CDK than an issue.

In the documentation about CDK apps and stacks, one code snippet uses a `DeploymentPipeline` class. What is it exactly ? (https://docs.aws.amazon.com/CDK/latest/userguide/apps_and_stacks.html)

And as a related question, what is the best pratice / advice for managing stacks in a production environement with the CDK ?

**Comment by sam-goodwin** [comment]
I think`DeploymentPipeline` represents a stack that manages the CI/CD of those other stacks defined in the app. It is unclear though ... @Doug-AWS can you comment on the docs?

AFAIK, we don't have docs specifically on how to manage stacks in production. @skinny85?

**Comment by sam-goodwin** [comment]
Some relevant issues:
* https://github.com/awslabs/aws-cdk/issues/233 - Cloud Assembly specification
* https://github.com/awslabs/aws-cdk/issues/308 - tracking the CI/CD story for CDK apps in general
* https://github.com/awslabs/aws-cdk/issues/1869 - update docs with an example of a CI/CD CDK App

**Comment by Doug-AWS** [comment]
IIRC that was part of a now-orphaned attempt to hack together a CI/CD pipeline, before we had any Code* constructs. I think we even used the term "Goldberg" as in Rube Goldberg, as the name implies. I'll talk to Elad and Rico, but I'm pretty sure I'll have to fix that reference to use Code*.

**Comment by Doug-AWS** [comment]
@eladb @rix0rrr ???

**Comment by eladb** [comment]
@Doug-AWS we should remove this very very old and obsolete hypothetical example that we've sketched out over a year ago.

**Comment by Doug-AWS** [comment]
It's been removed.
