### ISSUE TITLE
ecs.TaskDefinition taskRole and executionRole is not of type IRole

### ISSUE THREAD

**Issue by robertd** [awslabs/aws-cdk#1925]
In the construction of the `TaskDefinition`, the `taskRole` property is of type `Role` rather than `IRole`. Same goes for `executionRole`.

https://github.com/awslabs/aws-cdk/blob/488935ce9e2a414c94fbf13fc24c95c9626f7d11/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L26

https://github.com/awslabs/aws-cdk/blob/488935ce9e2a414c94fbf13fc24c95c9626f7d11/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L33

Possibly here too ...

https://github.com/awslabs/aws-cdk/blob/488935ce9e2a414c94fbf13fc24c95c9626f7d11/packages/%40aws-cdk/aws-ecs/lib/base/task-definition.ts#L115

**Comment by robertd** [comment]
Due to `executionRole` and `taskRole` being of `Role` type we are unable to assign imported roles which are of `IRole` type.

**Comment by robertd** [comment]
In my case ecs.FargateTaskDefinitionis created with imported roles (iam.Role.import()) rather than cdk creating necessary roles. I’ve tried to tackle PR myself, and it works in my case (ECS Fargate) but it breaks ESC EC2 cluster approach. I was hoping it would be an easy fix but I’m afraid that some cross-package refactoring is involved. Running build has been a struggle so I’m doing docker builds to test the code. I was just wondering if any core members can take a peek and see if the switch from using Role to IRole in aws-ecs package requires larger refactor. Thanks in advance.

**Comment by janaka** [comment]
I've come across effectively the same problem in C#. `Role.Import()` returns `Amazon.CDK.AWS.IAM.IIRole`. `FargateTaskDefinitionProps.ExecutionRole` is type  'Amazon.CDK.AWS.IAM.Role'

**Comment by robertd** [comment]
Thank you @rix0rrr.
