### ISSUE TITLE
ECS Readme sample code out of date (cluster.addDefaultAutoScalingGroupCapacity)

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#1926]
[When cluster.addDefaultAutoScalingGroupCapacity was renamed to addCapacity](https://github.com/awslabs/aws-cdk/commit/e3738acfcbeb9d3b8c97ecee2cb8b9b00e822ed2), sample code references were missed.

ECS README: 
https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/README.md

cdk-examples should be checked, too.  ex:  
https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/ecs/ecs-load-balanced-service/index.ts#L16

**Comment by JoHuang** [comment]
Hi

After changing to addCapacity function, there is no instanceCount option to pass into.
How should I set instanceCount?

Thanks
