### ISSUE TITLE
Breadcrumb links in User Guide broken

### ISSUE THREAD

**Issue by garnaat** [awslabs/aws-cdk#1927]
The User Guide has breadcrumb links along the top.  They look like:

`AWS Documentation -> AWS Cloud Development Kit -> etc.`

The AWS Cloud Development Kit link is broken and leads to a "Looking for Something" page.

**Comment by Doug-AWS** [comment]
I'll work with the editor to create a landing page for the CDK.

**Comment by Doug-AWS** [comment]
Fixed.
