### ISSUE TITLE
ecs.ContainerDefinition does not return a container name

### ISSUE THREAD

**Issue by robertd** [awslabs/aws-cdk#1950]
After I declare container instance...
```
const container = new ecs.ContainerDefinition(this, "Container", {
      image: ecs.ContainerImage.fromDockerHub(props.dockerRepositoryUrl),
      taskDefinition: taskDefinition,
      environment: {
        "HOST_DOMAIN": props.hostDomain
      }
    });
```

Service is expecting container name in `loadBalancers` section. It would be nice if `container` instance would be able to return `containerName` rather than me hardcoding it.

```
const service = new ecs.CfnService(this, "Service", {
      cluster: cluster.clusterName,
      loadBalancers: [{
        containerName: "Container",
        containerPort: 80,
        targetGroupArn: tg.targetGroupArn  
      }]
      ...
    });
```

**Comment by rix0rrr** [comment]
You are mixing L1 (CloudFormation) and L2 (hand-written) classes.

You can tell because the L1s all start with `Cfn` and the L2s don't. Please see my reading suggestions in https://github.com/awslabs/aws-cdk/issues/1949
