### ISSUE TITLE
CodeBuild: Support LOCAL_DOCKER_LAYER_CACHE

### ISSUE THREAD

**Issue by odanado** [awslabs/aws-cdk#1956]
By setting type as `LOCAL` and modes as `LOCAL_DOCKER_LAYER_CACHE`, CodeBuild can be cached Docker Image.
https://docs.aws.amazon.com/ja_jp/codebuild/latest/APIReference/API_ProjectCache.html

But, @aws-cdk/aws-codebuild@0.25.1 only can set type as `S3`.
https://github.com/awslabs/aws-cdk/blob/v0.25.1/packages/@aws-cdk/aws-codebuild/lib/project.ts#L606-L609

**Comment by rvdwijngaard** [comment]
+1

**Comment by SanderKnape** [comment]
I can look into implementing this feature, but would like some feedback on the how to do so first. As mentioned before there is currently a `cacheBucket` property (https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L591) that will enable S3 caching. I can add a new property, `cacheModes`, that accepts a list of cache modes (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectcache.html). Then I would also need to check if only one of `cacheBucket` or `cacheModes` is set. This is backwards-compatible change. I guess I can do this around this other validation that is happening: https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-codebuild/lib/project.ts#L658

Another option is to change the existing property to something new that would accept either S3 cache settings or a list of cache modes.

Any thoughts? Maybe @skinny85 ?
