### ISSUE TITLE
Asset `uploadIfChanged` only runs for files not for directories

### ISSUE THREAD

**Issue by brad-jones** [awslabs/aws-cdk#1997]
When using `new AssetCode('/some/path')`, a zip file is created using `prepareZipAsset` and then uploaded using `prepareFileAsset` which executes `uploadIfChanged`.

The problem is that the zip file obviously has some timestamp data (or similar) in it that changes the hash of the file. So on every single deployment, regardless of if the asset has actually changed or not, a new asset is uploaded.

`prepareZipAsset` should either produce a idempot zip file or it should run a similar `zipIfChanged` function.

Anyway my workaround for now has been to use <https://github.com/aws/aws-lambda-go/blob/master/cmd/build-lambda-zip/main.go> to generate the zip of my lambdas and then get CDK to just upload the zip.

FYI: `build-lambda-zip` does produce an idempot zip file.

**Comment by spg** [comment]
It seems like it's linked to the order of the files in the zip file (not the timestamps of the files themselves) https://github.com/awslabs/aws-cdk/issues/2759
