### ISSUE TITLE
Challenges navigating docs to find interface & parent class details

### ISSUE THREAD

**Issue by rclark** [awslabs/aws-cdk#200]
![image](https://user-images.githubusercontent.com/515424/42119432-7e9724d6-7bc0-11e8-9cf0-5954dcc3afbd.png)

Most of these constructs require me to provide some `props`, where the object I provide has to conform to an interface. In this case, the interface is `EventRuleProps`. 

It would be useful if the references in the documentation for these classes were hyperlinks -- so that I could click `EventRuleProps` here to jump straight to that interface description, or click the `EventRuleRef` to see what this class extends.

**Comment by debora-ito** [comment]
I believe this is fixed, so I'm going to go ahead and close this. Feel free to reopen if any further questions come up.
