### ISSUE TITLE
VpcNetwork should throw a descriptive error when selecting 0 subnets

### ISSUE THREAD

**Issue by MichaelHindley** [awslabs/aws-cdk#2011]
Trying to set up a ecs cluster with asg in a existing non-cdk managed vpc. 
The `externalVpc` is used without issue when working with Lambdas, but with ASG it fails due to AvailabilityZones being empty, but they do exist and they do work with at least one other resource.

```typescript
const externalVpc = ec2.VpcNetwork.import(this, 'exampleVPC', {
  availabilityZones: [cdk.Fn.importValue('az1'), cdk.Fn.importValue('az1')],
  publicSubnetIds: [cdk.Fn.importValue('publicsubnet1'), cdk.Fn.importValue('publicsubnet2')],
  vpcId: cdk.Fn.importValue('vpcId'),
});

// Cluster config
const cluster = new ecs.Cluster(this, 'cluster-test', {
  clusterName: 'cluster-test',
  vpc: externalVpc,
});

cluster.addCapacity('asg-test', {
  instanceType: new ec2.InstanceType('t3.small'),
  taskDrainTimeSeconds: 0,
});
```

results in

```
 CREATE_FAILED        | AWS::AutoScaling::AutoScalingGroup

 Property AvailabilityZones cannot be empty.
        new AutoScalingGroup (code\aws\node_modules\@aws-cdk\aws-autoscaling\lib\auto-scaling-group.ts:297:29)
        \_ Cluster.addCapacity (code\aws\node_modules\@aws-cdk\aws-ecs\lib\cluster.ts:78:30)
        \_ new ContainerRegistryStack (ode\operator-interface\aws\lib\container-repository-stack\ecr.ts:32:13)
        \_ Object.<anonymous> (code\operator-interface\aws\bin\aws.ts:12:1)
        \_ Module._compile (internal/modules/cjs/loader.js:689:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        \_ Module.load (internal/modules/cjs/loader.js:599:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:530:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        \_ startup (internal/bootstrap/node.js:283:19)
        \_ bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

The actual error is that ```
      vpcPlacement: {
        subnetsToUse: SubnetType.Public
      }
``` is missing in the config to `config.addCapacity`.

`vpcPlacement` is an optional parameter, but without it you get an error in this case.

**Comment by rix0rrr** [comment]
Yes, `VpcNetwork` should throw a descriptive error if it cannot find any subnets of the indicated type.

**Comment by rix0rrr** [comment]
Note to future implementors: not in *all* cases; sometimes consumers will do analysis on the subnets returned.

Honestly, it's probably better to add an API `subnetIds(vpcPlacement): string[]` which has the default validating behavior. This will satisfy the 9 out of 10 cases where constructs just want to take a list of subnets and stick them into a CFN resource, leaving constructs that have fallbacks to use the other function.
