### ISSUE TITLE
Typo: taskRole should be corrected to executionRole

### ISSUE THREAD

**Issue by quakeyy** [awslabs/aws-cdk#2015]
The line below should use `executionRole` instead of `taskRole`.
https://github.com/awslabs/aws-cdk/blob/3117cd35e02b2bd5f0845ffd14277bbee80eb09d/packages/%40aws-cdk/aws-ecs/lib/ec2/ec2-event-rule-target.ts#L98

For task that pulls the image from ECR, this typo causes CloudWatch Event to not able to invoke the task.

Thanks.

**Comment by rix0rrr** [comment]
I've gone back and forth on this, and I think there are cases in which it fails when we just put `executionRole` here. Fairly sure I used to have that and it didn't work for me. I appreciate that it might need to be `executionRole` in your case.

Can you share some of your code so that we can try to tease out in which cases it needs to be which value?

**Comment by rix0rrr** [comment]
cc @SoManyHs @clareliguori any insights?

I'm fairly sure I needed to put `taskRole` there to make the integ test that's currently in the repo work.

**Comment by quakeyy** [comment]
Here is my code for creating the CloudWatch Event triggered ECS Task:

```
const repo = Repository.import(this, 'Repo', { 
    repositoryName: 'xxxxxxxx'
});

const ec2TaskDefinition = new ecs.Ec2TaskDefinition(this, 'TaskDef', {
    networkMode: "bridge"
});

ec2TaskDefinition.addContainer('container', {
    image: ecs.ContainerImage.fromEcrRepository(repo),
    memoryLimitMiB: 128,
    command: [ "xxxxxxxx", "xxxxxxxx" ],
    logging: new ecs.AwsLogDriver(this, 'xxxxxxxx', { streamPrefix: 'xxxxxxxx' })
});

const target = new ecs.Ec2EventRuleTarget(this, 'EventTarget', {
    cluster,
    taskDefinition: ec2TaskDefinition,
    taskCount: 1
});

const rule = new events.EventRule(this, 'Rule', {
    enabled: true,
    description: "xxxxxxxx",
    scheduleExpression: 'rate(1 minute)'
});

rule.addTarget(target);
```
Another thing I think that is worth mentioning is that the "Task Role" created for my ECS Task has no policies attached to it so it is basically an empty role. I can see that is probably also why it does not do anything when passed to CloudWatch and I have to pass the "Execution Role" instead.

Thanks.
