### ISSUE TITLE
App.synthesize methods are marked as deprecated with no replacement

### ISSUE THREAD

**Issue by digitalsanctum** [awslabs/aws-cdk#2016]
In latest version (0.25.3) the App.synthesize methods are marked as deprecated but don't offer a replacement or pointer as to why. Please provide guidance for the "new" sythesize.

**Comment by rix0rrr** [comment]
From your question I can tell you are running/synthesizing CDK apps not in the way we intended them to. 

The intended way is to let the cdk toolkit drive your application by launching it as a subprocess, not to run CDK apps in-memory. In other words, you are using an unsupported part of the API, and those `synthesizeStack` methods were never supposed to have been there or public in the first place (they were there for the benefit of our unit tests). Please don't do that, and if you do, be aware that we can break you at any time.

Now, the slightly better news is that you can probably keep on doing what you are doing today by calling `app.run()` and inspecting the object that is returned to you from it. It will be an `InMemoryStore` and contain the templates of the stacks that got synthesized. But again, these APIs are not intended to be called by users directly.

**Comment by mbulman** [comment]
A bit tangential, but I have a need for adding business-specific validation to Stacks.  A contrived example would be something like "in dev always use on-demand billing for dynamodb".  Right now (0.24.1) I've extended Stack and overridden `toCloudFormation` to validate against the synthesized stack object.  I worry that this falls into the same category of "not intended to be called by users directly" and will break in a future upgrade.

@digitalsanctum what is your use case for relying on `synthesize` directly?

@rix0rrr depending on his answer, what's your guidance on the best place to hook in?  You mention `app.run` but then say don't do that ;)  Perhaps this is a feature request?

**Comment by rix0rrr** [comment]
I would consider it a feature request at the moment.

As a practical matter, you should be able to achieve the same effect by having a class implement `IAspect`, like this:

```ts
class DynamoValidator implements IAspect {
  public visit(construct: IConstruct) {
    if (Resource.isResource(construct) && construct.resourceType == 'AWS::DynamoDB::Table') {
      if (!whatIWant(construct)) { 
        throw new Error('oops');
     }
    }
  }
}

app.node.apply(new DynamoValidator());
```

There might be some details wrong with the code above (around type checking), but the pattern should hold.

**Comment by digitalsanctum** [comment]
The short version is I'd like to use CDK (without the CLI bits) in concert with the SDK to easily do things like integration tests. Yes, I could just use the SDK but I think there's a huge opportunity to be able to just use the CDK and the benefits that come with it like automatic IAM role creation, reusable constructs, etc. Being able to use the CDK synth and deploy without worrying about installing the CLI would be ideal. 

For the purposes of this issue, it would be nice to have your explanation noted in the code comment along with the deprecation for other folks that are using the public synth methods.

**Comment by digitalsanctum** [comment]
It seems the feature I describe above has already been proposed and voted for by several people here: https://github.com/awslabs/aws-cdk/issues/601
