### ISSUE TITLE
Workshop: clean up section should remind users to compile their code 

### ISSUE THREAD

**Issue by davidfmyers** [awslabs/aws-cdk#2017]
I've been working through cdkworkshop.com and on the cleanup step cdk diff does not detect changes to "lib/cdk-workshop-stack.ts". Similar to what's being experienced in issue  #1978 

What should I do to try to troubleshoot why the changes are not detected?

```
$ cat lib/cdk-workshop-stack.ts 
import cdk = require('@aws-cdk/cdk');

export class CdkWorkshopStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // nothing here!
  }
}

$ cdk diff
Stack CdkWorkshopStack
There were no differences
$ 
```

**Comment by eladb** [comment]
Just making sure: did you make sure to compile your code using “npm run build” or “tsc”?

**Comment by davidfmyers** [comment]
@eladb Running "npm run build" resolved it, my changes are now detected. That step should be added in the [clean up](https://cdkworkshop.com/30-hello-cdk/100-cleanup.html) section. Thanks for the help.

**Comment by eladb** [comment]
Assigning to @Doug-AWS

**Comment by Doug-AWS** [comment]
I guess we'll have to remind users to build and compile at every step. I'll make sure to also add a strong recommendation to run ```npm run watch``` in a separate window.

**Comment by Doug-AWS** [comment]
How do we get the changes deployed? I added links to many of the pages (see https://github.com/aws-samples/aws-cdk-intro-workshop/pull/27). The PR was merged into mainline over a week ago.

**Comment by davidfmyers** [comment]
@Doug-AWS, I didn't even think to look for the workshop on github. I should have checked and worked on this through that repo.

**Comment by eladb** [comment]
We have a strong recommendation to run "watch" already, but probably worth adding a small reference to this in a few places.

**Comment by Doug-AWS** [comment]
I added the following blurb to 30-hello-cdk/100-cleanup.html:

(if you don’t see anything, it’s likely because you either forgot to save the file or forgot to keep npm run watch running).

**Comment by Doug-AWS** [comment]
Why hasn't the workshop been updated?
