### ISSUE TITLE
Intrinsic functions and pseudo parameters hard to find, confusing to use

### ISSUE THREAD

**Issue by rclark** [awslabs/aws-cdk#202]
It might be worth considering splitting up '@aws-cdk/core' into smaller libraries. The reference docs are hard to browse because so much is included in this library, and I tend to end up with a very long list of imports from this lib.

For example, it might be worth breaking out intrinsic functions and pseudo parameters. Quick and easy access to these tends to be pretty important in my experience with Cloudformation.

Related, I find that defining both intrinsic functions and pseudo parameters as classes is a pretty bad fit to my mental model of what these represent. I would prefer to interact with pseudo parameters as though they were variables, and intrinsic functions like... functions.

For example, 

```js
new logs.LogGroupResource(stack, 'Logs', {
  logGroupName: new FnSub('/aws/lambda/${AWS::StackName}') as any,
  retentionInDays: 14
});
```

Not only do I have to use `as any` (maybe that's not as confusing to folks used to TypeScript), but `new FnSub()` seems odd. You might consider implementing function wrappers for these objects? I would find that more intuitive.

```js
const fnSub = (name) => new FnSub(name);
```

For pseudo parameters:

```js
new Lambda(stack, "Function", {
  functionName: new AwsStackName() as any,
  code: new LambdaS3Code(utilityBucket, `bundles/aws-cdk-explorer/${sha}.zip`),
  handler: 'index.js',
  runtime: LambdaRuntime.NodeJS
});
```

`new AwsStackName() as any` is just a lot to type for something that I think of as simply a variable. It'd be more meaningful to me if I could just reference `awsStackName` and that would give me the `{"Ref": "AWS::StackName"}` construct in the output template. If there was something like an "pseudo parameters functions" class:

```js
class PseudoParameters {
  get awsStackName() { return new AwsStackName(); }
}
```

**Comment by mirskiy** [comment]
In case anyone's still having trouble finding pseudo parameters and stumbles upon this issue, they are currently (0.29.0) in [cdk.Aws](https://awslabs.github.io/aws-cdk/versions/0.29.0/refs/_aws-cdk_cdk.html#aws) and work nicely.
