### ISSUE TITLE
lambda.Alias does not expose the role associated with the lambda.Function

### ISSUE THREAD

**Issue by sam-goodwin** [awslabs/aws-cdk#2023]
The `lambda.Alias` should set its `role` property to the underlying lambda function's `role`.

Say you have existing code which creates a lambda function with some basic grants:

```ts
const myFunction = new lambda.Function(this, 'Function', { .. } );
myBucket.grantReadWrite(myFunction.role);
```

And then you change this to use an `Alias` (which implements `IFunction`) because you want to start using traffic shifting deployments:

```ts
const myFunction = new lambda.Alias(this, 'Alias', {
  version: new lambda.Version(this, 'version', {
    lambda: new lambda.Function(this, 'Function', { .. } )
  }
}
myBucket.grantReadWrite(myFunction.role);
```

I'd expect the function's role to still have the policies granted by the s3 bucket, but they don't because the role associated with the aliased function is never exposed by the alias.

**Comment by RomainMuller** [comment]
Actually, I'd even venture that the `Alias` should probably implement `IFunction`

**Comment by sam-goodwin** [comment]
It does.
