### ISSUE TITLE
Token resolution bug with basic ApiGateway toCloudFormation

### ISSUE THREAD

**Issue by chriswa** [awslabs/aws-cdk#2043]
I'm using CDK to generate CloudFormation templates using `stack.toCloudFormation`. Everything has been working great until I tried to add an API Gateway: suddenly I'm running into a mysterious token error that I can't seem to figure out.

Here's my simple-as-possible code demonstrating the issue:

```
const cdk = require('@aws-cdk/cdk')
const apigateway = require('@aws-cdk/aws-apigateway')

class MyStack extends cdk.Stack {
  constructor(parent, id, props) {
    super(parent, id, props)
    const api = new apigateway.RestApi(this, 'MyRestApi')
  }
}

const stack = new MyStack()
console.log(JSON.stringify(stack.toCloudFormation()))
```

I am expecting to output a CloudFormation template, but instead, I get a very cryptic error:

```
/Users/username/mycdkproject/node_modules/@aws-cdk/cdk/lib/core/tokens/resolve.js:91
            throw new Error(`The key "${key}" has been resolved to ${JSON.stringify(resolvedKey)} but must be resolvable to a string`);
            ^

Error: The key "${Token[TOKEN.20]}" has been resolved to undefined but must be resolvable to a string
    at resolve (/Users/username/mycdkproject/node_modules/@aws-cdk/cdk/lib/core/tokens/resolve.js:91:19)
    at Object.resolve (/Users/username/mycdkproject/node_modules/@aws-cdk/cdk/lib/core/tokens/resolve.js:93:23)
    at ConstructNode.resolve (/Users/username/mycdkproject/node_modules/@aws-cdk/cdk/lib/core/construct.js:377:26)
    at elements.map.e (/Users/username/mycdkproject/node_modules/@aws-cdk/cdk/lib/cloudformation/stack.js:110:59)
    at Array.map (<anonymous>)
    at MyStack.toCloudFormation (/Users/username/mycdkproject/node_modules/@aws-cdk/cdk/lib/cloudformation/stack.js:110:40)
    at Object.<anonymous> (/Users/username/mycdkproject/index.js:12:34)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
```

Please let me know if there are any known workarounds I can use in the meantime.

Thanks!

**Comment by chriswa** [comment]
For reference, I've found a workaround in:

```
function toCloudFormation(stackClass) {
  const app = new cdk.App()
  new stackClass(app, 'MyStack')
  const appRunResult = app.run()
  const cfntJson = appRunResult.store.files['MyStack.template.json']
  return JSON.parse(cfntJson)
}
```

This seems very awkward and fragile, compared to the `toStackFormation()` method. Please let me know if there's another approach I should be using to generate a template.

For context, we are using CDK within a modular framework to generate templates (for each module) to be used in nested stacks.

**Comment by rix0rrr** [comment]
Can you tell me why you are not running your CDK app using the CDK toolkit?

**Comment by chriswa** [comment]
We decided to go with a modular approach to building our software, in which the modules that a product depends on provide Java JARs and/or CloudFormation template artifacts. Modules can depend on each other using nested stacks, which fits nicely with our understanding of CloudFormation best practices.

We considered a monolithic CDK approach (e.g. with each module publishing CDK code to an npm repo) but decided instead to make templates first-class citizens in our architecture because incrementally-adoptable systems are less risky. More specifically:

1. module authors can opt out of CDK and still use our framework by authoring raw templates,
	a. either because they are already comfortable with templates and don't want to learn CDK, or
	b. because a required CloudFormation feature isn't (yet) supported by CDK;
2. extensive documentation exists for CloudFormation templates, meaning that a developer can pretend they aren't using CDK and take advantage of that;
3. if we ever decide against using CDK in our framework, we can easily promote our template artifacts to source control and remove our CDK code.

Regarding 3, CloudFormation templates are tried-and-true, so it seemed reasonable to design our framework around them. CDK is too good to ignore for building CloudFormation templates, but as it's new, we decided against designing our framework around it.

For example, I believe StackSets are one of the features that we need to use which aren't supported by CDK toolkit?

I'm a vocal advocate of CDK in our organization, mostly because I find writing and maintaining templates to be tedious and error-prone. I'm hoping our "toCloudFormation" use case can be accepted by the CDK dev team, since it seems to be such low-hanging fruit — it's so low-hanging that we are already eating it. ;)

**Comment by eladb** [comment]
Check out the very-soon-to-be-released `@aws-cdk/assert.SynthUtils.toCloudFormation` method. I believe it should provide the result you want. 

We hope that when the CDK is more mature you’ll consider using it to represent your entire app, so you can leverage the tremendous power you get from advanced features like automatic cross stack references, context providers, etc. 

Would love to follow up if you have more feedback or questions. Closing for now.

**Comment by chriswa** [comment]
@eladb Thanks! That sounds great.

Out of curiosity, why "assert"?

**Comment by eladb** [comment]
We generally discourage people from synthesizing templates like this because the CLI has an important role in resolving environmental context and bundling assets. We are looking at exposing these capabilities as libraries so people could take advantage of the full feature set.
