### ISSUE TITLE
Minimum set of permissions to use cdk cli

### ISSUE THREAD

**Issue by simonemazzoni** [awslabs/aws-cdk#2055]
Hello,
I'm experimenting the cdk-cli.

According to the cdk workshop I found [here](https://cdkworkshop.com/15-prerequisites/200-account.html) the cdk-cli needs `AdministrationAccess` privileges to work.

Is it really necessary? It looks like the permissions are a little too much for the purpose of the tool. Am I missing something?

Thanks

**Comment by rix0rrr** [comment]
The CDK can be used to create any resource in your account. As such, it will need permission to create any resource in your account, which roughly amounts to AdministorAccess.

If you know you're only going to be creating Buckets and nothing else, feel free to use a role that only has `s3:CreateBucket`.
