### ISSUE TITLE
@aws-cdk/aws-certificatemanager 0.26.0 is corrupt

### ISSUE THREAD

**Issue by MichaelHindley** [awslabs/aws-cdk#2078]
I've been trying to install the @aws-cdk/aws-certificatemanager 0.26.0 package and I get the same error across different computers(win10, high sierra) and package managers (yarn, npm).

Coworkers are experiencing the same. 

NPM error:
"npm WARN tarball tarball data for @aws-cdk/aws-certificatemanager@^0.26.0 (sha512-MeCTe9fPcQe1CnJGJA0E9mkOZMOEQ98CXsL/JozWglR5yz6XneiOlPa1xLAFCpxbBxXVpGE5BwECoiGGNP6E1Q==) seems to be corrupted."

Yarn error:
"error https://registry.yarnpkg.com/@aws-cdk/aws-certificatemanager/-/aws-certificatemanager-0.26.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt:"

Running yarn add any-other-package works in all cases, it's only this package that results in the error.

**Comment by rix0rrr** [comment]
Thanks for the heads up!

**Comment by MichaelHindley** [comment]
I've managed to install it once with npm now, but not a second time. I'm wondering if this is a network issue or npm registry issue rather than anything to do with this repo actually :)

**Comment by rix0rrr** [comment]
Well that would make me feel a lot better if true.

**Comment by rix0rrr** [comment]
WOMM:

```
$ npm install @aws-cdk/aws-certificatemanager@0.26.0
npm WARN test-table@1.0.0 No description
npm WARN test-table@1.0.0 No repository field.

+ @aws-cdk/aws-certificatemanager@0.26.0
added 21 packages from 1 contributor and audited 744 packages in 10.039s
found 0 vulnerabilities

```

**Comment by rix0rrr** [comment]
This is from Europe.

**Comment by MichaelHindley** [comment]
I'm gonna chalk this up to some sort of network issue, even though it's only this package that experiences this issue. It might be the cloudflare cache nodes in front of the registries we're hitting here are having some sort of issue, since if I try to download the package using wget or curl it works, but npm/yarn fails with different flavors of timeouts and file corruption errors.
