### ISSUE TITLE
support aws/codebuild/golang:1.11 build image

### ISSUE THREAD

**Issue by rvdwijngaard** [awslabs/aws-cdk#2079]
Currently cdk only supports codebuild golang 1.10 image. ; please add support for golang 1.11.

**Comment by skinny85** [comment]
Thanks for reporting @rvdwijngaard ! In the meantime, you can use `codebuild.LinuxBuildImage.fromDockerHub('aws/codebuild/golang:1.11')` to unblock yourself.

**Comment by rvdwijngaard** [comment]
@skinny85 thanks for your suggestion.
