### ISSUE TITLE
Expose props as read/write properties in CFN resources and remove propertyOverrides

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#2100]
Perfectly reasonable application of aspects came up on Gitter:

> Hello, I'm trying to write a custom IAspect which sets the RoleName of any IAM Role in a stack to 
> include a particular prefix (for resource matching in IAM permissions). Unfortunately, this overrides
> any RoleName that is manually set in the stack itself.
> Is there a way for an IAspect to check whether an IAM Role already has RoleName set?

To enable this we would need to allow read/write access to the configured properties of a `CfnResource`, in a **typed** fashion (so it needs to be done in `cfn2ts`).

We need to think about types and JSII though.

A `RoleProps` struct will have `readonly` properties for evertyhing, so cannot be mutated. So the syntax will have to be something like:

```ts
cfnrole.properties = {
   ...cfnrole.properties, 
   roleName: 'MyPrefix-' + cfnrole.properties.roleName
};
```

Not great...

Same story across JSII, except in Javaland it will be even more annoying to copy the existing properties into a new builder object. We need to generate a "copy constructor" as well then.

**Comment by rix0rrr** [comment]
We could say "overrides!" but in that case it looks like:

```ts
cfnrole.propertyOverrides.roleName = 'MyPrefix-' + cfnrole.properties.roleName
```

Which I agree is slightly better, but super non-obvious.

**Comment by Doug-AWS** [comment]
Is this yet another version of an escape hatch?

**Comment by eladb** [comment]
The proposal is to expose all top-level L1 props as simple read/write properties of the construct (note that deep structs will still be readonly, but that should be fine).

So for example:

```ts
class interface CfnBucketProps {
  // ...
  readonly corsConfiguration?: CorsConfigurationProperty;
  readonly bucketEncryption?: BucketEncryptionProperty;
  // ...
}

export class CfnBucket {
  // ...
  public corsConfiguration?: CorsConfigurationProperty;
  public bucketEncryption?: BucketEncryptionProperty;

  // ...
}
```

Also, remove `propertyOverrides` (it's no longer useful).

Then, in `_toCloudFormation` rendering should happen from the properties of course to allow overrides to take effect.

@moofish32 might pick this up.

Discussed with @rix0rrr and @RomainMuller

**Comment by eladb** [comment]
A little note - we *hope* 🤞 that this does not conflict with attribute property names because they begin with the type name (e.g. bucketArn)

**Comment by RomainMuller** [comment]
We could also code generate an `IInterface` for that mutable property. This should also feature an arbitrary accessor (`[key: string]: any`) so people could leverage properties that did t make it to the spec yet.

It'd maintain the namespace-like encapsulation that prevents name collisions from being a problem, and retain the strong typed overrides. It may need a JSII feature to support objects with an index signature.

**Comment by eladb** [comment]
I am not sure it's worth the effort, and the developer experience is less attractive:

```ts
bucket.corsConfiguration = { boom! };
```

versus:

```ts
bucket.props.corsConfiguration = { bam! };
```

I doubt we'll ever have conflicts and if we do, and we can should implement this logic to mangle the property name if there's an attribute with exactly the same name (e.g. add something like a "Config" postfix). At any rate, if this will happen, it will be a very fringy edge case.

**Comment by moofish32** [comment]
Just to verify I'm thinking in line with the team a starting point might be:
1. Modify code generation to create a class property for each CloudFormation Property currently in the immutable `Cfn<resource>Props` interface
1. Keep the constructor with the immutable `Cfn<resource>Props` (no change here)
1. After class initialization assign & read all properties from the class members do not persist the properties class member (renderProperties method should now assemble the properties back into an object?)
1. Delete all references to the propertyOverrides solution

**Comment by rix0rrr** [comment]
Yep, that's about it what we were thinking as well.

**Comment by moofish32** [comment]
I'm digging in here, the code needs a little unwinding. Hopefully I'll have something in a couple of days.
