### ISSUE TITLE
cdk init --language python support

### ISSUE THREAD

**Issue by kapilt** [awslabs/aws-cdk#2120]
Invalid values:
  Argument: language, Given: "python", Choices: "csharp", "fsharp", "java", "typescript"

cdk --version
0.27.0 (build 7638a58)

**Comment by fulghum** [comment]
Hey Kapil, have you tried with CDK version 0.28.0 ?  That should be the first version where Python init templates are present.  We have a few more fixes for Windows developers rolling out soon, too.

**Comment by kapilt** [comment]
lgtm, thanks
