### ISSUE TITLE
"Granting Permissions" section needs content

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#2144]

**Comment by SanderKnape** [comment]
I think a first step for this issue could be to add a mention about the existence of the `grant*` methods to the IAM readme. That's where I would expect to find this. It can just be a single-or-two lines of mention about the existence, plus an example such as the following:

The following example gives the Lambda function write permissions (Put, Update, Delete) to the DynamoDB table:
 
```typescript
const fn = new lambda.Function(...);
const table = new dynamodb.Table(...);

table.grantWriteData(fn);
```

If you want to give only specific permissions, use the more generic `grant` method:

```typescript
const fn = new lambda.Function(...);
const table = new dynamodb.Table(...);

table.grant(fn, 'dynamodb:PutItem');
```

I can create a PR for this if this sounds like a good idea (@Doug-AWS, @eladb).

**Comment by Doug-AWS** [comment]
Heck yes, a PR would be awesome.

**Comment by Doug-AWS** [comment]
Moving guide issues to doc repo.
