### ISSUE TITLE
Documentation mistake in "Get Value from Context"

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#2162]
The topic https://docs.aws.amazon.com/CDK/latest/userguide/get_context_var.html indicates the context should created by users in cdk.context.json, but this file is supposed to be managed by the CLI. Users should still add context to cdk.json.

cdk.json is for humans to manage and cdk.context.json is for the CLI to manage. Both should be checked-in to ensure reproducbility of your synthesis.

**Comment by Doug-AWS** [comment]
Ah, thanks for the clarification. I'll fix the docs.

**Comment by Doug-AWS** [comment]
Fixed.

**Comment by BDQ** [comment]
@Doug-AWS the docs here too are a little confusing on this topic also:

https://docs.aws.amazon.com/cdk/latest/guide/context.html

**Comment by maheshmarkus** [comment]
The location of a local cdk.json is also unclear.

I think the location of the local file should be '~/.cdk.json'
