### ISSUE TITLE
Incorrect documentation on overriding resource properties

### ISSUE THREAD

**Issue by aaronbrashears** [awslabs/aws-cdk#2174]
The documentation on https://docs.aws.amazon.com/CDK/latest/userguide/cfn_layer.html under the section "Overriding Resource Properties" does not work. The documentation specfies:

```
bucketResource.propertyOverrides.analyticsConfigurations = [
    {
        id: 'config1',
        storageClassAnalysis: {
            dataExport: {
                outputSchemaVersion: '1',
                destination: {
                    format: 'html',
                    bucketArn: otherBucket.bucketArn // use tokens freely
                }
            }
        }
    }
];
```

Someone found you can use `addPropertyOverride()` though the capitalization becomes important so this block would become:

```
bucketResource.addPropertyOverride('AnalyticsConfigurations', [
    {
        Id: 'config1',
        StorageClassAnalysis: {
            dataExport: {
                OutputSchemaVersion: '1',
                Destination: {
                    Format: 'html',
                    BucketArn: otherBucket.bucketArn // use tokens freely
                }
            }
        }
    }
]);
```

**Comment by aaronbrashears** [comment]
Somewhat related: #1595

**Comment by otterley** [comment]
@Doug-AWS

**Comment by eladb** [comment]
When you say "does not work", what's the error message?

**Comment by Doug-AWS** [comment]
On it. I'm slowly replacing these hard-coded code examples with snippets (a system of adding tags within comments to identify the beginning and end of a chunk of code to put in the docs). This enables me to test my doc code examples with every release. and avoid making users feel the pain.

**Comment by Doug-AWS** [comment]
Fixed. See https://docs.aws.amazon.com/CDK/latest/userguide/cfn_layer.html#cfn_layer_resource_props.
