### ISSUE TITLE
Python init template (app) gets class name wrong

### ISSUE THREAD

**Issue by garnaat** [awslabs/aws-cdk#2183]
If you do:

```
$ mkdir pythonhw
$ cd pythonhw
$ cdk init --language python
```

The class name used in the import statement in `app.py` is not properly templatized and does not match the name of the class in the package directory file.  This causes an error like this:

```
(.env) $ cdk synth
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from pythonhw.pythonhw_stack import PyStack
ImportError: cannot import name 'PyStack' from 'pythonhw.pythonhw_stack' (/Users/garnaat/projects/cdkdev/pythonhw/pythonhw/pythonhw_stack.py)
Subprocess exited with error 1
```

**Comment by imajinos** [comment]
errata.    "cdk init app --language=python"

**Comment by eladb** [comment]
Another issue I ran into is that if your project directory has a hyphen, the generated python module will be invalid.

**Comment by garnaat** [comment]
Yep.  See #2180.
