### ISSUE TITLE
GitHub source authentication works differently

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#2199]
In our GitHubSource, `oauthToken` is required, but it doesn't actually do anything.

You're supposed to authenticate the whole of CodeBuild against all of your repositories using OAuth in the console. Afterwards, you don't have to pass a token value, you just have to set auth-type to "OAUTH" and it'll work.

For reference, the following seems to work fine:

```ts
new GitHubSource({
      owner: 'rix0rrr',
      repo: 'somerepoihave',
      oauthToken: cdk.SecretValue.plainText(''),
 })
```

@skinny85, any clue?

**Comment by skinny85** [comment]
Perhaps it's only needed for the webhook...?

@rix0rrr , can you try the above with `webhook: true`, and see what happens? (i.e., is a CodeBuild build triggered by a push to the repository)

**Comment by rix0rrr** [comment]
I did this with webhook: true, fwiw

**Comment by skinny85** [comment]
And did it work? (where builds triggered by just pushing to the repository?)

**Comment by rix0rrr** [comment]
Yep.  Looks like we've been thinking about this all wrong.

Before connecting to repos, you're supposed to call [ImportSourceCredentials](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ImportSourceCredentials.html) for GitHub, using a token you get from doing an OAuth browser flow or a Personal Access Token. CodeBuild will store this token somewhere on their end.

After that, you create a project and set [auth.type=OAUTH](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_SourceAuth.html#CodeBuild-Type-SourceAuth-type), which will lead them to use the token they have stored server side.

Until CloudFormation grows support for `ImportSourceCredentials` or we write a custom lambda, there's no way to do this unattended.

![codebuild](https://docs.aws.amazon.com/codebuild/latest/userguide/images/github-access-token-console.png)

**Comment by rix0rrr** [comment]
That means the action is to get rid of `oauthToken` and document this better.
