### ISSUE TITLE
Generate CloudFormation Tempate

### ISSUE THREAD

**Issue by VikasJindal84** [awslabs/aws-cdk#2258]
Hi,

Can we use ready to use cloud formation template form cdk ? In our case we might not be able to run cdk deploy , so what to create ready to use cloud formation template from cdk.

**Comment by robertd** [comment]
You can use `cdk synth -o cloudformation`. This will create cfn template in `cloudformation` directory of your aws-cdk project.  https://cdkworkshop.com/20-create-project/400-synth.html

**Comment by eladb** [comment]
`cdk synth` is your friend.

**Comment by rbs392** [comment]
@eladb is it possible to allow mustache templates in the generated Cloudformation file

Currently I'm getting errors like
jsii.errors.JSIIError: Alias name must be between 1 and 256 characters in a-zA-Z0-9:/_-
