### ISSUE TITLE
VPC Export Creates Output Without Value

### ISSUE THREAD

**Issue by kuhnboy** [awslabs/aws-cdk#2261]
**Describe the bug**
Calling export on a VPC creates a export without a value

**To Reproduce**
var vpc = new VpcNetwork(this, "vpc", new VpcNetworkProps { Cidr = ipNetwork, EnableDnsHostnames = true, EnableDnsSupport = true, MaxAZs = AvailabilityZones });
vpc.Export();

Results in: agc-dev failed: ValidationError: Template format error: Every Outputs member must contain a Value object
Template format error: Every Outputs member must contain a Value object

**Output**
Outputs:
  netvpcPublicSubnetIDsB4AEB182:
    Value:
      Fn::Join:
        - ","
        - - Ref: netvpcPublicSubnet1Subnet4CD4B50E
          - Ref: netvpcPublicSubnet2SubnetDA258F98
          - Ref: netvpcPublicSubnet3SubnetEEF98931
    Export:
      Name: agc-tst:netvpcPublicSubnetIDsB4AEB182
  netvpcPrivateSubnetIDs0D06D2E1:
    Value:
      Fn::Join:
        - ","
        - - Ref: netvpcPrivateSubnet1Subnet44E8FA8C
          - Ref: netvpcPrivateSubnet2Subnet4971F090
          - Ref: netvpcPrivateSubnet3Subnet0D065BB7
    Export:
      Name: agc-tst:netvpcPrivateSubnetIDs0D06D2E1
  netvpcVpcIdAE1C9B5B:
    Value:
      Ref: netvpc8AAA4B80
    **Export:
      Name: agc-tst:netvpcVpcIdAE1C9B5B**

**Expected behavior**
Exports are not created if they have no value.

**Version:**
 - OS: Win10
 - Programming Language: C#
 - CDK Version: 0.28.0

**Comment by jogold** [comment]
This has been fixed in https://github.com/awslabs/aws-cdk/commit/9e87661d33dfc9bcee0e4cb43e51b08b0d99a9ba but not yet released.
