### ISSUE TITLE
dynamodb global secondary indexes 

### ISSUE THREAD

**Issue by Fejuto** [awslabs/aws-cdk#2262]
**Describe the bug**
error:
C:\Users\Fejuto\Documents\git\idlegame\cdk\node_modules\@aws-cdk\aws-dynamodb\lib\table.ts:259
      throw new RangeError('a maximum number of global secondary index per table is 5');

limit for global secondary indexes is actually 20 https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-secondary-indexes

**To Reproduce**
make dynamodb table and add more than 5 global secondary indexes

**Comment by eladb** [comment]
Thanks for reporting
