### ISSUE TITLE
ECS container enforces having port mappings

### ISSUE THREAD

**Issue by AlexCheema** [awslabs/aws-cdk#2264]
**Describe the bug**
Should be able to create ECS container with no port mappings. This error occurs when trying to do so:
```
Error: Container test hasn't defined any ports. Call addPortMappings().
```

**To Reproduce**
Create an ecs cluster with a `Ec2TaskDefinition` that has a container with no port mappings specified.

**Expected behavior**
Should be able to have a container with no port mappings.

**Version:**
 - OS: Win10
 - Programming Language: Typescript
 - CDK Version: 0.28.0

**Comment by SoManyHs** [comment]
Hi @AlexCheema, could you include the task definition code you are trying to run? What network mode are you using?

**Comment by SoManyHs** [comment]
Closing due to lack of response. Feel free to re-open if you are still having issues.
