### ISSUE TITLE
cdk java init template broken 

### ISSUE THREAD

**Issue by jousby** [awslabs/aws-cdk#2289]
**Describe the bug**
I've been using the Java flavour of CDK for a while now and had several projects create prior to 0.23.0 successfully running on my macbook pro. I've just spun up a new Java project using the init template in version 0.28.0 and i'm having trouble using the cdk cli tool against it. It looks like this change (https://github.com/awslabs/aws-cdk/pull/1503) to the Java template might be causing me issues. The older java cdk apps still run fine. 

When I run a 'cdk' command against the new java project i get the following error: 
```
$ cdk list
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< com.myorg:cdk-new >--------------------------
[INFO] Building cdk-new 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ cdk-new ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.767 s
[INFO] Finished at: 2019-04-15T22:04:17+10:00
[INFO] ------------------------------------------------------------------------
Unable to find output file /var/folders/6k/6fp51jbx3xg83p3fs4vnr4l4t8strm/T/cdkxMefzi/cdk.out; are you calling app.run()?
```
**To Reproduce**
1. mkdir init-test
2. cd init-test
3. cdk init --language java
4. mvn package
5. cdk list

**Expected behavior**
Lists the helloworld stacks in the default App

**Version:**
 - OS = MacOS High Sierra (10.13.6)
 - Programming Language = Java
 - CDK Version = 0.28.0

**Comment by eladb** [comment]
Confirming this is an issue. As a workaround, just add `app.run()` at the end of your `main()` function.
