### ISSUE TITLE
Documentation: Review and refresh What is AWS CDK section

### ISSUE THREAD

**Issue by ccfife** [awslabs/aws-cdk#2293]
This is the first thing that many customers read about the CDK, so it's important that it is concise and gives readers a clear overview of CDK and where to learn more.

**Comment by Doug-AWS** [comment]
We're talking about this section: https://docs.aws.amazon.com/cdk/latest/guide/what-is.html

**Comment by Doug-AWS** [comment]
Moving all guide issues to doc repo.
