### ISSUE TITLE
The CompositePrincipal signature is inconvenient to use

### ISSUE THREAD

**Issue by mitchlloyd** [awslabs/aws-cdk#2327]
**Describe the bug**
The `new CompositePrincipal()` constructor accepts a list of `PolicyPrinciple`s as arguments. I'd like to be able to refactor my code to pass an array of principals, but the type is fighting me.

```ts
const compositePrincipal = new iam.CompositePrincipal(...authorizedPrincipals);
// Type error: Expected at least 1 arguments, but got 0 or more.
```

I realize there is a tradeoff here, since logically we'd like to have at least 1 principal in a composite principal. However, I feel that the benefit of a type error for `new iam.CompositePrincipal()` (rather than a synth-time error) is less than the benefit of being able to pass an array as arguments. 

**To Reproduce**

```ts
import * as iam from '@aws-cdk/aws-iam';

const ps = [new iam.AccountPrincipal('123'), new iam.AccountPrincipal('456')];
new iam.CompositePrincipal(...ps);
```

**Expected behavior**
No type errors.

**Version:**
 - OS: OSX
 - Programming Language: TypeScript
 - CDK Version: 0.19.0 (build 2625a05) (but also current version)

**Comment by rix0rrr** [comment]
That is a fair point, and it's actually an instance of a design strategy I hate myself (designing APIs for direct human use only, to the neglect of higher-level abstractions).

I concur, it should be an array with a run-time check.

**Comment by rix0rrr** [comment]
Although it's honestly not that hard to work around:

```ts
new iam.CompositePrincipal(ps[0], ...ps.slice(1));
```

**Comment by mitchlloyd** [comment]
That's what I did ^, but making consumers jump through that hoop seems unfortunate.
