### ISSUE TITLE
Export cluster with vpc that has no vpn gateway

### ISSUE THREAD

**Issue by AlexCheema** [awslabs/aws-cdk#2339]
**Describe the bug**
If you try to export a cluster from a stack with a vpc that has no vpn gateway, you get the following error:
`ValidationError: Template format error: Every Outputs member must contain a Value object
Template format error: Every Outputs member must contain a Value object`

**To Reproduce**
```
const vpc = new ec2.VpcNetwork(this, "VPC");
const cluster = new ecs.Cluster(this, "Cluster", { vpc });

cluster.export();
````

I narrowed this down to the vpc export `vpnGatewayId`.
As a workaround, I use this currently:
`const vpc = new ec2.VpcNetwork(this, "VPC", { vpnGateway: true });`

**Expected behavior**
Should be able to export a cluster.

**Version:**
 - OS
Windows 10
 - Programming Language
Typescript
 - CDK Version
0.28.0

**Comment by rix0rrr** [comment]
`export()` no longer needs to be called, if you want to reuse the VPC inside the same CDK app.

If you want to reuse VPCs across CDK apps, do an environmental lookup or construct one from attibutes.
