### ISSUE TITLE
iam: Grants only work on IAM objects, not arbitrary principals

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#236]
```ts
# Works
bucket.grantReadWrite(lambda.role)

# Does not work
bucket.grantReadWrite(new ArnPrincipal('arn:aws:...'));
```

From the point of view of the user, it makes sense to be able to add a grant to a principal, because that's what you do in IAM. 

Right now, this `grantReadWrite()` uses

* `identity.addToPolicy()`
* `identity.principal`

The `addToPolicy()` call should be a no-op. Better yet, it should probably return `true|false` on whether it did something, and if it returns `false` the permissions should be added on the resource instead of on the identity. This makes most use cases _just work_.

While we're at it:

```ts
# Should actually also work
bucket.grantReadWrite(lambda)
```

**Comment by rix0rrr** [comment]
Came up again while wanting to write the following code:

```
bucket.grantPut(new AccountPrincipal('12345'));
```

Doesn't work, because AccountPrincipal is not an IAM object.

**Comment by rix0rrr** [comment]
And it should do something different for cross-account permissions (add to both resource and identity).

**Comment by rix0rrr** [comment]
Came up again when @leepa was working on a workshop:

```ts
        bucket.grantRead(new ArnPrincipal("arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity " + webDistribution.getId()));
```

**Comment by rix0rrr** [comment]
Another one that came up on Gitter:

> In the ECR Repository construct, grantPull expects an IPrincipal. But how can I grant everyone in the org pull access? In classic cfn it's a Condition inside the policy.

Again a principal that is not an IAM identity, but a virtual thing which means the resource policy needs updatin'.

**Comment by Tehnix** [comment]
Is there any workarounds w.r.t. to this? Like adding it through the SDK/CLI in a post-hook? :/
