### ISSUE TITLE
CLI: `--exclusively` is `-e` for synth and deploy, but `-x` for destroy

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#2367]
**Describe the bug**

```
cdk destroy -e some-stack
```

should EXCLUSIVELY destroy `some-stack`, but in fact it wants to destroy ALL STACKS in the application. Oops.

**Comment by BDQ** [comment]
Did this not change to `-x` ?

**Comment by rix0rrr** [comment]
You are frigging right.

yargs should have told me about that, I feel :x
