### ISSUE TITLE
SSM.ParameterStoreString constructor only takes props; no scope or id args.

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#2370]
**Describe the bug**
It threw me off trying to create an instance. Is this deliberate?

**To Reproduce**
The guide had:
```
import ssm = require('@aws-cdk/aws-ssm');

const secureString = new ssm.ParameterStoreSecureString(this, 'MySecretParameter', {
    parameterName: 'my-secret-parameter-name',
    version: 1,
});

const myvalue = secureString.stringValue;
```

But when I pasted that into VSCode, I got an error, which was fixed by changing the intantiation to:

```
const secureString = new ssm.ParameterStoreSecureString({
    parameterName: 'my-secret-parameter-name',
    version: 1,
});
```

**Expected behavior**
Should the constructor include scope an id args?

**Version:**
 - OS Windows
 - Programming Language Typescript
 - CDK Version 0.28.0

**Comment by rix0rrr** [comment]
It was designed that way on purpose. I might agree it's confusing, but please don't mark an issue as `bug` if you're asking a question.

It got redesigned since, so closing because this issue no longer applies.
