### ISSUE TITLE
EventRules cannot have targets with the same Construct ID.

### ISSUE THREAD

**Issue by robwettach** [awslabs/aws-cdk#2377]
**Describe the bug**
Two Lambda `Function`s with the same Construct ID but in different scopes cannot both be used as targets to the same `EventRule`:

```
Error: Duplicate event rule target with ID: Resource
    at EventRule.addTarget (.../node_modules/@aws-cdk/aws-events/lib/rule.js:57:19)
    at new EventRule (.../node_modules/@aws-cdk/aws-events/lib/rule.js:26:18)
```

The issue is that `Function`'s `asEventRuleTarget` uses `node.id` as the `id` field for the `EventRuleTargetProps` ([source](https://github.com/awslabs/aws-cdk/blob/48d536b191fb205869ef6724b718540be1037135/packages/%40aws-cdk/aws-events-targets/lib/lambda.ts#L32)).  This isn't unique, as it's just the ID that was passed when creating the `Function` construct - instead it should use `node.uniqueId` ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/construct.ts#L31-L36)). This needs to be globally unique as when calling EventRule.addTarget this value is used as a unique identifier ([source](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts#L124-L126)).

**To Reproduce**
```
class CustomConstruct extends Construct {
  public readonly lambda: Function;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.lambda = new Function(this, "Resource", {
      code: new InlineCode("def handler:\n\tprint(\"Hello\")"),
      handler: "index.handler",
      runtime: Runtime.Python36
    });
  }
}

const construct1 = new CustomConstruct(this, "Construct1");
const construct2 = new CustomConstruct(this, "Construct2");

new EventRule(this, "ConflictingRule", {
  description: "This will fail because the targets both have the same Construct ID",
  scheduleExpression: "rate(1 minute)",
  enabled: true,
  targets: [
    construct1.lambda,
    construct2.lambda
  ]
});
```

**Expected behavior**
I can name my constructs in any manner I want, they can still be accepted as distinct EventRule targets without collision between two distinct construct instances.

**Version:**
 - OS: Mac OS
 - Programming Language: TypeScript
 - CDK Version: 0.26.0

**Comment by made2591** [comment]
The bug is still present in version 0.33: fixed in #2744
