### ISSUE TITLE
Error in documentation example for Bucket#grantPublicAccess

### ISSUE THREAD

**Issue by schof** [awslabs/aws-cdk#2384]
**Describe the bug**

The [documentation](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-s3.html?highlight=s3#@aws-cdk/aws-s3.Bucket.grantPublicAccess) for `grantPublicAccess` method for `Bucket` contains an invalid example.

>The method returns the iam.PolicyStatement object, which can then be modified as needed. For example, you can add a condition that will restrict access only to an IPv4 range like this:
>```
>const statement = bucket.grantPublicAccess();
>statement.addCondition(‘IpAddress’, { “aws:SourceIp”: “54.240.143.0/24” });
>```

That example is incorrect. The method now returns `iam.Grant` which does not have an `addCondition` method.

**To Reproduce**

See the [online documentation](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-s3.html?highlight=s3#@aws-cdk/aws-s3.Bucket.grantPublicAccess)

**Expected behavior**

I don't know how to create a working example (that's why I was checking the documentation.)

**Version:**
 - OS (N/A)
 - Programming Language (All)
 - CDK Version (v0.29.0)

**Comment by schof** [comment]
I will submit a documentation patch eventually but in the meantime here is a correct example:

```typescript
const grant = bucket.grantPublicAccess();
grant.resourceStatement!.addCondition(‘IpAddress’, { “aws:SourceIp”: “54.240.143.0/24” });
```

**Comment by eladb** [comment]
Thanks so much for reporting and fixing.
