### ISSUE TITLE
CDK Deploy picks NLB Stack [Child] first instead of VPC Stack [Parent]

### ISSUE THREAD

**Issue by xparticle** [awslabs/aws-cdk#2394]
**Describe the bug**
Created a CDK App with Multiple Stacks that have dependencies. Observed that NLB Stack gets deployed first before VPC Stack and fails.

**To Reproduce**
Please clone this repo and try out cdk deploy. https://github.com/xparticle/aws-cdk-test-toposort-issue

**Expected behavior**
CDK Deploy should "see" that NLB needs VPC ID from the VPC Stack and deploy VPC first and then NLB.

**Version:**
 - OS: MacOS High Sierra
 - Programming Language: Typescript
 - CDK Version: 0.29, also observed this on 0.28

**Comment by rix0rrr** [comment]
`export()/import()` never preserved dependencies. Use the VPC object directly. Now that `export()` is gone, this issue is no longer relevant.
