### ISSUE TITLE
Post Stack Deploy Hook/Trigger

### ISSUE THREAD

**Issue by rob-gonz** [awslabs/aws-cdk#2464]
**Concept**
After a stack deploy completes (success or failure) I propose that a hook/trigger-function previously attached to a stack be run. I foresee it being useful for further automation of additional resources related to some stacks. As an input to the function call, it could be the Cloud Formation output as an array.

**Reason**
There are quite a few resources that do not receive definitive names as part of the cloud formation document synth. You can't make any assumptions or know what the endpoint of your ELB/ALB/RDS/EC2/Elasticache resources will be until the stack fully deploys.  Having these values be available opens up a lot of opportunities to do additional things as part of the CDK.

**Use Case:**
A stack has successfully deployed.  With this deployment, a new site/subdomain is being launched. We would now have to go to our CDN/DNS-Host(Cloudflare) and create a CNAME entry manually.  We could use this trigger to a function that is provided the CloudFormation Output.  That function could then call other apis to further configuration.

I know this is far from a priority, especially since it is still not officially GA.  I just wanted to through it out there for now. I think it would be a feature that could open up some doors for additional automation.  The CDK has been excellent to work with so far.  This would just the icing on the cake, IMO.

**Comment by eladb** [comment]
See #1938. I believe it is a duplicate. Please add your use case there and close if this is indeed the case.

**Comment by rob-gonz** [comment]
@eladb Thanks for pointing that out. Closing this request.
