### ISSUE TITLE
Imported security group typename is "Import"

### ISSUE THREAD

**Issue by ali-habibzadeh** [awslabs/aws-cdk#2466]
**Describe the bug**
Same as Vpc imports (ImportedVpcNetwork) the typename needs to reflect the imported resource type.

**To Reproduce**
Use SecurityGroup.import to add SG to a bucket for example.

Query sgResource.node.typename and you get `Import` instead of `ImportedSecurityGroup`

**Expected behavior**

sgResource.node.typename should be `ImportedSecurityGroup`

**Version:**
 - OS: Mojave 10.14.4
 - Programming Language: TypeScript
 - CDK Version: 0.30.0

**Comment by eladb** [comment]
Can you please provide some details on why the type name is important to you? These are actually internal types. All you should care about is that it implements `IVpcNetwork`.

**Comment by eladb** [comment]
Closing for now. Reopen with a response

**Comment by ali-habibzadeh** [comment]
I use the type name for unit test

```
class ExampleS3Bucket extends BucketConstruct {
  constructor(parent: Construct) {
    super(parent, ResultsTableS3Bucket.name);
  }

  protected props: BucketProps = {
    ...this.baseProps
  };

  public bucket = new Bucket(this, ResultsTableS3Bucket.name, this.props);
}

test("SecurityGroupService correctly imports a SG into a stack", test => {
  const stack = new Stack();
  const myBucket = new ExampleS3Bucket(stack);
  const groupName = SecurityGroupNames.devSecurityGroup;
  new SecurityGroupService(myBucket).import(groupName);
  const stackImportedType = myBucket.node.findChild("sg-1").node.typename;
  // seems to be a bug: https://github.com/awslabs/aws-cdk/issues/2466
  test.is(stackImportedType, "Import");
});
```
