### ISSUE TITLE
Function.grantInvoke(IGrantable) fails with imported function

### ISSUE THREAD

**Issue by EricEdens** [awslabs/aws-cdk#2472]
**Goal**

My goal is to have two stacks, one representing the application and one representing an integration test. Each stack has a lambda, and I want the integration lambda to be able to call the application lambda.

**Describe the bug**

When attempting to implement this using the "Get a value from another stack" functionality described in the [docs](https://docs.aws.amazon.com/cdk/latest/guide/aws_construct_lib.html) I get the error *Policy statement must contain resources*:

```
3/5 | 4:09:34 PM | CREATE_FAILED        | AWS::IAM::Policy      | TestFunction/ServiceRole/DefaultPolicy (TestFunctionServiceRoleDefaultPolicy810BAB0B) Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 83c89c17-6df8-11e9-ae97-4d6d78c6e2d1)
	new Policy (/tmp/jsii-kernel-AFZIiZ/node_modules/@aws-cdk/aws-iam/lib/policy.js:23:26)
	\_ Role.addToPolicy (/tmp/jsii-kernel-AFZIiZ/node_modules/@aws-cdk/aws-iam/lib/role.js:67:34)

``` 

**To Reproduce**

Run `cdk deploy` on a two-stack app such as this:

```java
import javax.annotation.Nullable;

import software.amazon.awscdk.App;
import software.amazon.awscdk.Construct;
import software.amazon.awscdk.Stack;
import software.amazon.awscdk.services.lambda.Code;
import software.amazon.awscdk.services.lambda.Function;
import software.amazon.awscdk.services.lambda.FunctionImportProps;
import software.amazon.awscdk.services.lambda.FunctionProps;
import software.amazon.awscdk.services.lambda.IFunction;
import software.amazon.awscdk.services.lambda.Runtime;

public class TwoFunctionApp {

    static class ApplicationStack extends Stack {

        private final FunctionImportProps publicFunction;

        public ApplicationStack(@Nullable Construct scope, @Nullable String name) {
            super(scope, name);

            Function publicFunction = new Function(this, "PublicFunction", FunctionProps.builder()
                    .withCode(Code.asset("build/lib/lambda.zip"))
                    .withRuntime(Runtime.JAVA8)
                    .withMemorySize(256)
                    .withHandler("com.amazon.PublicFunction")
                    .build());

            this.publicFunction = publicFunction.export();
        }
    }

    static class IntegrationTestStack extends Stack {
        public IntegrationTestStack(@Nullable Construct scope, @Nullable String name, FunctionImportProps functionImportProps) {
            super(scope, name);

            IFunction appFunctionToCall = Function.import_(this, "ThePublicFunction", functionImportProps);

            Function testFunction = new Function(this, "TestFunction", FunctionProps.builder()
                    .withCode(Code.asset("build/lib/lambda.zip"))
                    .withRuntime(Runtime.JAVA8)
                    .withMemorySize(256)
                    .withHandler("com.amazon.TestFunction")
                    .build());

            appFunctionToCall.grantInvoke(testFunction);
        }
    }

    public static void main(String... args) {
        App app = new App();
        ApplicationStack application = new ApplicationStack(app, "application");
        new IntegrationTestStack(app, "integ", application.publicFunction);
        app.run();
    }
}

```

**Expected behavior**

If the two functions are defined in the same stack, the grantInvoke permissions are created as expected. So, I'm hoping for this to work across stacks.

**Version:**
 - OS: Ubuntu 18.04
 - Programming Language: Java 8
 - CDK Version: 0.29.0

**Comment by eladb** [comment]
We are working on updating our docs, basically, if these two stacks are within the same app, there is no need to "export" and "import" explicitly. The framework will automatically do that for you.

This means that for your use case the following should work:

```java
public class TwoFunctionApp {

    static class ApplicationStack extends Stack {

        private final Function publicFunction;

        public ApplicationStack(@Nullable Construct scope, @Nullable String name) {
            super(scope, name);

            Function publicFunction = new Function(this, "PublicFunction", FunctionProps.builder()
                    .withCode(Code.asset("lambda"))
                    .withRuntime(Runtime.JAVA8)
                    .withMemorySize(256)
                    .withHandler("com.amazon.PublicFunction")
                    .build());

            this.publicFunction = publicFunction;
        }
    }

    static class IntegrationTestStack extends Stack {
        public IntegrationTestStack(@Nullable Construct scope, @Nullable String name, Function functionFromOtherStack) {
            super(scope, name);

            Function testFunction = new Function(this, "TestFunction", FunctionProps.builder()
                    .withCode(Code.asset("lambda"))
                    .withRuntime(Runtime.JAVA8)
                    .withMemorySize(256)
                    .withHandler("com.amazon.TestFunction")
                    .build());

            functionFromOtherStack.grantInvoke(testFunction);
        }
    }

    public static void main(String... args) {
        App app = new App();
        ApplicationStack application = new ApplicationStack(app, "application");
        new IntegrationTestStack(app, "integ", application.publicFunction);
        app.run();
    }
}
```

Please let us know if this works for you, and reopen if there are any further issues/questions

**Comment by eladb** [comment]
https://github.com/awslabs/aws-cdk/issues/2475

**Comment by EricEdens** [comment]
Thanks for the response! I like the design allowing users to reference entities directly.

Your example works! 

The next hiccup occurs when I attempt to add read permissions to a bucket that was created in the integ stack. 

```
Error: 'integ' depends on 'application' (integ/TestFunction/ServiceRole/DefaultPolicy/Resource -> application/PublicFunction/Resource.Arn). Adding this dependency (application/PublicFunction/ServiceRole/DefaultPolicy/Resource -> integ/TestResources/Resource.Arn) would create a cyclic reference.
```

Interestingly, I can apply either `grantInvoke` or `grantRead`. If I apply both, however, I get the circular dependency error.

```java
 IntegrationTestStack extends Stack {
        public IntegrationTestStack(@Nullable Construct scope, @Nullable String name, Function functionFromOtherStack) {
            super(scope, name);

            Bucket testResources = new Bucket(this, "TestResources");

            Function testFunction = new Function(this, "TestFunction", FunctionProps.builder()
                    .withCode(Code.asset("lambda"))
                    .withRuntime(Runtime.JAVA8)
                    .withMemorySize(256)
                    .withHandler("com.amazon.TestFunction")
                    .build());
            functionFromOtherStack.grantInvoke(testFunction);
            testResources.grantRead(functionFromOtherStack);
        }
    }
}
```

**Comment by eladb** [comment]
It kind of makes sense that you get a circular dependency. `grantInvoke` defines an `AWS::Lambda::Permission` resource to your "integ" stack that references the Lambda function from your "application" stack, while `grantRead` adds a statement to the Lambda IAM execution role from your "application" stack that references the bucket from your "integ" stack.

Conceptually, I am wondering what's the use case for the application lambda function to read objects from a bucket defined in your integration stack. That actually sounds like a dependency you wouldn't want in the first place.

@rix0rrr what do you think?

**Comment by EricEdens** [comment]
For me, the overall issue is that I don't get circular reference errors when the resources are in a single stack. Once I refactor them into multiple stacks, I start getting circular references. Quite possibly it's a misunderstanding on the user's part, in which case documentation could help here (maybe it exists already?).

Regarding the usecase, the API operates on a large payload out-of-band -- the caller sets up the payload, invokes the lambda, and then waits for the results to be written. It's the caller's responsibility to ensure the callee's IAM role has appropriate read/write access to the S3 bucket.

**Comment by eladb** [comment]
Totally understand that this can cause confusion and we will make sure to include some information about this when we describe cross-stack references (we are currently working on general doc improvements).

As for your use case, I would still argue this is not the desirable architecture. What happens if you want to add another testing stack (e.g. for development)? Do you want to need to go and update the production stack with IAM permissions for this new stack? In general, I would try to isolate the testing stacks from production and the dependency direction should be test => prod and not the opposite.

I wonder if a 3rd stack that only includes the bucket can help (e.g. "drop box"). This way, your production stack can only depend on this bucket stack and then the testing stacks can also depend on those to write data.

**Comment by EricEdens** [comment]
To clarify a bit, the application stack and test stack would get duplicated on every instantiation of the CDK app. So, beta would have both stacks, and prod would have both stacks, but the beta resources would have zero permissions to call anything in prod.

Thanks for all of the clarification. I'll go back to the documentation and see if there are some other CDK primitives (maybe constructs?) that are more aligned with the factoring that we're looking for.
