### ISSUE TITLE
Doc topic about imports/export is misleading

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#2475]
**Describe the bug**

The section about imports/exports is misleading. There is no need to export+import resources anymore if they reside in the same CDK app. https://docs.aws.amazon.com/cdk/latest/guide/aws_construct_lib.html

**To Reproduce**
See #2472 

**Expected behavior**
See #2472 with response

**Version:**
 - OS: all
 - Programming Language: all
 - CDK Version: 0.30.0

**Comment by Doug-AWS** [comment]
I'll update the docs today.

**Comment by Doug-AWS** [comment]
The section no longer discusses export/import.
