### ISSUE TITLE
npm install @aws-cdk/aws-ecs << fails!!!

### ISSUE THREAD

**Issue by unicomp21** [awslabs/aws-cdk#2476]
**Describe the bug**
jdavis@DESKTOP-GCP4E2T:/mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts$ npm install @aws-cdk/aws-ecs
cdk-tests.ts@0.1.0 /mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts
├── @aws-cdk/aws-applicationautoscaling@0.30.0  extraneous
├── @aws-cdk/aws-autoscaling@0.30.0  extraneous
├── @aws-cdk/aws-ec2@0.30.0
├── @aws-cdk/aws-ecr@0.30.0  extraneous
├── @aws-cdk/aws-iam@0.30.0
├── @aws-cdk/aws-s3@0.30.0
├── @aws-cdk/aws-secretsmanager@0.30.0  extraneous
├── @aws-cdk/aws-servicediscovery@0.30.0  extraneous
└─┬ aws-cdk@0.30.0
  └─┬ minimatch@3.0.4
    └─┬ brace-expansion@1.1.11
      └── concat-map@0.0.1

npm WARN cdk-tests.ts@0.1.0 No repository field.
npm WARN cdk-tests.ts@0.1.0 No license field.
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "@aws-cdk/aws-ecs"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts/node_modules/.staging/balanced-match-68456ebf
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts/node_modules/.staging/balanced-match-68456ebf' -> '/mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts/node_modules/@aws-cdk/assets/node_modules/balanced-match'
npm ERR! enoent ENOENT: no such file or directory, rename '/mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts/node_modules/.staging/balanced-match-68456ebf' -> '/mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts/node_modules/@aws-cdk/assets/node_modules/balanced-match'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/unico/Documents/repo/dev/cdk-tests.ts/npm-debug.log
**To Reproduce**
Command line used or code snippet

**Expected behavior**
The aws-ecs package should install w/o errors, like the other packages.

**Version:**
 - OS: Linux
 - Programming Language: typescript
 - CDK Version: 30

**Comment by unicomp21** [comment]
[npm-debug.log](https://github.com/awslabs/aws-cdk/files/3145506/npm-debug.log)

**Comment by unicomp21** [comment]
didn't have the latest nodejs

**Comment by eladb** [comment]
Did you get it to work? What node did you have?

**Comment by unicomp21** [comment]
yep, it works now, for typescript.  .net core version still has issues
