### ISSUE TITLE
LambdaRestApi throws an error in C#

### ISSUE THREAD

**Issue by wmmagee** [awslabs/aws-cdk#2494]
**Describe the bug**
I've seen a new error using CDK 0.29 and 0.30 in .Net.  Using LambdaRestApi throws an error. 

"principal: required but missing"

**To Reproduce**
This code:
```
var api = new LambdaRestApi(this, "myrestapi",
    new LambdaRestApiProps
    {
        Handler = lambda
    });
```
gives me this error:
While synthesizing stack-name/lambda-name/ApiPermission.ANY..: Supplied properties not correct for "CfnPermissionProps"
  principal: required but missing

I could not reproduce using Typescript so I believe it's a .Net specific issue.  

My collegue made a work around by recreating the CustomLambdaIntegration in C# and using that directly.

**Expected behavior**
Should be able to use LambdaRestApi  to create an Lambda integration with API Gateway

**Version:**
 - Windows 10
 - C#
 - 0.29 and 0.30

**Comment by wmmagee** [comment]
I confirmed this is still an issue for 0.31

**Comment by matheusmaximo** [comment]
Having the same problem.

**Comment by Kylia669** [comment]
Hi @wmmagee,  what is the ` work around by recreating the CustomLambdaIntegration` ?

**Comment by wmmagee** [comment]
@Kylia669, we created a line for line remake of the CustomLambdaIntegration class but in C# (see below).  Then we used the RestApi construct and set it's default integration to an instance of our CustomLambdaIntegration class.

CustomLambdaIntegration (it's private because we implemented it inside the class where we used it and expect to remove our implementation when this bug is fixed)
```
private class CustomLambdaIntegration : AwsIntegration
{
    private readonly IIFunction handler;
    private readonly bool enableTest;

    public CustomLambdaIntegration(IIFunction handler, ILambdaIntegrationOptions options)
        : base(new AwsIntegrationProps
        {
            Proxy = options.Proxy ?? true,
            Service = "lambda",
            Path = $"2015-03-31/functions/{handler.FunctionArn}/invocations",
            Options = options
        })
    {
        this.handler = handler;
        this.enableTest = options.AllowTestInvoke == null ? true : false;
    }

    public override void Bind(Method method)
    {
        base.Bind(method);

        var principal = new ServicePrincipal("apigateway.amazonaws.com", new ServicePrincipalOpts());
        string description = $"{method.HttpMethod}.{method.Resource.Path.Replace('/', '.')}";

        this.handler.AddPermission($"ApiPermission.{description}", new Permission
        {
            Principal = principal,
            SourceArn = method.MethodArn
        });

        if (this.enableTest)
        {
            this.handler.AddPermission($"ApiPermission.Test.{description}", new Permission
            {
                Principal = principal,
                SourceArn = method.TestMethodArn
            });
        }
    }
}
```

Then, in place of using a LambdaRestApi we used a RestApi in the following manor
```
var proxyHandlerBackend = new CustomLambdaIntegration(proxyHandler.Build(stack), new LambdaIntegrationOptions());
restApi = new RestApi(stack, this.name, new RestApiProps
{
     DefaultIntegration = proxyHandlerBackend
});
```

**Comment by wmmagee** [comment]
This error is gone as of version 0.36.0 in my testing

**Comment by eladb** [comment]
Thanks for letting us know. Closing for now
