### ISSUE TITLE
Add Python to the list of supported languages in the README

### ISSUE THREAD

**Issue by ccfife** [awslabs/aws-cdk#2505]
**Describe the bug**
The following languages are currently supported:
- Java
- JavaScript, TypeScript
- .NET

**To Reproduce**
https://github.com/awslabs/aws-cdk/blob/master/README.md

**Expected behavior**
- Java
- JavaScript, TypeScript
- .NET
- Python

**Comment by eladb** [comment]
We also need to add the logo
