### ISSUE TITLE
Runtime info broken in NodeJS 12.0.0+

### ISSUE THREAD

**Issue by SanderKnape** [awslabs/aws-cdk#2530]
**Describe the bug**
When running NodeJS 12.0.0 or higher (tested with 12.0.0 and 12.1.0), the runtime information does not contain the versions for the private NodeJS libraries anymore. The `require.resolve` function used [here](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/runtime-info.ts#L58) doesn't properly return the package module.

I believe this is a breaking change introduced in NodeJS 12.0.0 through this PR: https://github.com/nodejs/node/pull/23683

Maybe for now it's an option to add a NodeJS version constraint to the package.json file with a < 12.0.0.

**To Reproduce**
* Install NodeJS 12.0.0 or higher (e.g. through [nodenv](https://github.com/nodenv/nodenv))
* Run the tests for the CDK app
```bash
cd /path/to/aws-cdk/packages/@aws-cdk/cdk
../../../node_modules/.bin/nodeunit test/test.app.js
```
* Note how the `runtime library versions` and `version reporting includes only @aws-cdk, aws-cdk and jsii libraries` tests fail

**Expected behavior**
Non-failing tests

**Version:**
 - OS: OSX
 - Programming Language: NodeJS 12.0.0 +
 - CDK Version: 0.31.0

**Comment by RomainMuller** [comment]
@SanderKnape I reckon I have fixed this. Can you confirm the behavior is correct with the latest CDK?

**Comment by SanderKnape** [comment]
Double checked, works!
