### ISSUE TITLE
ECS Fargate service cannot find VPC subnets by subnetName 

### ISSUE THREAD

**Issue by rrhodes** [awslabs/aws-cdk#2560]
**Description**
Attempted to instantiate a Fargate Service, selecting VPC subnets by subnet name 'private'. This service belongs to a Fargate cluster within a VPC. The VPC has two subnets with name 'private', but selecting them in the Fargate service raised:

`throw new Error('There are no ${describeSelection(selection)} in this VPC. Use a different VPC subnet selection.');`.

Running

`vpc.selectSubnets({ subnetName: 'private' })`

outside of the FargateService construct returns two subnets as expected.

**To Reproduce**
```
const fargateService = new FargateService(this, `FargateService`, {
      ...fargateServiceProps,
      vpcSubnets: {
        subnetName: 'private',
      },
    });
```

**Expected behaviour**
A Fargate service should successfully be deployed with one or more VPC subnets by the name 'private'.

**Version**
 - Programming Language: Typescript
 - CDK Version: 0.30.0

**Comment by rix0rrr** [comment]
To answer this question, we would need to see how your VPC is defined.

Also, no need to specify a subnet selection if you want to select the private subnets, that is the default selection.

**Comment by rrhodes** [comment]
> To answer this question, we would need to see how your VPC is defined. Please show us the relevant piece of code that defines your VPC.

We're importing an existing VPC network from our account using `VpcNetwork.import`. We fetch the AZs, subnet IDs, and the VPC ID properties from Parameter Store and feed this into the props.

```
const parameters = getParams({
  privateSubnet1: '/infrastructure/vpc/private_subnet_1',
  privateSubnet2: '/infrastructure/vpc/private_subnet_2',
  publicSubnet1: '/infrastructure/vpc/public_subnet_1',
  publicSubnet2: '/infrastructure/vpc/public_subnet_2',
  vpnSubnet1: '/infrastructure/vpc/vpn_subnet_1',
  vpnSubnet2: '/infrastructure/vpc/vpn_subnet_2',
  dbSubnet1: '/infrastructure/vpc/db_subnet_1',
  dbSubnet2: '/infrastructure/vpc/db_subnet_2',
  vpcId: '/infrastructure/vpc/id',
});
const publicSubnetIds = [parameters.publicSubnet1, parameters.publicSubnet2];
const publicSubnetNames: SubnetName[] = ['public'];

const privateSubnetIds = [
  parameters.privateSubnet1, parameters.privateSubnet2,
  parameters.vpnSubnet1, parameters.vpnSubnet2,
];
const privateSubnetNames: SubnetName[] = ['private', 'vpn'];

const isolatedSubnetIds = [parameters.dbSubnet1, parameters.dbSubnet2];
const isolatedSubnetNames: SubnetName[] = ['db'];

const availabilityZones = ['eu-west-1a', 'eu-west-1b'];

vpc = vpc.import(this, 'VpcId', {
  availabilityZones,
  privateSubnetIds,
  privateSubnetNames,
  publicSubnetIds,
  publicSubnetNames,
  isolatedSubnetIds,
  isolatedSubnetNames,
  vpcId,
})
```

> Also, no need to specify a subnet selection if you want to select the private subnets, that is the default selection.

We have four private subnets, two by name 'vpn' and two by name 'private". I only want the latter two, which is why I'm fetching by name 'private' in this case. Otherwise, yes, I'd be happy to proceed without any explicit selection.

**Comment by rix0rrr** [comment]
Fixed by https://github.com/awslabs/aws-cdk/pull/2649
