### ISSUE TITLE
C# init template is broken on Windows

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#2565]
**Describe the bug**
The .NET/C# template is broken on Windows.

**To Reproduce**
dotnet add package Amazon.CDK.AWS.S3
Results in:
Could not find any project in `D:\hello-cdk\`.

**Expected behavior**
This should add the S3 package.

**Version:**
 - Windows 10.
 - C#
 - 0.31.0

**Comment by McDoit** [comment]
Don't you need to run the `dotnet add package Amazon.CDK.AWS.S3` in the actual folder of the project?

I assume `D:\hello-cdk\` is the folder where you did run `cdk init app --language=csharp` and the you would need to run `dotnet add` in `D:\hello-cdk\src\HelloCdk`

**Comment by Doug-AWS** [comment]
That was the secret step, thanks. I'll update the docs.
