### ISSUE TITLE
SES example fails to deploy

### ISSUE THREAD

**Issue by hassankhan** [awslabs/aws-cdk#2584]
**Describe the bug**
When following the instructions from [here](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ses/test/example.receiving.lit.ts) as per instructions from [this comment](https://github.com/awslabs/aws-cdk/issues/1885#issuecomment-483418531), the stack fails to deploy with the following error:

```bash
 ❌  StackName failed: ValidationError: Template format error: Unrecognized resource types: [AWS::SES::ReceiptRule, AWS::SES::ReceiptRuleSet]
Template format error: Unrecognized resource types: [AWS::SES::ReceiptRule, AWS::SES::ReceiptRuleSet]
```

**To Reproduce**
Example file is [here](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ses/test/example.receiving.lit.ts)

**Expected behavior**
I expected the stack to deploy without any issues.

**Version:**
 - OS: macOS 10.14.5
 - Programming Language: NodeJS v10.14.1
 - CDK Version: 0.31.0

**Comment by shivlaks** [comment]
What was the region where you attempted to deploy your stack?

[SES regions](https://docs.aws.amazon.com/general/latest/gr/rande.html#ses_region) supported: `us-east-1`, `us-west-2`, `eu-west-1`

**Comment by hassankhan** [comment]
Ahh I was attempting to deploy to `eu-west-2`, my mistake. Thanks for the reminder, @shivlaks 👍
