### ISSUE TITLE
Point lambda `aws:asset:path` to source code instead of `.cdk.staging`

### ISSUE THREAD

**Issue by Gaafar** [awslabs/aws-cdk#2586]
Not sure if there is a way to do this now, but when I try invoking lambda function with SAM: `sam local` it points to the lamda directory inside `.cdk.staging` dir, instead of the source code directory. 

So when I change the source code SAM doesn't run the latest version on disk. I tried changing `aws:asset:path:` manually in the template file and it works, but maybe there should be a better way to do it instead of manual update.

**Comment by eladb** [comment]
You should be able to run `cdk synth --no-staging` to disable asset staging, in which case assets will be referenced from their original location. 

Can you try and let us know if this works?

**Comment by Gaafar** [comment]
> You should be able to run `cdk synth --no-staging` to disable asset staging, in which case assets will be referenced from their original location.
> 
> Can you try and let us know if this works?

Yes, that fixes it. I created a small PR to mention it in CLI docs
