### ISSUE TITLE
ApplicationLoadBalancer adds unexpected ingress rules to security group

### ISSUE THREAD

**Issue by markusl** [awslabs/aws-cdk#2607]
**Describe the bug**
I'm trying to create an ApplicationLoadBalancer with predefined security group rules to allow traffic only from specific IP addresses.

**To Reproduce**
```
    const securityGroup = new ec2.SecurityGroup(this, `Rule`, {
      vpc,
    });
    securityGroup.addIngressRule(new ec2.CidrIPv4('1.1.1.1/27'), new ec2.TcpPort(443), 'IP address');
    const loadBalancer = new elbv2.ApplicationLoadBalancer(this, `LoadBalancer`, {
      vpc,
      internetFacing: true,
      securityGroup,
    });
```

The generated code seems to incorrectly allow traffic from _any_ IP address for some reason:

```
        - CidrIp: 0.0.0.0/0
          Description: Allow from anyone on port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
```

**Expected behavior**
I would expect the traffic to be allowed only from the specified addresses.

**Version:**
 - OS: macOS
 - Programming Language: Typescript
 - CDK Version: 0.31.0

**Comment by jogold** [comment]
Can you try adding `open: false` in the listener props?

**Comment by markusl** [comment]
@jogold thanks for noticing! I wasn't aware of this property as it wasn't explicitly required.

```
    const listener = loadBalancer
      .addListener(`HttpsListener`, {
        port: 443,
        certificateArns: [certificate.certificateArn],
        open: false, // This will do the trick
      });
```
