### ISSUE TITLE
CodeBuild action with cdk synth fails 

### ISSUE THREAD

**Issue by peerjako-aws** [awslabs/aws-cdk#2643]
**Describe the bug**
cdk synth will fail in a CDK generated CodeBuild project due to lack of ec2:DescribeAvailabilityZones permissions. This seems to happen in an AWS account region where CDK has never been run before.

**To Reproduce**
Execute the following from buildspec in codebuild.PipelineProject with image
codebuild.LinuxBuildImage.UBUNTU_14_04_NODEJS_10_14_1

- npm run cdk synth SOMESTACKNAME -- -o .

**Expected behavior**
It took some debugging for me to figure out that in some occasions cdk synth will call "getValue" here:
https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/context-providers/availability-zones.ts

and fail when doing describeAvailabilityZones.
I suggest that we add Action "ec2:DescribeAvailabilityZones" by default to the policy CDK automatically creates for the CodeBuild execution role, or that we document that this is needed if cdk synth is going to be run from a CodeBuild project.

**Version:**
 - OS: Mac
 - Programming Language: TypeScript
 - CDK Version: 0.32.0

**Comment by peerjako-aws** [comment]
I guess this happens when cdk.context.json does not yet contain the account/region where cdk synth is run again. A scenario that is very likely when the CodeBuild gets its src input from a git repo.

**Comment by eladb** [comment]
@peerjako-aws this is actually the intended behavior. The rational is that environmental context (`cdk.context.json`) is information we recommend to commit into your repository so changes in it won't cause unsolicited changes to your infrastructure. For example, the set of AZs returned from `describeAvailabilityZones` (and CloudFormation's `Fn::GetAZs`) may change without warning and has been known to cause operational issues for customers.

This is why our recommended approach is to synthesize stacks manually (e.g. with your developer credentials) and commit the context file.

We are aware that some developers do not have such access to their production accounts, and at the moment we don't have a full solution to this use case. One possible approach could be for the ops team to obtain this information from the production accounts and hand it over to developers so it can be checked in.

**Comment by peerjako-aws** [comment]
@eladb ok this makes sense. I must have missed that best practice part somewhere in the documentation.
