### ISSUE TITLE
Why are noUnusedLocals and noUnusedParameters set to true by default?

### ISSUE THREAD

**Issue by abelmokadem** [awslabs/aws-cdk#2648]
Why are these 2 fields set to true in `tsconfig.json`? Just wondering. 

```
    "noUnusedLocals": true,
    "noUnusedParameters": true,
```

I keep changing them to false in all my projects because I prefer to assign any value I create to a variable so that I know what it is without having to look at the value itself. I know that this is a matter of taste, but I'm also wondering whether it's just me who is changing this in every project.

Cheers!

**Comment by rix0rrr** [comment]
Assuming you are talking about the projects generated using `cdk init`, I think this request is justified. It is not great for usability.

**Comment by eladb** [comment]
+1 we'll accept a PR to change this

**Comment by abelmokadem** [comment]
#2654
