### ISSUE TITLE
Unable to use cdk command on Windows

### ISSUE THREAD

**Issue by Iamz** [awslabs/aws-cdk#2657]
**Describe the bug**
Unable to run any cdk command on Windows OS after the project is initialized.

**To Reproduce**
mkdir temp
cd temp
cdk init --language=typescript
cdk synth

The following error occurs
```
'.' is not recognized as an internal or external command,
operable program or batch file.
Subprocess exited with error 1
```
If I open cdk.json and replace '/' with '\\' then execute "cdk synth" again, it will succeed.
```
{
  "app": ".\\node_modules\\.bin\\ts-node bin/temp.ts"
}
```

**Expected behavior**
Executing "cdk synth" on Windows OS should work without having to edit the cdk.json file.

**Version:**
 - OS: Windows 10
 - Programming Language: Typescript
 - CDK Version: 0.32.0

**Comment by eladb** [comment]
@Iamz thanks for reporting. Can you try to change `app` in `cdk.json` to be `npx ts-not bin/temp.ts` and let us know if this works.

**Comment by Iamz** [comment]
@eladb Yes, changing `app` to `npx ts-node bin/temp.ts` fixes the problem.

**Comment by eladb** [comment]
Awesome. We'll fix this (unless you are interested in submitting a PR :-))

**Comment by 15b883** [comment]
Hi, I have the same problem here.
But there's no problem going into the virtual environment on the MAC and executing the SDK synth.But in win10 virtual environment after the implementation of the error

`Subprocess exited with error 9009`

**Comment by Muhammadinaam** [comment]
> Hi, I have the same problem here.
> But there's no problem going into the virtual environment on the MAC and executing the SDK synth.But in win10 virtual environment after the implementation of the error
> 
> `Subprocess exited with error 9009`

I am also having this error

**Comment by advissor** [comment]
OS : WIndows 
Python : Python3
Local python returns a version via : 
```
C:\Users\XXX>python --version
Python 3.7.5
```
`python3 --version`, returns nothing

When running `cdk deploy` I also saw a 9009 error, in my case this was a format of python call in **cdk.json**

**This statement gave 9009 :** 
```
{
  "app": "python3 app.py"
}
```

**Works :** 
```
{
  "app": "python app.py"
}
```
So, you need to adjust properly binary call in **cdk.json**
