### ISSUE TITLE
Support AWS Step Functions callback patterns in workflow

### ISSUE THREAD

**Issue by albegali** [awslabs/aws-cdk#2658]
In order to support [Callback patterns in workflow](https://aws.amazon.com/it/about-aws/whats-new/2019/05/aws-step-functions-support-callback-patterns/), there is the need to append `.waitForTaskToken` string to `resourceArn` for the following task types:

- InvokeFunction
- PublishToTopic
- SendToQueue
- RunEcsFargateTask

I will submit a PR for this, looking forward to the comments and review.

**Comment by eladb** [comment]
Sounds great.

**Comment by qihsh** [comment]
Is it done for ```RunEcsFargateTask```? I could not find relevant documentation regarding setting ```waitForTaskToken``` for ```RunEcsFargateTask```.
