### ISSUE TITLE
Document where the CDK "leaks"

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#266]
The CDK provides an abstraction over CloudFormation, but there are still cases where users need to "break the glass" and understand what's going on under the hood. 

As a rule of thumb, we strive that the CDK's relationship to CloudFormation (or to any synthesized artifact) will "leak" in the situations that are similar to when compiled code "leaks" to the compiled program.

Here's an initial list:

* Cost
* Diagnostics
* Diff to deployed stack
* Resource attributes (that's actually a leak from the runtime)
* Resource Limits

**Comment by Doug-AWS** [comment]
Does the "Accessing the AWS CloudFormation Layer", https://docs.aws.amazon.com/CDK/latest/userguide/cfn_layer.html, topic satisfy? If so, please close this; otherwise, give me more info or we can talk about it.

**Comment by rix0rrr** [comment]
What's the best place for me to leave line by line comments?

**Comment by Doug-AWS** [comment]
Moving guide issues to doc repo.
