### ISSUE TITLE
0.32.0 Lambda Code Asset - ValidationError: Parameters: [XxxFunctionCodeArtifactHashXXXX] must have values

### ISSUE THREAD

**Issue by jiayun** [awslabs/aws-cdk#2664]
**Describe the bug**
My project structure:
- root/
-- cdk/
-- functions/

Lambda code asset in stack `const asset = Code.asset('../functions');`

Ran cdk deploy with cdk 0.32.0, I got the message - ValidationError: Parameters: [XxxFunctionCodeArtifactHashXXXX] must have values.

After I changed the cdk version back to 0.31.0, the same command succeeded.

**To Reproduce**
cdk deploy

**Expected behavior**
No error.

**Version:**
 - OS: macOS Mojave
 - Programming Language: TypeScript
 - CDK Version: 0.32.0

**Comment by BDQ** [comment]
@jiayun it's you CDK cli version is still on 0.31.0 - make sure you upgrade your globally installed version of the cli.

**Comment by jiayun** [comment]
@BDQ Thank you, you are right. Actually, I have the 0.29.0 version globally. 😭
