### ISSUE TITLE
Fn.cidr should return a List. Currently returns a String in Java

### ISSUE THREAD

**Issue by rgd11** [awslabs/aws-cdk#2671]
Am expecting the following code:

```
CfnParameter pVpcCidr;

CfnSubnet subnet = new CfnSubnet(this, "MySubnet",
  CfnSubnetProps.builder()
  ...  
  .withCidrBlock(Fn.select(4, Fn.cidr(pVpcCidr.getRef(), 16, "8"))
  .build();
```
to evalute to:
```
CidrBlock: !Select [ 4, !Cidr [ !Ref pVpcCidr, 16, 8 ]]
```
However, this fails to compile since Fn.select expects a list and Fn.cidr returns a string

**Comment by eladb** [comment]
`Fn.cidr` should return a list and not a string. In the meantime, you could work around by wrapping it in a token:

```ts
Fn.select(4, new Token(Fn.cidr(pVpcCidr.getRef(), 16, '8')).toList());
```

**Comment by rgd11** [comment]
Tried:
```java
Fn.select(4, new Token(Fn.cidr(this.pVpcCidr.getRef(), 16, "8")).toList())
```
and received:

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project xxxxxx: An exception occured while executing the Java class. Got a literal Token value; only intrinsics can ever evaluate to lists.

**Comment by eladb** [comment]
Sorry, you will need to use a lazy token: `Fn.select(4, new Token(() => Fn.cidr(pVpcCidr.getRef(), 16, '8')).toList());`
