### ISSUE TITLE
Documentation: Update Python CDK minimum version requirement to 3.6 (instead of 3.7)

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#2675]

**Comment by Doug-AWS** [comment]
See https://github.com/awsdocs/aws-cdk-guide/pull/11. I'll close this once the docs have been updated.

**Comment by fulghum** [comment]
Nice!  Thanks Doug.  We should probably start organizing dev guide issues in the aws-cdk-guide repo, eh?

**Comment by Doug-AWS** [comment]
Done.
