### ISSUE TITLE
Issues using DynamoEventSource

### ISSUE THREAD

**Issue by armandosoriano** [awslabs/aws-cdk#2681]
**Describe the bug**
Following [guide](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-event-sources-readme.html#dynamodb-streams) to attach a trigger to DynamoDb throws the following compiler error:. 
```
error TS2345: Argument of type 'import(".../node_modules/@aws-cdk/aws-dynamodb/lib/table").Table' is not assignable to parameter of type 'import(".../node_modules/@aws-cdk/aws-lambda-event-sources/node_modules/@aws-cdk/aws-dynamodb/lib/table").Table'.
Types have separate declarations of a private property 'table'
```
Doing `@ts-ignore` on it, throws:
```
.../node_modules/@aws-cdk/aws-lambda-event-sources/lib/dynamodb.js:17
target.addEventSourceMapping(`DynamoDBEventSource:${this.table.node.uniqueId}`, {
^
TypeError: target.addEventSourceMapping is not a function
at DynamoEventSource.bind (.../node_modules/@aws-cdk/aws-lambda-event-sources/lib/dynamodb.js:17:16)
at Function.addEventSource (.../node_modules/@aws-cdk/aws-lambda/lib/function-base.js:150:16)
```

**To Reproduce**
Use `fn.addEventSource(new DynamoEventSource(table, { startingPosition: StartingPosition.Latest }));`.

**Expected behavior**
It might work as stated in docs

**Version:**
 - OS: Linux
 - Programming Language: TypeScript
 - CDK Version: 0.31

**Comment by eladb** [comment]
Can you please ensure that all your dependencies use the same CDK version and recreate your node_modules

**Comment by armandosoriano** [comment]
Sure let me rebuild everything

**Comment by armandosoriano** [comment]
@eladb thanks! you were right, all was about `"@aws-cdk/aws-lambda-event-sources": "^0.32.0",` and the rest of dependencies pointing to `0.31.0`

**Comment by eladb** [comment]
Yap
