### ISSUE TITLE
Lambda fromFunctionArn has bug

### ISSUE THREAD

**Issue by cbrothersnow** [awslabs/aws-cdk#2696]
**Describe the bug**

The `lambda.fromFunctionArn` is calling `extractNameFromArn`

```ts
const functionName = extractNameFromArn(attrs.functionArn);
```

This function will never work because the the `cdk.fn.select` steps from 0 not 1

```ts
function extractNameFromArn(arn) {
    return cdk_1.Fn.select(6, cdk_1.Fn.split(':', arn));
}
```

So at minimum this should be return cdk_1.Fn.select(5, cdk_1.Fn.split(':', arn));

But also this doesn't take into consideration arns with resource and/or / in them .

since an arn can have the form:
arn:partition:service:region:account-id:resource
arn:partition:service:region:account-id:resourcetype/resource
arn:partition:service:region:account-id:resourcetype/resource/qualifier
arn:partition:service:region:account-id:resourcetype/resource:qualifier
arn:partition:service:region:account-id:resourcetype:resource
arn:partition:service:region:account-id:resourcetype:resource:qualifier

**To Reproduce**
Command line used or code snippet

**Expected behavior**
since an arn can have the form:
arn:partition:service:region:account-id:resource
arn:partition:service:region:account-id:resourcetype/resource
arn:partition:service:region:account-id:resourcetype/resource/qualifier
arn:partition:service:region:account-id:resourcetype/resource:qualifier
arn:partition:service:region:account-id:resourcetype:resource
arn:partition:service:region:account-id:resourcetype:resource:qualifier

You have to look for the "/" and adjust.  Something like this:

```ts
function extractNameFromArn(arn) {
    var functionName = cdk_1.Fn.split(':', arn);
    var functionReturn = ""
    var functionLength = functionName.length;
    if (cdk_1.Fn.conditionContains(functionName, "/")){
        functionLength = cdk_1.Fn.split('/', arn).length;
        functionReturn = cdk_1.Fn.select(functionLength - 1, cdk_1.Fn.split('/', arn));
    } else {
        functionReturn = cdk_1.Fn.select(functionLength - 1, cdk_1.Fn.split(':', arn));
    }
    return functionReturn;
}
```

**Version:**
 - Cloud9
 - Typescript
 - CDK Version 0.33.0

**Comment by rix0rrr** [comment]
https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda

We know for a fact that a Lambda ARN will look like this:

```
arn:aws:lambda:region:account-id:function:function-name[:version]
 0   1    2      3       4          5          6           7
```

So as far as I can tell the code would appear to be correct.

What is the error you're experiencing?

**Comment by cbrothersnow** [comment]
This:

    const lambdaSingleFunction = lambda.Function.fromFunctionAttributes(this, "LambdaSingleUserRotation", {
            //functionArn: "arn:aws:lambda:" + props.regionName + ":function:function-name",
            functionArn:"arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser",

        })
    new cdk.CfnOutput(this, "functionLength", {
        value: lambdaSingleFunction.functionName,
    })

On synth give me:


/home/ec2-user/environment/set-acaweb/cdk/node_modules/@aws-cdk/cdk/lib/cfn-output.ts:86
      throw new Error(`Missing value for CloudFormation output at path "${this.node.path}"`);
            ^
Error: Missing value for CloudFormation output at path "set-acaweb-dev-LambdaStack/lambda/lambdaSingleFunction"
    at new CfnOutput (/home/ec2-user/environment/set-acaweb/cdk/node_modules/@aws-cdk/cdk/lib/cfn-output.ts:86:13)
    at new Lambda (/home/ec2-user/environment/set-acaweb/cdk/lib/lambda-stack.ts:34:1)
    at new LambdaStack (/home/ec2-user/environment/set-acaweb/cdk/bin/dev/lambda.ts:14:9)
    at Object.<anonymous> (/home/ec2-user/environment/set-acaweb/cdk/bin/dev/lambda.ts:18:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
Subprocess exited with error 1

If I change it to arn:aws:serverlessrepo:us-east-1:297356227824:applications:SecretsManagerRDSMySQLRotationSingleUser

The synth works.  But that isn’t the arn, because of the “/”.

I get the error above if I try to use arn:aws:serverlessrepo:us-east-1:297356227824: SecretsManagerRDSMySQLRotationSingleUser

Which should be a valid arn.

I don’t have a log of the deploy error, but it’s something about again about not being able to parse the arn to find the function name.

The cdk.Fn.select function start the array element count at 0, not 1.  So for a valid arn of arn:aws:serverlessrepo:us-east-1:297356227824: SecretsManagerRDSMySQLRotationSingleUser if you use cdk.Fn.select(6 you get nothing

Arn(0):aws(1):serverlessrepo(2):us-east-1(3):297356227824(4): SecretsManagerRDSMySQLRotationSingleUser(5)

I changed the function locally and it works for all cases:

function extractNameFromArn(arn) {
    var functionName = cdk_1.Fn.split(':', arn);
    var functionLength = functionName.length;
    var functionReturn = cdk_1.Fn.select(functionLength - 1, cdk_1.Fn.split(':', arn));
    if (cdk_1.Fn.conditionContains(functionName, "/")){
        functionLength = cdk_1.Fn.split('/', arn).length;
        functionReturn = cdk_1.Fn.select(functionLength - 1, cdk_1.Fn.split('/', arn));
    }
    return functionReturn;
}





Carol Brothers
Senior DevOps Engineer
[signature_1887532665]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by jogold** [comment]
Seems to me that `arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser` is not the ARN of a function but the ARN (application id in this case) of a Serverless Application (see `AWS::Serverless::Application`).

**Comment by cbrothersnow** [comment]
Oh, you are correct.  Sorry.  The function works fine, when you know what you’re doing 😊


Carol Brothers
Senior DevOps Engineer
[signature_1338018081]

Email: carol.brothers@ucop.edu
Phone: (510) 587-6224
University of California, Office of the President
300 Lakeside Drive, 12th floor, 12216
Oakland, CA 94612
[Title: LinkedIn - Description: LinkedIn icon]<https://www.linkedin.com/in/carolbrothers>

**Comment by RomainMuller** [comment]
Alright - I'm closing this since there is in fact no problem :) Thanks for confirming!
