### ISSUE TITLE
Cannot run cdk synth without specifying AWS credentials/region

### ISSUE THREAD

**Issue by boyangfu** [awslabs/aws-cdk#2697]
I'm using another system to deploy my CF templates and there's no easy way right now for me to run CDK synth to generate the CF templates without specifying a profile. Seems like there should be a way to do this.

**Comment by boyangfu** [comment]
Why was this closed? Not requiring a region isn't the same as not requiring a profile

**Comment by boyangfu** [comment]
To clarify, I'd like to run CDK synth without using the default profile, or specifying any profile, keys, or region

**Comment by dapirian** [comment]
We'd also like to do this, why was this closed with no comment?
