### ISSUE TITLE
Recommended alternate of manual changeset review with release 0.33.0

### ISSUE THREAD

**Issue by shashanktomar** [awslabs/aws-cdk#2700]
I am not sure if this is covered before but I failed to find any reference.

The infrastructure pipeline workflow with CF is:

1. CF changes go through pull request 
2. This triggers a CodeBuild action to generate a changeset
3. A manual block halt the pipeline
4. Someone with appropriate permissions reviews the change and apply the changeset
5. Stack is deployed

For CDK our workflow is:
1. CDK changes go through pull request
2. This triggers a CodeBuild action to generate CF templates using cdk synth
3. Another CodeBuild action generates a changeset for these templates
This is followed by step 3, 4 and 5 from the previous workflow

After the release of *cloud assemblies* we are confused if the same flow is still supported. If not, what is the recommended workflow to have a manual review process by an authorized user?

**Comment by skinny85** [comment]
Hey @shashanktomar ,

yes, the same flow is still supported. We might release a flow based on Cloud Assemblies in the future, but the one you described will always be valid.

Does this alleviate your concerns?

Thanks,
Adam

**Comment by shashanktomar** [comment]
Thanks for the reply Adam, yes it does.
