### ISSUE TITLE
dynamodb.Table needs a `removalPolicy` prop

### ISSUE THREAD

**Issue by mansisorathiya** [awslabs/aws-cdk#2710]
How to attach Deletion policy to software.amazon.awscdk.services.dynamodb.Table Class ?

**Comment by NGL321** [comment]
Thanks for reaching out!
DeletionPolicy is an enumerable option of a CDK resource (cfnresource) in the Construct Library! I recommend taking a look at the [Construct Library documentation](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/cdk/deletionpolicy.html#cdk_DeletionPolicy).

Try something along the lines of: `resource.options.deletionPolicy = DeletionPolicy.Retain;`.

Let me know if this is what you were trying to accomplish!

**Comment by eladb** [comment]
I believe @mansisorathiya is asking about the `dynamodb.Table` construct (L2) and not the `dynamodb.CfnTable` construct (L1). Indeed, L1 have an `options` field which is where you can specify raw CloudFormation options for the low-level resource.

Some L2s (such as `s3.Bucket`) actually expose a [`removalPolicy`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#removalpolicy) prop which offers an API for defining the deletion policy, but we haven't gotten around to adding those to all stateful L2s (see #2282). It should be easy to add if you anyone is interested to pick this up.

As a workaround, you should be able to use an escape hatch like so:

```ts
const resource = table.node.findChild('Resource') as CfnResource;
resource.options.deletionPolicy = DeletionPolicy.Retain;
```
