### ISSUE TITLE
Can't get port from RDS DatabaseCluster Endpoint

### ISSUE THREAD

**Issue by joehillen** [awslabs/aws-cdk#2711]
**Describe the bug**
I can't pass the RDS port from one stack to another.

I open a question on [StackOverflow](https://stackoverflow.com/questions/56401924/what-is-the-correct-way-to-pass-an-rds-databasecluster-from-one-stack-to-another) about it, but now I think it's actually a bug.

**To Reproduce**

```ts
class DbStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: { vpc: ec2.Vpc }) {
    super(scope, id);
    const { vpc } = props;
    const db = new DatabaseCluster(this, "Database", {
      engine: rds.DatabaseClusterEngine.AuroraPostgresql,
      engineVersion: "10.7",
      masterUser: {
        username: "admin",
      },
      defaultDatabaseName: "main",
      instanceProps: {
        instanceType: new ec2.InstanceType("r5.large"),
        vpcSubnets: {
          subnetType: ec2.SubnetType.Private,
        },
        vpc,
      },
      storageEncrypted: true,
      parameterGroup: {
        parameterGroupName: "default.aurora-postgresql10",
      } as any,
    });
    console.log(db.clusterEndpoint);
    console.log(db.clusterEndpoint.hostname);
    console.log(db.clusterEndpoint.port);
    console.log(db.clusterEndpoint.socketAddress);
  }
}
```

The console output is:

```
Endpoint {
  hostname: '${Token[Resource.Endpoint.Address.148]}',
  port: -1.8881545897087827e+289,
  socketAddress: '${Token[Resource.Endpoint.Address.148]}:{IndirectPort}' }
${Token[Resource.Endpoint.Address.148]}
-1.8881545897087827e+289
${Token[Resource.Endpoint.Address.148]}:{IndirectPort}
```

**Expected behavior**

I need a way to determine the port.

**Version:**
 - OS: Linux
 - Programming Language: Typescript
 - CDK Version: 0.33.0

**Comment by joehillen** [comment]
This might be a duplicate of https://github.com/awslabs/aws-cdk/issues/2679, but not exactly.

**Comment by joehillen** [comment]
Just confirmed. Still happening in v0.34

**Comment by cjyclaire** [comment]
+1 for this, seeing the same behavior

**Comment by jogold** [comment]
This should be fixed in the next release, as a temporary workaround in v0.34.0 you can do this to use the `socketAddress` somewhere

```ts
const socketAddress = `${db.clusterEndpoint.hostname}${new cdk.Token(db.clusterEndpoint.port)}`;
```

**Comment by dekoza** [comment]
The problem is still present on 1.45.0 - I get port number `-1.8881545897087736e+289` instead of `3306`. Looks like overflow.

**Comment by balupraveendatty** [comment]
This issue is still there in `1.82`, Please provide a fix for this
```
Name: ....
Value:
  Fn::Join:
    - ""
    - - jdbc:postgresql://
      - Fn::GetAtt:
          - RDSDBInstanceD5E32DDA
          - Endpoint.Address
      - :-1.8881545897088128E289/maindb
```

**Comment by skinny85** [comment]
@balupraveendatty maybe you're missing a call to `Token.asString()` somewhere where you're passing the `port` directly as a number, where a string is expected? For example, this works for me:

```ts
        const vpc = new ec2.Vpc(this, 'Vpc');
        const db = new rds.DatabaseCluster(this, "Database", {
            engine: rds.DatabaseClusterEngine.auroraPostgres({
                version: rds.AuroraPostgresEngineVersion.VER_10_7,
            }),
            instanceProps: {
                vpc,
            },
        });
        new cdk.CfnOutput(this, 'Output', {
            value: cdk.Token.asString(db.clusterEndpoint.port),
        });
```

Produces:

```yaml
Outputs:
  Output:
    Value:
      Fn::GetAtt:
        - DatabaseB269D8BB
        - Endpoint.Port
```

**Comment by balupraveendatty** [comment]
Nice one, cheers @skinny85

**Comment by belinde** [comment]
Issue still present in 1.98.0. I want to put the port inside a secret, so skinny85's workaround doesn't seem a viable option

**Comment by v1pz3n** [comment]
Thanks @skinny85 , you saved me :smiling_face_with_three_hearts:

**Comment by moltar** [comment]
Looks like this is still an issue.

When I console.log the port:

```ts
console.log('port', cluster.clusterEndpoint.port)
```

I get:

```
port -1.8881545897088303e+289
```

**Comment by moltar** [comment]
Btw, I can fix it like this:

```ts
Object.assign(cluster.clusterEndpoint, { port: 5432 })
```

**Comment by skinny85** [comment]
@moltar https://github.com/aws/aws-cdk/issues/2711#issuecomment-765628398

**Comment by moltar** [comment]
@skinny85 But I don't have the option to wrap in `cdk.Token.asString`, as I am passing the entire cluster instance to another construct (see linked issue above my first comment). Should the third party construct be handling this then?

**Comment by skinny85** [comment]
OK... can you show the consuming code then?

**Comment by moltar** [comment]
https://github.com/moia-oss/bastion-host-forward/blob/81eedc3077db756f4f6737038f7e4728e95c302f/lib/aurora-serverless.ts#L50-L52

**Comment by skinny85** [comment]
Right. Exactly like I said in https://github.com/aws/aws-cdk/issues/2711#issuecomment-765628398, the code should be:

```ts
      port: Token.toString(props.serverlessCluster.clusterEndpoint.port),
```

, **not**:

```ts
      port: props.serverlessCluster.clusterEndpoint.port.toString(),
```

**Comment by sangheestyle** [comment]
> ```ts
> cdk.Token.asString(
> ```

not `Token.toString` but `cdk.Token.asString` which you earlier mentioned. :)
