### ISSUE TITLE
Where are the docs files?

### ISSUE THREAD

**Issue by kidbrax** [awslabs/aws-cdk#2743]
CONTRIBUTING.md says they are in the docs/src directory but that doesn't seem to be in this repo anymore. I'd like to fix some discrepancies in the docs.  Where can I submit those changes?

**Comment by eladb** [comment]
You should be able to submit PRs against https://github.com/awsdocs/aws-cdk-guide/tree/master/doc_source

**Comment by Doug-AWS** [comment]
All of the CDK Developer Guide topics have a link to the markdown version of the topic in the guide repo, aws-cdk-guide. Click the cat shadow, edit away, and file a PR.
