### ISSUE TITLE
[Question] Why have a separate package for AWS CodePipeline actions?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [awslabs/aws-cdk#2746]
Just a (hopefully) simple question for reasoning behind AWS CodePipeline actions being in their own separate package.

I understand that the "simple" reasoning would be "to decrease bundle sizes/separate concerns", however my initial thought would be to use cherry-picking.

For example, couldn't you simply cherry pick via:
```
import { S3SourceAction } from '@aws-cdk/aws-codepipeline/actions';
```

Maybe it's just aesthetic preference, but if it's functionally different, I would appreciate the reasoning; might lead me to adopt a similar pattern in my own libs.

**Comment by rix0rrr** [comment]
The biggest reason (in my mind) is to avoid circular dependencies.

For an example of where we haven't done that yet and it's causing problems, see: https://github.com/awslabs/aws-cdk/issues/2739
