### ISSUE TITLE
Rename default CDK dev guide page

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#2748]
Currently, the default page of the CDK dev guide is titled "What is the AWS CDK?" and the file name is `what-is.html`. Basically that's the first result in a Google search for "aws cdk docs" and it looks odd.

Let's change this to "index.html" and the title to "AWS Cloud Development Kit" please.

**Comment by Doug-AWS** [comment]
Work in progress.

**Comment by Doug-AWS** [comment]
Sorry, no can do. I ran into a build issue and don't have time to track it down now. Maybe after GA.

**Comment by Doug-AWS** [comment]
Done. If you navigate to https://docs.aws.amazon.com/cdk/latest/guide, you'll be directed to https://docs.aws.amazon.com/cdk/latest/guide/home.html. I've redirected https://docs.aws.amazon.com/cdk/latest/guide/what-is.html to that page also.
