### ISSUE TITLE
Developer Guide: Versioning section

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#2762]
The CDK Developer Guide should include a short section that explains versioning, talks about semver usage and expectations, etc.

**Comment by Doug-AWS** [comment]
IIRC, semver means:

- If I create code in CDK v1.0, it works without change in CDK v1.x.
- If I create code in CDK v.1.0, it may need modifying to work in CDK v2.x.

We also need to explain stability.

**Comment by fulghum** [comment]
@RomainMuller – probably makes sense for you to think about this content as well since it's related.

**Comment by Doug-AWS** [comment]
How about: https://docs.aws.amazon.com/cdk/latest/guide/aws_construct_lib.html#aws_construct_lib_versioning

**Comment by RomainMuller** [comment]
@Doug-AWS - I've rephrased it slightly in https://corp.quip-amazon.com/zHjEA5L05v1W/CDK-Versions-API-Stability

**Comment by Doug-AWS** [comment]
I'll take a look and add it to the docs soon.

**Comment by RomainMuller** [comment]
Duplicate of awslabs/cdk-ops#370
