### ISSUE TITLE
onCloudTrailPutObject doesn't accept lambda function as target anymore

### ISSUE THREAD

**Issue by MichaelHindley** [awslabs/aws-cdk#2783]
edit: Use the `aws-events-targets` package and `targets.LambdaFunction`.

Leaving up for RTFM shame 👍 

**Describe the bug**
In 0.32, `bucket.onPutObject` was renamed to `bucket.onCloudTrailPutObject` and the signature was also changed. Before it was possible to trigger a lambda based on the PutObject event, but their types are not compatible anymore.

**To Reproduce**
// shared
```typescript
const trail = new cloudtrail.Trail(stack, 'trail', {
  trailName: "name"
})

trail.addS3EventSelector([sourcesBucket.arnForObjects('')], {
  readWriteType: cloudtrail.ReadWriteType.WriteOnly
})

const aLambda = new lambda.Function(....)
const aBucket = new s3.Bucket(...)
```

// pre 0.32, works
```typescript
aBucket.onPutObject('id', aLambda) // class Funtion from aws-lambda/lib/function.d.ts
```

// post 0.32, does not work
```typescript
aBucket.onCloudTrailPutObject('id', {
  target: aLambda, // Error: type 'bind' is missing in type Function, but required in type IRuleTarget
    })
```

From the docs, it mentions that `bind` should be **The CloudWatch Event Rule that would trigger this target.**.  However the docs for `OnCloudTrailPutObject` mentions that it **Defines an AWS CloudWatch event rule that can trigger a target.**

So the reference in `bind` should not be needed since it should already be known what the Event Rule is, like it was pre 0.32.0.
I can't seem to find the equivalent functionality based on the api's on the objects, I doubt it's been removed but I also can't seem to figure out what exactly is expected to be provided after the changes.

**Expected behavior**
Allow setting Lambda as target for `bucket.OnCloudTrailPutObject`

**Version:**
 - OS Win 10
 - Typescript
 - CDK Version 0.33.0

**Comment by konstantinj** [comment]
Hi, I'm looking for the correct usage of `onCloudTrailPutObject` with Lambda. Did you find out how it works now?
