### ISSUE TITLE
CDK: Could not run version check due to error EACCES: permission denied, open '/usr/local/lib/node_modules/aws-cdk/lib/../.LAST_VERSION_CHECK'

### ISSUE THREAD

**Issue by markusl** [awslabs/aws-cdk#2790]
**Describe the bug**

When on a system which uses multiple user accounts, `cdk synth` may return an error with missing permissions to do LAST_VERSION_CHECK

```
Could not run version check due to error EACCES: permission denied, open '/usr/local/lib/node_modules/aws-cdk/lib/../.LAST_VERSION_CHECK'
```

**To Reproduce**

On account A:

```
$ npm i -g aws-cdk

```

On account B:

```
$ cdk synth
```

**Expected behavior**
CDK Synth would work normally

**Version:**
 - OS: Macbook
 - Programming Language: Typescript
 - CDK Version: 0.33.0

**Comment by RomainMuller** [comment]
Hey @markusl - just to make sure... Is this **failing** for you?
In principle, this message should only be a warning...

I still think this is a bug (putting the timestamp file in a possibly read-only location isn't so great), but if that is just a warning, the urgency of fixing this is a little lower 😅

**Comment by markusl** [comment]
@RomainMuller now that you asked, it seems to be a warning only, but I was a little bit confused as it _looked like_ an error to me :)

**Comment by rix0rrr** [comment]
Fixed by https://github.com/awslabs/aws-cdk/pull/2774
