### ISSUE TITLE
Property 'EcsTask' does not exist in @aws-cdk/aws-events-targets

### ISSUE THREAD

**Issue by sohailalam2** [awslabs/aws-cdk#2801]
**Describe the bug**
The current NPM version of the `@aws-cdk/aws-events-targets` library version 0.33.0 does not include the `EcsTask` IRuleTarget type. 

Although the github repo includes it under the same version number [here](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-events-targets/test/ecs/integ.event-fargate-task.ts).

**To Reproduce**
`npm install @aws-cdk/aws-events-targets@0.33.0`

```js
const events = require('@aws-cdk/aws-events');
const targets = require('@aws-cdk/aws-events-targets');

// ... 
// ...

    const rule = new events.Rule(this, 'Cron', {
      enabled: true,
      scheduleExpression: 'cron(0 18 ? * MON-FRI *)',
    });

    rule.addTarget(
      new targets.EcsEc2Task({
        cluster,
        taskDefinition,
        taskCount: 1,
        containerOverrides: [
          {
            containerName: 'TheContainer',
            command: ['echo', events.EventField.fromPath('$.detail.event')],
          },
        ],
      })
    );
```

**Expected behavior**
It is expected that this EcsTask definition should be exported in the same version. 

**Version:**
 - OS: Windows 10
 - Programming Language: Javascript
 - CDK Version: 0.33.0 (build 50d71bf)

**Comment by jogold** [comment]
As of v0.33.0, the only ECS target available is the `EcsEc2Task` (https://github.com/awslabs/aws-cdk/blob/v0.33.0/packages/%40aws-cdk/aws-events-targets/lib/ecs-ec2-task.ts and https://github.com/awslabs/aws-cdk/blob/v0.33.0/packages/%40aws-cdk/aws-events-targets/test/ecs/integ.event-task.lit.ts).

What you see on master will be released in v0.34.0

**Comment by sohailalam2** [comment]
Thanks @jogold ... whats the ETA for v0.34.0? 😄 Can't wait for it :)

**Comment by jogold** [comment]
See https://github.com/awslabs/aws-cdk/pull/2791

**Comment by sohailalam2** [comment]
Wow awesome 👏 Thanks for the update... closing the ticket.
