### ISSUE TITLE
NoSuchBucket

### ISSUE THREAD

**Issue by psxcode** [awslabs/aws-cdk#2813]
I'm getting "NoSuchBucket: The specified bucket does not exist"
while trying to deploy

Bootstrap is done and green
Synth provides correct result
Deploy gives me error

This is the setup
```js
const app = new App()
const stack = new Stack(app, 'MyStack')
const func = new Function(stack, 'MyLambda', {
  runtime: Runtime.NodeJS810,
  code: Code.asset(resolve('build/echo.zip')),
  handler: 'index.handler',
})
app.synth()
```

`yarn cdk boostrap --profile myname`
`> Environment aws://my-account/eu-north-1 bootstrapped (no changes)`

`yarn cdk deploy --profile myname`
asks a question about Role creation, I reply - yes
`> MyStack failed: NoSuchBucket: The specified bucket does not exist`

**Version:**
 - macOS Mojave 10.14.5
 - Typescript
 - 0.34.0 (build 523807c)

**Comment by bashwork** [comment]
https://github.com/awslabs/aws-cdk/issues/1270

**Comment by psxcode** [comment]
I've seen this issue, and it seemed like not my case. But after reading it again, I realise that it might be it. Thank you. I will close this issue..
