### ISSUE TITLE
EC2 Container Service Role

### ISSUE THREAD

**Issue by FlorinAsavoaie** [awslabs/aws-cdk#2827]
**Describe the bug**

I would expect that when using `@aws-cdk/aws-ecs.Cluster.addCapacity`, the instance role created would simply use the `AmazonEC2ContainerServiceforEC2Role` managed policy, as described in the [ECS documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html). However, it seems like it creates a completely new policy with hardcoded permissions.

**To Reproduce**
```typescript
const cluster = new ecs.Cluster(this, 'Cluster', {
    clusterName: 'MyECSCluster',
    vpc: this.vpc
});
cluster.addCapacity('ASG', {
    instanceType: new ec2.InstanceType('c5.large'),
    taskDrainTimeSeconds: 0
});
```

A new `ClusterASGInstanceRoleDefaultPolicy########` policy is created.

**Expected behavior**
I'd expect that the `AmazonEC2ContainerServiceforEC2Role` managed policy is attached to the instance role.

**Version:**
 - Windows / Linux / OSX
 - Typescript
 - 0.34

**Comment by NGL321** [comment]
Hi Florin!

Sorry for the delay in response. As indicated [here](https://github.com/awslabs/aws-cdk/pull/2881#issuecomment-502611841), this is the intended function addCapacity. Please see the link for more info on why.

If you find anything else, please don't hesitate to post!
