### ISSUE TITLE
cdk.out potentially not containing correct files

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#2836]
**Describe the bug**
I would expect to have a single `cdk.out` directory in my CDK directories, but in the build tree I can see they're nested:

```
$ find . -name cdk.out
...
./packages/@aws-cdk/aws-dynamodb-global/test/cdk.out
./packages/@aws-cdk/aws-dynamodb-global/test/cdk.out/cdk.out
...
```

Don't know which one is used when, and maybe everything works out correctly, but this sets my spidey senses tingling that something is wrong.

**Comment by eladb** [comment]
The second cdk.out is not a directory... it’s the name of the legacy manifest file, and we emit it for backwards compatibility with  pre 0.33.0 toolkit
