### ISSUE TITLE
env parameter of cdk.Stack constructor seems to be ignored

### ISSUE THREAD

**Issue by dhx-mike-palandra** [awslabs/aws-cdk#2841]
**Describe the bug**
`env` parameter of `cdk.Stack` constructor seems to be ignored.  Apologies if I overlooked something obvious.

**To Reproduce**
1. Initialize a new python CDK project
`cdk init --language python`

2. ./cdk_test/cdk_test_stack.py: initialize any construct/resource in the sample stack class; e.g.
`sns.Topic(self, 'CdkTestTopic')`

3. app.py: initialize the stack with an explicit region that differs from your default; e.g.
```
app = cdk.App()
env = cdk.Environment(region='us-east-2')
stack = CdkTestStack(app, 'my-cdk-test', env=env)
```

**Expected behavior**
Relevant cdk commands that interact with CloudFormation (e.g., diff, deploy, destroy, etc.) should operate on the region specified above in app.py. In my case, they did not.

**Version:**
 - OS:  cpe:/o:fedoraproject:fedora:30
 - Programming Language:  Python 3.7.3  
 - CDK Version:  0.34.0 (build 523807c)

**Comment by made2591** [comment]
I think this is discussed in #2866 - by the way, a *temporary fix* should be already present ([line 515](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/cdk/lib/stack.ts#L515)) here) ... but I didn't understand exactly why it doesn't work 🤔

**Comment by NGL321** [comment]
Hi @dhx-mike-palandra!

It looks like @made2591 linked a duplicate issue that has since been resolved.
Please confirm if this fixed your problem so we can either close this issue, or readdress the problem.

Thanks!

**Comment by dhx-mike-palandra** [comment]
Thanks for following up.  I tested again with the latest CDK release:
```
$ cdk --version
0.36.0 (build 6d38487)
```

Unfortunately, the issue still persists; i.e. despite an explicit region specification of "us-east-2", issuing "cdk deploy" creates a stack in my default region (which is not us-east-2).

**Comment by eladb** [comment]
Can you please share some code for a minimal repro?

**Comment by eladb** [comment]
Oh, just saw that you provided one... Are you propagating `kwargs` from your stack to the base `Stack`?

**Comment by dhx-mike-palandra** [comment]
No; I was not.  I just corrected that and tried again, and the stack indeed is created in us-east-2.  Sorry for not catching that earlier.  Thanks for your advice.  Take care.

**Comment by eladb** [comment]
No worries, just made the same mistake myself in a little python app I am working on :-)

**Comment by shearn89** [comment]
Just for future googlers - I just bumped into this on CDK 2.8. I was referencing the region/account passed in via `env` as `self.env.region` in my stack. Turns out that you need to reference them as `self.region`! Took me a few minutes to work out, doh!
