### ISSUE TITLE
codebuild.Project.addToRoleInlinePolicy should allow you to specify the policyName

### ISSUE THREAD

**Issue by corymhall** [awslabs/aws-cdk#2845]
Currently there are two ways to attach an IAM policy to the default IAM role that is created with the codebuild project.

1. `addToRolePolicy` - Adds the provided policy statement to the default inline policy created with the role.
2. `addToRoleInlinePolicy` - Creates a new inline policy with the hardcoded name `CodeBuildEC2Policy` and adds the provided policy statement. 

It would be great if the `addToRoleInlinePolicy` method allowed you to specify the `policyName` so that we could create as many inline policies as we want.

**Comment by corymhall** [comment]
I was going to create a pull request to add this functionality, but I noticed there is already a pull request that is updating that method https://github.com/awslabs/aws-cdk/pull/2662. Can this be addressed in that pull request, or should I wait until that is implemented and create a separate PR?

**Comment by skinny85** [comment]
Hey @corymhall ,

thanks for opening the issue. The method `addToRoleInlinePolicy` was exposed accidentally on `Project`. The intention of it was to keep it private, and that's what the PR #2662 will do. If you need that functionality, you should call it directly on the `IRole` `Project` exposes: `project.role.attachInlinePolicy(new iam.Policy(...))`.

Thanks,
Adam

**Comment by corymhall** [comment]
ah that makes sense. Thanks for the quick response!
