### ISSUE TITLE
cdk --help has issues

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#2848]
It still states:

  --json, -j            Use JSON output instead of YAML
                                                      [boolean] [default: false]

Which makes no sense as it output JSON anyway. We need a -y (YAML) flag for those who want YAML

It also states:

  --app, -a             REQUIRED: command-line for executing your app or a cloud
                        assembly directory (e.g. "node bin/my-app.js")  [string]

Which is also incorrect. The example should be "npx ts-node bin/my-app.ts"

**Version:**
 - Windows
 - TypeScript
 - 0.34.0

**Comment by rix0rrr** [comment]
> Which makes no sense as it output JSON anyway. We need a -y (YAML) flag for those who want YAML

Is that true? I was under the impression we were outputting YAML.

> Which is also incorrect. The example should be "npx ts-node bin/my-app.ts"

What it *should* be is discutable. At the very least it's incorrect to say that the example is incorrect. It's a matter of workflow and preference.

**Comment by mhuebner** [comment]
Any ideas on how to set yaml output? Just updated to `0.34.0` and there seems to be no way to output in yaml as already mentioned by @Doug-AWS

**Comment by Doug-AWS** [comment]
Sorry, I was completely wrong. The cdk commands output YAML by default and you need only use the -j flag to get JSON.

**Comment by mhuebner** [comment]
I'm getting Json output only in `0.34.0`. No chance to switch to yaml.

**Comment by Doug-AWS** [comment]
Really? Here's the first 4 lines of **cdk synth** for the code created in the https://docs.aws.amazon.com/cdk/latest/guide/ecs_example.html:

```Resources:
  MyVpcF9F0CA6F:
    Type: AWS::EC2::VPC
    Properties:```

And with the -j flag:

```{
  "Resources": {
    "MyVpcF9F0CA6F": {
      "Type": "AWS::EC2::VPC",```

**Comment by mhuebner** [comment]
Yes, Console output seems to be YML but looking into folder `cdk.out` only contains json files.

**Comment by Doug-AWS** [comment]
Excellent point. @rix0rrr?

**Comment by elexisvenator** [comment]
since 0.34, the yaml seems to be output to console (even when `--output` is specified) and the output folder always contains json.  Previously if `--output` was specified no stacks were output in console. These are both problems - I would much prefer yaml file outputs, and I don't want to spam my console with stacks everytime I synth.

**Comment by rix0rrr** [comment]
`cdk.out` should be treated as a CLI-internal directory, and should not be treated as the final output directory.

**Comment by rix0rrr** [comment]
I'm going to close this issue as the title no longer covers its contents. Please use #2965 to discuss the output of YAML/JSON to output directories.
