### ISSUE TITLE
SDK calls in CDK code

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#2855]
I was wondering, if there is a suggested place for embedding regular SDK API calls into CDK code. Some of our resources need external data that we retrieve thru SDK. What's the preferred way (having in mind javascript is asynchronous) of doing this? Shall I make API calls im between constructs, or there is a dedicated place to do such stuff?

regards

**Comment by rix0rrr** [comment]
Hi there,

We'd be happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow. If you could please [ask that same question again on StackOverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk) and paste the link to it here, we will answer it for you over there.

I will now close this issue, feel free to reopen when pasting the StackOverflow link.
