### ISSUE TITLE
Python - create VPC with subnets in certain CIDRs

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#2884]
Because of the inter-accounts VPC peering, I am forced to create VPC in certain CIDR blocks - this is the mapping for Ireland region:

```
eu-west-1a: 10.12.68.0/23
eu-west-1b: 10.12.70.0/23
eu-west-1c: 10.23.72.0/23
```

I can't find a way how to pass these CIDRs to VPC Construct. Id it doable without engaging Cfn* resources?

thanks in advance

**Comment by rix0rrr** [comment]
Hi there,

We'd be happy to help you out, but GitHub issues is not a support forum. There are websites much better suited for that, such as StackOverflow. If you could please [ask that same question again on StackOverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk) and paste the link to it here, we will answer it for you over there.

I will now close this issue, feel free to reopen when pasting the StackOverflow link.
