### ISSUE TITLE
Describe how to define a shared stack for test dev data

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#289]
The use case is as follows: a team of developers has a dynamo table with lots of test data that they use for development. Ideally we would want the individual developers' stacks to point to this shared DDB table.

I would model this like this. My CDK app will contain the following stacks:

1. "test-data" stack with a DDB table and an Output parameter
2. "dev" stack that instantiates the app's main stack but allows passing an ARN of a Table instead of creating a table.

Perhaps the data store will be an input to the dev stack *anyway* to maintain isolation between persistent and non-persistent components of the arch so passing through a dev stack will just be a natural thing.

Sketch (with environments modeled as keys):

```js
const naStorage = new CustomerTable(this, { env: 'NA' });
const euStorage = new CustomerTable(this, { env: 'EU' });
const devStorage = new CustomerTable(this, { env: 'shared-dev', capacity: { read: 1, write: 1 } });

const prodNA = new MyStack(this, { env: 'NA', storage: naStorage });
const prodEU = new MyStack(this, { env: 'EU', storage: euStorage });
const dev = new MyStack(this, { storage: devStorage });
```

Notice that:

`devStorage` is in the `shared-dev` environment, while the `dev` stack is in the default environment (environment is not specified). This means that people can share the storage but not share the dev stack.

**Comment by Doug-AWS** [comment]
Tracked in #1525

**Comment by Doug-AWS** [comment]
Moving guide issues to doc repo.
