### ISSUE TITLE
Include @types/ dependencies in `dependencies` not `devDependencies`

### ISSUE THREAD

**Issue by everett1992** [awslabs/aws-cdk#2895]
**Describe the bug**
Typescript packages using aws-cdk cannot find a declaration file for module 'yargs'
**To Reproduce**

Create a typescript package that requires aws-cdk.

```console
mkdir repro && cd repro
echo "{}" > package.json
npm install typescript@3.5.2 aws-cdk@0.34.0
./node_modules/.bin/tsc --init
echo "import 'aws-cdk'" > index.ts
./node_modules/.bin/tsc
```

```console
node_modules/aws-cdk/lib/settings.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'yargs'. '/local/home/calebev/repro/node_modules/yargs/index.js' implicitly has an 'any' type.
  Try `npm install @types/yargs` if it exists or add a new declaration (.d.ts) file containing `declare module 'yargs';`
```

Typescript will type check libraries by default. It will fail checking aws-cdk because cdk does not include it's dependencies types in `dependencies`, it includes them in `devDependencies`.

Customers can fix this issue by
 - adding @types/yargs to their dependencies.
 - adding --skipLibCheck to their typescript options.

**Expected behavior**
There should not be any type errors in an effectively empty package. aws-cdk should include it's type dependencies in it's dependencies.

**Version:**
 - linux
 - javascript
 - 0.34.0

**Comment by RomainMuller** [comment]
I think in fact the real problem is that we should not be exporting symbols that depend on a particular 3P dependency. There is no actual need for they args declarations there (we can live with a much simpler, much more restrictive type here).
