### ISSUE TITLE
ecs: Rename `hwType` in `EcsOptimizedAmiProps` interface to `hardwareType`

### ISSUE THREAD

**Issue by hencrice** [awslabs/aws-cdk#2896]
As title suggested

**Comment by NGL321** [comment]
Hi Yenlin, thank you for following the contribution guidelines and creating an issue for your changes!

However, the purpose behind that rule is to justify the changes you are making.
Please add some content here to explain why you think that 'hwType' needs to be renamed!

**Comment by hencrice** [comment]
Hey Noah,

This suggestion came from an ECS-internal API review.
