### ISSUE TITLE
Publish the cdk-integ-tools package so end users can have integration tests for their code

### ISSUE THREAD

**Issue by KingOfPoptart** [awslabs/aws-cdk#2898]
It'd be nice to be able to have integration tests for end-users.  The cdk-integ package is pretty handy for that, but its currently not published.  End users only have the option currently to have unit tests which I think can be improved by exporting the integration test functionality.

**Comment by CaerusKaru** [comment]
Duplicate of https://github.com/awslabs/aws-cdk/issues/300

**Comment by NGL321** [comment]
> Duplicate of #300

@CaerusKaru is correct (thank you!)! I am closing the issue for now. If this isn't what you were looking for, please feel free to clarify in a comment and I will reopen the issue.
