### ISSUE TITLE
Python - add tags to CfnEIP

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#2899]
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/CfnEIP.html

Neither resource constuctor nor any of the modifier methods support setting tags.

**Comment by RomainMuller** [comment]
Hello @lkoniecz,

This class is generated from the CloudFormation Resource Specification.
My understanding is that `AWS::EC2::EIP` does not presently have a `Tags` property, and it is hence impossible for us to support that.

Regards,
Romain.

**Comment by cudandres** [comment]
@lkoniecz here is a workaround I found


```python
# ....
new_eip = core.CfnResource(self, "eip_for_nat", type='AWS::EC2::EIP', properties={
    'Domain': 'vpc',
    'Tags': [
        {'Key': 'Name','Value': self.stack_name + "/for_nat"}
    ] 
})

new_eip.apply_removal_policy(core.RemovalPolicy.RETAIN)
alloc_id =  new_eip.get_att('AllocationId').to_string()

# ... continue on
nat_gw = ec2.CfnNatGateway(self, "nat_gw_for_private_space", 
subnet_id=subnet.subnet_id, allocation_id=alloc_id)
nat_gw.node.add_dependency(new_eip)
# ...
```

**Comment by rezen** [comment]
@lkoniecz here is a workaround I discovered

```python
# ....
new_eip = core.CfnResource(self, "eip_for_nat", type='AWS::EC2::EIP', properties={
    'Domain': 'vpc',
    'Tags': [
        {'Key': 'Name','Value': self.stack_name + "/for_nat"}
    ] 
})

new_eip.apply_removal_policy(core.RemovalPolicy.RETAIN)
alloc_id =  new_eip.get_att('AllocationId').to_string()

# ... continue on
nat_gw = ec2.CfnNatGateway(self, "nat_gw_for_private_space", 
subnet_id=subnet.subnet_id, allocation_id=alloc_id)
nat_gw.node.add_dependency(new_eip)
# ...
```

**Comment by lkoniecz** [comment]
@RomainMuller 
Right, I was most likely looking thru GUI, which allows tagging Elastic IPs, so this is rather cloudformation incompatibility.

@rezen
Thanks for the hint. I might try it out.

to be closed.
