### ISSUE TITLE
Toolkit: run integration tests automatically 

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#294]
The toolkit has a bunch of integration tests that we currently execute manually. We need to run them per commit as part of the pipeline.

**Comment by eladb** [comment]
Okay, investigated the idea of creating an account for every test run 🏃‍♀️ and it seems like it is impossible to delete accounts using an API, only create accounts, so I think this a dead end at the moment. Anyone thinks otherwise? @rix0rrr @RomainMuller @sam-goodwin

**Comment by eladb** [comment]
Okay, discovered a couple of issues when trying to assume a role from a different account:

1. The JavaScript SDK doesn't have support for the [credential_source](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles) option, which is needed because credentials are available through the `EcsContainer` credentials provider (see https://github.com/aws/aws-sdk-js/issues/1916).
2. If --profile is passed to the CDK toolkit and there are credentials in the environment, the profile should prevail and not the environment, but that's probably less of a problem because we don't have environment variables set on CodeBuild.

What I am going to try to do is extract credentials from the ECS provider on CodeBuild and see if I can construct an AWS config file that will work with the current implementations.

**Comment by rix0rrr** [comment]
Alternatively, go around the toolkit and use the CLI to assume credentials? Not so nice, but I do this all the time:

```
#!/bin/bash
set -euo pipefail
arn=$1

name=$(whoami)-shell
creds=$(aws sts assume-role --role-arn "$arn" --role-session-name $name)

export AWS_ACCESS_KEY_ID=$(echo $creds | jq .Credentials.AccessKeyId | xargs)
export AWS_SECRET_ACCESS_KEY=$(echo $creds | jq .Credentials.SecretAccessKey | xargs)
export AWS_SESSION_TOKEN=$(echo $creds | jq .Credentials.SessionToken | xargs)

export PS1="\[\033[1;93m\][$arn] \W\$ \[\033[0m\]"
bash --norc -i
```

(Substitute Node magic for the `jq` call)

**Comment by eladb** [comment]
Yeah, why didn't I think of that!

**Comment by eladb** [comment]
Works! Hell yeah @rix0rrr Thanks!
