### ISSUE TITLE
software.amazon.awscdk.services.codebuild.GitHubEnterpriseSource missing after upgrade to 0.35.0

### ISSUE THREAD

**Issue by digitalsanctum** [awslabs/aws-cdk#2940]
**Describe the bug**
software.amazon.awscdk.services.codebuild.GitHubEnterpriseSource is missing and no mention of the change in changelog.

**To Reproduce**
Upgrade from 0.34.0 to 0.35.0

**Expected behavior**
software.amazon.awscdk.services.codebuild.GitHubEnterpriseSource is present or documentation of 

**Version:**
 - Ubuntu
 - Kotlin with Java CDK artifacts
 - 0.35.0

**Comment by digitalsanctum** [comment]
After chatting on Gitter, I was clued in that it's a case of APIs changing and not being reported or incorrectly reported in changelog. For others that are looking for the equivalent, the syntax looks something like this:
```
val gitHubEnterpriseSourceProps = GitHubEnterpriseSourceProps.builder()
            .withCloneDepth(1)
            .withHttpsCloneUrl(props.cloneUrl)
            .withWebhook(false)
            .build()
val gitHubEnterpriseSource = Source.gitHubEnterprise(gitHubEnterpriseSourceProps)
```

**Comment by skinny85** [comment]
Apologies for the misleading Changelog entry on this @digitalsanctum .

I'm resolving this one, please comment if you need anything else from our side.
