### ISSUE TITLE
aws-cloudformation bundles aws-sdk

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#2951]
The AWS CloudFormation library depends on and bundles the aws-sdk library, just for some service metadata.

It should not do that.

**Comment by RomainMuller** [comment]
Is that not just a dev-dependency?

**Comment by eladb** [comment]
This is worrying. 

How about we introduce this as a separate experimental module? I am concerned that this is at the bottom of our dependency graph.

@jogold, FYI

**Comment by eladb** [comment]
I am taking care of this.

**Comment by jogold** [comment]
The only reason why `aws-sdk` is declared as a dependency is to derive IAM statements from SDK service/actions:
https://github.com/awslabs/aws-cdk/blob/4f13e18172c677b3f34f1c51f64c50bb9f4b4e24/packages/%40aws-cdk/aws-cloudformation/lib/aws-custom-resource.ts#L182-L193

Alternatives:
* find another way to map SDK service/actions to IAM statements
* do not derive statements from SDK service/actions and force users to always add the proper statements to the `AwsCustomResource` construct

**Comment by eladb** [comment]
@jogold thanks for chiming in. This doesn't sound like the right tradeoff.

**Comment by eladb** [comment]
@jogold are you available for a quick chat on Gitter?
