### ISSUE TITLE
feat(aws-apigateway): RestApi to use logical id as a name for APIs instrea of name of current construct

### ISSUE THREAD

**Issue by julienlepine** [awslabs/aws-cdk#2957]
When creating a Rest API inside a construct, the `name` attribute of the newly created `AWS::ApiGateway::RestApi` is based only on the `id` of the apigw.RestApi entry. 

This limits discoverability when a Stack has multiple APIs. Having a name that would be equal to the LogicalId of the created CloudFormation resource would simplify discoverability.

**Comment by NGL321** [comment]
Hi Julien! Thank you so much for contributing. We are working hard to stabilize the CDK APIs and tuning them to meet our consistency guidelines. While we work on getting the APIs aligned with our guidelines, we are pausing work on most community PRs starting around the 21st of this month. Please continue to report issues and submit feature requests, of course. We expect to get back to work on community PRs within a few weeks.
