### ISSUE TITLE
ValidationError: Circular dependency due to Tags

### ISSUE THREAD

**Issue by bigluck** [awslabs/aws-cdk#2986]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
Tags containing a resource names could create a Circular dependency.

* **What is the expected behavior (or behavior of feature suggested)?**
Been able to disable the internal resolver.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Unfortunately It's too much easy to generate circular dependencies.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0 (build c5e43e2)
  - Module Version: 0.35.0 (build c5e43e2)
  - OS: OSX Mojave
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

My Stack:

```typescript
const vpc = ec2.Vpc.fromVpcAttributes(this, 'vpc', {
  vpcId: 'myid',
  availabilityZones: ['us-west-2a'],
});

const ecsCluster = new ecs.Cluster(this, 'cluster', {
  clusterName: `service-cdk-${this.toosoEnv}`,
  vpc,
});
ecsCluster.node.applyAspect(new cdk.Tag('ResourceName', `ecs/${ecsCluster.clusterName}`));
```

CF output:

```json
{
  "Resources": {
    "RecsCluster34087BB6": {
      "Type": "AWS::ECS::Cluster",
      "Properties": {
        "ClusterName": "service-cdk-dev",
        "Tags": [
          {
            "Key": "ToosoResource",
            "Value": {
              "Fn::Join": [
                "",
                [
                  "ecs/",
                  {
                    "Ref": "RecsCluster34087BB6"
                  }
                ]
              ]
            }
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "service-cdk-dev-us-west-2/Cluster/Resource"
      }
    }
  }
}
```

CF Error:

```
service-cdk-dev-us-west-2: deploying...
service-cdk-dev-us-west-2: creating CloudFormation changeset...

 ❌  service-cdk-dev-us-west-2 failed: ValidationError: Circular dependency between resources: [RecsCluster34087BB6]
```

**Comment by made2591** [comment]
I don't know if I'm wrong, but this seems to be the expected behavior in CF: you can't create a tag with as value the name of the resource itself - because that name *doesn't exist* until the end of the creation of the resource itself ... 🤔what do you mean exactly with *been able to disable the internal resolver*?

**Comment by jogold** [comment]
You should be able to do the following to avoid self referencing:
```ts
const vpc = ec2.Vpc.fromVpcAttributes(this, 'vpc', {
  vpcId: 'myid',
  availabilityZones: ['us-west-2a'],
});

const clusterName = `service-cdk-${this.toosoEnv}`;
const ecsCluster = new ecs.Cluster(this, 'cluster', {
  clusterName,
  vpc,
});
ecsCluster.node.applyAspect(new cdk.Tag('ResourceName', `ecs/${clusterName}`));
```

**Comment by bigluck** [comment]
Thanks @made2591 & @jogold.

@jogold the solution you've suggested works.

Thanks again.
