### ISSUE TITLE
Feature Gap / Interface Mismatch: AlarmWidget, Alarm, and IAlarm

### ISSUE THREAD

**Issue by BBonifield** [awslabs/aws-cdk#3068]
I'm not sure if this is intended or an oversight, but `AlarmWidgetProps` is setup with `readonly alarm: Alarm;` rather than `readonly alarm: IAlarm;`.  This prevents you from referencing alarms via `Cloudwatch.Alarm.fromAlarmArn`, which returns an `IAlarm`.

I ask because, for the underlying Cloudformation DashboadBody, I believe the following JSON structure is allowed, and it only requires the ARN:

```
{
  "type": "metric",
  "x": 0,
  "y": 6,
  "width": 6,
  "height": 3,
  "properties": {
    "title": "Availability (%)",
    "annotations": {
      "alarms": [
        "arn:aws:cloudwatch:some-specific-arn"
      ]
    },
    "view": "timeSeries",
    "stacked": false
  }
},
```

Thanks!

**Comment by eladb** [comment]
Confirming this is an issue. @shivlaks we should update our awslint rule to cover more than just props...
