### ISSUE TITLE
TypeScript is broken - 0.36.0

### ISSUE THREAD

**Issue by lielran** [awslabs/aws-cdk#3073]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

I took the cdk init, upgrade to 0.36.0.
the type file seems empty:
![image](https://user-images.githubusercontent.com/1004667/60153211-42c82600-97ec-11e9-86dc-c2509f321a6e.png)

![image](https://user-images.githubusercontent.com/1004667/60153182-32b04680-97ec-11e9-8fc1-54b3dab7a8f9.png)

**Comment by eladb** [comment]
Is this a brand new app initialized with a 0.36.0 CLI? 

The “@aws-cdk/cdk” module has been renamed to “@aws-cdk/core” as described in the [release notes](https://github.com/awslabs/aws-cdk/releases/tag/v0.36.0).

**Comment by lielran** [comment]
Thanks @eladb 
missed that. closing now
