### ISSUE TITLE
elasticloadbalancingv2: fix to be able to set deregistrationDelay

### ISSUE THREAD

**Issue by cohalz** [awslabs/aws-cdk#3074]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

deregistrationDelay causes the following error

```typescript
    const targetGroup = new ApplicationTargetGroup(this, "TargetGroup", {
      deregistrationDelay: Duration.seconds(10),
      vpc,
    });
```

```
/Users/cohalz/example/node_modules/@aws-cdk/core/lib/private/intrinsic.ts:25
      throw new Error(`Argument to Intrinsic must be a plain value object, got ${value}`);
            ^
Error: Argument to Intrinsic must be a plain value object, got () => {
            throw new Error(`Duration.toString() was used, but .toSeconds, .toMinutes or .toDays should have been called instead`);
        }
    at new Intrinsic (/Users/cohalz/example/node_modules/@aws-cdk/core/lib/private/intrinsic.ts:25:13)
    at Function.asAny (/Users/cohalz/example/node_modules/@aws-cdk/core/lib/token.ts:74:48)
    at Function.asString (/Users/cohalz/example/node_modules/@aws-cdk/core/lib/token.ts:51:53)
    at Duration.toString (/Users/cohalz/example/node_modules/@aws-cdk/core/lib/duration.ts:137:18)
    at new TargetGroupBase (/Users/cohalz/example/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-target-group.ts:208:95)
    at new ApplicationTargetGroup (/Users/cohalz/example/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-target-group.ts:81:5)
```

* **What is the expected behavior (or behavior of feature suggested)?**

No errors occurred

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by mhuebner** [comment]
Have a look at the duplicate/related issue: #3080
