### ISSUE TITLE
Issue with machineImages when multiple autoscalinggroups in the same scope

### ISSUE THREAD

**Issue by AlexCheema** [awslabs/aws-cdk#3076]
* **I'm submitting a ...**
  - [X] :beetle: bug report

I create 2 AutoScalingGroups in the same scope but there seems to be a conflict in the creation of the machine image id.

```
<path>\node_modules\@aws-cdk\core\lib\construct.js:420
            throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^

Error: There is already a Construct with name 'SsmParameterValue:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:C96584B6-F00A-464E-AD19-53AFF4B05118.Parameter' in MyStack [MyStack]
```

Environment:
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Win10
  - Language: Typescript

**Comment by eladb** [comment]
Thanks for reporting.  I think the solution should be to reuse the same parameter, so it becomes a singleton essentially. Feels like we have many of those singletones... maybe we can find a way to make it easier to author them.

**Comment by AlexCheema** [comment]
> Thanks for reporting. I think the solution should be to reuse the same parameter, so it becomes a singleton essentially. Feels like we have many of those singletones... maybe we can find a way to make it easier to author them.

No problem - great to see cdk moving forward so quickly and happy to help in the little ways I can.
The issue is not actually the IMachineImage being created twice but it is this line: `const imageConfig = props.machineImage.getImage(this);`. Even if using a singleton for the IMachineImage instance, this line is executed each time an AutoScalingGroup is created so it does not help. This blocks you from using more than AutoScalingGroup in the same scope, unless you use different machine images (with different imageId).

**Comment by mhuebner** [comment]
Same here:
`Error: There is already a Construct with name 'SsmParameterValue:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:C96584B6-F00A-464E-AD19-53AFF4B05118.Parameter' in EcsStack [FkEcsStack]`

**Comment by mhuebner** [comment]
Can someone point me to the root cause of this issue? I cannot find any problematic code changes when looking at #3009.

**Comment by mhuebner** [comment]
@NGL321 any chance to get this fixed? Unfortunately it breaks our Stacks (huge ones) and currently there is no workaround to get this working with > `0.36`

**Comment by mhuebner** [comment]
One word: **Awesome**! 
Thank you very very much, guys. This helps me a lot!
