### ISSUE TITLE
Chore (docs): Readme.md files need vetting for 0.36.0 release

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#3079]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
For example, the breaking changes state:

core: Context.getSsmParameter has been removed. Use ssm.StringParameter.valueFromLookup

However, the readme shows (first for a plain string; second for a secret string):

const stringValue = ssm.StringParameter.fromStringParameterAttributes
const secretValue = ssm.StringParameter.fromSecureStringParameterAttributes

I suspect we'll find other instances of similar out-of-date docs.

*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

* **What is the expected behavior (or behavior of feature suggested)?**

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: xx.xx.xx
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by mhuebner** [comment]
Please have a look at #3081 as well

**Comment by Doug-AWS** [comment]
Nevermind. I figured it out.
