### ISSUE TITLE
Circular dependency introduced by `cdk docs`

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/aws-cdk#31]
The introduction of the dependency `aws-cdk-toolkit` *depends-on* `aws-cdk-docs` created a cycle through `aws-cdk-all`, due to the presence of integration tests in most L2 construct libraries (they use `aws-cdk-toolkit`).

We need to break the cycle:
* **Short term**: take an un-modeled dependency on `aws-cdk-docs` and gracefully handle inability to load it (rendering an error message inviting the user to install the missing dependency).
* **Long term**: Break `aws-cdk-toolkit` into several sub-packages that would allow integration tests to depend only on the subset of features they use.

**Comment by rix0rrr** [comment]
I believe this is no longer applicable.
