### ISSUE TITLE
S3 Bucket with public read access fails to create

### ISSUE THREAD

**Issue by AlexCheema** [awslabs/aws-cdk#3102]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
```typescript
    const staticBucket = new s3.Bucket(this, "StaticBucket", {
      versioned: false,
      publicReadAccess: true
    });
```
This code gives the following error: 
```
3/7 | 12:26:06 PM | CREATE_FAILED        | AWS::S3::BucketPolicy       | StaticBucket/Policy (StaticBucketPolicy4D0F6D8E) API: s3:PutBucketPolicy Access Denied
        new BucketPolicy (/node_modules/@aws-cdk/aws-s3/lib/bucket-policy.ts:32:5)
        \_ Bucket.addToResourcePolicy (/node_modules/@aws-cdk/aws-s3/lib/bucket.ts:346:21)
        \_ Function.addToPrincipalOrResource (/node_modules/@aws-cdk/aws-iam/lib/grant.ts:115:22)
        \_ Bucket.grantPublicAccess (/node_modules/@aws-cdk/aws-s3/lib/bucket.ts:497:22)
        ...
```

* **What is the expected behavior (or behavior of feature suggested)?**
Should create an S3 Bucket with public read access.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - OS: Windows 10
  - Language: Typescript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)
This happens on both v0.35.0 and v0.36.0

**Comment by AlexCheema** [comment]
False alarm. Somehow the "Block public access (account settings)" was enabled on my AWS account.

**Comment by 0xdevalias** [comment]
For anyone else who ends up here, you may want to look at the following for solutions/workarounds:

- https://github.com/aws/aws-cdk/issues/25358
- https://github.com/aws/aws-cdk/issues/25983
- https://www.reddit.com/r/aws/comments/12tqqpw/aws_cdk_api_s3_putbucketpolicy_access_denied_and/
