### ISSUE TITLE
apigateway: support custom domains

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#3103]
Missing capability in API gateway (#723)

**Comment by eladb** [comment]
WIP

**Comment by moravcik** [comment]
I'm trying to map my RestApi to existing domain name (created earlier and mapped to multiple rest APIs) with following code:

      const domainName = DomainName.fromDomainNameAttributes(this, 'MyApiDomain', {
        domainName: 'my.existing.domain.name',
        domainNameAliasTarget: 'XXX,       // I would prefer having this property as optional
        domainNameAliasHostedZoneId: 'YYY' // I would prefer having this property as optional
      });
      domainName.addBasePathMapping(myRestApi, { basePath: 'mymapping' });

and I am getting following error (when compiling cdk code):

    Property 'addBasePathMapping' does not exist on type 'IDomainName'.

or when I retype `domainName as DomainName` (when running `cdk synth`, `cdk diff` or `cdk deploy`):

    TypeError: domainName.addBasePathMapping is not a function

Are there any plans to address such case? I am using CDK version 0.36.2

**Comment by jderose9** [comment]
It seems odd that the default endpoint type is REGIONAL. It seems that most users that are making a public API with custom domain name would benefit from choosing EDGE instead, which is the default selection when using the console.

**Comment by eladb** [comment]
Thanks for this feedback. This makes sense to me. I'll open an issue

**Comment by f-Stabby** [comment]
I am also running into the issue referenced above but not responded to.
https://github.com/aws/aws-cdk/issues/3103#issuecomment-508544101

I can import an existing custom domain mapping with the from_domain_name_attributes, but there is no add_base_path_mapping method on IDomainNames for some reason, so I can do nothing with it.

Any solution?

**Comment by jderose9** [comment]
@moravcik @f-Stabby 

I'm not really sure what fromDomainNameAttributes is for, but I was able to add a base path mapping this way:

````
        const domain = new apigw.DomainName(this, 'myApiDomain', {
          domainName: "api.mydomain.com",
          certificate: acm.Certificate.fromCertificateArn(this, "myApiDomainCertificate", "<cert arn>"),
          endpointType: apigw.EndpointType.EDGE
        });

        domain.addBasePathMapping(api, { basePath: 'v1'});
````

Hope that helps somehow!

**Comment by f-Stabby** [comment]
FromDomainNameAttributes should be like the other "fromxx" functions that exist in most constructs in that, it is for referencing a resource that already exists.

Rather than deleting a preexisting resource and recreating it, I would like to be able to reference the domain name using FromDomainNameAttributes, then add a base path mapping to it.

Hope this gives more context.
@jderose9

**Comment by devarpi** [comment]
> @moravcik @f-Stabby
> 
> I'm not really sure what fromDomainNameAttributes is for, but I was able to add a base path mapping this way:
> 
> ```
> const domain = new apigw.DomainName(this, 'myApiDomain', {
>   domainName: "api.mydomain.com",
>   certificate: acm.Certificate.fromCertificateArn(this, "myApiDomainCertificate", "<cert arn>"),
>   endpointType: apigw.EndpointType.EDGE
> });
> 
> domain.addBasePathMapping(api, { basePath: 'v1'});
> ```
> 
> Hope that helps somehow!

We need to add new api to existing custom domain. This will create new domain. Is there a way to do that?

**Comment by JoshM1994** [comment]
> > @moravcik @f-Stabby
> > I'm not really sure what fromDomainNameAttributes is for, but I was able to add a base path mapping this way:
> > ```
> > const domain = new apigw.DomainName(this, 'myApiDomain', {
> >   domainName: "api.mydomain.com",
> >   certificate: acm.Certificate.fromCertificateArn(this, "myApiDomainCertificate", "<cert arn>"),
> >   endpointType: apigw.EndpointType.EDGE
> > });
> > 
> > domain.addBasePathMapping(api, { basePath: 'v1'});
> > ```
> > 
> > 
> > Hope that helps somehow!
> 
> We need to add new api to existing custom domain. This will create new domain. Is there a way to do that?

I believe if you follow a similar pattern but instead of using `new apigw.DomainName...` you use:

```ts
const domain = DomainName.fromDomainNameAttributes(...)
```

then you should be able to use a domain which already exists.

**Comment by mbsimonovic** [comment]
@JoshM1994 read the comments above, fromDomainNameAttributes returns the interface `IDomainName` which does not have this property `addBasePathMapping`. Casting it to the class results in a runtime error `TypeError: domainName.addBasePathMapping is not a function`. So seems like there's no way to do this?

**Comment by kamaz** [comment]
@mbsimonovic yes, it is possible.

Instead of using `new DomainName()` you have to use ` DomainName.fromDomainNameAttributes` and then define `BasePathMapping`. 

Example below, I hope it helps:

```
const api = new RestApi(this, "rest-api", {}); 

const domainName = DomainName.fromDomainNameAttributes(this, "dev-example", {
   domainName: "dev.example.com",
   domainNameAliasHostedZoneId: "",
   domainNameAliasTarget: ""
});

new BasePathMapping(this, "path-mapping-users", {
      basePath: "users",
      domainName: domainName,
      restApi: api
});
```

**Comment by roitman-g** [comment]
What is  domainNameAliasTarget in domain name attributes?

**Comment by uglow** [comment]
@roitman-g I found the answer to to your question [here](https://github.com/aws/aws-cdk/discussions/13725?sort=new)

**Comment by BwL1289** [comment]
@roitman-g and for anyone else out there trying to figure out how to get `domainNameAliasTarget` programmatically in CDK -- from what I've found, there's no good way. 

The answer [here](https://github.com/aws/aws-cdk/discussions/13725?sort=new) is correct, but unless I'm mistaken, it doesn't seem there's a way to grab it as a property from any other resource construct (except after you create the custom domain in CDK like `new_custom_domain_name.domain_name_alias_domain_name`, for example).

There may be a good reason for this under the hood, but not sure. 

Best alternative I found is saving as an SSM parameter in CDK when I create the custom domain and importing it thereafter.

If @eladb you know of (or if anyone finds one) a better way, please let me know.
