### ISSUE TITLE
python - no changelog information about CidrIPv4 removal

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#3118]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

aws_ec2.CidrIPv4 was removed, add_igress_rule method signature was changed but it's not mentioned in the changelog
synthesize
AttributeError: module 'aws_cdk.aws_ec2' has no attribute 'CidrIPv4'

* **What is the expected behavior (or behavior of feature suggested)?**
Please list down all API breaking changes

* **What is the motivation / use case for changing the behavior or adding this feature?**
Know all API changes before upgrading to newer version.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0 (build 6d38487)
  - Module Version: 0.36.0
  - OS: [Ubuntu 19.4]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
Hmm, you are right that the CHANGELOG did not include the breaking change indicator for this change.

The object you're looking for moved to `Peer.ipv4()`

**Comment by rix0rrr** [comment]
Unfortunately it's too late for us to update the change log now. Closing.
