### ISSUE TITLE
EKS: No AMI for Kubernetes 1.13 or Unable to determine AMI from AMI map since stack is region-agnostic

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#3120]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
```
vpc = aws_ec2.Vpc(scope=self, id='VpcCustomEnv', cidr='192.168.0.0/16')
eks_cluster = aws_eks.Cluster(scope=self, id='EksCluster', vpc=vpc)
eks_cluster.add_capacity(id='capacity', instance_type='t2.large'desired_capacity=1)
```
exits with **jsii.errors.JSIIError: Unable to determine AMI from AMI map since stack is region-agnostic**

if you add a version to EKS, say 
`eks_cluster = aws_eks.Cluster(scope=self, id='EksCluster', vpc=vpc, version='1.13')`

exits with **jsii.errors.JSIIError: We don't have an AMI for kubernetes version 1.12**

* **What is the expected behavior (or behavior of feature suggested)?**
Program compiles and outputs a valid template

* **What is the motivation / use case for changing the behavior or adding this feature?**
Whole EKS service is completely disabled in 0.36

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0 (build 6d38487)
  - Module Version: 0.36.0
  - OS: [Ubuntu 19.4 ]
  - Language: [ Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by lkoniecz** [comment]
Related to https://github.com/awslabs/aws-cdk/pull/2922.

Found a solution, pass region thru env variable 
`DevelopmentStack(app=app, id='Dev', env={'region': 'eu-west-1'})`
Overload the super constructor call with
`super().__init__(app, id, **kwargs)`

**Comment by eladb** [comment]
You can also use the `CDK_DEFAULT_REGION` and `CDK_DEFAULT_ACCOUNT` to associate the stack with the CLI's env:

```python
DeploymentStack(
  app=app, 
  id='Dev', 
  env={
    'account': os.environ['CDK_DEFAULT_ACCOUNT'], 
    'region': os.environ['CDK_DEFAULT_REGION']
  }
)
```
