### ISSUE TITLE
Version reporting is not working for env-agnostic stacks

### ISSUE THREAD

**Issue by jogold** [awslabs/aws-cdk#3142]
* **I'm submitting a ...**
  - [x] :beetle: bug report

* **What is the current behavior?**
When working/deploying env-agnostic stacks version reporting is not working (`AWS::CDK::Metadata` is never deployed). This is because the check for the fact `CDK_METADATA_RESOURCE_AVAILABLE` fails (region is unknown).

* **What is the expected behavior (or behavior of feature suggested)?**
Version reporting should work for env-agnostic stacks. The version reporting check should use the deploy time resolved region.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version: 0.36.0
  - Language: all

**Comment by eladb** [comment]
Wow, @jogold thanks for reporting this. Nice catch!

**Comment by jogold** [comment]
Just found out because I have one of my cdk stacks that is creating only one resource via `route53.HostedZone.fromHostedZoneAttributes`. In the long term it will of course create and own a route53 hosted zone resource but this solution was easier for quick migration (the code/stack structure is already there).

Previously this stack deployed fine because the template contained a `AWS::CDK::Metadata` resource, now I'm getting a CF validation error `ValidationError: Template format error: At least one Resources member must be defined.`

May I open a PR to skip deploying stacks without resources? via filter in `selectStacks`
https://github.com/awslabs/aws-cdk/blob/9d19aef869f27001ed88189fd277aa721de29886/packages/aws-cdk/lib/api/cxapp/stacks.ts#L106

**Comment by eladb** [comment]
> May I open a PR to skip deploying stacks without resources? via filter in selectStacks

Why not? Sounds good. Issue a warning?
