### ISSUE TITLE
Incorrect default value for Protocol enum in ECS

### ISSUE THREAD

**Issue by garnaat** [awslabs/aws-cdk#3143]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**

The default value for the enum Protocol is listed as ``Tcp`` but it is really ``TCP``.  See:
https://github.com/awslabs/aws-cdk/blob/6d3848747ffdf29e26f568478cb9931eae96027f/packages/%40aws-cdk/aws-ecs/lib/container-definition.ts#L589

* **What is the expected behavior (or behavior of feature suggested)?**
Show the correct default value in the documentation.

* **What is the motivation / use case for changing the behavior or adding this feature?**
Correctness.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0 (build 6d38487)
  - Module Version: xx.xx.xx
  - OS: all
  - Language: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by Doug-AWS** [comment]
I own the dev guide, https://docs.aws.amazon.com/cdk/latest/guide/*. This is a reference issues, so I'm assigning it to Rico.

**Comment by rix0rrr** [comment]
This is not an issue with the API reference itself, it's an issue with the source code.

@garnaat and @Doug-AWS: in the future, may I suggest that if you see these kinds of trivial mistakes, you click the pencil icon in the top-right of the file view on GitHub, change it, and turn it into a PR? For the reporter, it will take roughly the same amount of time as creating a GitHub issue for the reporter, but it will save the downstream dev team that time yet again since we can just accept the PR and move on.

**Comment by garnaat** [comment]
I don't like to create PR's that don't address at least one issue, hence I created the issue first.  I just didn't work my way back to create the PR right away as it didn't seem like a super-high priority.  Anyway, now there is a PR.

**Comment by garnaat** [comment]
I realize now that I didn't assign the issue to myself which would have avoided this entire conversation.  Sorry.
