### ISSUE TITLE
Specify DeletionPolicy to delete for RDS

### ISSUE THREAD

**Issue by choweiyuan** [awslabs/aws-cdk#3148]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

Hi, new to the library here.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [x] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
I'd like to create RDS (DatabaseInstance with DeletionPolicy of "Delete", however CDK generates it to "Retain" and I have no way to programmatically set it (unless I use CfnDBInstance?)
https://docs.aws.amazon.com/cdk/api/latest/java/index.html?software/amazon/awscdk/services/rds/package-summary.html

* **What is the expected behavior (or behavior of feature suggested)?**
CloudFormation generated should specify DeletionPolicy as "Delete", and deletes RDS Instance on Stack Deletion.

* **What is the motivation / use case for changing the behavior or adding this feature?**
I want to be able to tear down RDS via CloudFormation without retaining RDS Instance

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0
  - Module Version:0.36.0
  - OS: [OSX Mojave]
  - Language: [Java/Kotlin]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by jogold** [comment]
You should be able to set `removalPolicy` to `cdk.RemovalPolicy.DESTROY`

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-rds.DatabaseInstance.html#removalpolicy

`withRemovalPolicy` in Java https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/rds/DatabaseInstanceProps.Builder.html#withRemovalPolicy-software.amazon.awscdk.core.RemovalPolicy-

**Comment by choweiyuan** [comment]
not sure how I missed that, spent hours looking for it.. thanks! Closing this issue
