### ISSUE TITLE
Documentation links and links from Google are broken for weeks now

### ISSUE THREAD

**Issue by lambrospetrou** [awslabs/aws-cdk#3151]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

- Visit https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sam.CfnFunction.html#events and click on `EventSourceProperty`
- It should open the documentation for that type but instead I get a generic 404 Amazon page

Also, even the results from Google are broken for at least 2 weeks now since they link to https://docs.aws.amazon.com/cdk/api/latest/typescript/api/cdk/cfnresource.html for example which goes to the generic 404 Amazon page.

* **What is the expected behavior (or behavior of feature suggested)?**

I expected to see a valid documentation page.

* **Please tell us about your environment:**

  - OS: OSX Mojave | Ubuntu

**Comment by NGL321** [comment]
Hi @lambrospetrou,

Thank you for reporting this. I just checked the links, and as indicated they are broken. I'm sorry that you ran into this issue, I am looking into it now.

**Comment by lambrospetrou** [comment]
Hello, any update on this? It's amazingly annoying when going through the documentation and even Google results to get the 404 pages and then having to manually search for things.

**Comment by rix0rrr** [comment]
Can you share the Google query that is sending you to a 404 please?

**Comment by lambrospetrou** [comment]
https://www.google.com/search?q=aws+cdk+cfnresource&oq=aws+cdk+cfnresource

**Comment by rix0rrr** [comment]
Hmm,  unfortunately (of course) Google is showing me a different results page :(

In any case: it's unfortunate that we recently changed the package of all these, and I'm sorry you're having a hard time Googling for them right now. Google will correct the 404s out of its index eventually, probably in a couple of weeks. Unfortunately we have no control over Google's behavior in this case.

In the mean time, you'll be happy to know we're working on the docs site and including classes that didn't use to be documented, so that should solve your internal links leading to 404s problem.

**Comment by lambrospetrou** [comment]
I know about Google, but I think it's good if the CDK team requested a re-crawling of their website to renew the cache.

In addition, Google results was only a small part of the issue I opened. The links _inside the documentation_ are broken, so I think the ticket should remain open until those are fixed.

The example I posted above is still broken.

1. https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sam.CfnFunction.html#events
2. Click `EventSourceProperty`

With Google and the internal links broken, you understand it's just wasting time trying to navigate around and search one by one.

If you still want to close this ticket could you please link to the issue ticket that's tracking the work for the update of the documentation you mentioned?
