### ISSUE TITLE
ECS drain hook can't change instance state to draining

### ISSUE THREAD

**Issue by ScOut3R** [awslabs/aws-cdk#3190]
The draining function's IAM policy does not provide enough permission to change the ECS instance state.

* **What is the current behavior?**
The `ecs:UpdateContainerInstancesState` permission is provided for the cluster ARN but the function needs to set the state on the instance which has a different ARN.

```
An error occurred (AccessDeniedException) when calling the UpdateContainerInstancesState operation: User: arn:aws:sts::assumed-role/[role]/[function] is not authorized to perform: ecs:UpdateContainerInstancesState on resource: arn:aws:ecs:ap-southeast-2::container-instance/[instance]
```

* **What is the expected behavior (or behavior of feature suggested)?**
The function should have access to the cluster instance to set the state.

* **What is the motivation / use case for changing the behavior or adding this feature?**
The draining function can't set the instance to draining which defeats its sole purpose.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.1
  - Module Version: 0.36.1
  - OS: Linux
  - Language: TypeScript

**Comment by pkandasamy91** [comment]
Thanks for reaching out @ScOut3R, we're looking into the issue and will get back to you with more information.

**Comment by pkandasamy91** [comment]
UpdateContainerInstancesState and ListTasks need to be restricted to the containerInstance resource.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-supported-iam-actions-resources.html

**Comment by ScOut3R** [comment]
Thank you for pointing out the documentation! Looks like the ARN format defined in the documentation refers to the long ARN @pkandasamy91. The legacy format does not have the cluster name.

**Comment by pkandasamy91** [comment]
@ScOut3R the fix has been is pending: [PR:#3196](https://github.com/awslabs/aws-cdk/pull/3196#pullrequestreview-257798454)

**Comment by ScOut3R** [comment]
@pkandasamy91 beat me to it :D

**Comment by pkandasamy91** [comment]
@ScOut3R thanks for the feedback! Instead of using the resource arn (which would vary depending on if you opted into using long arns or not), we used the cluster as the condition key for restricting the scope of the permissions on ListTasks and UpdateContainerInstancesState actions.

The fix has been merged in!
