### ISSUE TITLE
PolicyStatementProps should accept Effect.

### ISSUE THREAD

**Issue by nikamipara** [awslabs/aws-cdk#3195]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [X ] :beetle: bug report

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
As per Current Behaviour to set allow policy on on say dummy action we have to write following.

```
var policy = new PolicyStatement(PolicyStatementProps.builder()
.withActions(List.of("dummy_action"))
.build()
);
policy.setEffect(Effect.ALLOW);
```

* **What is the expected behavior (or behavior of feature suggested)?**
Expected is following.
```
var policy = new PolicyStatement(PolicyStatementProps.builder()
.withActions(List.of("dummy_action"))
.withEffect(Effect.ALLOW)
.build()
);
```

* **What is the motivation / use case for changing the behavior or adding this feature?**

* **Please tell us about your environment:**
  
  - CDK CLI Version: 00.36.00
  - Module Version: xx.xx.xx
  - OS: [all | Windows 10 | OSX Mojave | Ubuntu | etc... ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
Fixed in https://github.com/awslabs/aws-cdk/pull/3165
