### ISSUE TITLE
[Python] aws_iam module is broken (Role, PolicyStatement, ?)

### ISSUE THREAD

**Issue by bgdnlp** [awslabs/aws-cdk#3212]
* **I'm submitting a ...**
  - [X] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
  Unable to create an IAM policy or role. This code demonstrates a couple of the errors. Tried other things which also failed, but I suspect they are related. Anything involving PolicyStatement seems to fail, including things like adding a policy to a lambda function using Function methods. Since most useful IAM related tasks involve PolicyStatement, I'd say the module is broken. Apologies if I'm wrong and the title is misleading.

  ```
  #!/usr/bin/env python3
  from aws_cdk import (
          core,
          aws_ec2,
          aws_iam)
  
  
  class IAMTest(core.Stack):
      def __init__(self, app, id):
          super().__init__(app, id)
  
          # Should work according to docs, but fails.
          # role.add_to_policy(aws_iam.PolicyStatement.add_all_resources())
  
          # Works as expected
          aws_ec2.Vpc(self, "this_works")
  
          # Works (doesn't raise an exception on synth)
          aws_iam.Role.from_role_arn(
              self,
              'role_id',
              'arn:aws:iam::123456789012:role/myrole')
  
          # Complains about too many arguments:
          # TypeError: __init__() takes 3 positional arguments but 4 were given
          aws_iam.Role(
              self,
              'myRole',
              aws_iam.ServicePrincipal('sns.amazonaws.com'))
  
          # Also complains about too many arguments:
          # TypeError: __init__() takes 1 positional argument but 2 were given
          aws_iam.Policy(
              self,
              'cognito_attr',
              policy_name='cognito_attr',
              statements=aws_iam.PolicyStatement({
                  'actions': 'cognito-idp:ListUsers',
                  'resources': '*'}))
  
  
  app = core.App()
  Stack = IAMTest(app, 'IAMTest')
  
  app.synth()
  ```
  
  If the lines involving `aws_iam` are commented out and only the VPC line remains, the app synthesizes just fine.

* **What is the expected behavior (or behavior of feature suggested)?**
  I would expect to be able to create a custom policy and attach it to a role.

  Using CfnManagedPolicy works as expected, but I didn't (yet) find a way to attach the resulting policy to a role that was automatically generated by `aws_cdk.aws_lambda`.

* **What is the motivation / use case for changing the behavior or adding this feature?**
  Setting custom IAM policies.

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0, 0.36.2, 0.37.0 (probably 0.35.0 too)
  - Module Version: 0.36.0, 0.36.2, 0.37.0 (probably 0.35.0 too)
  - OS: all
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by garnaat** [comment]
Sorry you are having trouble.  More examples would help a lot here but the following code does work for me.  I'm not sure if it does exactly what you want but it should get you on the right track.

```python
#!/usr/bin/env python3
from aws_cdk import (
        core,
        aws_ec2,
        aws_iam)


class IAMTest(core.Stack):
    def __init__(self, app, id):
        super().__init__(app, id)

        # Should work according to docs, but fails.
        # role.add_to_policy(aws_iam.PolicyStatement.add_all_resources())

        # Works as expected
        aws_ec2.Vpc(self, "this_works")

        # Works (doesn't raise an exception on synth)
        aws_iam.Role.from_role_arn(
            self, 'role_id', 'arn:aws:iam::123456789012:role/myrole')

        # Complains about too many arguments:
        # TypeError: __init__() takes 3 positional arguments but 4 were given
        role = aws_iam.Role(
            self, 'myRole',
            assumed_by=aws_iam.ServicePrincipal('sns.amazonaws.com'))

        # Also complains about too many arguments:
        # TypeError: __init__() takes 1 positional argument but 2 were given
        aws_iam.Policy(
            self, 'cognito_attr',
            policy_name='cognito_attr',
            statements=[aws_iam.PolicyStatement(
                actions=['cognito-idp:ListUsers'],
                resources=['*'])],
            roles=[role],
        )


app = core.App()
Stack = IAMTest(app, 'IAMTest')

app.synth()
```

**Comment by bgdnlp** [comment]
That's obvious and now I feel stupid. Thank you very much, I'll close the issue.

**Comment by garnaat** [comment]
I don't think it was obvious at all.  Like I said, we need lots more examples to help people get started.  I'll turn this into one.

**Comment by bgdnlp** [comment]
For what it's worth...

I did search a lot for examples on how to do it in Python, but didn't find anything relevant. I often get by skimming through Typescript examples, so I did the same thing in this case. Problem is, I know nothing about Typescript or Javascript. The examples I found looked like
```typescript
role.addToPolicy(new PolicyStatement({
  resources: ['*'],
  actions: ['lambda:InvokeFunction'] }));
```
Which is correct, of course, but to my Python eyes `actions: ['list']` translated quickly to a dictionary and that's where it all started to go wrong. Had I paid more attention to the lack of quotes, or to the documentation, well, I should have spotted it.

A quick Rosetta stone type of reference between languages might help others in similar situations. Like, this is how a class is defined, this is what an argument looks like, this is a function, etc.

What would be really awesome is if you could apply the same magic you use to generate the different languages to generating examples. They could double as tests. You wouldn't even have to check that the output is correct, which could be tedious for complex examples. Just that all languages generate the same output, it should be good enough.
