### ISSUE TITLE
cdk init not working

### ISSUE THREAD

**Issue by BardiaAfshin** [awslabs/aws-cdk#3223]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [x] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
1. install conda 4.6.14 version
2. run "conda create --name testingonly python=3.6
3. pip install aws-cdk.core --upgrade
4. run "cdk init"

output I get:
(testing) ➜  somethign git:(master) cdk 
zsh: command not found: cdk

* **What is the expected behavior (or behavior of feature suggested)?**

something happens, cdk command runs, but right now 

* **What is the motivation / use case for changing the behavior or adding this feature?**
I want to initialize a cdk project

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.37.0
  - Module Version: 0.37.0
  - OS: [OSX Mojave ]
  - Language: [all | TypeScript | Java | Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by bgdnlp** [comment]
`zsh: command not found: cdk` means the cdk did not run, probably because it wasn't found in path. You might have not installed it correctly. Since this is a support request, Github isn't the right place to ask.

**Comment by rix0rrr** [comment]
You probably did not install cdk at all. Try

```
npm install -g aws-cdk
```

**Comment by rix0rrr** [comment]
Closing. Please direct follow-up questions to StackOverflow.

**Comment by BenoitDel** [comment]
ZSH doesn't take into account what you put in your path via bashrc. Typically, Node could be broken by ZSH installation, and so your cdk-cli. You have to put your NVM on your path by copy pasting bashrc into zshrc. That should repair node and cdk at the same time. I hope that helps
