### ISSUE TITLE
Vpc property maxAZs is ignored

### ISSUE THREAD

**Issue by Console32** [awslabs/aws-cdk#3237]
* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*

If I create a brand new stack, specify a region that has at least 3 AZs (ex: eu-central-1) and create a Vpc. 

```
new MaxAzTestStack(app, 'MaxAzTestStack', { 
  env: {
    region: 'us-east-1'
  }
});
```

```
export class MaxAzTestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new ec2.Vpc(this,'test', { })
  }
}
```

The Vpc spans two AZ and creates 4 Subnets

* **What is the expected behavior (or behavior of feature suggested)?**

Deploying the stack should create a VPC that spans 3 AZs as described in the propeprty maxAZs of the Vpc, but the value is ignored (even if set to 99)

* **What is the motivation / use case for changing the behavior or adding this feature?**

The maxAZs property is required to create a vpc network that needs more than 2 AZs

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.37.0
  - Module Version: 0.37.0
  - OS: Windwos 10
  - Language: TypeScript

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by mhuebner** [comment]
You have to set `account` in your env. See #3083
