### ISSUE TITLE
Cdk synth doesn't work with multiple stacks 

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#3247]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
```
from aws_cdk import (
    aws_s3,
    core
)

class BucketStackOne(core.Stack):
    def __init__(self, app: core.App, id: str, **kwargs) -> None:
        super().__init__(app, id, **kwargs)
        aws_s3.Bucket(scope=self, id='Bucket1')


class BucketStackTwo(core.Stack):
    def __init__(self, app: core.App, id: str, **kwargs) -> None:
        super().__init__(app, id, **kwargs)
        aws_s3.Bucket(scope=self, id='Bucket2')


app = core.App()
BucketStackOne(
    app=app,
    id='stack1',
    env={
        'region': os.environ['CDK_DEFAULT_REGION'],
        'account': os.environ['CDK_DEFAULT_ACCOUNT']
    })

BucketStackTwo(
    app=app,
    id='stack2,
    env={
        'region': os.environ['CDK_DEFAULT_REGION'],
        'account': os.environ['CDK_DEFAULT_ACCOUNT']
    })

app.synth()
```

cdk synth produces no output

* **What is the expected behavior (or behavior of feature suggested)?**

list down synthesized templates from all stacks

* **What is the motivation / use case for changing the behavior or adding this feature?**

to see synthesized templates before deploying

* **Please tell us about your environment:**
  
  - CDK CLI Version:0.36.0 (build 6d38487)
  - Module Version: 0.36.0
  - OS: [Ubuntu]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by lkoniecz** [comment]
in multiple stack app stack name must be passed to synth

**Comment by blake-enyart** [comment]
@lkoniecz how did you pass the stack name to synth in the CLI for CDK?

**Comment by lkoniecz** [comment]
@blake-enyart -e option

**Comment by Dzhuneyt** [comment]
This is not clear enough. How do we synthesize more than one stack? An example would be useful.

**Comment by hoegertn** [comment]
`cdk synth` synthesizes all stacks in your app. The files are in the `cdk.out` folder. If the app only has one stack it is also printed to the console.

**Comment by HeskethGD** [comment]
I am running cdk synth in a project with cdk pipelines and it only seems to be synthesising the devops pipeline stack and not the stacks that it deploys. I'm looking in the cdk.out folder.
