### ISSUE TITLE
Cdk synth print 'Including dependency stacks' instead of template

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#3248]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] :beetle: bug report
  - [ ] :rocket: feature request
  - [ ] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
*If the current behavior is a :beetle:bug:beetle:: Please provide the steps to reproduce*
```
from aws_cdk import (
    aws_ec2,
    core
)
from aws_cdk.aws_ec2 import IVpc


class DevelopmentStack(core.Stack):
    def __init__(self, app: core.App, id: str, **kwargs) -> None:
        super().__init__(app, id, **kwargs)
        self.vpc = aws_ec2.Vpc(scope=self, id='Vpc', cidr='192.168.0.0/16')
    

class TestStack(core.Stack):
    def __init__(self, app: core.App, id: str, vpc: IVpc, **kwargs) -> None:
        super().__init__(app, id, **kwargs)
        aws_ec2.SecurityGroup(scope=self, id='TestSg', vpc=vpc)


app = core.App()
dev = DevelopmentStack(
    app=app,
    id='dev',
    env={
        'region': os.environ['CDK_DEFAULT_REGION'],
        'account': os.environ['CDK_DEFAULT_ACCOUNT']
    })
TestStack(
    app=app,
    id='test-sg',
    env={
        'region': os.environ['CDK_DEFAULT_REGION'],
        'account': os.environ['CDK_DEFAULT_ACCOUNT']
    },
    vpc=dev.vpc)
app.synth()
```

cdk synth prints 'Including dependency stacks: dev'

* **What is the expected behavior (or behavior of feature suggested)?**
The commands prints the synthesized template. 
template

* **What is the motivation / use case for changing the behavior or adding this feature?**
To see what the template looks like

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.36.0 (build 6d38487)
  - Module Version: 0.36.0
  - OS: [Ubuntu]
  - Language: [Python ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

**Comment by rix0rrr** [comment]
Fixed by https://github.com/awslabs/aws-cdk/pull/3259. Not the way you'd prefer it to, but at least the message will tell you what to do.
