### ISSUE TITLE
Maven Java sources and javadoc artifacts

### ISSUE THREAD

**Issue by fulghum** [awslabs/aws-cdk#333]
I see the class library exposed in the Maven artifacts, but I don't see a sources or javadoc jar.  It would be awesome to build these and include them with the Maven artifacts so that IDEs can automatically pick up source attachment and documentation.

ex: https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html

**Comment by eladb** [comment]
Fixed
