### ISSUE TITLE
Applets: allow multi-applet stacks

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#341]
Requested via email

**Comment by sasaraf** [comment]
Hi, we would like to make usage of the applet to describe different environment of deployment, e.g. to make declarative structure for 'dev|prod|integration' env for example.
However, it seems that we can instantiate only a single 'type' per applet/stack.

we would like to be able to do something like:
applets:
  infra-stack:
   type: ./network-layer-construct
   properties:
     name: infra-network
   type: ./db-layer-construct
    properties:
      name: our-db

Will you support such scenario? Thanks

**Comment by rix0rrr** [comment]
That is true, at the moment one applet corresponds to one stack. 

What would you prefer, and how would you use it?

**Comment by sasaraf** [comment]
Hi, thanks for the fast respond. I assume the best way to describe 'our thoughts' will be using serverless-terminology. hope ok. We tend to think of constructs as our 'plugins', the building blocks that wraps basic logic/concepts. For example, apigw-access-with-cognito-authorizer, apigw-with-private-link, etc. And we wanted a declarative way that can be used by us or system engineer to describe our deployment. Not exactly serverles.yml ,but indeed some kind of format that will help us describe several constructs that builds a single stack. That is why we wanted to ask that each applet=stack, will allow several 'types' children to allow this. could it be useful for others too as you see it? Thanks in advance!

**Comment by sasaraf** [comment]
Hi, small ping following the above. thanks in advance!

**Comment by rix0rrr** [comment]
Thanks for your response.

At the moment, we're not planning to implement multi-construct applet stacks. I'm not opposed to it, but I think the gain wouldn't be large enough.

There are no ways to combine constructs together (for example, reference an output of a construct as another construct's input). In the end, each construct in the stack would be standalone. At that point, what's the advantage of even combining them into the same stack? They might as well be deployed separately. 

Once we start allow referencing between applets, we're kind of rebuilding CloudFormation, and there's probably something better we could be doing instead.

I will turn this issue into a feature request for that feature, but I can't make any promises on when it will be implemented.

**Comment by sasaraf** [comment]
Highly appreciate the elaborated consideration of the issue. You explained well. Our thought was to be able to combine into simple small constructs what we refer to as 'best-practice/well-architecture small features', That could be as i mentioned above apigw-connected-with-waf-and-cloud-front, apigw-exposed-via-private-link, etc. Those joint building blocks (turned into constructs) could help build a full featured solution (single stack) that can later on enjoy the good-updates cloudformation supports. etc. However, i do realize it is not high necessity at the moment as we can still enjoy the cdk as is, with coding the above need.
Thanks again! for the good/clear answer.
