### ISSUE TITLE
codepipeline: There should be a way to insert a stage before an existing one (and not append)

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#347]
Currently, Pipelines only allows appending stages. This creates a limitation in usability. For example, we have a general purpose construct that defines a pipeline for code library builds. The current pipeline has two stages: build and release. We wish to implement a method `.addTest(...)`, which will conditionally "inject" another stage between "build" and "release" only if it's called. If there are no tests, there should still be two stages.

Maybe we can do something like `new Stage(pipeline, 'Bla', { insertBefore: someOtherStage })`.

**Comment by skinny85** [comment]
Moved to PR #460 after problems with the fork when the repo was changed to public.
