### ISSUE TITLE
Create a "How-To Define a Stack in a Specific Region" section

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#355]

**Comment by Doug-AWS** [comment]
Done. I also added a how-to get your current account and region, and a link to the info in Getting Started about getting your default credentials and region.

This info is in the "How-To: Define a Stack in a Specific Region" section of cookbook.rst in the dougsch/addhowto branch. Once I've finished this round of how-to sections, I'll open a PR and add the PR # to this issue and close it.

**Comment by Doug-AWS** [comment]
I'll add this to the How-To section of the guide and send out a link once I rebuild the docs.

**Comment by rix0rrr** [comment]
I think we should merge this topic with https://github.com/awslabs/aws-cdk/issues/1870. The other topic will be the *real* user scenario/question, where this is an implementation detail used to achieve #1870.

I propose to close this ticket.

**Comment by Doug-AWS** [comment]
Agreed.
