### ISSUE TITLE
Create a "How-To Store my Secret Data" section

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#357]

**Comment by Doug-AWS** [comment]
Secrets Manager? I don't see where CFN supports it yet.

**Comment by lestephane** [comment]
Is this possibly relevant? https://aws.amazon.com/about-aws/whats-new/2018/08/aws-cloudformation-introduces-dynamic-references-to-support-aws-/

I'm personally interested in the documentation on how to dynamically generate a secure string. In my case an HMAC signing key (512 bits long, 64 characters) in either a SSM secure string (preferred, cheaper) or secrets manager (also suitable, but more expensive).

**Comment by Doug-AWS** [comment]
Dropping the priority and adding to the backlog.

**Comment by Doug-AWS** [comment]
Moving guide issues to doc repo.
