### ISSUE TITLE
docs: Create a "How-To Tag my Resources" section

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#360]

**Comment by Doug-AWS** [comment]
See PR #538

**Comment by Doug-AWS** [comment]
I'm working on this now.

**Comment by eladb** [comment]
@Doug-AWS FYI: https://github.com/awslabs/aws-cdk/pull/1451

**Comment by Doug-AWS** [comment]
I'm going to tackle this today.

**Comment by Doug-AWS** [comment]
See https://docs.aws.amazon.com/CDK/latest/userguide/constructs.html#constructs_tagging
