### ISSUE TITLE
cdk-init template for .NET

### ISSUE THREAD

**Issue by mpiroc** [awslabs/aws-cdk#457]
It should be possible to run `cdk init --language dotnet`.

**Comment by Doug-AWS** [comment]
Do we want the exact same stack as we create in TypeScript? I vote yes, as it makes other doc blurbs consistent so I don't have to tabify large chuncks of the Getting Started.

**Comment by eladb** [comment]
I would actually prefer all init templates to be aligned to our getting started and not vice versa 😄

**Comment by Doug-AWS** [comment]
So a stack with only an S3 bucket w/versioning enabled?

**Comment by eladb** [comment]
Not even - an empty project. The idea is that you wouldn’t need to start deleting things in your project to begin

**Comment by rix0rrr** [comment]
Done, right?

**Comment by mpiroc** [comment]
Yep, fixed by #617.
