### ISSUE TITLE
Java - "Malformed enum value"

### ISSUE THREAD

**Issue by maciejwalkowiak** [awslabs/aws-cdk#467]
Using version "0.8.0", creating VPC stack does not work:

 
    VpcNetwork vpc = new VpcNetwork(this,
                "MyCdkVpc",
                VpcNetworkProps.builder()
                               .withCidr("10.0.0.0/16")
                               .withMaxAZs(3)
                               .withSubnetConfiguration(Arrays.asList(
                                       SubnetConfiguration.builder()
                                                          .withSubnetType(SubnetType.Private)
                                                          .withName("my-private-subnet-1")
                                                          .withCidrMask(24)
                                                          .build()))    
                               .withNatGateways(1)
                               .build());

Results in following error:

    Malformed enum value: @aws-cdk/aws-ec2.SubnetType/Private
    Error: Malformed enum value: @aws-cdk/aws-ec2.SubnetType/Private

when executing `cdk deploy`.

Same applies to other enums like `DefaultInstanceTenancy`.

**Comment by rix0rrr** [comment]
Thanks for the report! At the moment we're a bit busy getting our release cycle finished, but we'll pick this up as soon as possible.

**Comment by maciejwalkowiak** [comment]
Thanks! TypeScript support on the other hand works like a charm. Really awesome tool!

**Comment by moofish32** [comment]
@rix0rrr -- if this is something I broke and you can point me in the right place let me know.

**Comment by rix0rrr** [comment]
I'm honestly not sure, but it doesn't seem like something you should have been able to break. So don't worry about it.

Thanks for offering though!

**Comment by eranation** [comment]
Similar issue with the java getting started example: Exception in thread "main" software.amazon.jsii.JsiiException: Malformed enum value: @aws-cdk/aws-s3.BucketEncryption/KmsManaged

**Comment by eladb** [comment]
Thanks for reporting. We understand why this happens and will hopefully include a fix in our next release, probably early next week.

**Comment by eladb** [comment]
Apologies for the unpleasant experience!

**Comment by maciejwalkowiak** [comment]
No worries, I actually started to love TypeScript version!
