### ISSUE TITLE
Find a strategy to fix the leakage of aws-cdk-resources through higher level libraries

### ISSUE THREAD

**Issue by RomainMuller** [awslabs/aws-cdk#48]
The ergonomics of writing a Construct Library that exposes some attributes are not ideal. For example, writing a construct that uses a `Bucket` from `aws-cdk-s3` and exposes the `BucketArn` attribute:

```ts
import { Construct } from 'aws-cdk';
import { s3 } from 'aws-cdk-resources'; // <-- HERE
import { Bucket } from 'aws-cdk-s3';

export class Foo extends Construct {
    public readonly bucketArn: s3.BucketArn; // <-- THERE

    constructor(parent: Construct, name: string) {
        this.bucketArn = new Bucket(this, 'Bar').bucketArn;
    }
}
```

One way is to re-export the classes from `aws-cdk-resources` that are used in the signatures of the classes in higher level libraries, but this requires lots of boilerplate on the construct library authors, so it's not ideal either...

**Comment by eladb** [comment]
We've done that!
