### ISSUE TITLE
Introduce magic construct identifier that does not add to the logical ID hash

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#482]
Right now, as soon as you extract functionality out of a construct and move it to a separate construct that is now wrapped by the original one, all logical IDs change for the already deployed resources. That is generally now what you want.

A simple solution is a magic construct identifier (like `"Resource"` is today) that does not get added to the name nor the hash (today, `"Resource"` does not get added to the name but it DOES get added to the hash).

This is not introduce a chance of conflicts, since if the parent's logical ID was unique, the new child's logical ID must be unique as well, and no other child can have the same logical ID (because the magic identifier must be unique among siblings).

In fact, we could (should?) change `"Resource"` to be this unique marker... with the downside that all logical identifiers change, all tests break, and all customers have to replace all resources in all of their stacks.

**Comment by rix0rrr** [comment]
Changing the semantics of `"Resource"` is probably too invasive.

How about one of these:

* `"Wrapped"`
* `"Default"`
* `"Index"` (<-- we're web tech!)

**Comment by eladb** [comment]
`Default` sounds good.
