### ISSUE TITLE
Rename @aws-cdk/aws-custom-resources to @aws-cdk/custom-resources

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#483]

**Comment by rix0rrr** [comment]
Yes, this is not a service 😁

**Comment by RomainMuller** [comment]
Is it not? I believe it corresponds to the [`AWS::CloudFormation::CustomResource`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html) which to a certain extend I would regard as a CloudFormation entity in the same regimen as other entities. Quite possibly this should be merged with `@aws-cdk/aws-cloudformation`, but I think that's about as far as I'd go...

**Comment by eladb** [comment]
Good point @RomainMuller - agreed it should be part of the `@aws-cdk/aws-cloudformation` L2.
