### ISSUE TITLE
Doc navigation issue w/TOC

### ISSUE THREAD

**Issue by Doug-AWS** [awslabs/aws-cdk#499]
When you navigate through the online docs, it loses track of where you are in the table of contents.

Repro steps: 

1. Open the reference, https://awslabs.github.io/aws-cdk/reference.html
2. Click on EC2
3. Click on S3
4. Click back

You'll see the EC2 reference, but the TOC shows S3.

**Comment by debora-ito** [comment]
This doesn't happen on Chrome, after I click back EC2 is highlighted.

**Comment by Doug-AWS** [comment]
Hmm, it does on Chrome and Firefox, but not Edge or IE, on my computer. I haven't check Safari yet.

**Comment by Doug-AWS** [comment]
Closing as if it's an issue, it's likely the browser.
