### ISSUE TITLE
How to import existing VPC 

### ISSUE THREAD

**Issue by nikhilbhoj** [awslabs/aws-cdk#506]
Hi,

Can any one guide, how to import existing VPC like we can do in terraform using data  using ec2.VpcNetwork()  construct ?

const vpc = new ec2.VpcNetwork(this, 'VPC');

Thanks,
Nikhil

**Comment by nikhilbhoj** [comment]
Thanks @eladb  , I will try and update on this.

**Comment by debora-ito** [comment]
Hi @nikhilbhoj are you still having issues?

**Comment by nikhilbhoj** [comment]
@debora-ito , I haven't done it yet. I will do it in the coming weekend and update my finding.

**Comment by pierreozoux** [comment]
Coming from this [StackOverflow](https://stackoverflow.com/questions/51718355/what-is-the-best-way-to-use-the-aws-cdk-to-get-the-cidr-of-the-vpc) Indeed, it would be a nice to have to have a helper to import just with a vpcId. Is there a feature request for that already?

**Comment by eladb** [comment]
@pierreozoux it's usually not very useful to just have a VPCID because in most cases you would need to specify a subnet in order to actually use the VPC.

**Comment by pierreozoux** [comment]
@pda it was exactly my use case, thanks for sharing :)

**Comment by kevinslin** [comment]
does the introduction of [`ec2.Vpc.fromLookup(opts: VpcLookupOptions): IVpc`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#static-fromlookupscope-id-options) address all the issues in this thread?  this is available in the `0.33` release and has been one of my favorite changes in the cdk :)

```
/**
 * Properties for looking up an existing VPC.
 *
 * The combination of properties must specify filter down to exactly one
 * non-default VPC, otherwise an error is raised.
 */
export interface VpcLookupOptions {
  /**
   * The ID of the VPC
   *
   * If given, will import exactly this VPC.
   *
   * @default Don't filter on vpcId
   */
  readonly vpcId?: string;

  /**
   * The name of the VPC
   *
   * If given, will import the VPC with this name.
   *
   * @default Don't filter on vpcName
   */
  readonly vpcName?: string;

  /**
   * Tags on the VPC
   *
   * The VPC must have all of these tags
   *
   * @default Don't filter on tags
   */
  readonly tags?: {[key: string]: string};

  /**
   * Whether to match the default VPC
   *
   * @default Don't care whether we return the default VPC
   */
  readonly isDefault?: boolean;
}
```

**Comment by eladb** [comment]
`ec2.Vpc.fromLookup` is the recommended approach to use an existing VPC within CDK apps. I am closing this issue for now. Please reopen if there are use cases that are still not covered.

**Comment by pagameba** [comment]
If you are getting errors as of 0.36 this only works if you add `{ env: { region: "your-region", account: "your-account-id"} }` to your stack creation call (bin/stack.ts).

**Comment by eladb** [comment]
Please also note that you can use the `CDK_DEFAULT_ACCOUNT` and `CDK_DEFAULT_REGION` environment variables when you define `env` to bind the stack to the CLI's configuration.

**Comment by david-a** [comment]
Hi, I'm using `ec2.Vpc.fromLookup` and started getting this warning recently:
[Warning at /xxxx/Vpc] No routeTableId was provided to the subnet 'subnet-xxxx'. Attempting to read it's .routeTable.routeTableId will return null/undefined. (More info: https://github.com/aws/aws-cdk/pull/3171)
Have you changed anything related to it in the last version of CDK?

**Comment by Rauttis** [comment]
@david-a I had the same issue. In my case removing `cdk.context.json` and letting cdk re-generate it fixed the issue.

**Comment by markingram** [comment]
I'm attempting to import a created VPC using the approach recommended above but it only works if I supply the vpcId. I'd rather use something less volatile like a name.

```javascript
        const vpc = ec2.Vpc.fromLookup(this, "vpc", {
            // vpcId: "vpc-0e3e027882ce530fa",   // <--- this by itself works
            // tags: {"Name": "base-infrastructure-vpc"},
            vpcName: "base-infrastructure-vpc/vpc",
        });
```
In the above snippet having `vpcId` by itself works whereas having either of the other two by themselves doesn't work. What am I doing wrong?

**Comment by nikhilbhoj** [comment]
I have created one blog post on this for CDK in custom VPC for me it works. Here is the link for that  https://nikhilbhojcloud.blogspot.com/2019/08/cdk-fargate-load-balanced-service-using.html  by referring VPC as "MyVPC"

**Comment by markingram** [comment]
hmm... actually my code works if I *don't* depend on `@aws-cdk/aws-elasticache`...

**Comment by ashwgupt** [comment]
Is there a way that we can query and find the CIDR range for an existing VPC? We are using `VpcLookupOptions` to get the reference but we are still not able to find the CIDR range set for the VPC, which is needed for one of our Security Group definition. Any advice will be highly appreciated.

**Comment by ashwgupt** [comment]
@elabdb any suggestions on this the above question of any possible way of finding default cidr range of an existing vpc?

**Comment by jaymay19** [comment]
Running into a similar issue as @ashwgupt . I can import an existing VPC no problem but when I try to access the `vpcCidrBlock` property (needed to set up some other resources):

`this.vpc.vpcCidrBlock // undefined`.

Any reason this isn't populated when importing the VPC?

**Comment by andreifinski** [comment]
Any luck with bypassing this, anyone? running into the same issue with undefined CIDR: 
`Cannot perform this operation: 'vpcCidrBlock' was not supplied when creating this VPC`

**Comment by lulu-jplute** [comment]
@eladb, what's the point of importing a VPC if you have to specify all the other attributes (e.g., subnets, AZs, etc.) and not just the VPC ID? I'd imagine the CDK would get this information on behalf of the developer.

**Comment by pchaganti** [comment]
Seems like specifying a VPC id should be all the CDK should need. It can glean all relevant/connected resources from that. Importing each piece separately is time consuming and makes for a horrible user experience.
