### ISSUE TITLE
Possible error in generated template for CloudFront distributions

### ISSUE THREAD

**Issue by lusentis** [awslabs/aws-cdk#508]
Hello,
I was trying to deploy a CloudFront Distribution, simply by following the examples provided in the documentation:

```js
new cloudfront.CloudFrontWebDistribution(
    this,
    'PublicWWWDistribution',
    {
        originConfigs: [
            {
                s3OriginSource: {
                    s3BucketSource: this.bucket,
                },
                behaviors: [
                    {
                        isDefaultBehavior: true,
                    },
                ],
            },
        ],
    }
);
```

But... when I run `cdk deploy`, the stack update fails with the following error:
```
n47E3983B
[4/7] Sun Aug 05 2018 20:10:59 GMT+0200 (CEST)  CREATE_FAILED       [AWS::CloudFront::Distribution] PublicWWWDistributionCFDistributionXXXX Exactly one of CustomOriginConfig and S3OriginConfig must be specified
```

I'm specifying an s3 Origin and, from what I can see from the [web_distribution](https://github.com/awslabs/aws-cdk/blob/bb956763e619d9ec39803f4e9672f165c32aa5f7/packages/%40aws-cdk/aws-cloudfront/lib/web_distribution.ts#L506) code in CDK, you are **not setting the `S3OriginConfig` property** ([required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html#cfn-cloudfront-distribution-origin-s3origin) by CloudFormation). If I'm not wrong, in a YAML template this property can be specified as an empty object literal `S3OriginConfig: {}`.

Also, I see that the CloudFormation template that's *expect*ed in the [tests](https://github.com/awslabs/aws-cdk/pull/45/files#diff-13f9aba5b39fff941cc195392a461f17), does not work for the same reason.

```bash
$ cdk --version
0.8.0 (build bb95676)
```
Thanks,

**Comment by mindstorms6** [comment]
You are totally right!

This particular part underwent extensive testing when used with OriginAccessIdentities - (we're required to use them). I'm adding integ tests for the open bucket version now - PR incoming.

**Comment by lusentis** [comment]
Great! Thanks 😁
I can test if/when there's a pr/branch.

**Comment by lusentis** [comment]
@mindstorms6 I can [try to] open a PR today if you wish :smile:
