### ISSUE TITLE
CodeCommit-CodePipeline: artifactName property of PipelineSource could be optional

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#522]
Right now I have to type it, but artifact names seem like they're implementation details that I only very occasionally would care about.

Either default it to a fixed string (`"SourceArtifact"`) or a guaranteed unique string (`parent.name + this.name + "Artifact"`).

**Comment by eladb** [comment]
@skinny85 is this still on your radar?

**Comment by skinny85** [comment]
This one is done 👍.
