### ISSUE TITLE
Cannot Create IAM:ServiceLinkedRole

### ISSUE THREAD

**Issue by aeriqkim** [awslabs/aws-cdk#569]
There is no mechanism to create a serviced linked IAM role using the CDK currently for example for use with ECS.

**Comment by rix0rrr** [comment]
That is correct at the moment.

Can you give us a sense of how impacting this for you? As to your example, ECS will create the SLR for you automatically I believe?

**Comment by rix0rrr** [comment]
No longer convinced it's a good idea to implement this. `AWS::IAM::ServiceLinkedRole` can only be created in one stack, and most services are arranged to automatically create a service linked role upon first invocation.

Closing, please reopen when a good use case comes up.
