### ISSUE TITLE
CustomResource creation

### ISSUE THREAD

**Issue by xdodocodex** [awslabs/aws-cdk#588]
I am trying to introduce a custom resource doing as follow:
```
import {cloudformation} from '@aws-cdk/aws-cloudformation'
export class MainStack extends cdk.Stack {
    constructor(parent: cdk.App, id: string, props?: cdk.StackProps) {
        super(parent, id, props);
        new cloudformation.CustomResource(this, "Test", {
            serviceToken: ""
        });
    }
}
```
of course the _serviceToken_ property need a correct Arn but the problem here is that I have an error which say:

> Type MainStack is not assignable to type Construct Property 'id' is missing in type 'MainStack'

I understand the error but I can't not understand why it happens since I'm using this stack class for other CloudFormation resources.

Can someone help me?

**Comment by eladb** [comment]
I think it might be a non-compatible change we made to the core library and you have incompatible libraries in your project. Try to upgrade all of your modules to 0.8.2 and let us know if this persists.

**Comment by xdodocodex** [comment]
Thank you for the answers, unfortunately updating to version 0.8.2 didn't work.
Can you provide me a snippet of CustomResource initialization?
Maybe I am doing something wrong.

**Comment by rix0rrr** [comment]
Hi @xdodocodex,

I don't know about the errors you are seeing, but I did notice you were using the underlying raw `cloudformation.CustomResource` class. We actually have a wrapper for that, simply called `CustomResource` (not in the `cloudformation.` namespace).

There's an example of how to use it in the `packages/@aws-cdk/aws-cloudformation/examples` directory, here:

https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-cloudformation/example/index.ts

**Comment by eladb** [comment]
@xdodocodex did @rix0rrr's pointer help? Is this still an issue?

**Comment by rix0rrr** [comment]
Assuming resolved. Please reopen if you're still having issues.
