### ISSUE TITLE
Add doc topic about context under “concepts”

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#600]
From a Gitter discussion: 
> you can use a context key to indicate if you are in dev/prod and consult it anywhere in your stack via getContext. It’s basically a mechanism very similar to environment variables or thread-local storage that allows you to propagate implicit state throughout your CDK app. You can either set the context in code or via the toolkit/cdk.json. In the future you’ll be able to bind context values to environments (#290).

**Comment by rix0rrr** [comment]
We definitely need to document context, but shouldn't we recommend people write parameterized constructs instead? (I.e., using "props"). Context is invisible (bad for readability), untyped (bad for reliability) and transitive (very useful, but should only be used when it's necessary).

As in, would you recommend people write a command-line tool that accepts options via command-line arguments or via environment variables?

**Comment by Doug-AWS** [comment]
We should document ALL ways of stuffing information into your CDK app--context/command-line, env vars, SSM, export/import, ...

Then add recommendations/caveats, such as "Using context variables is risky as 1. They reduce visibility in your code. (are you positive you'll remember what you did last January?)"

**Comment by Doug-AWS** [comment]
Please review https://docs.aws.amazon.com/CDK/latest/userguide/context.html

**Comment by Doug-AWS** [comment]
Closing as done.
