### ISSUE TITLE
Examples with API Gateway

### ISSUE THREAD

**Issue by hassankhan** [awslabs/aws-cdk#602]
Would be awesome if there was some documentation regarding setting up an API Gateway with Lambda-Proxy integration with one or more Lambda functions.

**Comment by hassankhan** [comment]
On a related note, I've written up an `ApiGateway` construct that simplifies API creation massively but I'm not quite sure how to add it to the repo or how to write proper tests:

```typescript

export type MethodType = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface HttpConfig {
  path: string;
  method: MethodType;
  cors?: boolean;
}

export interface LambdaConfig {
  lambdaFn: Lambda.Function
  http: HttpConfig
}

export type EndpointType = 'EDGE' | 'REGIONAL' | 'PRIVATE';

export interface ApiGatewayProps {
  name: string;
  endpoints: LambdaConfig[];
  endpointTypes: EndpointType[];
  cacheEncrypted?: boolean;
  cacheSize?: '0.5' | '1.6' | '6.1' | '13.5' | '28.4' | '58.2' | '118' | '237';
  cacheTtl?: number;
  caching?: boolean;
  logging?: boolean;
  logLevel?: 'OFF' | 'ERROR' | 'INFO';
  metrics?: boolean;
  stageName: string;
}

new ApiGateway(this, 'MyAPI', {
  name: 'MyAPI',
  stageName: 'dev',
  endpointTypes: [ 'EDGE' ],
  logging: true,
  endpoints: [
    {
      lambdaFn: lambdaFn,
      http: {
        path: '/',
        method: 'GET'
      }
    }
  ],
});
```

**Comment by rix0rrr** [comment]
@hassankhan, that is amazing! If you really want to contribute this to the CDK standard library, we would gladly accept it! In that case, I would have some style pointers on your code to bring it in line with the rest of our library, and I can tell you about what we expect from testing.

However, before you put in all the effort I believe that @mindstorms6 also had some API-gateway related code lying around, and it would be a waste if you both spent effort on it. So I'll let him chime in first to see where his code is at, and then we can discuss specifics further.

**Comment by mindstorms6** [comment]
I'm all for this - my efforts have been focused on using the `AWS::Serverless::API` (for their 'new deployment each time' feature). I think there's a happy spot for both. We can probalby hide them behind the same interface. 

Also, looping in @RomainMuller

**Comment by hassankhan** [comment]
Awesome, I'll try and get a PR once #474 is resolved 👍

**Comment by rix0rrr** [comment]
Okay, some comments then:

* We expect docstrings on all public types, functions and properties (and preferably, also on private ones).
* TypeScript union types (`GET | POST | PUT | ...`) don't translate well to other programming languages, and we're targeting all common languages with the API. Use an enum instead.
* Anything that could conceivably be optional should be (noticing you're already doing this, that's great!)
* Try not to nest parameters too much. For example, seems like `LambdaConfig` and `HttpConfig` could be merged?
* The `cacheSize` parameter makes me quite unhappy (numbers in a string) but I suppose that's just the way the API is. Can we find symbolic names for these?

**Comment by hpfs74** [comment]
Is the aws-apigateway usable in production? It is really hard to understand how to create a stack that includes a apigateway. A small example would be nice as starting point.

**Comment by hassankhan** [comment]
@hpfs74 I'm sure the `aws-apigateway` construct is production-ready on its own (since it's only wrapping CloudFormation). That said, I'll try and find some time this week to make a PR with the constructs I created, sorry for the delay 👍

**Comment by hpfs74** [comment]
That would be awesome @hassankhan

**Comment by rhboyd** [comment]
@mindstorms6 your work has been creating the cfn template with the serverless:transform, and then you let cfn do the actual transform to create the template?

**Comment by eladb** [comment]
I am working on an API gateway construct library. Stay tuned!

**Comment by hassankhan** [comment]
Really sorry @eladb, couldn't find the time to make the PR. Is it still worth making one or is it better to leave it to you?

**Comment by eladb** [comment]
I am on it, would love your feedback when I submit a PR.
