### ISSUE TITLE
Use cdk init in Getting Started

### ISSUE THREAD

**Issue by hassankhan** [awslabs/aws-cdk#612]
Currently the project setup process in the documentation requires basically manually setting up a project from scratch. This could greatly be simplified by having users use the `cdk init` command to quickly bootstrap a project.

**Comment by rix0rrr** [comment]
This was discussed and we explicitly opted for this to walk people through the entire process (to show there is no magic).

**Comment by hassankhan** [comment]
Fair enough, I personally feel it somewhat kneecaps the Getting Started process by making it longer than it needs to be.

**Comment by eladb** [comment]
We do [mention](https://awslabs.github.io/aws-cdk/getting-started.html#initializing-the-project) `cdk init` at the beginning of the getting started topic.

**Comment by eladb** [comment]
Closing for now
