### ISSUE TITLE
VPC Placement Strategy is not complete

### ISSUE THREAD

**Issue by moofish32** [awslabs/aws-cdk#614]
The concept of a placement strategy is a nice abstraction. In the current form there are some gaps:
1. Isolated subnets are ignored (that's my miss)
1. Public subnets may come in pairs (e.g. Ingress only public subnet and Egress only public subnets, this separation commonly occurs so a NACL can be used on egress to protect against layer 3/4 data exfiltrations)
1. Many private subnets can also occur in large team VPCs where network isolation in layers is desired

The use of tags to select subnets might be something to consider. In order to quickly enable teams the support of simply allowing users to specify `subnetIds` would unblock current users.

**Comment by rix0rrr** [comment]
I'm just working on that in here: https://github.com/awslabs/aws-cdk/pull/610

Can you elaborate some on additional things you would like to see in there?

**Comment by rix0rrr** [comment]
(Please do it in the PR)
