### ISSUE TITLE
assets: directory support

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#638]
Allow a recursive directory to be uploaded as an asset without zip archive

**Comment by rix0rrr** [comment]
Does it delete existing files that are no longer in the source directory?

**Comment by eladb** [comment]
It should I think

**Comment by rix0rrr** [comment]
@eladb  Is this done? It should be, right?

**Comment by eladb** [comment]
Not really, but somewhat superseded by bucket deployment (https://github.com/awslabs/aws-cdk/pull/971). Let’s close for now and see if the need arises
