### ISSUE TITLE
develop helper class for DynamoDB AutoScaling param to make it easier for devs to setup auto-scaling without needing to explicitly define all values in AutoScalingProps

### ISSUE THREAD

**Issue by SeekerWing** [awslabs/aws-cdk#644]
https://github.com/awslabs/aws-cdk/pull/637#discussion_r213664763

**Comment by rix0rrr** [comment]
Is this issue resolved?

**Comment by eladb** [comment]
I don't believe so, the idea is to allow people to use "canned" auto-scaling properties instead of specifying thousands of parameters

**Comment by rix0rrr** [comment]
This is in now.
