### ISSUE TITLE
Support GSI and LSI through DynamoDB Table

### ISSUE THREAD

**Issue by jungseoklee** [awslabs/aws-cdk#655]
Hi AWS CDK,

First of all, I am happy to see this project :)

As DynamoDB user, it would be great to support GSI and LSI through [DynamoDB Table](https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L38). Currently, a low-level approach is required as follows if GSI or LSI is needed, which makes high-level methods, such as `addPartitionKey` and `addSortKey`, less useful.
```
new dynamodb.cloudformation.TableResource(this, 'cdk', {
    attributeDefinitions: [
        {
            attributeName: 'foo',
            attributeType: 'S'
        },
        {
            attributeName: 'bar',
            attributeType: 'S'
        }
    ],
    tableName: 'cdk',
    keySchema: [
        {
            attributeName: 'foo',
            keyType: 'HASH'
        },
        {
            attributeName: 'bar',
            keyType: 'RANGE'
        }
    ],
    provisionedThroughput: {
        readCapacityUnits: 10,
        writeCapacityUnits: 10
    },
    globalSecondaryIndexes: [
        {
            indexName: 'cdk-gsi',
            keySchema: [
                {
                    attributeName: 'bar',
                    keyType: 'HASH'
                }
            ],
            projection: {
                projectionType: 'ALL'
            },
            provisionedThroughput: {
                readCapacityUnits: 10,
                writeCapacityUnits: 10
            }
        }
    ]
});
```

**Comment by eladb** [comment]
Definitely a missing feature in our dynamo db library

**Comment by eladb** [comment]
#606

**Comment by jungseoklee** [comment]
I am curious about how you implement this feature: are you considering sort of public methods, such as `addGlobalSecondaryIndex`, or a totally different approach?

**Comment by eladb** [comment]
Yes, something like that should work. If it makes sense, we sometimes also like to provide a declarative syntax via `props`, but only if it's not too cumbersome.

**Comment by jungseoklee** [comment]
I close this issue because both GSI and LSI are supported now.
