### ISSUE TITLE
Use secure values for SSM Parameter store based secrets

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#656]
CloudFormation recently [launched](https://aws.amazon.com/about-aws/whats-new/2018/08/aws-cloudformation-introduces-dynamic-references-to-support-aws-) support for secure values, so we should use them for the CDK [SecretParameter](https://awslabs.github.io/aws-cdk/refs/_aws-cdk_cdk.html?highlight=secret#@aws-cdk/cdk.SecretParameter)

**Comment by drabinowitz** [comment]
is the recommendation on this for the time being to store the secret as a plain text string in the SSM Parameter Store?

**Comment by eladb** [comment]
Related to #242
