### ISSUE TITLE
Serverless Code Version - required

### ISSUE THREAD

**Issue by mindstorms6** [awslabs/aws-cdk#66]
Howdy!

According to the serverless docs : https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object

The version of a code thing isn't required

> Data Types
> S3 Location Object
> Specifies the location of an S3 object as a dictionary containing Bucket, Key, and optional Version properties.

> Example:
> ```
> CodeUri:
>   Bucket: mybucket-name
>   Key: code.zip
>   Version: 121212
> ```

But we've got it marked non optional in our code
( i think it's sourced from : https://github.com/awslabs/aws-cdk/blob/4a7eaa6846d54c383022266809e3c3d3100992b6/packages/aws-cdk-resources/cloudformation-specs/000_sam.spec.json#L197 )

And putting a dummy value (like `0` is super not valid)

**Comment by rix0rrr** [comment]
We'll have to deal with this on a case-by-case basis.
