### ISSUE TITLE
Lambda doesn't need to be able to access the code bucket from it's execution role

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#664]
Currently, we are granting it read access to the asset's bucket, but that's not needed since Lambda downloads the code as part of the function creation, not execution.

**Comment by eladb** [comment]
Yes, I think it's the user who executes `CreateFunction`. That's when Lambda downloads your code into their own bucket (I presume) and from that point, they don't need to access your bucket anymore. Which makes sense.

**Comment by rix0rrr** [comment]
But wait, if this is true, how come I had to do the [asset prefix permissions](https://github.com/awslabs/aws-cdk/pull/510) change?

Have I just been hallucinating that?

**Comment by eladb** [comment]
Right... We need to investigate

**Comment by rix0rrr** [comment]
Oh, I remember, that had to do with CodeBuild. So Lambda wasn't involved at all.
