### ISSUE TITLE
Add Tracing configuration for Lambda CDK construct

### ISSUE THREAD

**Issue by SeekerWing** [awslabs/aws-cdk#671]
Add Tracing configuration for Lambda CDK construct

https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html

Provide user a simple boolean flag to turn on tracing. 
This should enable tracing in LambdaResource and add permission as follows
          - Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Effect: Allow
            Resource: '*'

**Comment by SeekerWing** [comment]
in the interest of keeping it simple for the customer, i was planning on proposing, we keep this Active if we ever set it. Passthrough is a subset of Active. If a customer setting up a lambda does decide to instrument their Lambda, I think it best that instrumentation happens irrespective of whether the upstream explicitly asks for it or not. Let me know if you don't think this falls in the purview of enforcing best practices on the clients.

**Comment by eladb** [comment]
The purpose of L2 (the AWS Construct Library) is to expose the entire surface area. We are trying not to be opinionated about best practices, but rather help users make the right choice and optimize the usage for the common case/best-practice (which is different then not exposing it at all). I would encourage providing documentation on the enum that helps users make the best choice.

**Comment by SeekerWing** [comment]
got you, will build accordingly.
