### ISSUE TITLE
Remove `policy` argument from `s3.BucketProps`

### ISSUE THREAD

**Issue by amitsha** [awslabs/aws-cdk#672]
s3.Bucket takes BucketProps which can take a policy as in the below code snippet:
The issue here is that policy requires the bucket to which it will be attached.

This seems like a bug unless I'm doing something wrong.
`const s3Bucket = new s3.Bucket(this, logicalName, {
            versioned: true,
            bucketName: name,
            encryption: s3.BucketEncryption.KmsManaged,
            policy: new s3.BucketPolicy(this, "MyS3BucketPolicy", {
                bucket: s3Bucket
            })
        });
`

**Comment by rix0rrr** [comment]
You are right, that can't really work. 

To get a policy onto your bucket, use the `bucket.addToPolicy()` method with a `cdk.PolicyStatement` object: https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-s3.html?highlight=bucket#bucket-policy

We'll use this ticket to track the removal of the BucketPolicy argument.
