### ISSUE TITLE
 Prerequisites section should have minimal version of runtimes and tools

### ISSUE THREAD

**Issue by rednes** [awslabs/aws-cdk#682]
https://awslabs.github.io/aws-cdk/getting-started.html

With reference to Getting Started, I tried to make TypeScript's AWS CDK app.
In the `Compile the Code` section, I got an error when building TypeScript.

https://awslabs.github.io/aws-cdk/getting-started.html#compile-the-code

```
$ npm run build
'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'esnext' for tsconfig.json (3,19): error TS 6046: Argument for ' .
```

In `tsconfig.json` , target of compilerOptions is set to `ES2018`.
Therefore, TypeScript needs to be a version supporting ES2018.

ES2018 is supported by TypeScript 2.7.
https://github.com/Microsoft/TypeScript/issues/20342

The version of TypeScript installed in my environment is old.

```
$ tsc -v
Version 2.6.2
```

It was solved by installing the latest TypeScript and building it.

```
$ npm install typescript -g
$ tsc -v
Version 3.0.3
$ npm run build
```

It will help peeple like me that using old version TypeScript mindlessly.

**Comment by Doug-AWS** [comment]
The current "Installing and Configuring the AWS CDK" section, https://docs.aws.amazon.com/CDK/latest/userguide/install_config.html, has the following under "Prerequisites":

You must install Node.js (>= 8.11.x) to use the command-line toolkit and language bindings.

If you use Java, you must set the JAVA_HOME environment variable to the path to where you have installed the JDK on your machine to build an AWS CDK app in Java.

You must specify both your credentials and a region to use the toolkit, as described in Specifying your Credentials. 

I'll add the TypeScript info, but who knows the requirements for Java, .NET/C#?

**Comment by Doug-AWS** [comment]
Assigning to Mathew as he owns the .NET port.

**Comment by Doug-AWS** [comment]
Here's what I have:

CLR version >= 4.5

**Comment by Doug-AWS** [comment]
From Aaron for C#:

.NET standard 2.0 compatible implementation:
- .NET Core >= 2.0
- .NET Framework >= 4.6.1
- Mono >= 5.4

As soon as I publish the updated doc I will provide the URL here and close this issue.

**Comment by Doug-AWS** [comment]
https://docs.aws.amazon.com/CDK/latest/userguide/install_config.html#install_config_prerequisites
