### ISSUE TITLE
Add support for Lambda EventSourceMapping

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#707]
The AWS Construct Library should allow users to setup [event source mappings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html) for Lambda.

Example on how to [setup SQS](https://gist.github.com/insanitybit/e093195db76a030918e3957ad544866a#gistcomment-2705942)

**Comment by rix0rrr** [comment]
@eladb, fixed?

**Comment by eladb** [comment]
Fixed by https://github.com/awslabs/aws-cdk/pull/1063
