### ISSUE TITLE
Directory assets: symlinks

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#731]
Allow configuring how symlinks are treated:

1. Do not materialize symlinks
1. Materialize all symlinks
1. Materialize symlinks that are outside the tree

**Comment by sentient-jbreindel** [comment]
I think this would be welcomed upgrade. It could be as easy as switching out the current archiver library with a different one. There seems to be some chatter on the issues in archiver about supporting [materializing symlinks](https://github.com/archiverjs/node-archiver/issues/311) but doesn't seem like anything concrete was released yet. 

For now I'm just leveraging my underlying `zip` linux utility [here](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/archive.ts#L10) which is really hacky but supports following the symlinks out of the box.

**Comment by kennu** [comment]
+1 from here because I can't deploy my Node.js Lambda function which has some node_modules symlinked using `npm link`. I believe the default should be to materialize so that `npm link` works out-of-the-box.

**Comment by justinmchase** [comment]
This is a pretty important required feature.

In nodejs its possible to create either links as @kennu said for testing or to actually put a hard dependency to a relative module such as:
```
"dependencies:" {
  "shared": "../shared"
}```

Which will make a symlink to the `shared` folder under your functions `node_modules`. In this case the process of packaging the zip file for deployment needs to follow the symlink and also package all sub files.

I don't think it's really necessary to have options here, it needs to always do it.
