### ISSUE TITLE
CodeBuild: add support for secondarySources and secondaryArtifacts

### ISSUE THREAD

**Issue by andrewrch** [awslabs/aws-cdk#738]
I think this is quite a new feature in CodeBuild, but it would be great if CDK supported this (Currently I am blocked from using CDK to deploy our build projects for this reason)

https://docs.aws.amazon.com/codebuild/latest/userguide/sample-multi-in-out.html

**Comment by paulhopkins11** [comment]
Any progress on this?

**Comment by eladb** [comment]
@skinny85 ?

**Comment by skinny85** [comment]
I haven't started on this yet, but it's currently the third most important issue in my backlog, so I promise I'll get to it soon :)

**Comment by paulhopkins11** [comment]
Hi, thanks for the update. Do you have any idea when cdk might move from developer preview to formal release? We are looking to adopt this as it is awesome but people have raised concerns that it hasn't been formally released yet. Thanks.
