### ISSUE TITLE
[dotnet] Reference to S3 Bucket when adding lambda

### ISSUE THREAD

**Issue by andreigec** [awslabs/aws-cdk#754]
Is it currently possible to reference an existing s3 bucket when creating a lambda (CDK-0.9.2)? 

BucketRef.Import is abstract, so I can't create an instance of it, and S3.Bucket shouldn't be used when there is an existing resource.

I'm passing the values in via  Amazon.CDK.AWS.Lambda.FunctionProps

**Comment by rix0rrr** [comment]
You're being bitten by this bug: https://github.com/awslabs/jsii/issues/223

We're working on it. Closing this in favor of the other issue.
