### ISSUE TITLE
Doc Topic Context In cdk.json

### ISSUE THREAD

**Issue by moofish32** [awslabs/aws-cdk#759]
Can we add some documentation about how users should think about the context data in `cdk.json`

Topics I think could help new users:
1. Should I use this to pass in arguments?
1. Should I persist values in here for my team/CD system to use? 
1. How should I my Stacks, Apps, or Construct (Lib?) projects interact with context? (e.g. should a construct never use Context data set by a human because that should be only for app/stack elements?)

cc/ @eladb this issue came from me seeing users not knowing `setContext` `getContext` existed.

**Comment by moofish32** [comment]
Not directly related but perhaps we can kill my questions in here? https://github.com/awslabs/aws-cdk/pull/700

**Comment by Doug-AWS** [comment]
Yep, 700 includes the information you request.
