### ISSUE TITLE
Caret ranges in package.json and breaking changes

### ISSUE THREAD

**Issue by jmhummel** [awslabs/aws-cdk#763]
Currently, all packages within aws-cdk reference other cdk modules using caret ranges: `^0.9.2`
Here is an example from `@aws-cdk/aws-lambda`:
```
  "dependencies": {
    "@aws-cdk/assets": "^0.9.2",
    "@aws-cdk/aws-cloudwatch": "^0.9.2",
    "@aws-cdk/aws-codepipeline-api": "^0.9.2",
    "@aws-cdk/aws-ec2": "^0.9.2",
    "@aws-cdk/aws-events": "^0.9.2",
    "@aws-cdk/aws-iam": "^0.9.2",
    "@aws-cdk/aws-logs": "^0.9.2",
    "@aws-cdk/aws-s3": "^0.9.2",
    "@aws-cdk/aws-s3-notifications": "^0.9.2",
    "@aws-cdk/aws-sqs": "^0.9.2",
    "@aws-cdk/cdk": "^0.9.2",
    "@aws-cdk/cx-api": "^0.9.2"
  },

```
https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/package.json

The most recent release of `0.9.2` introduced many breaking changes. Projects dependent on `0.9.1` version are now broken, even if they specified the exact version in their package.json, as each `0.9.1` dependency pulls in other cdk modules using `^0.9.1`

Please consider using exact versions of cdk dependencies within modules for the next release.

**Comment by rix0rrr** [comment]
The mistake here was releasing as `0.9.2` instead of `0.10.0`. Our apologies for the breakage, we will do better going forward.
