### ISSUE TITLE
Fluent APIs inconsistently applied

### ISSUE THREAD

**Issue by jungseoklee** [awslabs/aws-cdk#764]
Some services or methods support builder pattern for L2 construct as returning `this` [1], which is convenient, but is a source of inconsistent API experiences. For example, S3 does not have the pattern.

It would be better to support or enforce the builder pattern across _ALL_ L2 constructors if possible. If impossible, could we consider not using the pattern?

[1] https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L165

**Comment by jungseoklee** [comment]
Thanks for clarification :) I will clean up if see the pattern.

**Comment by rix0rrr** [comment]
I think `PolicyStatement` is the prime offender. That one's an exception, since it's more like a fancy data-carrying object.
