### ISSUE TITLE
0.9.2 broke .NET init template

### ISSUE THREAD

**Issue by costleya** [awslabs/aws-cdk#770]
➜  one git:(master) ✗ dotnet build src
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj...
  Restore completed in 160.7 ms for /Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj.
HelloConstruct.cs(14,35): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloStack.cs(8,31): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloStack.cs(10,27): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloStack.cs(10,52): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(27,31): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(19,31): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(19,60): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(16,26): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(16,38): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]

Build FAILED.

HelloConstruct.cs(14,35): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloStack.cs(8,31): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloStack.cs(10,27): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloStack.cs(10,52): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(27,31): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(19,31): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(19,60): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(16,26): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
HelloConstruct.cs(16,38): error CS0012: The type 'DeputyBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.JSII.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. [/Users/costleya/Work/broken-pipe-test/one/src/HelloCdk/HelloCdk.csproj]
    0 Warning(s)
    9 Error(s)

Time Elapsed 00:00:01.22

**Comment by eladb** [comment]
@mpiroc @costleya 

* We need an integration test for the .NET init template (awslabs/cdk-ops#124)
* There is no explicit reference to `DeputyBase` in the code. Why does .NET require that we add a reference in the csproj? Seems wrong that the project will need to explicitly specify indirect dependencies? Any idea?

**Comment by costleya** [comment]
I have realized this is a more complicated issue. The template build fine o windows, but breaks on MacOS. Doing further investigation.

**Comment by costleya** [comment]
Actually, it was a caching issue on my machine. I had a JSII runtime dependency cached that was unsigned, causing this issue. Resolving.

**Comment by mpiroc** [comment]
@costleya The build scripts for .NET JSII packages invoke `dotnet nuget locals all -clear`, which should prevent this issue. How did you initiate the build?

**Comment by Doug-AWS** [comment]
Dumb question: Are we supporting .NET on MacOS? Seems like a unlikely edge case.

**Comment by mpiroc** [comment]
@mpiroc Yes, it's not longer an edge case. .NET Standard/Core are fully-cross platform.

**Comment by mpiroc** [comment]
@Doug-AWS Yes, it's no longer an edge case. .NET Standard/Core are fully-cross platform.

**Comment by Doug-AWS** [comment]
Thanks.
