### ISSUE TITLE
cdk diff should indicate if only Output CF description added, then Cloudformation will not update.

### ISSUE THREAD

**Issue by ygoodmn** [awslabs/aws-cdk#778]
CDK Version 0.9.0

Enhancement: cdk diff should indicate if only an Ouput Resource was Added, cloudformation will not update.

Steps: 
1. Add only Output Cloud formation description
2. run cdk deploy 
3. Get Stack was already up-to-date
4. run cdk diff

Expected:
[+] Added (Output will be updated on next Resource update)<Description>

Actual:
+] Added  <Desciption>

Example:
From Synth
*********************
_Outputs:
LoadBalancerArn:
Description: NLB
Value:
Ref: NLB
Export:
Name: 'NLBArn'_

From Terminal:
*****************************
user@ubuntu:~/sms100$ cdk deploy cdk-NLB
Starting deployment of stack cdk-NLB...
Stack was already up-to-date, it has ARN _arn:aws:cloudformation:us-west-1:123456:stack/cdk-NLB/01314e0-c15f-11e8-ab9b-50fae8123456_ cdk-sms104-NLB

user@ubuntu:~/sms100$ cdk diff cdk-NLB
[+] Added LoadBalancerArn: {"Description":"NLB","Value":{"Ref":"NLB"},"Export":{"Name":{"NLBArn"}}}''

**Comment by hoshitocat** [comment]
I think that will occur exception when stack status is `UPDATE_ROLLBACK_COMPLETE`.
