### ISSUE TITLE
dotnet: cdk takes long time to execute

### ISSUE THREAD

**Issue by indikaudagedara** [awslabs/aws-cdk#793]
How long is 'long'/how slow is 'slow'? 

```
PS E:\tmp> cdk init --language dotnet
PS E:\tmp> dotnet build src
...
Time Elapsed 00:00:02.05

PS E:\tmp> $sw = [Diagnostics.Stopwatch]::StartNew()
PS E:\tmp> cdk ls
PS E:\tmp> $sw.Stop();
PS E:\tmp> $sw.Elapsed.Seconds
43
```

In my case it takes around 40 seconds for `cdk` to execute the `ls` command  in Windows. In comparison, `dotnet build` takes about 2 seconds.

In a docker container `cdk ls` takes about 30 seconds ([Dockerfile](https://github.com/indikaudagedara/dockerfiles/blob/master/aws-cdk-dotnet/Dockerfile))
```
root@1840d1c48712:/tmp/cdk# time cdk ls
hello-cdk-1
hello-cdk-2

real    0m27.063s
user    0m12.470s
sys     0m6.060s
```

Is there any work in the backlog to improve `cdk` execution time?

**Comment by rix0rrr** [comment]
Can you run it again with `-v` to give us an idea of where it's spending the time?

**Comment by indikaudagedara** [comment]
Sorry not sure what you mean. The logs above are from when I ran cdk from command line.

**Comment by rix0rrr** [comment]
I am referring to the line `dotnet src/HelloCdk/bin/Debug/netcoreapp2.1/HelloCdk.dll base64:xxxx` that you yourself mentioned as the culprit (where the tool was taking a long time to complete).

What if you take that exact command (as shown) and copy/paste it into the command-line and then run it. Does it take the same amount of time, or is it faster then?

**Comment by rix0rrr** [comment]
By the way, only try this if you edited the logs to not include the base64 data. If it literally says `base64:xxx` that's not going to work...

**Comment by indikaudagedara** [comment]
Ah got it.. Still takes the same amount of time...
```
root@25cc6ad3f3f3:/tmp/cdk# time dotnet src/HelloCdk/bin/Debug/netcoreapp2.1/HelloCdk.dll base64:xxx
{
  "stacks": [
    {
      "name": "hello-cdk-1",
      "environment": {
        "name": "1111/ap-southeast-2",
        "account": "1111",
        "region": "ap-southeast-2"
      }
    },
    {
      "name": "hello-cdk-2",
      "environment": {
        "name": "1111/ap-southeast-2",
        "account": "1111",
        "region": "ap-southeast-2"
      }
    }
  ]
}

real    0m21.579s
user    0m11.030s
sys     0m5.720s
```

**Comment by rix0rrr** [comment]
Then that's how long it takes to run your .NET program. You might try profiling it to see where the time is going.

**Comment by eladb** [comment]
@costleya is this on your radar?

**Comment by indikaudagedara** [comment]
Any updates on this one? It takes about 3 mins for lambda code update via cdk compared to cloudformation update of same stack which completes in less than 20secs. I suspect the synth step is what takes the most of time. Improving that would be great.

**Comment by eladb** [comment]
We need to do some profiling for .net to understand what’s going on. The next release should improve things slightly (x2) as we have changed the protocol between the toolkit and the app to only require a single invocation of the app once in the regular case, but it still feels like there is room for improvement.

**Comment by rix0rrr** [comment]
I believe this has been solved.

**Comment by unicomp21** [comment]
It still takes forever.

**Comment by unicomp21** [comment]
Think I'll switch over to typescript.

**Comment by fulghum** [comment]
Hey @unicomp21 – sorry you're seeing performance issues with the .NET CDK.  We're actively investing in the .NET CDK and we did some performance enhancements that we saw drastically speed up execution.  Could you tell us a little more detail about what you saw (i.e. CDK version, project setup, commands, etc) so that we can repro and fix this?

**Comment by unicomp21** [comment]
I was running within the "linux on windows" subsystem.  Just realized it's the antimalware service on windows.  Disabling it helps a "lot".
