### ISSUE TITLE
Guidance on Testing

### ISSUE THREAD

**Issue by patoncrispy** [awslabs/aws-cdk#796]
Is there any guidance on how to validate our Stacks or Constructs? As a lot of configuration is generated by instantiating classes, it doesn't lend to traditional unit testing techniques - not that it should! I am simply curious if there are techniques or approaches recommended for validating that the configuration we have created using the CDK is what we wanted in the first place.

**Comment by rix0rrr** [comment]
While working on constructs today we have 2 testing strategies:

* Fine-grained unit tests; we instantiate our constructs with some parameters, then make assertions on the resources that would be created by the construct. You can see this all over our codebase (in the `test/` directories) and we have a library with some helper functions called `@aws-cdk/assert`.
* Integration tests; we take a complete CDK app, synthesize it and deploy it (to verify that the things actually deploy correctly). Then we "fix" the template: it's not allowed to change anymore. If it does, we have to redeploy and check that everything still works (and update the expected output).

Depending on what you want to achieve, you can try one of these strategies. Synthesizing an app to a template and diffing the previous against the current synthesized template whenever you make changes is an easy way to spot changes.

**Comment by patoncrispy** [comment]
Thanks for this, @rix0rrr. Will go take a look at the test suites!
