### ISSUE TITLE
.NET language not on the project README.md

### ISSUE THREAD

**Issue by ccfife** [awslabs/aws-cdk#819]
The last sentence, "The CDK is currently available for Java, JavaScript, and TypeScript.", must include .NET.

**Comment by Doug-AWS** [comment]
I can include .NET in the README.md, but we still need content from the .NET porters for the Getting Started topic, so I'm assigning it to Aaron also.

**Comment by eladb** [comment]
@costleya any ETA on updates to our Getting Started for .NET?

**Comment by Doug-AWS** [comment]
README.md fixed by PR #820

**Comment by Doug-AWS** [comment]
.NET is in the readme and has been since PR #1185 was merged about two weeks ago.
