### ISSUE TITLE
docs + readme: a diagram that explains the relationship between resources, constructs, stacks and apps

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#839]
suggested by @arun-gupta

**Comment by Doug-AWS** [comment]
I saw this back in April:

[CDK_Architecture.pdf](https://github.com/awslabs/aws-cdk/files/2465826/CDK_Architecture.pdf)

**Comment by Doug-AWS** [comment]
See the "CDK Application" diagram about 1/2 way down https://docs.aws.amazon.com/CDK/latest/userguide/what-is.html (feel free to give me any feedback).

**Comment by Doug-AWS** [comment]
Closing as done.
