### ISSUE TITLE
Applets: integrate into toolkit

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#849]
Right now you have to:

```ts
npm install -g @aws-cdk/applets-js
```

Which is not great, would be better if it was integrated into CDK toolkit in some way.

Would also be nice to be able to invoke an applet directly from NPM (without `package.json` or `cdk.json`). Think of the possibilities!

**Comment by eladb** [comment]
Maybe we should open a separate issue for assets in applets

**Comment by RomainMuller** [comment]
I agree with @eladb - asset support actually has two sides... Support for assets embedded in the applet construct will be supported standard, what needs a new mechanism is how to plug "external" files with the applet document that will be sued when deploying.

**Comment by rix0rrr** [comment]
Mmmyeah, you're right. I was actually confused about how they were supposed to be used. Let's make this issue about integration into the toolkit then.

-------

I don't really like the mechanism of having to make a `cdk.json` to contain the `cdk-applet-js` command. It also makes it impossible to have multiple applet files in the same directory. How about:

```ts
cdk --applet bla.yaml deploy
```
?

**Comment by rix0rrr** [comment]
Added to top-level:

> Would also be nice to be able to invoke an applet directly from NPM (without package.json or cdk.json). Think of the possibilities!

**Comment by eladb** [comment]
This is related to some ideas I've had around "auto discovery" of app type in the toolkit so people won't need `cdk.json` at all. For example, we can identify `package.json` file and use `main` to determine this is a JavaScript app and run it through node. Maybe we can standardize around an extention such as `.cdk.yaml`  for applets, so one could do `cdk -a myapplet.cdk.yaml deploy` and boom! 

As for npm, yes! Very cool idea. `cdk -a npm://package@version/MyApplet`?
