### ISSUE TITLE
Property 'missingContext' is missing in type 'Construct'.

### ISSUE THREAD

**Issue by adam-imeson** [awslabs/aws-cdk#858]
Tried to pull and build the [commit](https://github.com/awslabs/aws-cdk/commit/ed1e1e450cbeb21256868857fc6830d798949a5f) exposing the generated L1 for Neptune.  A typescript app with the following code looks good:
```
const database = new neptune.cloudformation.DBClusterResource(this, 'NeptuneCluster', {});
```
Unfortunately, it doesn't transpile, throwing the following error:
```
Admin:~/environment/graph-database-cdk (cdk-at-ed1e1e4) $ npm run build

> graph-database-cdk@1.0.0 build /home/ec2-user/environment/graph-database-cdk
> tsc

../aws-cdk/packages/@aws-cdk/cdk/lib/cloudformation/stack.ts:45:5 - error TS2322: Type 'Construct' is not assignable to type 'Stack'.
  Property 'missingContext' is missing in type 'Construct'.

45     return curr;
       ~~~~~~~~~~~~

```
I think that this is a problem in the cdk because even an empty app doesn't transpile, throwing the same error.  Either that or I didn't build the cdk correctly, which is entirely possible seeing as I hadn't done it before.

**Comment by eladb** [comment]
@adam-imeson let us know if this is still an issue after aligning all version numbers.
