### ISSUE TITLE
aws-dynamodb: refactor to use Application AutoScaling library

### ISSUE THREAD

**Issue by jungseoklee** [awslabs/aws-cdk#861]
ApplicationAutoScaling `ScalingPolicy` and `ScalableTarget` are shared concepts across multiple AWS services, such as DynamoDB, ECS, EMR, RDS, and SageMaker [1], but the current implementation does not follow the design. For example, DynamoDB has its own implementation [2]. Especially, I am not sure if it is a right direction to manage the same service principal, `application-autoscaling.amazonaws.com`, in different places.

Therefore, I propose managing  all ApplicationAutoScaling snippets under `aws-applicationautoscaling` package, which not only brings all benefits of "reuse and module" principles, but helps to adopt changes or new features of ApplicationAutoScaling fast.

[1] https://docs.aws.amazon.com/autoscaling/application/APIReference/API_ScalingPolicy.html
[2] https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L418-L450

**Comment by rix0rrr** [comment]
I'm working on autoscaling as we speak. Thanks for the note. We're probably going to refactor the current implementation once I've modeled the autoscaling package properly.

**Comment by jungseoklee** [comment]
Are you working [EC2 AutoScaling scaling policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html) or [ApplicationAutoScaling scaling policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalingpolicy.html)?

I presume the autoscaling you're working on is probably #856, which is about EC2 AutoScaling. Please note that this issue is about ApplicationAutoScaling.

**Comment by rix0rrr** [comment]
What I was writing in #856 applies to both kinds of autoscaling. But the library I'm currently working on is definitely application autoscaling.
