### ISSUE TITLE
Lambda Directory doesn't work on windows, uses /tmp

### ISSUE THREAD

**Issue by gaffo** [awslabs/aws-cdk#863]
The following stack:

```
import cdk = require('@aws-cdk/cdk');
import apigateway = require('@aws-cdk/aws-apigateway');
import lambda = require('@aws-cdk/aws-lambda');

class MyStack extends cdk.Stack {
    constructor(parent: cdk.App, id: string, props?: cdk.StackProps) {
        super(parent, id, props);

        const lmbda = new lambda.Function(this, "Lambda", {
            code: lambda.Code.directory("python_dir"),
            handler: 'index.handler',
            runtime: lambda.Runtime.Python36,
        });

        const apigw = new apigateway.LambdaIntegration(lmbda, {
            proxy: true,
        });
        const api = new apigateway.RestApi(this, 'api', {
            defaultIntegration: apigw
        });

        api.root.addMethod('ANY');
        const all = api.root.addResource("{proxy+}");
        all.addMethod("ANY");
    }
}

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);

        new MyStack(this, 'hello-cdk', {
        	env: {
        		region: "us-west-2",
                account: "925495567782",
        	},
        });
    }
}

process.stdout.write(new MyApp(process.argv).run());
```

Fails to deploy on windows with:

```
C:\Users\gaffo\cdk-test> cdk deploy hello-cdk
 ⏳  Starting deployment of stack hello-cdk...
 ❌  Deployment of stack hello-cdk failed: Error: ENOENT: no such file or directory, mkdtemp '/tmp/cdk-assetsXXXXXX'
ENOENT: no such file or directory, mkdtemp '/tmp/cdk-assetsXXXXXX'
```

It's pretty obviously guessing that it wants /tmp as a directory which doens't work on windows.

**Comment by eladb** [comment]
I believe this was [fixed](https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/assets.ts#L45). What version of the toolkit are you using?

**Comment by gaffo** [comment]
0.10.0

On Oct 7, 2018 22:51, "Elad Ben-Israel" <notifications@github.com> wrote:

I believe this was fixed
<https://github.com/awslabs/aws-cdk/blob/master/packages/aws-cdk/lib/assets.ts#L45>.
What version of the toolkit are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/awslabs/aws-cdk/issues/863#issuecomment-427727386>, or mute
the thread

**Comment by eladb** [comment]
Are you certain? I am referring to the command line toolkit (`cdk --version`)

**Comment by gaffo** [comment]
0.8.0 (build bb95676)

**Comment by eladb** [comment]
Let us know if upgrading to 0.10.0 (`npm i -g aws-cdk`) solves your issue.

**Comment by gaffo** [comment]
That works. Didn't realize I had to update the tool seperately from the libraries.
