### ISSUE TITLE
Surface integration tests as samples

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#883]
We have many integration tests in our code base and most of them should be relevant as examples for how to use various features of the CDK. If only we added a bit of commentary, we could technically add them all as examples to our docs.

**Comment by eladb** [comment]
Copy: @ccfife @Doug-AWS

**Comment by jungseoklee** [comment]
I love the idea, but a minor comment. Some tests focus on "testing" itself rather than "documentation". Thus, how about having annotation and surface tests having the annotation only?

**Comment by Doug-AWS** [comment]
See (kinda related) #1277

**Comment by Doug-AWS** [comment]
The only way this works is using automation/script. Putting in the backlog for now.

**Comment by Doug-AWS** [comment]
Moving guide issues to doc repo.
