### ISSUE TITLE
core: Disable export-by-default

### ISSUE THREAD

**Issue by rix0rrr** [awslabs/aws-cdk#903]
This might run us into Export limits at some point (50-ish per account?)

Suggested fix: only make them exports once `makeImportValue()` is called (or `export: true` is passed).

**Comment by eladb** [comment]
related: #1095 
we are going to stop using this pattern anyway

**Comment by tsykora-verimatrix** [comment]
I didn't find a way how to disable outputs in CDK. Was this feature implemented? I can't see it in the documentation.
Without it the 200 resource hard-limit per template doesn't seem achievable.
I'm running into the number of outputs limit per template although all of those outputs are automatically generated by CDK, I do not generate any outputs in my code:
failed: Error [ValidationError]: Template format error: Outputs count 77 is greater than max allowed 60

It seems like CF/CDK prefer many small stacks over fewer bigger stacks, is it true @rix0rrr @eladb ?
