### ISSUE TITLE
apigateway: "methodResponses" is missing from MethodOptions

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#905]
For some reason, `methodResponses` is missing from the API Gateway `Method` construct.

**Comment by eladb** [comment]
@john-shaskin go ahead, it's all yours! ❤️

**Comment by john-shaskin** [comment]
Getting a PR together for this shortly.

**Comment by john-shaskin** [comment]
Addressed in https://github.com/awslabs/aws-cdk/pull/1572

**Comment by divyachaudhary2** [comment]
Hi is there any update on when this will be deployed?

**Comment by john-shaskin** [comment]
The PR is awaiting a second review. I’ll do some prodding.
