### ISSUE TITLE
Add oauth token as param to codebuild.GitHubEnterpriseSource

### ISSUE THREAD

**Issue by ellery44** [awslabs/aws-cdk#907]
Currently  `codebuild.GitHubEnterpriseSource` does not let me pass oauth token like we can for `codebuild.GitHubSource`

I want to be able to do something like this.
```typescript
new codebuild.Project(stack, 'Project', {
  source: new codebuild.GitHubEnterpriseSource("https://mycompany.github.com", "my_oauth_token")
});
```

cc/ @moofish32

**Comment by ellery44** [comment]
https://github.com/awslabs/aws-cdk/pull/908

**Comment by rix0rrr** [comment]
Closed byt he PR I suppose?
