### ISSUE TITLE
S3 Examples for Bucket Policy are Broken

### ISSUE THREAD

**Issue by awood45** [awslabs/aws-cdk#942]
https://awslabs.github.io/aws-cdk/refs/_aws-cdk_aws-s3.html#bucket-policy'

```typescript
// broken because addToPolicy doesn't exist
const bucket = new Bucket(this, 'MyBucket');
bucket.addToPolicy(statement);

// broken because policy can't be added to bucket props
const policy = new BucketPolicy(this, 'MyBucketPolicy');
const bucket = new Bucket(this, 'MyBucket', { policy });
```

It looks like the `grant` family of methods on the bucket are the only way to achieve bucket policies currently, though I'm not sure on that front. Regardless, the examples are broken in `0.12`

**Comment by eladb** [comment]
The example is definitely broken, but the usages are there (just moved around a little):

- `addToPolicy` is now called `addToResourcePolicy`
- You can use `BucketPolicy` but you'll have to specify the bucket when you define the policy (and not vice versa): `new BucketPolicy(this, 'MyPolicy', { bucket })`

**Comment by rix0rrr** [comment]
Nobody should be using `BucketPolicy`, so we shouldn't even have an example that mentions it.
