### ISSUE TITLE
Use of "private" properties prevents multiple versions of a module in the same closure

### ISSUE THREAD

**Issue by eladb** [awslabs/aws-cdk#979]
Due the fact that when a class has private/protected members, TypeScript uses __nominal type checking__ instead of __structural type checking__, different versions of the same class would not be compatible.

See details and example in https://github.com/Microsoft/TypeScript/issues/28128.

Bottom line, it appears that using "private" members is not practical for class libraries since it means classes cannot be used across versions and it is a common use case for ecosystems to have multiple versions of the same class in an application's closure.

To ensure that this cannot happen with the CDK and AWS Construct Library, I am proposing that jsii will not allow the use of TypeScript's `private` modifier. Instead it will recommend that users prefix a member with an underscore `_`, which will be hidden from jsii languages and is a common practice in JavaScript to denote private members.

The next step to enable multiple major versions is to allow jsii-runtime to load multiple versions into a module's closure. At the moment it is prohibited (awslabs/jsii#61).

**Comment by rix0rrr** [comment]
I imagine it's just the typechecker that's affected, so shouldn't have any impact on jsii. 

But this is a supposition :).

**Comment by eladb** [comment]
@rix0rrr you are right, but the current implementation of the jsii-runtime has a limitation (https://github.com/awslabs/jsii/issues/61) that won't allow multiple versions of the same module to be loaded into the runtime, so in a sense those are related.

**Comment by eladb** [comment]
This is the issue: https://github.com/Microsoft/TypeScript/issues/8346

**Comment by eladb** [comment]
Here's a repro:

[repro.zip](https://github.com/awslabs/aws-cdk/files/2505873/repro.zip)

**Comment by eladb** [comment]
Another discussion on the topic: https://github.com/Microsoft/TypeScript/issues/7755

Basically, private members do not participate in _structural typing_ intentionally in order to protect from overriding private implementation.

As much as I can see the purist reasoning behind it (and it seems like the TypeScript team doesn't intend to change things), we need a solution that will allow multiple versions of @aws-cdk/cdk to work together. This is especially tricky around base classes like `Construct` and `Resource`.

To be pragmatic about this, I'd like to propose that for these base classes, we will not use `private` members, but rather just use `_` prefix to indicate those members are private. This is not an uncommon convention in JavaScript and jsii will hide these member from native languages.

@rix0rrr @RomainMuller I wonder what you guys think about this.

**Comment by rix0rrr** [comment]
I HATE EVERYTHING ABOUT IT.

But seriously.

I'd like to see automation around this, and preferably I wouldn't have to defile my code to work around these kinds of issues. I would like to see automatic translation of `private xxx()` to `public _xxx()` at the compilation phase. Either by postprocessing on the generated `.js` and `.d.ts` files, or by writing a compiler plugin.

**Comment by eladb** [comment]
I agree. It’s a huge limitation of private members in typescript, which I am not 100% sure they realize. I’ll chime in on one of these conversations to present our use case and ask for guidance.

In the meantime, we could either block the usage of private members at the Jsii level (tell you to use underscore and explain why) or just solve this locally for cdk.Construct and other core base classes, so that we could start versioning modules separately.

**Comment by RomainMuller** [comment]
I share @rix0rrr's philosophical issue with this. It is uncanny to me that I cannot use privates as pure implementation details. However, Javascript is what it is, and from that perspective I guess we have to preserve usability of the CDK.

**Comment by eladb** [comment]
This is actually a Typescript thing. Whether you use the CDK or not, if you wanted to use TypeScript to vend a class library, you wouldn't want to use "private" properties. I know, it's weird.

**Comment by IPyandy** [comment]
I don't like it, but a limitation of the language is a limitation. Based on the issue MS/Typescript rep adding interfaces for all types seems like a major headache. I'm not sure how my OCD will handle the _ everywhere, but improving functionality and practicality right now to get real use cases to me is more important than a few semantics.

I do agree with @rix0rrr that maybe in the future some logic and automation around this would be useful, though for now, your proposal seems fair.

**Comment by eladb** [comment]
The implication is that we will have to define an interface for every exported class in every module and somehow enforce that only those interfaces are used to reference these classes... doesn’t seem realistic

**Comment by eladb** [comment]
@huijbers proposed that the only reason typescript actually exposes private properties in type declarations is to allow objects to reference private properties of other objects of the same type. This was also mentioned in one of the typescript discussions (https://github.com/Microsoft/TypeScript/issues/7755#issuecomment-204167721), another reason was to ensure that derived classes do not override the private property by accident.

@huijbers proposed to modify the typescrip  compiler and add a mode which won’t private propert declarations, and perhaps can even enforce accessing private properties that are not via “this”.

What do you guys think? Maybe we can propose this as a contribution to typescript?

**Comment by christophercurrie** [comment]
Can you provide a link to that proposal? I can see it being valuable for some use cases.

A related question would be, what are private members being used for, and is there a way to eliminate them altogether, perhaps by making more types immutable?

**Comment by eladb** [comment]
In a conversation with @rix0rrr, he suggested that perhaps the correct modeling for dependencies that are exposed outside of a module's API is to use `peerDependencies` instead of normal dependencies, and I tend to agree.

For jsii code (CDK, AWS Construct Library, etc), we could enforce this at the jsii level: if a module's public API includes types from external modules, jsii can require that those are defined as `peerDependencies` instead of normal dependencies.

The problem is that we cannot enforce this for modules written by 3rd parties. We can recommend, guide and also make sure our templates are using `peerDependencies` for things like `@aws-cdk/cdk` (which by definition is exposed in the API), but we can't really enforce it as far as I know.
