### ISSUE TITLE
Fix capitalization of lambda.Runtime names

### ISSUE THREAD

**Issue by dstufft** [awslabs/aws-cdk#980]
It is expected that names are going to be mangled to idiomatic names when the CDK is generated for different target languages. However, not all of the names are currently accurate in their source naming.

The one I just ran into, is ``@aws-cdk/aws-lambda.Runtime.NodeJS*``. Because it's written as ``NodeJS*`` instead of ``NodeJs*``, it's conceptually 3 words, ``Node``, ``J``, ``S``, which gets mangled to ``node_j_s*`` when targeting Python (which uses snake casing).

We should probably fix these existing names so that they are consistent.

This is likely not going to be the last time something like this happens, so we probably want to come up with a strategy for handling these cases that doesn't break end user code, but allows us to fix these names.

**Comment by rix0rrr** [comment]
Seems useful to put a single name parser into `jsii-pacmak` so it can be shared by all codegens.

By the way, I'm not even sure I like `node_js` as a snake case. Should we just degenerate to naming hints?

**Comment by eladb** [comment]
Blocked on the decision of #2222
