### ISSUE TITLE
Support cdk-integ tools outside of this package

### ISSUE THREAD

**Issue by mindstorms6** [awslabs/aws-cdk#993]
Hi friends!

I'm writing stuff - and it's so fun!
But the time has come to write some tests and things.
Right now - it's easy to test within this repo, but if I were a weirdo and were doing it outside of here - it's not super easy to consume `cdk-integ` and friends. (Or maybe it is and I'm just really dumb).

Am I missing something obvious? (Probably) 
Or is this actually not do-able today?

Help me please!

**Comment by rix0rrr** [comment]
Not doable, unfortunately. They're repo- private tools

**Comment by eladb** [comment]
We should integrate this capability into the toolkit (duplicate #300)
